### ISSUE TITLE
The example/docker-compose/local no longer works to query traces

### ISSUE THREAD

**Issue by r0fls** [grafana/tempo#1024]
The example here: https://github.com/grafana/tempo/tree/main/example/docker-compose/local

No longer seems to work to query the resulting traces. It ingests them, e.g. I see the following logs:

```
synthetic-load-generator_1  | 21/10/11 19:45:00 INFO ScheduledTraceGenerator: Emitted traceId 1a8c952c1ae6f106 for service frontend route /cart
synthetic-load-generator_1  | 21/10/11 19:45:00 INFO ScheduledTraceGenerator: Emitted traceId ed94586cd06ba7d2 for service frontend route /cart
```

But then in the Grafana UI I get:

>Metric request error

When trying to query a given trace.

**To Reproduce**

1. Run docker compose up from the `7bfaaf379387cd042f1da8f56b457fc4f69cd9d4` commit in the directory here:
https://github.com/grafana/tempo/tree/main/example/docker-compose/local
2. Wait for the synthetic load generator to insert some traces
3. Go to the Grafana UI and try to query the trace:

![Screen Shot 2021-10-11 at 12 46 50 PM](https://user-images.githubusercontent.com/1858004/136847424-9ffc1045-4018-48d5-8fc5-e66b5a20e65c.png)

**Expected behavior**
The trace query works

**Environment:**
 - Infrastructure: local
 - Deployment tool: docker-compose

**Comment by kvrhdn** [comment]
Can confirm this happens with me too, log from Grafana
```
t=2021-10-12T08:54:22+0000 lvl=eror msg="Metric request error" logger=context userId=0 orgId=1 uname= error="failed to convert tempo response to Otlp: proto: wrong wireType = 2 for field DroppedAttributesCount" remote_addr=172.20.0.1
```

**Comment by kvrhdn** [comment]
Temporary workaround: instead of using `latest` use `r12-6e94c1f`.
