### ISSUE TITLE
Ingesters are reporting failed flushes while rolling out

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1035]
**Describe the bug**
During a rollout of the ingesters, as ingesters are being restarted they report failed flushes (`tempo_ingester_failed_flushes_total`).

![](https://user-images.githubusercontent.com/7748404/137177124-f730fc33-aaca-4c3d-82f3-9b64666b99e4.png)

**To Reproduce**
1. Run Tempo distributed with ingress traffic (otherwise no blocks have to be flushed)
2. Rollout the ingesters so they restart

**Expected behavior**
As an ingester is being restarted it should either finish flushing the block or cancel the operation so it can be retried after restarting. This should not be reported as a failed flush.

**Environment:**
 - Infrastructure: Kubernetes, ingesters are in a statefulset
 - Deployment tool: Jsonnet

**Additional Context**

**Comment by joe-elliott** [comment]
Searching the past 30 days in all ops and prod environments I am no longer seeing this issue. I'm going to close this as fixed in 1.4. We can reopen if it reoccurs.

**Comment by adirmatzkin** [comment]
Got here while investigating an alert for Ingester flushes failure, following [the runbook](https://github.com/grafana/tempo/tree/main/operations/tempo-mixin/runbook.md#TempoIngesterFlushesFailing).

@kvrhdn Do we still want the line marking this (1035) issue as a known issue? Maybe it should be removed? 🙃
