### ISSUE TITLE
Docs: Add information about how to provision Tempo as part of the data source YAML files in /datasources/tempo.md

### ISSUE THREAD

**Issue by lnryan** [grafana/tempo#1084]
Please add information on how to provision tempo as part of the datasource yaml files. 
For example, the section provided for Loki is straight-forward and detailed. Something similar for Tempo would be very helpful.
https://grafana.com/docs/grafana/latest/datasources/loki/#configure-the-data-source-with-provisioning

**Comment by osg-grafana** [comment]
@KMiller-Grafana this one yours or mine?

**Comment by GrafanaWriter** [comment]
> @GrafanaWriter not sure who owns Tempo docs rn...

@zuchka - @KMiller-Grafana is the owner of Tempo docs (along with GET, Loki, and GEL)

**Comment by zalegrala** [comment]
Joe has an example of this here: https://github.com/joe-elliott/tempo-otel-example/blob/master/config/datasource.yml#L8

**Comment by knylander-grafana** [comment]
This could be part of the getting started work that Heds and I are working on.
