### ISSUE TITLE
Vulture creates incorrectly timestamped traces

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1101]
**Describe the bug**
When vulture creates traces it uses `time.Unix()` which returns unix epoch in seconds. However, the Jaeger StartTime field is in microseconds precision.

**Comment by zalegrala** [comment]
Do you know where this is documented?  I've put up a PR to change the calls, but not sure how to verify what you're seeing.  How did this surface for you?

**Comment by joe-elliott** [comment]
if you search for a vulture created trace you can see that after it goes through the jaeger -> otlp translation its start time is incorrect:

![image](https://user-images.githubusercontent.com/2272392/141186867-16c72683-3994-43a7-976d-5d712a1cf48f.png)

**Comment by zalegrala** [comment]
Ah I see that now.  I notice too that the duration is empty.

**Comment by zalegrala** [comment]
Alright, we're in the right decade now.  I'll get the tests updated on the PR.

![image](https://user-images.githubusercontent.com/88330524/141488833-329058cf-f28d-44b0-a15b-ad644cdc8126.png)
