### ISSUE TITLE
Update Tempo's open-telemetry/collector dependency

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1102]
**Is your feature request related to a problem? Please describe.**

Tempo depends on [go.opentelemetry.io/collector](https://pkg.go.dev/go.opentelemetry.io/collector) for its receivers. We are currently still using v0.21 while the latest version is already v0.38...

https://github.com/grafana/tempo/blob/c5d007da27071358fa9b12730c048f0eddbeb82c/go.mod#L57

The receivers are used by the distributor: https://github.com/grafana/tempo/search?q=go.opentelemetry.io%2Fcollector

**Describe the solution you'd like**

Update the dependency.
Update the documentation if this changes any defaults (I'm thinking about https://github.com/grafana/tempo/issues/637).

**Describe alternatives you've considered**

If we don't update we are going to miss out on security and performance improvements.

**Additional context**
N/A

**Comment by kvrhdn** [comment]
We should probably also look into updating our opentelemetry-proto submodule:
https://github.com/grafana/tempo/blob/c5d007da27071358fa9b12730c048f0eddbeb82c/.gitmodules#L1-L3

I don't expect any changes in the traces format, but it's good to stay fairly up-to-date.

Diff: https://github.com/open-telemetry/opentelemetry-proto/compare/a17f202fdae65e828ac29fb663b5bc5b64b13290...main

**Comment by trexx** [comment]
I take it that upgrading the collector dependency will also allow enabling TLS on the otlp receiver?

**Comment by annanay25** [comment]
The collector was updated in the following PRs
- https://github.com/grafana/tempo/pull/1142
- https://github.com/grafana/tempo/pull/1214
Should we rename this issue (to only update the proto) and move it into the next milestone?

**Comment by kvrhdn** [comment]
I'm not sure if we want to bother updating the proto. OTLP traces is declared stable so not much has changed.
These are changes between our version and main: https://github.com/open-telemetry/opentelemetry-proto/compare/a17f202fdae65e828ac29fb663b5bc5b64b13290...main

Maybe we can look into this when we work on new backend formats?
