### ISSUE TITLE
Query-frontend doesn't log request details when request is cancelled

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1136]
**Describe the bug**

The query-frontend logs some details about the query when it completes, for example:

```
level=info ts=2021-11-25T11:32:38.59660534Z caller=handler.go:96 tenant=1 method=GET traceID=57060d6b589d1903 url="/tempo/api/search?x-dbg-exhaustive=true&limit=20" duration=7.079269575s response_size=96 status=200
```

If you cancel the request before it completes, this log does not appear.

**To Reproduce**

1. Run Tempo (single binary or distributed, shouldn't matter)
2. Monitor logs from the query-frontend
3. Perform a query that is slow (so you have enough time to cancel it)
4. Cancel the request
5. Nothing is logged by the query-frontend

_Note: it's surprisingly difficult to get a slow query in a normal sized Tempo. To makes this easier to test you might want to introduce a `time.Sleep(5 * time.Second)` somewhere in the query path._

**Expected behavior**

I'd expect to see the usual logline, but with `status=499`.

**Additional Context**

The log line is printed here:

https://github.com/grafana/tempo/blob/ba93a400a4968c303cdbff9f5ccf88f6194489ca/modules/frontend/handler.go#L96-L104

I believe we should not return early when the request fails:

https://github.com/grafana/tempo/blob/ba93a400a4968c303cdbff9f5ccf88f6194489ca/modules/frontend/handler.go#L67-L76

**Comment by wperron** [comment]
Hi 👋 I'll take a look

**Comment by JosephWoodward** [comment]
@wperron Are you still working on this? I'm looking for an issue to pick up so happy to take a look if you've been unable to find the time?

**Comment by wperron** [comment]
> @wperron Are you still working on this? I'm looking for an issue to pick up so happy to take a look if you've been unable to find the time?

I was planning and getting to it this week but feel free to take a look if you want!
