### ISSUE TITLE
Backend Search: Serverless Implementations

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1175]
- [ ] Code improvements/bug fixes
  - [x] Support pools of external search endpoints
  - [x] Build/Test serverless folder as part of CI
  - [x] tempo-cli command to do backend search
  - [x] Have queriers prefer themselves to the external search endpoints
  - [x] Fix min/max time range on blocks
  - [x] Support searching on fields besides strings
  - [x] Add ingestion time range limits to spans
  - [ ] Improve querier/query-frontend relationship. Can we have per endpoint `max_parrallelism`?
- [ ] Build tooling to create code packages for all major cloud providers
  - [x] GCP
  - [x] AWS
  - [ ] Azure
- [ ] Create guides for deploying to the major cloud providers
  - [x] GCP
  - [x] AWS
  - [ ] Azure

**Comment by kvrhdn** [comment]
> Determine why coldstart is faster than reusing existing function instances

I wonder if this might be a garbage collection issue? After the execution the function is frozen and garbage collection can not run. So if we are allocating a lot, it will probably have to run during the next execution.

**Comment by joe-elliott** [comment]
Removed

> Determine why coldstart is faster than reusing existing function instances

b/c I no longer think this is an issue with Cloud Functions. I believe I was exhausting a resource in the querier that was causing timeouts and retries.

**Comment by joe-elliott** [comment]
This was completed except for Azure. Splitting off a new issue and closing this.  

See #1898
