### ISSUE TITLE
Allow to disable the ssl cert validation on the S3 API

### ISSUE THREAD

**Issue by ntimo** [grafana/tempo#1182]
**Is your feature request related to a problem? Please describe.**
Currently its not possible to deploy tempo in a way where the a self hosted S3 e.g. a minio instance is secured with a certificate form a private CA. This is problematic for enterprises that use on private CAs that are then used to secure private minio instances over https. 

**Describe the solution you'd like**
A config flag to disable the ssl cert validation

**Comment by trexx** [comment]
You can use some Golang environment variables to override where the application looks for its ca bundles.
SSL_CERT_FILE and SSL_CERT_DIR can be used to add your private CA.

Eg:
    Env:
      - name: SSL_CERT_FILE
        value: /etc/tempo/ca/ca-bundle.pem

**Comment by zalegrala** [comment]
It looks like this is currently possible when using minio/s3.

https://github.com/grafana/tempo/blob/main/tempodb/backend/s3/config.go#L15

Though, if you have TLS enabled on the server side and also have the capability to inject the CA cert into the environment as @trexx suggests, that might be a better alternative.

Does the configuration option work for your situation here?

**Comment by trexx** [comment]
I've just tried this, and the flag in fact disables TLS entirely and forces http. It does not disable certificate verification.
It still maybe necessary to use the env var or mount over /etc/ssl/certs/ca-certificates.crt

**Comment by mdisibio** [comment]
Fixed in a duplicate issue:  https://github.com/grafana/tempo/issues/1466
