### ISSUE TITLE
Show only a subselection of span names when selecting Service Name

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/tempo#1203]
**Describe the bug**

Hello

Right now, in the Tempo UI if you select a Service Name to filter by, and you click on the Span Name drop down, you will see all the span names for all the Services, not just for the service you have just selected. It would be nice that if you select a Service Name, then only the spans related to this Service Name will be selectable in the Span Name drop down.

**To Reproduce**
In Grafana, Open up Explore and select the Tempo Data Source. 
Click on Search (the Beta feature). 
Select a Service Name
All the Span names will show up, whether it is related to the Service Name or not

![image](https://user-images.githubusercontent.com/83230950/148227465-1822b5c7-9d7f-4592-a6c9-3816474dfce2.png)

**Expected behavior**
When selecting a Service Name as the first drop down, then it should automatically filter Span Name to show only those span names related to the Service Name. 

**Environment:**
Any recent version of Grafana with the new Tempo search UI (marked in Beta)

**Comment by connorlindsey** [comment]
@joe-elliott Ping me when this is in progress and I can update Grafana to use it

**Comment by joe-elliott** [comment]
The current search and block formats make this difficult. We are moving to a new block format that may make this easier. Bumping this a version to keep it on the list.

**Comment by logamanig** [comment]
Any update on this pls?

**Comment by joe-elliott** [comment]
@logamanig We are currently working on releasing 2.0 which will not include this.

This feature is being worked on by @mapno and is currently in the design phase. 2.1 is a fair target.

**Comment by mapno** [comment]
Done in https://github.com/grafana/tempo/pull/2253. Additional work can be tracked in https://github.com/grafana/tempo/issues/1868.
