### ISSUE TITLE
Reduce alert sensitivity of `TempoCompactionsFailing` by adding time range

### ISSUE THREAD

**Issue by jleloup** [grafana/tempo#1270]
**Describe the bug**

I have some recurring error events from Tempo Compactor stating about "unable to mark block compacted".
This leads to an increase of errors reported in `tempodb_compaction_errors_total` and eventually to an alert `TempoCompactionFailing` from tempo mixins.
Still I can see that some blocks are written properly in our long term storage.

This happens only on our Azure environments, where Tempo is configured to leverage Azure Blob Storage as a long term storage.

**To Reproduce**
1. Start Tempo 1.3.0 with Azure Blob Storage configured
2. Wait for a compaction cycle with proper blocks to compact & store

**Expected behavior**

Compacted blocks are successfully pushed to azure Blob Storage & then marked as compacted without errors.

**Environment:**
 - Infrastructure: Kubernetes, Azure Blob Storage
 - Deployment tool: Helm using the official Helm chart version 0.15.1

**Additional Context**

Some facts I noted from the log excerpt below:

* it seems that block compaction itself is fine: three bocks being compacted this time
* only one block is being reported as written successfully
* the two other compacted blocks are begin reported as "unable to mark block compacted"

Log event:

```
level=info ts=2022-02-03T11:00:00.19999426Z caller=compactor.go:159 msg="compacting block" block="&{Version:v2 BlockID:2a28423a-e49d-4559-8a71-29d261c51a70 MinID:[0 0 0 0 0 0 0 0 0 0 20 31 40 187 88 225] MaxID:[0 0 0 0 0 0 0 0 255 249 1 145 102 130 228 103] TenantID:single-tenant StartTime:2022-02-02 10:07:25.732873517 +0000 UTC EndTime:2022-02-02 10:57:35.528783691 +0000 UTC TotalObjects:73566 Size:223999036 CompactionLevel:2 Encoding:zstd IndexPageSize:256000 TotalRecords:1349 DataEncoding:v1 BloomShardCount:1}"                    
level=info ts=2022-02-03T11:00:00.486055004Z caller=compactor.go:159 msg="compacting block" block="&{Version:v2 BlockID:86afe677-f894-4b17-8a64-bd0f4a2aef05 MinID:[0 0 0 0 0 0 0 0 0 0 28 174 165 39 113 71] MaxID:[0 0 0 0 0 0 0 0 255 255 80 48 30 98 139 7] TenantID:single-tenant StartTime:2022-02-02 09:30:18.774778096 +0000 UTC EndTime:2022-02-02 10:31:45.29685295 +0000 UTC TotalObjects:136854 Size:429678416 CompactionLevel:8 Encoding:zstd IndexPageSize:256000 TotalRecords:2563 DataEncoding:v1 BloomShardCount:4}"
level=info ts=2022-02-03T11:00:52.379924172Z caller=compactor.go:272 msg="writing compacted block" block="&{Version:v2 BlockID:79e2b1c5-527e-4437-bd6c-74c5056a0c25 MinID:[0 0 0 0 0 0 0 0 0 0 20 31 40 187 88 225] Max D:[0 0 0 0 0 0 0 0 255 255 80 48 30 98 139 7] TenantID:single-tenant StartTime:2022-02-02 09:30:18.774778096 +0000 UTC EndTime:2022-02-02 10:57:35.528783691 +0000 UTC TotalObjects:210385 Size:654719673 CompactionLevel:9 Encoding:zstd IndexPageSize:0 TotalRecords:0 DataEncoding:v1 BloomShardCount:0}"
level=error ts=2022-02-03T11:00:52.836096855Z caller=compactor.go:302 msg="unable to mark block compacted" blockID=2a28423a-e49d-4559-8a71-29d261c51a70 tenantID=single-tenant err="-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /drone/src/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====\nDescription=404 The specified blob does not exist., Details: (none)\n   HEAD https://<PLACEHOLDER>.blob.core.windows.net/tempo/single-tenant/2a28423a-e49d-4559-8a71-29d261c51a70/meta.json?timeout=61\n   Authorization: REDACTED\n   User-Agent: [Tempo Azure-Storage/0.13 (go1.17.6; linux)]\n   X-Ms-Client-Request-Id: [12c5a4ae-f644-4454-6021-1babe4161850]\n   X-Ms-Date: [Thu, 03 Feb 2022 11:00:52 GMT]\n   X-Ms-Version: [2019-12-12]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 404 The specified blob does not exist.\n   Date: [Thu, 03 Feb 2022 11:00:52 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [12c5a4ae-f644-4454-6021-1babe4161850]\n   X-Ms-Error-Code: [BlobNotFound]\n   X-Ms-Request-Id: [b3ca0076-201e-0117-7ded-18a160000000]\n   X-Ms-Version: [2019-12-12]\n\n\n"
level=error ts=2022-02-03T11:00:52.839477899Z caller=compactor.go:302 msg="unable to mark block compacted" blockID=86afe677-f894-4b17-8a64-bd0f4a2aef05 tenantID=single-tenant err="-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /drone/src/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====\nDescription=404 The specified blob does not exist., Details: (none)\n   HEAD https://tempo78ae58b475aa.blob.core.windows.net/tempo/single-tenant/86afe677-f894-4b17-8a64-bd0f4a2aef05/meta.json?timeout=61\n   Authorization: REDACTED\n   User-Agent: [Tempo Azure-Storage/0.13 (go1.17.6; linux)]\n   X-Ms-Client-Request-Id: [e3714a2b-80dd-4bd5-6416-37c1bd266ef0]\n   X-Ms-Date: [Thu, 03 Feb 2022 11:00:52 GMT]\n   X-Ms-Version: [2019-12-12]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 404 The specified blob does not exist.\n   Date: [Thu, 03 Feb 2022 11:00:52 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [e3714a2b-80dd-4bd5-6416-37c1bd266ef0]\n   X-Ms-Error-Code: [BlobNotFound]\n   X-Ms-Request-Id: [b3ca007a-201e-0117-01ed-18a160000000]\n   X-Ms-Version: [2019-12-12]\n\n\n"
level=info ts=2022-02-03T11:00:52.839613101Z caller=compactor.go:150 msg="compaction complete"
```

**Comment by jleloup** [comment]
Overall compaction looks pretty fine but still those errors slips through recuringly.

![Screen Shot 2022-02-03 at 14 48 25](https://user-images.githubusercontent.com/20790125/152355297-6c2ce801-d639-4f3d-ab98-d5505e8980c0.png)

![Screen Shot 2022-02-03 at 14 50 47](https://user-images.githubusercontent.com/20790125/152355675-b91071de-7ff5-4e7b-ae4b-a0ad43434219.png)

**Comment by jleloup** [comment]
Regarding the `TempoCompactionFailing` alert itself I believe a `for` instruction is missing: https://github.com/grafana/tempo/blob/main/operations/tempo-mixin/yamls/alerts.yaml#L45

Adding a `for: 5m` would help triggering this alert for transient issues like this one. I don't know if this is intentional though :)

**Comment by joe-elliott** [comment]
This is likely caused by multiple compactors attempting to compact the same blocks. This can occur if two compactors disagree on the state of the consistent hash ring. The consistent hash ring is what is used to shard jobs across the compactors so if two compactors see the ring in different states they may both think they own a particular job.

Likely causes:
- Regularly dying or OOMing compactors can cause ring  instability and disagreements
- Rollouts. Particularly slow ones. Its recommended to mass rollout the compactor to prevent this issue.
- For some reason compactors see a different ring. Maybe they are in different gossip clusters?

As you have seen things still basically work even if you are seeing this error but it's certainly not ideal as compactors are duplicating work as well as data.

Regarding the suggested alert change. Yeah, I think either a `for` clause or a configurable threshold would be valuable.

**Comment by jleloup** [comment]
Thanks for your detailed answer.

Indeed the two environments were this issue happens seems to be misconfigured and are pushing to the very same Azure storage container.

**Comment by annanay25** [comment]
@jleloup I'm going to change title to reflect the `for 5m` issue with the alert and reopen this.
