### ISSUE TITLE
Traces from different agents

### ISSUE THREAD

**Issue by nexcode** [grafana/tempo#1272]
There are several servers in the local network. Each server has its own grafana agent. Services are connected to their localhost agents.

If the request was balanced so that it was not sent to other servers (localhost), then the trace is displayed correctly:
<img width="442" alt="correct" src="https://user-images.githubusercontent.com/10132325/152447405-2969b383-0f24-4bd4-ad8c-58c1ddbdfb5a.png">

If the request was balanced so that it was sent to other servers, then the trace is shown incorrectly:
<img width="442" alt="incorrect" src="https://user-images.githubusercontent.com/10132325/152447535-bca2d9f6-2a7d-4d8f-b9e1-45e71fa78590.png">

**Comment by kvrhdn** [comment]
Timestamps are added to the spans by the application that generates them. AFAIK the agent will not modify them in any way, it just collects them and forwards them to Tempo.
I suspect your servers are not using the same time, one server seems to have a drift of about 2ms. I would recommend using something like NTP to ensure all your servers use the same time.

**Comment by nexcode** [comment]
On all servers:
```
NTP enabled: yes
NTP synchronized: yes
```

**Comment by nexcode** [comment]
External NTP servers were used
