### ISSUE TITLE
Backend not hit 

### ISSUE THREAD

**Issue by mrkwtz** [grafana/tempo#1281]
**Describe the bug**
We're using Tempo v1.3.1 with Grafana 8.3.6 and S3 as the storage backend. It seems like when we query traces for multiple hours (e.g. last 24h) only the ingester is queried for its data (which is always around the last 1-2h). When we chose a time range between now-1h and now-24h the 23h are returned correctly. You also "feel" that the backend is hit because it takes much longer. 

So it seems like when you query a time range where both the ingester and the object storage should be hit, only the ingester is. 

**To Reproduce**
1. Try to query the last 24h hours with default config for "query_ingesters_until" and "query_backend_after". See that it only returns the last 1-2 hours.
2. Try to query now-24h to now-1h see that it returns the requested 23h and hits the object storage.

**Expected behavior**
When requesting the last 24h Tempo should return the whole 24h. 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm (tempo-distributed chart v0.15.2)

**Additional Context**

Rendered Tempo config
```
query_frontend:
  search:
    max_duration: 0
multitenancy_enabled: false
search_enabled: true
compactor:
  compaction:
    block_retention: 1440h
  ring:
    kvstore:
      store: memberlist
distributor:
  ring:
    kvstore:
      store: memberlist
  receivers:
    jaeger:
      protocols:
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:55681
        grpc:
          endpoint: 0.0.0.0:4317
querier:
  frontend_worker:
    frontend_address: tempo-tempo-distributed-query-frontend-discovery:9095
ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
    - tempo-tempo-distributed-gossip-ring
overrides:
  max_search_bytes_per_trace: 0
  per_tenant_override_config: /conf/overrides.yaml
server:
  http_listen_port: 3100
  log_level: info
  log_format: json
  grpc_server_max_recv_msg_size: 4.194304e+06
  grpc_server_max_send_msg_size: 4.194304e+06
storage:
  trace:
    backend: s3
    s3:
      bucket: XXXXX
      endpoint: s3.eu-central-1.amazonaws.com
      region: eu-central-1
    blocklist_poll: 5m
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    cache: memcached
    memcached:
      consistent_hash: true
      host: tempo-tempo-distributed-memcached
      service: memcached-client
      timeout: 500ms
```

Helm values

```
    compactor:
      config:
        compaction:
          block_retention: 1440h
    config: |
      #--- This section is manually inserted (Robin) ---
      query_frontend:
        search:
          {{- if .Values.queryFrontend.extraConfig.max_duration }}
          max_duration: {{ .Values.queryFrontend.extraConfig.max_duration }}
          {{- else }}
          max_duration: 1h1m0s
          {{- end }}
      #-------------------------------------------------
      multitenancy_enabled: false
      search_enabled: {{ .Values.search.enabled }}
      compactor:
        compaction:
          block_retention: {{ .Values.compactor.config.compaction.block_retention }}
        ring:
          kvstore:
            store: memberlist
      distributor:
        ring:
          kvstore:
            store: memberlist
        receivers:
          {{- if  or (.Values.traces.jaeger.thriftCompact) (.Values.traces.jaeger.thriftBinary) (.Values.traces.jaeger.thriftHttp) (.Values.traces.jaeger.grpc) }}
          jaeger:
            protocols:
              {{- if .Values.traces.jaeger.thriftCompact }}
              thrift_compact:
                endpoint: 0.0.0.0:6831
              {{- end }}
              {{- if .Values.traces.jaeger.thriftBinary }}
              thrift_binary:
                endpoint: 0.0.0.0:6832
              {{- end }}
              {{- if .Values.traces.jaeger.thriftHttp }}
              thrift_http:
                endpoint: 0.0.0.0:14268
              {{- end }}
              {{- if .Values.traces.jaeger.grpc }}
              grpc:
                endpoint: 0.0.0.0:14250
              {{- end }}
          {{- end }}
          {{- if .Values.traces.zipkin}}
          zipkin:
            endpoint: 0.0.0.0:9411
          {{- end }}
          {{- if or (.Values.traces.otlp.http) (.Values.traces.otlp.grpc) }}
          otlp:
            protocols:
              {{- if .Values.traces.otlp.http }}
              http:
                endpoint: 0.0.0.0:55681
              {{- end }}
              {{- if .Values.traces.otlp.grpc }}
              grpc:
                endpoint: 0.0.0.0:4317
              {{- end }}
          {{- end }}
          {{- if .Values.traces.opencensus }}
          opencensus:
            endpoint: 0.0.0.0:55678
          {{- end }}
          {{- if .Values.traces.kafka }}
          kafka:
            {{- toYaml .Values.traces.kafka | nindent 6 }}
          {{- end }}
      querier:
        frontend_worker:
          frontend_address: {{ include "tempo.queryFrontendFullname" . }}-discovery:9095
          {{- if .Values.querier.config.frontend_worker.grpc_client_config }}
          grpc_client_config:
            {{- toYaml .Values.querier.config.frontend_worker.grpc_client_config | nindent 6 }}
          {{- end }}
      ingester:
        lifecycler:
          ring:
            replication_factor: 1
            kvstore:
              store: memberlist
          tokens_file_path: /var/tempo/tokens.json
      memberlist:
        abort_if_cluster_join_fails: false
        join_members:
          - {{ include "tempo.fullname" . }}-gossip-ring
      overrides:
        {{- toYaml .Values.global_overrides | nindent 2 }}
      server:
        http_listen_port: {{ .Values.server.httpListenPort }}
        log_level: {{ .Values.server.logLevel }}
        log_format: {{ .Values.server.logFormat }}
        grpc_server_max_recv_msg_size: {{ .Values.server.grpc_server_max_recv_msg_size }}
        grpc_server_max_send_msg_size: {{ .Values.server.grpc_server_max_send_msg_size }}
      storage:
        trace:
          backend: {{.Values.storage.trace.backend}}
          {{- if eq .Values.storage.trace.backend "gcs"}}
          gcs:
            {{- toYaml .Values.storage.trace.gcs | nindent 6}}
          {{- end}}
          {{- if eq .Values.storage.trace.backend "s3"}}
          s3:
            {{- toYaml .Values.storage.trace.s3 | nindent 6}}
          {{- end}}
          {{- if eq .Values.storage.trace.backend "azure"}}
          azure:
            {{- toYaml .Values.storage.trace.azure | nindent 6}}
          {{- end}}
          blocklist_poll: 5m
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
          cache: memcached
          memcached:
            consistent_hash: true
            host: {{ include "tempo.fullname" . }}-memcached
            service: memcached-client
            timeout: 500ms
    distributor:
      replicas: 1
    gateway:
      enabled: true
    global_overrides:
      max_search_bytes_per_trace: 0
    ingester:
      persistence:
        enabled: true
      replicas: 1
    memcachedExporter:
      enabled: true
    querier:
      replicas: 1
    queryFrontend:
      extraConfig:
        max_duration: "0"
      replicas: 1
    search:
      enabled: true
    server:
      logFormat: json
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::XXXXX
      name: tempo
    serviceMonitor:
      enabled: true
    storage:
      trace:
        backend: s3
        s3:
          bucket: XXXXX
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1
    traces:
      jaeger:
        grpc: true
        thriftBinary: true
        thriftCompact: true
        thriftHttp: true
      otlp:
        grpc: true
        http: true
```

**Comment by joe-elliott** [comment]
When you are querying for the past 24h are you getting a full result set back?

Tempo will begin searching the backend in parallel to the ingesters but the ingesters will generally return much faster. If you're searching the past 24h and getting 20 results back (default limit) then it's probably just b/c there were enough hits in the ingester to satisfy your conditions.

**Comment by mrkwtz** [comment]
@joe-elliott when I query for the last 24h I only get a subset back like 1-2h of data. I'm also setting the limit to 1,000,000 so it should be much more. Like said in the description: once I disable the ingester query completely and only pull from the object storage I get the correct result back.

**Comment by mrkwtz** [comment]
I'm getting tens of thousands back. There can't be a max limit that is that low.

**Comment by joe-elliott** [comment]
So, I'm honestly not sure. I'd be interested in the value of this metric:
```
sum(rate(tempo_request_duration_seconds_count{route=~"querier_tempo_api_.*"}[$__interval])) by (route)
```
When you are making your queries. It will show us roughly how much work the queriers are doing. If this is spiking when you  choose last `24h` it likely means that Tempo is attempting to search the backend. If it is not spiking then it means it's doing an ingester only search.

**Comment by joe-elliott** [comment]
> I'm getting tens of thousands back. There can't be a max limit that is that low.
You're correct. The config option I was thinking about defaults to 0 which means the limit is not restricted.

If you could provide a trace of the query we might be able to dig up a few clues as to why this is happening. We are definitely not seeing this. I can execute a query over the past 1 hour and see (via the trace) requests going to both the ingesters and the backend.

The entire trace would be valuable, but the `frontend.ShardSearch` span in particular will provide clues. It would be interesting to know these values in the two different search cases: now-24h to now vs now-24h to now-1h.

![image](https://user-images.githubusercontent.com/2272392/153502359-397dc01d-ba43-4b6b-b871-b0ce86b711b0.png)

Other things that may help are the logs made by the queriers. With these logs we can clearly see if the querier is receiving jobs to search only the ingesters or also the backend blocks. This is what a job to search a block looks like:

```
GET /querier/tempo/api/search?blockID=898a2cac-6a1a-496f-8a7c-9abe353d4bb3&dataEncoding=v2&encoding=lz4-1M&end=1644530267&indexPageSize=256000&limit=20&minDuration=3s&pagesToSearch=33&start=1644526667&startPage=330&tags=+service.name%3D%22tempo-query-frontend%22&totalRecords=2006&version=v2
```

This is what the job to search the ingesters looks like.
```
GET /querier/tempo/api/search?end=1644530267&limit=20&minDuration=3000ms&start=1644526667&tags=service.name%3Dtempo-query-frontend
```

My guess is that either:
- the query frontend is not creating all of the jobs it should and is only creating the "search ingesters" job
- the query frontend is returning results early from just the ingesters even though it's also attempting to search the backend.

Thank you for helping us debug this! I have not had a chance to do so, but I will pull and test the helm chart directly in case it's a quirk of the helm chart config that is not occurring to me.

**Comment by mrkwtz** [comment]
Thanks for the answer I'll try to get back to your questions asap. Maybe a stupid question, but how do I enable traces for Tempo itself? :smile:

**Comment by mrkwtz** [comment]
Hey @joe-elliott sorry for the delay. I set the envs for the query-frontend and I see traces from tempo incoming but not with the spans you showed above. That's the only one I get at the start time of the query-frontend service.

![image](https://user-images.githubusercontent.com/18321378/154468613-dda91e22-3303-4763-9c18-9ad7a8ef7dc9.png)

Do I need to set other configs to enabled tracing for all components?

**Comment by kvrhdn** [comment]
This seems to be a trace from the tempo-query component, not the query-frontend. tempo-query is an optional component that offers a Jaeger API on top of Tempo's native API. It runs as a sidecar in the query-frontend pod.
If you are using a recent version of Grafana (which you are) this component isn't necessary, Grafana can query Tempo's query-frontend directly.
Are you using the Tempo or the Jaeger datasource in Grafana?

> I set the envs for the query-frontend and I see traces from tempo incoming but not with the spans you showed above. That's the only one I get at the start time of the query-frontend service.

You will have to set these variables on all the containers in the query path (`query-frontend`, `querier` and `ingester`). Also note the `query-frontend` pod contains two containers: `query-frontend` and `tempo-query`. You have to set these variables on both containers individually.

**Comment by kvrhdn** [comment]
This is what a trace for a search request looks like in our environment: notice the service name is `tempo-query-frontend` and the root span name is `HTTP GET - tempo_api_search`. I think you captured a trace from an unrelated operation.

![Screenshot 2022-02-17 at 16 25 10](https://user-images.githubusercontent.com/7748404/154513543-829c9071-aa25-4e87-a242-983b0d2c91f9.png)

The easiest way to find a trace from a query operation is to use the traceID logged in the query-frontend logs.

**Comment by mrkwtz** [comment]
Finally got it working :) 

(1) now-24h to now
![image](https://user-images.githubusercontent.com/18321378/154528627-3faff935-c15c-414a-a453-9ef60780a4b6.png)


(2) now-24h to now-1h
![image](https://user-images.githubusercontent.com/18321378/154528367-76d46e71-6f49-475d-83a0-b5bd71a47b8f.png)

Hope that helps

**Comment by joe-elliott** [comment]
Nice!  So on the first query I'm seeing 3 requests made and 2 blocks found. This suggests that the query frontend is finding 2 blocks and creating one request for each. Then it creates one more request to search the ingesters for a total of 3.

On the second query I'm seeing 23 blocks found and 23 requests made. So this suggests the ingesters are not being searched on the second query. This seems correct.

The first query is searching the backend, but very lightly. I'm surprised by this mismatch. I would expect that both queries would hit roughly the same number of blocks. Maybe slightly more for the first one then the second. If you look in the `HTTP GET - tempo_api_search` span (the parent of the one you've captured in your screenshots) we can see the exact parameters that are passed to the frontend:

![image](https://user-images.githubusercontent.com/2272392/154564129-7e2d9d21-ef5a-4b20-aa0b-7a4faac5bb00.png)

If you can provide this it can really help us eliminate a few final cases.

**Comment by mrkwtz** [comment]
Unfortunately this here is the full trace. There are no traces / spans from the gateway service.

![image](https://user-images.githubusercontent.com/18321378/154583584-9a6779df-3b68-4c71-b3da-03d2e4301536.png)

**Comment by joe-elliott** [comment]
It's the parent of the one you have dropped down:

![image](https://user-images.githubusercontent.com/2272392/154584930-4693eb8e-014d-45a3-9bac-6d2fe468d634.png)

**Comment by mrkwtz** [comment]
Ah ok sorry. Got it

![image](https://user-images.githubusercontent.com/18321378/154647835-5908249d-fdbc-44b9-b11f-2fba1ba03bf7.png)

**Comment by mrkwtz** [comment]
Hey @joe-elliott thanks for bearing with me and the fix :) Is there an estimate for the release?

**Comment by joe-elliott** [comment]
We will be cutting a 1.3.2 with this fix. I'm hoping to get it done sometime this week.

**Comment by joe-elliott** [comment]
1.3.2 has been released: https://github.com/grafana/tempo/releases/tag/v1.3.2

Thanks again for reporting this issue!
