### ISSUE TITLE
Explore log button in the split view is not working.

### ISSUE THREAD

**Issue by Jojoooo1** [grafana/tempo#1288]
**Describe the bug**
Explore log button in the split view is not working.

**To Reproduce**
1. Tempo 1.3.0
2. Grafana 8.3.6

**Expected behavior**
Should redirect to logs

**Environment:**
 - Infrastructure: Kubernetes using grafana chart (loki, promtail, tempo) and kube-prometheus-stack
 - Deployment tool: helm

**Additional Context**
![Screenshot from 2022-02-17 09-21-56](https://user-images.githubusercontent.com/17641873/154481715-08f119c8-df98-45f4-9f7d-8d28aeca5f61.png)
![Screenshot from 2022-02-17 09-22-05](https://user-images.githubusercontent.com/17641873/154481721-e7644eab-a89a-4e0d-9af6-b2e7b3375ca1.png)

**Comment by kvrhdn** [comment]
Hi, the traces-to-logs feature uses tags that exist on the span to create a Loki query. What tags are used to create a Loki query can be configured in the preferences of the Tempo datasource:

![Screenshot 2022-02-17 at 13 52 12](https://user-images.githubusercontent.com/7748404/154485482-e8bd8563-4a9d-4182-b207-558b66a87e06.png)

In this case Grafana will search the span for the tags `cluster`, `namespace` and `pod` to build a Loki query. If none of the tags are present on the span the resulting query will empty `{}`. Empty queries aren't allowed in Loki and will thus result in an error (that's what you are seeing).

So you should check your spans to figure out what tags you have set and which can be used to link traces to logs. Both traces and logs should share a common set of tags for this to work.

This explanation might help as well: https://community.grafana.com/t/need-to-customize-tempo-option-for-trace-logs-with-loki/59612/6?u=koenraad

**Comment by kvrhdn** [comment]
Btw, you can enrich your spans using the Grafana Agent. The [traces_config](https://grafana.com/docs/agent/latest/configuration/traces-config/) of the agent has a section to configure `scrape_configs`. If this is enabled the agent will scrape labels from the pods and add them to spans from that pod. This is what I use to add `namespace` and `pod` tags to my spans.

**Comment by Jojoooo1** [comment]
Hi @kvrhdn thanks the answer. But it is actually set as follow

![Screenshot from 2022-02-17 11-35-29](https://user-images.githubusercontent.com/17641873/154503738-2b8f970e-97fc-438c-911e-22b53dc1f61d.png)

![Screenshot from 2022-02-17 11-37-12](https://user-images.githubusercontent.com/17641873/154504009-12031713-3cff-4dbb-8363-d578696fc365.png)

**Comment by kvrhdn** [comment]
Great, glad you managed to get it working 🙌🏻
