### ISSUE TITLE
Post spans to Tempo through Jaeger grpc (14250)

### ISSUE THREAD

**Issue by pkrishnanreflexion** [grafana/tempo#1299]
I am trying to migrate a bunch of traces from Elasticsearch to Tempo.
For this I query JaegerGRPC (Jaeger-query) and get a response which needs to be pushed to Tempo through tempo receiver GRPC.

This is my tempo-local.yaml

```

server:
  http_listen_port: 3200

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
        grpc:                          # for a production deployment you should only enable the receivers you need!
  log_received_traces: true


ingester:
  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
  max_block_bytes: 1_000_000           # cut the head block when it hits this size or ...
  max_block_duration: 5m               #   this much time passes

compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000       # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local                     # backend configuration to use
    block:
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      index_downsample_bytes: 1000     # number of bytes per index record
      encoding: zstd                   # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
      encoding: snappy                 # wal encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100                 # worker pool determines the number of parallel requests to the object store backend
      queue_depth: 10000

search_enabled: true

```

The response from my client is successful, but the tempo or the tempo logs does not show any traces received.
I have cross checked the grpc port and all appears to be correct.

Any recommendations on how to push traces into tempo through GRPC?

**Comment by joe-elliott** [comment]
What tool are you using to push traces? Does a quick scan of logs/metrics from this tool give any indication of what the issue may be? Can you open the tempo host/port from the network namespace it is running in? Can you share configuration of the tool you are using?

> For this I query JaegerGRPC (Jaeger-query) and get a response which needs to be pushed to Tempo through tempo receiver GRPC.
jaeger-query was a grpc shim we used to use to query Tempo using the Jaeger UI. It is no longer necessary. I'm concerned that you are mentioning it b/c it has nothing to do with ingesting traces and I'm afraid there is some confusion about its intended purpose.

**Comment by pkrishnanreflexion** [comment]
Thanks for your response.

I have a Python script to read Jaeger-Query using GRPC. That returns a "SpansChunkResponse" and I am using it to Post.
The issue was with the object I was tryin to push. That is now resolved and I can successfully push the traces. 
I did not have to change any config settings in tempo.

<img width="1125" alt="Screen Shot 2022-02-24 at 9 00 14 AM" src="https://user-images.githubusercontent.com/94964199/155452725-10255fb9-55d3-4ef8-82a8-8536761b26fb.png">

**Comment by pkrishnanreflexion** [comment]
We would like to push some legacy traces to tempo. Is there a way by which we can change the timestamp "ts" of the Spans pushed into tempo, to reflect the actual timestamp in the "spans"?

**Comment by joe-elliott** [comment]
Tempo doesn't change the timestamps of the spans during ingestion, but it does use ingestion time for a block's min/max time.

What this means in practice is that traces will be retrievable by id, but if you try to search for a trace using a time range it will not return. I am currently working on a change to correct this and base the block time on the actual span times and not the ingestion time.

**Comment by pkrishnanreflexion** [comment]
Thanks!

**Comment by suxiaoxiaomm** [comment]
@pkrishnanreflexion Could you kindly share your scripts to me? I also need to do data migration from jaeger elasticsearch to tempo, while I don't have any clue yet.

**Comment by joe-elliott** [comment]
@suxiaoxiaomm given normal trace retention (7d? 14d? 30d?)  it is likely not worth migrating all the data from one backend to another. It is up to your org, but my recommendation would be cutting over to the new tool and then just using both for awhile until all the data has been dropped in the old one.

**Comment by suxiaoxiaomm** [comment]
@joe-elliott Thank you for the response. 
I wrote a go script with use Jaeger gRPC [FindTraces](https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v3/query_service.proto), and send the response traces to OpenTelemetry collector via gRPC as well, which will forward the traces to Tempo.

Now I can find the old traces with query with TraceID. 

But the problem is, I cannot search those old traces via for example, service name, with time ranges.

Could you suggest what was missing here?

**Comment by joe-elliott** [comment]
if you push a very old trace to Tempo it will store it and return it by ID, but it will likely not be searchable. When the trace is pushed if it is outside the `ingestion_time_range_slack` it will keep the trace but will not update the block's time range to reflect the trace exists in that block. This is to prevent every block from having huge time ranges due to people pushing past and future traces. The default slack is `2m`.

Search for `ingestion_time_range_slack` here:
https://grafana.com/docs/tempo/latest/configuration/#storage-block-configuration-example

You could increase this value to be multiple days/weeks while you do your migration and then revert to default during normal operation.

**Comment by suxiaoxiaomm** [comment]
@joe-elliott Thanks a lot for the suggestion. Will try and let you know the result.

**Comment by suxiaoxiaomm** [comment]
@joe-elliott It works perfect. Thank you so much!!
