### ISSUE TITLE
queue_depth default not working

### ISSUE THREAD

**Issue by mrkwtz** [grafana/tempo#1344]
**Describe the bug**
It seems like the `storage.trace.pool.queue_depth` default config in https://github.com/grafana/tempo/blob/v1.3.2/tempodb/pool/config.go#L12 which should be 10k is not applied. When we don't set it, it seems to default to 200 and causes a lot of `error querying store in Querier.FindTraceByID: queue doesn't have room for X jobs` errors.

That is our `tempodb_work_queue_max` metric value when we don't override the defaults
![image](https://user-images.githubusercontent.com/18321378/158162662-cde7c099-3f81-4dfe-9ae9-46aabe0a330f.png)

That is our `tempodb_work_queue_max` metric value when we set  `storage.trace.pool.queue_depth` explicitly to 10k
![image](https://user-images.githubusercontent.com/18321378/158163441-470615c0-5631-4f72-b34a-1da703573ef2.png)

As soon as we set the configuration explicitly the `error querying store in Querier.FindTraceByID: queue doesn't have room for X jobs` errors disappear.

**Expected behavior**
`storage.trace.pool.queue_depth` should default to 10k as documented

**Environment:**
 - Tempo version: 1.3.2
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by joe-elliott** [comment]
Thanks for the issue! The actual default config is set here:
https://github.com/grafana/tempo/blob/main/modules/storage/config.go#L83

Although our docs say the defaults are the values from the code that you linked:
https://github.com/grafana/tempo/blob/main/docs/tempo/website/configuration/_index.md?plain=1#L643

So either we need to fix the defaults or fix the docs. Do you have strong feelings either way on what the defaults should be?

**Comment by joe-elliott** [comment]
Yeah, I agree that that default has not aged well. I appreciate you bringing this to our attention. The fix is in!
