### ISSUE TITLE
Enable compaction and retention in Tanka single-binary

### ISSUE THREAD

**Issue by irizzant** [grafana/tempo#1352]
**Describe the bug**
As far as I can see retention is enabled in [microservices](https://github.com/grafana/tempo/blob/e9008c5ebae92162616610ef791e4c596147feab/operations/jsonnet/microservices/configmap.libsonnet#L75) mode but in [single-binary](https://github.com/grafana/tempo/blob/e9008c5ebae92162616610ef791e4c596147feab/operations/jsonnet/single-binary/configmap.libsonnet#L17) only `compacted_block_retention` is provided. 

**To Reproduce**
1. Start Tempo in single-binary mode with Tanka
2. Inspect the ConfigMap

**Expected behavior**
Retention enabled by default

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Tanka

**Comment by joe-elliott** [comment]
That line in the single binary jsonnet is really strange. I'm not sure why we are setting it to `24h`. My guess is it should be removed and allow the default of `1h` to be used. I'm wondering if whoever made it confused it with `block_retention` when they created it (probably me).

`compacted_block_retention` is configurable value that controls how long compacted blocks are left in object storage after they have been compacted into larger blocks. They are generally left in object storage for an hour or so. This allows all the different polling components (queriers and compactors) to update their state to see the new blocks before the old blocks are removed.

I think we should just change `compacted_block_retention` -> `block_retention`. Thoughts?
