### ISSUE TITLE
Incorrectly using path.Join?

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#136]
filepath.Join => path.Join

**Comment by dgzlopes** [comment]
Researched this a little.

`path.Join` uses `/` as separator regardless of the operating system. And well, that can be a problem! 

For example, in Windows, some paths use `\` as separators.

[Source code](https://golang.org/src/path/path.go?s=4034:4066#L157:):
```go
func Join(elem ...string) string {
	for i, e := range elem {
		if e != "" {
			return Clean(strings.Join(elem[i:], "/"))
		}
	}
	return ""
}
```

On the other hand, filepath.Join uses OS-specific separators.

**Comment by joe-elliott** [comment]
This is the least defined issue ever :).  Thank you for doing some research on this.  There are definitely a few places where we should correct this behavior:

tempodb/backend/diskcache/disk_cache.go
tempodb/wal/wal.go

tempodb/backend/local/local.go should probably be changed as well, but i'm wondering why it's not using tempodb/backend/util/util.go 
@annanay25 any ideas?
