### ISSUE TITLE
Service Dependency Graph Panel

### ISSUE THREAD

**Issue by klayders** [grafana/tempo#1369]
Hello, can we see the possibility of using tempo in grafan to display microservice communication as a graph?
Like this https://grafana.com/grafana/plugins/novatec-sdg-panel/

**Comment by kvrhdn** [comment]
Hi! Yes, we've called this feature _service graphs_. The Grafana Agent and the latest builds of Tempo can generate metrics which are used by Grafana to draw service graphs. We extract service names out of ingested traces and keep track of the amount of calls between them and their respective latencies.

Docs on configuring this with the Grafana Agent and Grafana: https://grafana.com/docs/tempo/latest/grafana-agent/service-graphs/

The Tempo metrics-generator can generate these metrics from within Tempo (so you don't need to run the agent anymore) but we haven't fully documented this yet. This will be officially released in the next Tempo release which is planned in a couple of weeks.

**Comment by klayders** [comment]
awesome!!! =)
