### ISSUE TITLE
Multitenancy : support otlp java-agent

### ISSUE THREAD

**Issue by liguozhong** [grafana/tempo#1381]
**Is your feature request related to a problem? Please describe.**

https://grafana.com/docs/tempo/latest/configuration/multitenancy/

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-both-span-and-metric-exporters

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kvrhdn** [comment]
Hi, can you clarify what you need? Tempo can ingest both OTLP HTTP and OTLP gRPC, you just have to enable the respective receivers [in the distributor config section](https://grafana.com/docs/tempo/latest/configuration/#distributor). If you want to send OTLP from the Java agent to Tempo you have to configure the agent to send data to the distributor.

**Comment by liguozhong** [comment]
@kvrhdn  Thanks for such a quick response.

We sent it through the http protocol of java-agent, and encountered the error "failed to extract org id". 
After looking at the source code, tempo could only extract the tenant information in the header through grpc. 
Therefore, we speculate that tempo cannot support the writing method of otlp through http

-javaagent:/Users/fuling/ali/sourcetree/prometheus-arms-aliyun-demo/src/main/java/com/monitise/prometheus_demo/opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=lokitracetestapp -Dotel.exporter.otlp.traces.endpoint=http://8.142.104.231:4318/v1/traces -Dotel.javaagent.debug=true -Dotel.exporter.otlp.protocol=http/protobuf -Dotel.exporter.otlp.protocol=http/protobuf

![image](https://user-images.githubusercontent.com/9583245/163308217-6dd36818-b528-4173-8860-9255c642bf5a.png)

**Comment by liguozhong** [comment]
@kvrhdn ,The “tracesReceiver.Export(req.Context(), otlpReq)” function of the otlp collector loses the header of the http request, and tempo passes the multi-tenant id through the header. It makes tempo unable to complete multi-tenant authentication through the http protocol. 

vendor/go.opentelemetry.io/collector/receiver/otlpreceiver/otlphttp.go:47
![image](https://user-images.githubusercontent.com/9583245/163338052-31f95abd-ddb9-45a4-8a01-b86e650523fd.png)

**Comment by liguozhong** [comment]
tempo should to implement the authenticator interface, which can get the header information.

![image](https://user-images.githubusercontent.com/9583245/163349674-7df4a2bc-801f-4532-8666-c50883e14e21.png)

![image](https://user-images.githubusercontent.com/9583245/163349829-7362a955-16c8-44fa-b289-a13e272365f9.png)

**Comment by liguozhong** [comment]
refer url：https://github.com/open-telemetry/opentelemetry-collector/blob/main/client/client.go

**Comment by liguozhong** [comment]
oidc auth demo
example：https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oidcauthextension
