### ISSUE TITLE
Pass a Logger/MetricsFactory to TempoDB

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#14]
The database code needs a way to log and publish metrics.  We need to decide if it will be tightly integrated with the rest of tempo and just use the same logger as everything else.  The other option being to pass these utilities as params.

**Comment by annanay25** [comment]
A logger is already passed to TempoDB, we also need to pass a prometheus registry.

**Comment by mdisibio** [comment]
Take existing metrics and register them via passed in registry obj instead of globally.
