### ISSUE TITLE
Support Kafka as a source of spans

### ISSUE THREAD

**Issue by Ultrafenrir** [grafana/tempo#1412]
**Is your feature request related to a problem? Please describe.**
I would like to have ability to put Kafka as a buffer between grafana agent and tempo. For better data availability, as we used to do with logs and what jaeger offer.

**Describe the solution you'd like**
Grafana agent can act as Kafka producer and can write spans into Kafka , and tempo can be consumer that read and stores the spans.

**Describe alternatives you've considered**
Jaeger can do that , but I would like to use grafana stack 

**Additional context**
It’s really common pattern to put Kafka as a buffer in different processing systems.

**Comment by joe-elliott** [comment]
This should already be possible by using a Kafka receiver configured on the distributor:

https://grafana.com/docs/tempo/latest/configuration/#distributor

Available options are here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver

Both of the following should be possible:

( otel collector | grafana agent) -> kafka -> tempo
( otel collector | grafana agent) -> kafka -> (otel collector | grafana agent ) -> tempo

However, I can honestly say I've never run Tempo pulling spans from a queue, so I'm not sure what the bottlenecks are operationally. You will likely run into scaling issues we are unaware of. If this occurs, please report back so we can improve!
