### ISSUE TITLE
Unhealthy Compactors Stay in the Ring

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#142]
I've seen an unhealthy compactor stay in the ring for hours after it was gone.  Research this and see if it's a matter of configuration or actually a bug of some kind.

Should we use a simpler discovery mechanism like DNS?

**Comment by joe-elliott** [comment]
If you are seeing this issue and are unable to successfully forget a compactor it is recommended to click the "Forget" button.  Wait a full 10 seconds, stand up, stretch, get all your grocery shopping done, come back and then hit F5.  The compactor should be forgotten.

If you quickly spam "Forget" then old compactors seem to stay in the ring.  This is believed to be an issue with the memberlist propagation of the ring.

**Comment by annanay25** [comment]
Forget behaviour may be fixed with https://github.com/cortexproject/cortex/pull/3603 and will reflect once we vendor in the latest cortex version. 

Research for a way to not-care about a compactor disappearing from the ring.

**Comment by gouthamve** [comment]
Can this be closed?

**Comment by joe-elliott** [comment]
We believe that #442 fixed this issue, but have not seen it in again in our internal cluster to confirm.  I'd rather keep this open until we verify.

**Comment by slim-bean** [comment]
This happened again, could not get the unhealthy compactor to leave, ended up port-forwarding 4-5 compactors between two people and clicking forget a lot and eventually it went away.

**Comment by joe-elliott** [comment]
@pstibrany has reported he feels the issue will be fixed in Cortex 1.7.0.  We will keep an eye on it after the upgrade.

**Comment by pstibrany** [comment]
It's the same https://github.com/cortexproject/cortex/pull/3603 fix, but Tempo currently doesn't use Cortex version with that fix in.

**Comment by joe-elliott** [comment]
Confirmed fixed in our environment by #512 

Thanks @pstibrany!

**Comment by joe-elliott** [comment]
We've seen this again, but found a way to mitigate.  The changes in Cortex have certainly made it easier to deal with, but it does still happen occassionally.

Details have been added to the appropriate runbook entries: https://github.com/grafana/tempo/pull/532

**Comment by joe-elliott** [comment]
Further updates on this.  We have since switched to using this values in our memberlist config and have not been able to trigger this issue since:

```
memberlist:
    left_ingesters_timeout: 30m
    pull_push_interval: 15s
    retransmit_factor: 5
```

**Comment by joe-elliott** [comment]
Possible fixes going into Cortex now:

https://github.com/cortexproject/cortex/pull/4420
https://github.com/cortexproject/cortex/pull/4419
