### ISSUE TITLE
Trace query causes runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jooooel** [grafana/tempo#1440]
**Describe the bug**
Trying to query a specific `TraceId` in Grafana, getting "Query data error". Many traces can be viewed, some return this error. Not really sure what the reason is. Logs from Tempo after the failed query in Grafana:

```
2022-05-23 18:33:45.269731 I | http: panic serving 10.9.2.8:50694: runtime error: invalid memory address or nil pointer dereference
goroutine 4086 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x1ae7780, 0x32682c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1()
	/drone/src/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:150 +0x139
panic({0x1ae7780, 0x32682c0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/grafana/tempo/modules/frontend.newTraceByIDMiddleware.func1.1(0xc04e4fbe00)
	/drone/src/modules/frontend/frontend.go:169 +0x8f0
github.com/grafana/tempo/modules/frontend.RoundTripperFunc.RoundTrip(0x1dce37d, 0x1dc1f75)
	/drone/src/modules/frontend/middleware.go:13 +0x1f
github.com/grafana/tempo/modules/frontend.(*handler).ServeHTTP(0xc040e14de0, {0x22597b8, 0xc00012e930}, 0xc04e4fbe00)
```

**To Reproduce**
1. Tempo installed via Helm (`tempo` chart, version 0.15.0) in Kubernetes
2. `values.yaml`:

```
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3100"

tempo:
  resources:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 6Gi

  storage:
    trace:
      backend: azure
      block:
        bloom_filter_false_positive: .05
        index_downsample_bytes: 1000
        encoding: zstd
      wal:
        path: /tmp/tempo/wal
        encoding: snappy
      azure:
        container-name: tempo
        storage-account-name: <will_be_replaced_by_secret>
        storage-account-key: <will_be_replaced_by_secret>
      pool:
        max_workers: 100
        queue_depth: 10000

  overrides:
    max_bytes_per_trace: 50000000

  ingester:
    trace_idle_period: 10s
    flush_check_period: 5s
    max_block_bytes: 1_000_000
    max_block_duration: 5m

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
    jaeger: null
    opencensus: null
```

**Expected behavior**
That I can view the Trace in Grafana

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

I'd be happy to provide more information if needed!

**Comment by joe-elliott** [comment]
So 0.15.0 is Tempo 1.4.0. You may want to update to 0.15.1/1.4.1. I don't think it will fix this particular issue, but it does patch a few bugs:

https://github.com/grafana/tempo/releases/tag/v1.4.1

Here is the line in question:
https://github.com/grafana/tempo/blob/6e96c52be52e5e6b63e1189e069fef4488305cd5/modules/frontend/frontend.go#L169

We are definitely not guarding against a nil resp here. In fact, looking a few lines up it really feels like we should be:

https://github.com/grafana/tempo/blob/6e96c52be52e5e6b63e1189e069fef4488305cd5/modules/frontend/frontend.go#L129-L132

If `rt.RoundTrip()` errors and returns a nil resp then this panic would occur. I am seeing this a handful of times in our internal clusters in the past week.

Thanks for the report.

**Comment by joe-elliott** [comment]
It's honestly hard to say. The panic is eating a real error that could be almost anything. If you update your query-frontend to use this image: `grafana/tempo:main-d46f67a` we should be able to get the real error message.

**Comment by jooooel** [comment]
Alright! Yeah, that gave me a much better error message :D 

`failed to get trace with id: 90df50ded8ea88fb976b200b347bffda Status: 500 Internal Server Error Body: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (16380708 vs. 4194304)`

I think that can help me move forward. We're having problems in general with large traces, I think I need to find some params to tune. But I guess using the "monolith" Helm chart isn't the best option in that case, seems to be pretty limited in what I can actually tune 🤔

**Comment by joe-elliott** [comment]
You can use the `server:` field in the helm chart to adjust grpc max message sizes. This field here:

https://github.com/grafana/helm-charts/blob/9c67f70a3bbe6ebefc5b556cab4e1ed180cb91fd/charts/tempo/values.yaml#L41-L43

Is interpolated into the configmap here:

https://github.com/grafana/helm-charts/blob/9c67f70a3bbe6ebefc5b556cab4e1ed180cb91fd/charts/tempo/templates/configmap-tempo.yaml#L23-L24

Docs here (covers most common options):

https://grafana.com/docs/tempo/latest/configuration/#server

Full config struct here:

https://github.com/weaveworks/common/blob/master/server/server.go#L54
