### ISSUE TITLE
Tempo Metrics Generation uses different metrics labels to Grafana Agent

### ISSUE THREAD

**Issue by hedss** [grafana/tempo#1444]
**Is your feature request related to a problem? Please describe.**
In Grafana Agent, the generated metrics labels are:
```bash
traces_spanmetrics_latency_sum
traces_spanmetrics_latency_count
traces_spanmetrics_latency_bucket
traces_spanmetrics_call_counts
```

In Tempo metrics server side we generate metrics called:
```bash
traces_spanmetrics_duration_seconds_sum
traces_spanmetrics_duration_seconds_count
traces_spanmetrics_duration_seconds_bucket
traces_spanmetrics_call_counts
```

Obviously, the first three differ between the Agent and Tempo.

There is also a difference on the label for the status code, in Grafana Agent it's:
```bash
status_code
```
and in Tempo metrics generation it's:
```bash
span_status
```

**Describe the solution you'd like**
We should either consider altering these to the OTel standard, or at least documenting these differences so that should users change from Grafana Agent metrics generation to Tempo, they understand the changes they will need to make.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by knylander-grafana** [comment]
@hedss On the documentation side, is this something that might be handled by a UI error message warning the user?

**Comment by hedss** [comment]
@knylander-grafana That's an interesting question, but Grafana would probably need to understand that trace span metrics are being received and the user's not requesting the right ones, so it'd need to look at panels using those names (or the Explorer). Not sure how viable this is.
