### ISSUE TITLE
Snyk SBOM CI GitHub Action check fails from Pull Requests

### ISSUE THREAD

**Issue by marc-sensenich** [grafana/tempo#1458]
**Describe the bug**

`Snyk SBOM CI / snyk_scans (pull_request)` GitHub Action check fails on a PR due to `Snyk is missing auth token in order to run inside CI. You must include your API token as an environment value: `SNYK_TOKEN=12345678`. See https://github.com/grafana/tempo/runs/6678686899?check_suite_focus=true for an example failed check. This is most likely due to the Snyk API token GitHub Action secret not being propagated to Pull Requests.

**To Reproduce**
Open a Pull Request to https://github.com/grafana/tempo from a fork and as a non-member of https://github.com/grafana

**Expected behavior**

`Snyk SBOM CI / snyk_scans (pull_request)` should pass in CI if it was to run on PRs or failures should be ignored.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

Introduced as part of https://github.com/grafana/tempo/pull/1455

**Comment by TomsioncatiGraf** [comment]
+1 for non-blocking.  Ta!
