### ISSUE TITLE
Redis: Support SentinelPassword

### ISSUE THREAD

**Issue by Poweranimal** [grafana/tempo#1460]
A sentinel redis cluster that is protected by a password cannot be accessed by tempo.

The following error gets thrown:
```text
level=warn ts=2022-05-31T23:20:52.472993079Z caller=experimental.go:19 msg="experimental feature in use" feature="Redis cache"
redis: 2022/05/31 23:20:52 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required.
level=error ts=2022-05-31T23:20:52.480956783Z caller=redis_cache.go:43 msg="error connecting to redis" name=tempo err="redis: all sentinels specified in configuration are unreachable"
```

So far, the `SentinelPassword` is not a configuration options, yet. See [here](https://github.com/grafana/tempo/blob/a9475c4953d9f07ea41993c15844f461056c8573/pkg/cache/redis_client.go#L55).

Extending the redis config with `SentinelPassword` of [redis.UniversalOptions](https://github.com/grafana/tempo/blob/a9475c4953d9f07ea41993c15844f461056c8573/vendor/github.com/go-redis/redis/v8/universal.go#L28) should allow password auth for redis sentinel clusters.

**Comment by joe-elliott** [comment]
Agree this would be a nice change. If you want to take a swing at it, let us know. Otherwise we'll try to handle it when we can.

**Comment by zalegrala** [comment]
I can pick this up.  I'll take a look this week.

**Comment by zalegrala** [comment]
@Poweranimal We've merged a change that should implement what was asked for here.  When you try out the feature, let us know if you have any trouble.

**Comment by Poweranimal** [comment]
@zalegrala 
Thanks a lot for adding the feature.
I’m going to try it out through out this week.

**Comment by Poweranimal** [comment]
Well. a bit late, but I can confirm that the `tempo-querier` and `tempo-compactor` can successfully connect and read/write to redis sentinel.
Thank you very much for your contribution!
