### ISSUE TITLE
Tempo periodically remove blocks

### ISSUE THREAD

**Issue by TruongQToan** [grafana/tempo#1493]
**Describe the bug**
In my setup, I have separated Compactor component into a separate service. I notice that even though the retention period is 72h for the compactor, the blocks that have Age past 24h will get compacted and deleted. I have checked all the logs of Compactor and see that the Compactor doesn't compact those blocks. So there's maybe a bug here.
This is the results of the list block command.
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/12953538/174053805-3b144c1c-4906-41f6-8f3e-b5c015f8b100.png">

After the age of this block `bb17600b-1b52-40a7-9123-624a2056e655` past 24h, it gets compacted.
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/12953538/174054041-4f1222d0-6bae-4732-9373-38396be295cf.png">

**To Reproduce**
I don't know if it can be reproduced or not. It happens on my live env.
**Expected behavior**
Blocks can be retained for 72h, not get deleted in 24h.
**Environment:**
 - Infrastructure: bare-metal for ingesters and distributors. Docker for Compactor.
 -  - Deployment tool: I used Ansible to deploy ingesters and distributors. Compactor are one instance that is deployed separately.

**Comment by TruongQToan** [comment]
This is my config file for compactor
```
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 
  grpc_server_max_recv_msg_size: 4194304_000000
  grpc_server_max_send_msg_size: 4194304_000000

search_enabled: false

compactor:
  compaction:
    compaction_window: 12h
    max_block_bytes: 20_000_000_000
    block_retention: 72h
    compacted_block_retention: 1h

storage:
  trace:
    backend: s3
    block:
      bloom_filter_false_positive: .01
      index_downsample_bytes: 1000
      encoding: zstd
    wal:
      path:       
      encoding: zstd
    s3:
      bucket:
      endpoint: 
      access_key: 
      secret_key:
      insecure: true
    pool:
      max_workers: 100
      queue_depth: 1000

overrides:
  ingestion_burst_size_bytes: 15000000_000000
  ingestion_rate_limit_bytes: 15000000_000000
  max_bytes_per_trace: 0
  max_traces_per_user: 0
```

**Comment by TruongQToan** [comment]
No I have checked the logs of the Compactor but didn't see those lines.

**Comment by joe-elliott** [comment]
Do you have a lifecycle policy on your backend that is removing objects after a certain period of time?

**Comment by TruongQToan** [comment]
This is my backend config.
```
server:
  http_listen_address: 0.0.0.0
  http_listen_port: ${HTTP_PORT}
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: ${GRPC_PORT}
  grpc_server_max_recv_msg_size: 4194304_000000
  grpc_server_max_send_msg_size: 4194304_000000
  log_level: debug

search_enabled: false

querier:
  frontend_worker:
    frontend_address:

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:${RECEIVER_PORT}

ingester:
  lifecycler:
    id: ${RING_ID}
    interface_names:
      - bond0
    ring:
      replication_factor: 1
      kvstore:
        store: etcd
        etcd:
          endpoints:
            
  trace_idle_period: 10s
  max_block_bytes: 1_000_000_000
  max_block_duration: 5m
  flush_check_period: 3s
  concurrent_flushes: 128

storage:
  trace:
    backend: s3
    local:
      path: 
    block:
      bloom_filter_false_positive: .01
      index_downsample_bytes: 1000
      encoding: zstd
    wal:
      path:
      encoding: zstd
    s3:
      bucket: 
      endpoint: 
      access_key: 
      secret_key:
    pool:
      max_workers: 100
      queue_depth: 1000

overrides:
  ingestion_burst_size_bytes: 15000000_000000
  ingestion_rate_limit_bytes: 15000000_000000
  max_bytes_per_trace: 0
  max_traces_per_user: 0
  metrics_generator_processors: [span-metrics]

metrics_generator_enabled: true

metrics_generator:
  ring:
    instance_id: ${RING_ID}
    instance_addr: ${HOST_IP}
    instance_interface_names:
      - bond0
    kvstore:
      store: memberlist
  processor:
    span_metrics:
      dimensions:
      service_map_path:
  registry:
    external_labels:
      source: tempo
      cluster: backend
  storage:
    path:
    remote_write:
      - url:         
      - send_exemplars: true
```
So I don't have any policy like that.

**Comment by TruongQToan** [comment]
No, I don't have that policy for S3. Actually, by looking at the `list block` command, the blocks are compacted and then deleted by the compactor. But I cannot find what process compacts those blocks.

**Comment by joe-elliott** [comment]
I think this is normal Tempo operation. After compacting a block Tempo marks it compacted by moving `meta.json` to `meta.compacted.json`. It will then wait a period of time specified by `compactor.compaction.compacted_block_retention` and then remove the compacted block.

Tempo waits a period of time before removing the old blocks because the various components rely on polling to become aware of changes to the blocks in the backend. By waiting before deleting it allows the queriers and query frontends to continue using the data in the block until they update their internal blocklists.

The process of compaction takes 8 smaller blocks and creates 1 larger one. When the smaller blocks are deleted no data is lost b/c it has all been copied into the larger block.

I will say that it's odd you're not seeing a log line indicating the deletion though. It should be logged here:
https://github.com/grafana/tempo/blob/main/tempodb/retention.go#L53

**Comment by TruongQToan** [comment]
Closed this issue. The problem is that someone has deployed another compactor issue that conflict with this one. So we cannot find the logs.
