### ISSUE TITLE
Wrong component name used in Grafana Trace View

### ISSUE THREAD

**Issue by mecseid** [grafana/tempo#1494]
**Describe the bug**
Inside Grafana, when check a specific trace, the Trace View shows incorrectly the service name, and because of that, draw a wrong trace.
I don't know it's a configuration issue from my side, Tempo, or Grafana issue, so I created the issue here, because I think something not processed correctly from Tempo side.

**To Reproduce**
I attached the JSON export of the trace.
[trace.json.txt](https://github.com/grafana/tempo/files/8918642/trace.json.txt)

**Expected behavior**
As in the attached picture, the latest api-gateway should be nginx.
![component-name](https://user-images.githubusercontent.com/6381828/174066130-14776104-550c-4c0f-8b24-2300fe4b17b5.png)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Version: 1.4.1
 - Grafana version: 9.0.

**Comment by joe-elliott** [comment]
The service.name in the screenshot is "api-gateway" and that is also what its displayed. This seems correct to me.
Are you saying that the service.name should be "nginx"?

Does this happen regularly? Can you give an example trace that when pushed to Tempo triggers this issue?

**Comment by joe-elliott** [comment]
Oh, is this a zipkin trace? Zipkin gives the same span id to parent/child spans that cross service boundaries. We have code here that attempts to unravel that:

https://github.com/grafana/tempo/blob/main/modules/frontend/deduper.go

Possibly this is related.

**Comment by joe-elliott** [comment]
I believe the trace provided is what Tempo is returning to you. Zipkin is an http based protocol and fairly easy to curl directly:

https://grafana.com/docs/tempo/latest/api_docs/pushing-spans-with-http/

If you could provide a trace that, when pushed to Tempo exhibits the issue shown, it would be very helpful for finding any issues.
