### ISSUE TITLE
Include block ID in compactor error messages

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#1499]
If the compactor gets an error reading one of the input blocks, it logs a message like below. In this case it is a corrupted data file:
```
msg="error during compaction cycle" err="error iterating input blocks: error reading objects for records, err: unexpected non-zero len data header"
```

Let's add the block ID that encountered the error which will make troubleshooting much easier.

**Comment by annanay25** [comment]
> good first issue

Oops I already added this in the `vParquet/compactor` - https://github.com/grafana/tempo/pull/1479/commits/bc53205dbf433524449db110230f12e8b8f7bf97

**Comment by electron0zero** [comment]
@mdisibio can this be closed?

**Comment by electron0zero** [comment]
going to close this, if you think this is not done. please reopen.

**Comment by twix14** [comment]
The issue is still valid for non-parquet blocks. I'm on the latest version

```json
{"caller":"compactor.go:120","err":"error iterating input blocks: error reading objects for records, err: unexpected non-zero len data header","level":"error","msg":"error during compaction cycle","ts":"2023-01-24T09:51:36.674766413Z"}
```
