### ISSUE TITLE
s3 storage not working with IAM roles for AWS.

### ISSUE THREAD

**Issue by hd-deman** [grafana/tempo#1500]
**Describe the bug**
IAM roles for service accounts not working with s3 backend

**To Reproduce**
1. Follow this https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
2. add to helm values: 
```
serviceAccount: 
  annotations: 
    "eks.amazonaws.com/role-arn": "<role_arn_here>"
```
3. omit access_key/secret_key the values in s3 storage.

**Expected behavior**
access without access key.

**Environment:**
 - Infrastructure: AWS EKS
 - Deployment tool: Helm

**Comment by mdisibio** [comment]
Hi, it looks like this should be working as another user had success with EKS + IRSA here: https://github.com/grafana/tempo/issues/1285    Can you paste the error message Tempo is logging?  A few things to double check:
* the iam role has all of the needed bucket permissions
* the kubernetes service account looks correct (as described by kubectl or another tool)
* the pods are associated with the service account as expected

**Comment by datsabk** [comment]
Facing this issue at my end - The IAM role is as expected, service account is also assigned but still it doesn't seem to work. 

Are we expected to pass the IAM role as environment variable by any chance?

**Comment by datsabk** [comment]
This is interesting - I just found out that Tempo used Instance role by default instead of Service account role. Thats a concerning thing. Why does it do that? How do I change that behaviour ?
