### ISSUE TITLE
Add more blocklist metrics

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#1502]
The tempo blocklist is polled in the background by the poller, and the poller is interesting because it is the "source of truth" for the rest of the system, and the place with the most accurate view of the blocks in the backend.  It currently records one metric for the number of live blocks: [tempodb_blocklist_length](https://github.com/grafana/tempo/blob/main/tempodb/blocklist/poller.go#L125)

Since we have the entire lists of live and compacted blocks right there, let's record some other useful and easy to calculate metrics.  I propose these new metrics:

* tempodb_backend_objects
  * The total number of objects (traces) in the backend, defined as the sum(meta.TotalObjects).
  * Gauge, int64
  * Labels:  tenant, block status ("live", "compacted")
* tempodb_backend_bytes
  * The total number of bytes in the backend.  Just summing the data files `sum(meta.Size)` would fairly accureate.  We could include index files by also adding `sum(meta.IndexPageSize * meta.TotalRecords)`.  Bloom filters are not straightforward, because while the meta includes BloomShardCount, it doesn't include the shard size.  I have some ideas on this, but I think it's ok to skip. The data file is typically >99% of the block size anyway.
  * Gauge, int64
  * Labels: tenant, block status ("live", "compacted")

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by mdisibio** [comment]
> Can I pick this up?

Hi, thanks for asking!  We are planning to assign this one to a new member of the Tempo team internally.
