### ISSUE TITLE
Kubernetes operator for Grafana Tempo

### ISSUE THREAD

**Issue by pavolloffay** [grafana/tempo#1532]
**Is your feature request related to a problem? Please describe.**

I would like to deploy Tempo by using Kubernetes operator that would take care of deploying and day two operations: scaling, monitoring, upgrading...

**Describe the solution you'd like**

Kubernetes operator with Tempo custom resource definition (CRD).

**Describe alternatives you've considered**

Tempo helm chart https://github.com/grafana/tempo/tree/main/operations/helm 

**Additional context**

**Comment by pavolloffay** [comment]
The operator is currently WIP in this repository https://github.com/os-observability/tempo-operator

**Comment by joe-elliott** [comment]
Closing this issue b/c the operator exists and is fantastic:

https://github.com/grafana/tempo-operator/
