### ISSUE TITLE
Can post and get spans, but no spans in logs or S3.

### ISSUE THREAD

**Issue by toddcooke** [grafana/tempo#1561]
**Describe the bug**
I am able to post spans to tempo using curl, retrieve spans from tempo using curl by traceid, but when I look in the tempo logs or in my S3 bucket, I see no spans.

**To Reproduce**
1. Create an s3 bucket in AWS.
2. Set up a kubernetes cluster.
3. Set up kube2iam (for s3 access). See usage https://github.com/jtblin/kube2iam#usage
4. Install tempo to kubernetes cluster: `helm upgrade --namespace default -f values-tempo.yaml --install tempo grafana/tempo-distributed
`
5. Port forward the distributor port so you can post spans using curl `kubectl --namespace default port-forward "$(kubectl --namespace default get pods | grep tempo-tempo-distributed-distributor | awk '{print $1}')" 9411 &`
6. Port forward the query frontend port so you can retrieve spans using curl `kubectl --namespace default port-forward "$(kubectl --namespace default get pods | grep tempo-tempo-distributed-query-frontend | awk '{print $1}')" 3100 &`
7. Post span using curl `curl -X POST http://localhost:9411 -H 'Content-Type: application/json' -d '[{
 "id": "1234",
 "traceId": "0123456789abcdef",
 "timestamp": 1608239395286533,
 "duration": 100000,
 "name": "span from bash!",
 "tags": {
    "http.method": "GET",
    "http.path": "/api"
  },
  "localEndpoint": {
    "serviceName": "shell script"
  }
}]'`
8. Retrieve span using curl `curl http://localhost:3100/api/traces/0123456789abcdef`

**Expected behavior**
I expect to see logs in the tempo-tempo-distributed-distributor-... pod.

I also expect to see spans (or anything) in my S3 bucket.

**Environment:**
 - Infrastructure: kubernetes cluster
 - Deployment tool: helm

**Additional Context**
Not sure which logs may be useful. I can post them as needed.

Tempo helm values file:
```
search:
  enabled: true
traces:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
  opencensus:
    enabled: true
storage:
  storage:
    trace:
      backend: s3
      s3:
        bucket: redacted
        endpoint: s3.us-east-1.amazonaws.com
      blocklist_poll: 5m
      wal:
        path: /tmp/tempo/wal
        encoding: snappy
      pool:
        max_workers: 100
        queue_depth: 10000
tempo:
  podAnnotations:
    iam.amazonaws.com/role: redacted
distributor:
  podAnnotations:
    iam.amazonaws.com/role: redacted
  config:
    log_received_traces: true
compactor:
  podAnnotations:
    iam.amazonaws.com/role: redacted
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000       # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m
    flush_size_bytes: 5242880
querier:
  podAnnotations:
    iam.amazonaws.com/role: redacted
queryFrontend:
  podAnnotations:
    iam.amazonaws.com/role: redacted
ingester:
  podAnnotations:
    iam.amazonaws.com/role: redacted
  config:
    trace_idle_period: 10s
    max_block_bytes: 1_000_000
    max_block_duration: 5m
    complete_block_timeout: 10m
memcached:
  enabled: false

```

**Comment by joe-elliott** [comment]
"flushing block" is the line it logs when the ingester pushes a block to s3. Something like:

```level=info ts=2022-07-11T20:07:21.467230217Z caller=flush.go:300 msg="flushing block" userid=1 block=5424425a-fee1-42b5-b7b3-ef14137c3b74
```
If you are seeing that log message there should definitely be blocks of traces in your bucket. They would be at:

`s3://<your bucket>/<tenant id>/<block id>`

**Comment by toddcooke** [comment]
That is the weird thing, the s3 bucket is empty.

If I check with the command line:
```
➜  ~ AWS_PROFILE=tempo aws s3 ls <the bucket name>
➜  ~ 
# no output
```

And if I check with the aws console:
<img width="509" alt="Screen Shot 2022-07-12 at 8 13 48 AM" src="https://user-images.githubusercontent.com/7469379/178487434-602dacde-2b5d-4326-bc93-32c050ae7766.png">

**Comment by joe-elliott** [comment]
So it appears that your Tempo instance is just storing all of the traces locally at `/var/tempo/traces`. We just need to figure out why the helm settings did not apply correctly.

**Comment by toddcooke** [comment]
Do you think this is a helm issue on my end or a Tempo issue? It's not clear to me at the moment.

**Comment by toddcooke** [comment]
I was able to get spans into S3 by changing my values-tempo.yaml file to:
```
traces:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
  opencensus:
    enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: staging.tempo
      endpoint: s3.us-east-1.amazonaws.com
    blocklist_poll: 5m
    wal:
      path: /tmp/tempo/wal
      encoding: snappy
    pool:
      max_workers: 100
      queue_depth: 10000

tempo:
  podAnnotations:
    iam.amazonaws.com/role: redacted
distributor:
  podAnnotations:
    iam.amazonaws.com/role: redacted
compactor:
  podAnnotations:
    iam.amazonaws.com/role: redacted
querier:
  podAnnotations:
    iam.amazonaws.com/role: redacted
queryFrontend:
  podAnnotations:
    iam.amazonaws.com/role: redacted
ingester:
  podAnnotations:
    iam.amazonaws.com/role: redacted
```
And otherwise running the same setup as mentioned here: https://github.com/grafana/tempo/issues/1561#issue-1300667704

**Comment by joe-elliott** [comment]
Thanks for reporting the fix back!
