### ISSUE TITLE
Improve Warnings testing and presentation

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1575]
Currently we try to print warnings for the user if their config seems like it might be incorrect:

https://github.com/grafana/tempo/blob/701739d14082396c4a304a4c0c818aa320478523/cmd/tempo/app/config.go#L119

Instead of directly logging, let's adjust this function to return a slice of strings that the caller can then log. Then we can:

- Add tests to confirm it returns the expected strings for a given configuration
- Improve visibility by logging lines like "-- CONFIGURATION WARNINGS --" before we spit out the warnings.

Currently warnings can disappear into the logs:

![image](https://user-images.githubusercontent.com/2272392/178818023-1963d8dc-bdf8-4c27-90b2-3c33322346a0.png)

**Comment by frzifus** [comment]
Hi, can i work on it?

**Comment by zalegrala** [comment]
@frzifus You bet you can work on it!  Assign this issue to yourself if you decide to pick it up, and if you don't mind keep us updated on how its going.  Let us know if any questions come up that can help you along.

**Comment by frzifus** [comment]
awesome! But, might be a stupid question - how do i assign it to me? ^^

**Comment by joe-elliott** [comment]
I'm not sure if you can assign it, but I just did. Give it a shot!
