### ISSUE TITLE
[Feature Request] Zone aware replication

### ISSUE THREAD

**Issue by Whyeasy** [grafana/tempo#1578]
**Is your feature request related to a problem? Please describe.**

When a Tempo cluster grows and grows the chances increase that the data lands in the same zone. To mitigate this it would be great to have zone aware replication like Mimir.

**Describe the solution you'd like**

Zone aware replication feature enabled for tempo so that we are certain the data is replicated in different zones and by doing this making it more reliable.

**Comment by zalegrala** [comment]
Thanks for the bump and the report.  This is something I think we know we want, but not sure about timeline here.  Give us a little bit to discuss and figure out which milestone this goes into.

**Comment by philiptrovato** [comment]
Don't believe its documented in the Tempo repo, but the standard Cortex "Zone Aware" config works fine, example below (zone_awareness_enabled, availability_zone)... Works at least for the ingesters, Have not tried other components. Just need to set it up via the config file and var expansion (`-config.expand-env=true`), as direct configuration via ENV Vars are not supported.

ingester:
  lifecycler:
    # We want to start immediately and flush on shutdown.
    join_after: 0
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /opt/monitoring/tempo/wal/tokens
    ring:
      kvstore:
        store: consul
        prefix: tempo-ingesters/
        consul:
          host: localhost:8500
          acl_token: ${CONSUL_ACL_TOKEN}
          http_client_timeout: 20s
          consistent_reads: false
          watch_rate_limit: 1
          watch_burst_size: 1
      replication_factor: 2
      zone_awareness_enabled: ${TEMPO_ZONE_AWARENESS}
    availability_zone: ${TEMPO_AZ}
    readiness_check_ring_health: false
    interface_names:
    - eth1
    - eth0

**Comment by zalegrala** [comment]
Interesting.

**Comment by zalegrala** [comment]
If anyone in the community has a chance to test and confirm the above, that would be appreciated.
