### ISSUE TITLE
block file number increases dramatically after switching to parquet stoage

### ISSUE THREAD

**Issue by alburthoffman** [grafana/tempo#1587]
**Describe the bug**

**To Reproduce**
1. Start Tempo (SHA or version): main-3e003d6
2. Perform Operations (Read/Write/Others) READ/WRITE

**Expected behavior**
Expect the queries run faster than before. But the queries become slower. And what I suspend is the number of block keeps increasing, while the old v2 storage is very stable and only requires less than 200 blocks.
![image](https://user-images.githubusercontent.com/863684/179654078-e03523c0-bcd7-4eb8-b802-f6545fc29693.png)

The traffic is about 300K spans per second. 

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Comment by annanay25** [comment]
Hi @alburthoffman, thanks for opening this issue.

Yes, we are aware and working on compaction improvements to ensure the blocklist length remains as low as possible. For now, the solution is to horizontally scale compactor replicas, but we will try adding performance improvements in this area over the next couple of weeks.

Meanwhile, if you could provide us with more information on what kind of queries are being executed against Tempo and the relative slowdowns compared to v2, it would help diagnose performance bottlenecks further. Thanks!
