### ISSUE TITLE
Running docker-compose example for otel-collector on Fedora server

### ISSUE THREAD

**Issue by giuliohome** [grafana/tempo#1590]
**Describe the bug**
I'm not able to run the example on Fedora 35 server with podman emulating docker.

**To Reproduce**

```bash
sudo systemctl start podman.socket
sudo DOCKER_BUILDKIT=0 docker-compose up -d
sudo docker-compose ps
```

I see

```
NAME                                        COMMAND                  SERVICE                    STATUS              PORTS
otel-collector-grafana-1                    ""                       grafana                    running             3000/tcp
otel-collector-otel-collector-1             "--config=/etc/otel-…"   otel-collector             exited (1)
otel-collector-prometheus-1                 "--config.file=/etc/…"   prometheus                 created             9090/tcp
otel-collector-synthetic-load-generator-1   "./start.sh"             synthetic-load-generator   exited (1)
otel-collector-tempo-1                      "-config.file=/etc/t…"   tempo                      exited (1)          3200/tcp, 4317-4318/tcp, 9411/tcp, 14268/tcp
```

**Expected behavior**
Container should be running

**Environment:**
 - Fedora server 35 running on virtualbox from windows 10 enterprise laptop
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**
```
[giulio@fedora otel-collector]$ sudo docker-compose logs | grep otel-collector-otel-collector-1
otel-collector-otel-collector-1            | 2022-07-20T10:12:10.107Z   info    service/collector.go:297        Starting otelcol...  {"Version": "v0.32.0", "NumCPU": 2}
otel-collector-otel-collector-1            | 2022-07-20T10:12:10.107Z   info    service/collector.go:236        Loading configuration...
otel-collector-otel-collector-1            | Error: cannot load configuration's parser: error loading config file "/etc/otel-collector.yaml": unable to read the file /etc/otel-collector.yaml: open /etc/otel-collector.yaml: permission denied
otel-collector-otel-collector-1            | 2022/07/20 10:12:10 collector server run finished with error: cannot load configuration's parser: error loading config file "/etc/otel-collector.yaml": unable to read the file /etc/otel-collector.yaml: open /etc/otel-collector.yaml: permission denied
```

**Comment by mapno** [comment]
Hi @giuliohome. So from the logs it appears that the OTel collector is unable to open the config file, and fails to start up due to that. I assume the other services — Tempo and the synthetic-load-generator — fail for the same reason.

I'm not familiar with podman, but this seems to be a specific error for that tools. I've read online that a possibility is running containers with `--privileged` flag. Could you try this and see if that works? I've run it locally with docker and haven't found this issue.

**Comment by giuliohome** [comment]
Thank you for the quick answer. I understand this is too specific of podman so I close the issue. I will test anyway what you suggest and in the meantime I'll try in a google cloud shell and not on fedora. Will open again if it makes sense. Thanks

**Comment by giuliohome** [comment]
Cool! Tested on google cloud shell and Tempo tracing is working there! (I only had to change grafana port to 3003 because I had Theia Cloud Editor on 3000, then I could web preview port 3003 and see an emitted trace id).
The specific issue on Fedora appears complex to be solved, I'll get back here in case I manage to find a  workaround...
