### ISSUE TITLE
Servicegraph support for producer -> consumer spans

### ISSUE THREAD

**Issue by Samuron** [grafana/tempo#1604]
Hello and thank you for your work here! We have started using Servicegraphs and this is a great feature, but I think it can be extended to support even more cases

**Is your feature request related to a problem? Please describe.**
Currently servicegraph only displays relationships between services based on spans with Client and Server kinds, it may make sense to extend the funcionality to treat Producer and Consumer in similar fashion to display relationships between peers that are communicationg using some kind of messaging 

**Describe the solution you'd like**
Treat Producer as Client and Consumer as Server and draw relationship between them

**Describe alternatives you've considered**
Change telemetry to use Client and Server spans insteam of Producer, Consumer

**Comment by mapno** [comment]
Hi @Samuron, thanks for opening this issue. This is exactly what this PR is addressing 😄 
https://github.com/grafana/tempo/pull/1576. It should be merged into Tempo shortly.

**Comment by annanay25** [comment]
@Samuron I'll be closing this issue, feel free to reopen if you have any other questions. Thanks!
