### ISSUE TITLE
[docs] Add information about the linux binary available under release assets

### ISSUE THREAD

**Issue by zhzure** [grafana/tempo#1607]
**hi, thanks for this amazing repo!**
here is the problem:
my application process running on a  2C2G linux machine, which would be deployed privately on customer's machine
is there any way i can install tempo without those huge dependency like docker/k8s
i can't find in [docs](https://grafana.com/docs/tempo/latest/getting-started/example-demo-app/)

**Comment by annanay25** [comment]
Hi @zhzure; thanks for filing this issue.

Tempo releases come with a linux amd64 binary, you can find the latest one here - https://github.com/grafana/tempo/releases/tag/v1.4.1 - under the "Assets" section.

I am going to rename this ticket to reflect the issue with docs!

**Comment by zhzure** [comment]
> Hi @zhzure; thanks for filing this issue.
> 
> Tempo releases come with a linux amd64 binary, you can find the latest one here - https://github.com/grafana/tempo/releases/tag/v1.4.1 - under the "Assets" section.
> 
> I am going to rename this ticket to reflect the issue with docs!

thanks for replying, i find binary in release
but i don't know how to run it, i found some cmd in [docker-compose example](https://github.com/grafana/tempo/tree/main/example/docker-compose/local),but i am not sure if it's the right one to deploy locally, and seems this is no explain about filed in tmpo.config
it's kind of confusing

**Comment by GrafanaWriter** [comment]
@knylander-grafana - can you please review?

**Comment by knylander-grafana** [comment]
We've added instructions tonight for how to install using Linux. I'll add some text for where to find the Assets as well to this PR: https://github.com/grafana/tempo/pull/1954

**Comment by knylander-grafana** [comment]
We've added an example for Linux binary and a link to the release assets under the Release Notes for Tempo with this PR: https://github.com/grafana/tempo/pull/1954
