### ISSUE TITLE
[Docs] Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [grafana/tempo#1620]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:

- How to upgrade Tempo to the newer version (hopefully with no downtime)
- How to downgrade Tempo to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by joe-elliott** [comment]
For specific versions we provide a changelog that highlights any considerations on upgrade. 

In the general case the jsonnet and helm examples "encode" our upgrade procedure using k8s primitives.  e.g.

https://github.com/grafana/tempo/blob/503d8311df02f6da48f04d0805217e217b5cd722/operations/jsonnet-compiled/Deployment-distributor.yaml#L15-L18

https://github.com/grafana/tempo/blob/503d8311df02f6da48f04d0805217e217b5cd722/operations/jsonnet-compiled/Deployment-compactor.yaml#L14-L17

However, I agree it would be nice to have explicit documentation somewhere for those not using k8s for deployments.

**Comment by knylander-grafana** [comment]
I'm going to start tackling this topic for Tempo 2.0.  Loki has this page we can use as a reference: https://grafana.com/docs/loki/latest/upgrading 

So far, I have these topics to cover: 

* Parquet updates for users who used Parquet with version 1.5
* Metrics-generator and search config file updates 
* Overall process
