### ISSUE TITLE
[Doc] Update or create doc for Tempo config using Helm

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#1628]
Update the HELM deployment instructions for Tempo. Right now we have a pointer to a Helm chart that goes to these places: 
* GET: https://github.com/suitupalex/helm-charts/tree/enterprise-traces/charts/enterprise-traces
* Tempo: https://github.com/grafana/tempo/tree/main/example/helm 
* Helm chart PR: https://github.com/grafana/helm-charts/pull/1759 

We don't have any instructions for Tempo for Helm configuration. Our [instructions for Tempo](https://grafana.com/docs/tempo/latest/getting-started/example-demo-app/) point to the above repo link.  

* Community has a Helm chart.
* Is the Helm chart for GET linked above provided by Grafana?

Possible SME: @zalegrala is researching Helm charts -- See https://github.com/grafana/helm-charts/pull/1701

Verify default values are correct. See https://github.com/grafana/tempo/issues/2047

Example Mimir docs:
* Doc in repo:  https://github.com/grafana/mimir/blob/main/docs/sources/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/_index.md
* Helm chart get started guide in Mimir: https://grafana.com/docs/mimir/latest/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/
* Helm chart for production in Mimir: https://grafana.com/docs/mimir/latest/operators-guide/running-production-environment-with-helm/configuration-with-helm/ 
* See also https://github.com/grafana/mimir/blob/main/docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md

Technical requirements: 

Helm chart doc should follow the same location structure as the Mimir helm chart doc: https://github.com/grafana/mimir/tree/main/docs/sources/helm-charts/mimir-distributed

Content should appear on the Helm chart doc landing page (Loki and Mimir are there)

**Comment by zalegrala** [comment]
I've started some modifications on the Helm chart above.  I think I should be able to get it working today.

**Comment by knylander-grafana** [comment]
See Mimir doc for Helm: https://github.com/grafana/mimir/pull/2299/files

Also, several members of the Doc Squad (Ursula, me, Chris, Fiona) are working with Helm chart people (Zach Leslie, Krajo) to work on how Helm chart documentation is presented to our customers. See [Notes - Helm char docs](https://docs.google.com/document/d/1Coex4V5ePJBciTNl2-6vOjUbFAmBFaUt9PKC2nTHqIE/edit?usp=sharing) Google file for notes.

**Comment by knylander-grafana** [comment]
@GrafanaWriter I'm going to schedule some time with @hedss to write the Tempo and GET doc for the helm chart for the Tempo 2.0 release. 
@osg-grafana should be a reviewer on this project.

**Comment by knylander-grafana** [comment]
See Loki blog post about Helm charts - https://grafana.com/blog/2022/12/19/the-only-helm-chart-you-need-for-grafana-loki-is-here/

New Helm portal is supposed to go live on Jan 9th. https://github.com/grafana/website/issues/10900#issuecomment-1355099192

**Comment by GrafanaWriter** [comment]
Moving to in progress based on the comments above 🎉

**Comment by knylander-grafana** [comment]
@hedss found two issues with the Helm charts. He created a PR to address these issues ( https://github.com/grafana/helm-charts/issues/2111, https://github.com/grafana/helm-charts/issues/2112): https://github.com/grafana/helm-charts/pull/2131 

Unfortunately, this doc is on hold until the above issue is resolved.

**Comment by knylander-grafana** [comment]
@joe-elliott  has been working on the Tempo helm-charts repo to address some of the issues (not related to the issue Heds found). 

I'm going to meet with Zach today to see what we can do to create a basic Helm cart doc for Tempo.

**Comment by knylander-grafana** [comment]
@zalegrala and I have created a draft Helm procedure for Tempo. I've been able to walk through the procedure and install the Helm chart itself and have the nodes start in the K8s cluster on my laptop. However, I have to work on storage configuration to get things working correctly.

**Comment by knylander-grafana** [comment]
@osg-grafana: @jdbaldry has a PR in the Tempo repo (https://github.com/grafana/tempo/pull/2096) to move the doc files so they mirror the Mimir repo's doc structure. This will let us have the Tempo Helm doc appear in the Helm doc portal.

**Comment by zalegrala** [comment]
@knylander-grafana Is there a branch I can review for the draft change?

**Comment by knylander-grafana** [comment]
Last Friday, Zach and I spent two hours reviewing the doc and updating. The PR was shared with the internal tempo and Helm channels for review.

**Comment by knylander-grafana** [comment]
Should we use the values.yaml or the custom.yaml file? After reading through the values.yaml file for the tempo-distributed helm chart, I updated the Helm doc PR with suggestions for using values.yaml. These changes are not merged, however the procedure itself works. I can test things, but I don't know how to verify that the Helm values are set properly. 

Zach has also created a PR with Helm chart examples, including custom.yaml: https://github.com/grafana/tempo/pull/2124 

This makes me think that the better option is to use the custom.yaml file. The values.yaml file is pretty complicated and would be nice to have as simple as possible. 

The questions I have are: 
* What is the best practice? 
* If values are not set in customer.yaml (like the username and passwords), are those values defaulted to the ones present in values.yaml? 

I am going to meet with @zalegrala this week to hopefully answer these questions.
