### ISSUE TITLE
Metrics Generator Prometheus out of order bug

### ISSUE THREAD

**Issue by altanozlu** [grafana/tempo#1640]
**Describe the bug**
Sometimes tempo enters to a loop even i restart tempo, prometheus doesn't accept remote write because it's out of order.
Only solution i have found is, removing tempo data then restarting.

**Environment:**
 - Tempo version is 8179c436c150162d7f1484c1eb0c59b48c10d921
 - Infrastructure: Ubuntu 22 in GCP
 - Go version: go1.19 linux/amd64
 - Using single binary

**Additional Context**
Prometheus logs:
```
ts=2022-08-03T04:50:03.404Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=456
ts=2022-08-03T04:50:03.408Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=425
ts=2022-08-03T04:50:03.412Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=410
ts=2022-08-03T04:50:03.416Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=302
emplars" num_dropped=477
ts=2022-08-14T19:18:02.373Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=487
ts=2022-08-14T19:18:02.380Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=475
ts=2022-08-14T19:18:02.387Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=473
ts=2022-08-14T19:18:02.392Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=467
ts=2022-08-14T19:18:02.399Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=432
ts=2022-08-14T19:18:02.405Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=427
ts=2022-08-14T19:18:02.410Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=434
ts=2022-08-14T19:18:02.417Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=428
ts=2022-08-14T19:18:02.423Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=430
ts=2022-08-14T19:18:02.429Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=415
ts=2022-08-14T19:18:02.436Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=411
ts=2022-08-14T19:18:02.442Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=314
```

At 22:20 i've removed tempo data folder and created it then restarted tempo.

<img width="1581" alt="Ekran Resmi 2022-08-14 23 03 27" src="https://user-images.githubusercontent.com/5479094/184553203-be623195-f444-4f9f-85a7-6265008a961c.png">

**Comment by joe-elliott** [comment]
So we do keep an on disk metrics WAL, but I believe it's mainly for local queuing. It would be fine to wipe this file every time Tempo starts.

So is the out of order data it's failing to push always exemplars? Is that metric you are showing the metrics generated from Tempo?

**Comment by altanozlu** [comment]
> So we do keep an on disk metrics WAL, but I believe it's mainly for local queuing. It would be fine to wipe this file every time Tempo starts.
> 
> So is the out of order data it's failing to push always exemplars? Is that metric you are showing the metrics generated from Tempo?

metrics are generated by tempo, it's keep failing and sometimes work, best way to fix it is removing tempo data

**Comment by joe-elliott** [comment]
When we deploy the metrics generator we purposefully an empty dir so the wal is wiped on restart.

https://github.com/grafana/tempo/blob/fce278e853b7a0e6fb04f4e098d8e436be93a074/operations/jsonnet/microservices/generator.libsonnet#L53

@kvrhdn what happens if prom remote write falls behind? do we lose data since we wipe the wal on restart?

**Comment by kvrhdn** [comment]
The WAL is indeed only used for caching samples on disk before sending them, this reduces memory pressure if an outage happens. The pointer of the remote writer isn't persisted unfortunately, so after a restart it will continue sending from the end of the file, not wherever it was at before. So if the remote write falls behind and the instance is restarted, some samples will not be sent.
When the metrics-generator is shut down, it tries to flush all the samples. So during a clean shutdown all samples and exemplars should have been sent.

We use the Prometheus code, so our WAL will behave exactly the same as the Prometheus Agent. I know the Prometheus folks are working on persisting the remote write marker, so this might improve in the future.

That said, I have not seen this error before. Does this only start happening after a restart? Maybe the instance is being shutdown incorrectly?

**Comment by altanozlu** [comment]
as far as i remember, it happened after i change config (i don't wait much to shut it down i just keep pressing ctrl + c) or restarting after https://github.com/grafana/tempo/issues/1592
idk if it's related to it but there is also https://github.com/grafana/tempo/issues/1592#issuecomment-1239257823

**Comment by kvrhdn** [comment]
https://github.com/grafana/tempo/issues/1592 shouldn't be related since the metrics-generator does not do anything with Parquet. I think the way you shut down might be causing issues, when we receive the shutdown signal we try to flush the remaining data and afterwards wipe the directory (since it isn't used anyways): https://github.com/grafana/tempo/blob/0cd8a36210fbf2e46ed1007ec9810bc5f617c73c/modules/generator/storage/instance.go#L97-L99
If you shutdown the process while it's still writing data the data might get corrupted. Wiping the data isn't required for a clean shutdown but there is no need to hold on to it either.

I'd say avoid try to avoid those abrupt shutdowns or otherwise just always wipe the metrics-generator WAL before restarting the component.
