### ISSUE TITLE
Docs feedback: /api_docs/_index.md

### ISSUE THREAD

**Issue by carlosjgp** [grafana/tempo#1641]
Link to "the global override strategy" is broken (404)
![image](https://user-images.githubusercontent.com/1277613/184613397-d3442955-f35e-47a0-b7f5-4f551f3302d3.png)

**Comment by knylander-grafana** [comment]
The content was moved but not forwarded. The 404 link in the note should go to this page: https://grafana.com/docs/tempo/latest/configuration/#overrides

**Comment by joe-elliott** [comment]
Thanks for the report!
