### ISSUE TITLE
1.5.0-rc2: Distributor fails to start with s3 error

### ISSUE THREAD

**Issue by rlex** [grafana/tempo#1648]
**Describe the bug**
Ran tempo-distributed chart with tempo set to 1.5.0-rc2 image tag for testing.
Got distributor in crashloop with following error in logs: 

```
level=error ts=2022-08-16T20:08:14.211177646Z caller=main.go:109 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on yggdrasil-tempo: The AWS Access Key Id you provided does not exist in our records."
```
Even if i pass S3 data to distributor it still fails to start with same error.
Not quite sure why distributor even needs s3 access? Maybe analytics like in loki too? https://github.com/grafana/loki/issues/6572#issuecomment-1174610650

metrics generator also failed to start until i added S3 creds to env. 

If that matters, i add s3 to config with env vars:
```
      - storage:
          trace:
            block:
              version: vParquet
            backend: s3
            s3:
              access_key: ${S3_ACCESS_KEY_ID}
              bucket: example-tempo
              endpoint: s3.eu-central-2.example.org
              region: eu-central-2
              secret_key: ${S3_SECRET_KEY}
```
and expandenv set to true.

**To Reproduce**
1. Start Tempo with tempo-distrubuted with tag set to 1.5.0-rc2
2. Observe error

**Expected behavior**
Tempo should start

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm with tempo-distributed chart.

**Comment by joe-elliott** [comment]
Yes, this is due to the addition of usage stats. It's mentioned in the 3rd bullet point under breaking changes:

https://github.com/grafana/tempo/releases/tag/v1.5.0-rc.0

We will also highlight this change in the announcement blog post and include details for those who want to disable it. You can either add the appropriate configuration/permissions for s3 or disable it using the following yaml:
```
usage_report:
  reporting_enabled: false
```

**Comment by rlex** [comment]
> You can either add the appropriate configuration/permissions for s3

that worked for metrics-generator but not for distributor

**Comment by joe-elliott** [comment]
It seems like you're getting the error: `The AWS Access Key Id you provided does not exist in our records.`

Can you double check the correct credentials have been supplied?

**Comment by rlex** [comment]
they're shared between all components and sourced from single secret, so yeah, should be ok. I'l a bit afk for now, but i'll check later. Might be misconfig on my side indeed.
Btw, 1.5 added /var/tempo for distributor too? I noticed that it fails to create folders with r/o FS, but even if i add mount for it, i don't see any files, only some pre-created folders.

**Comment by joe-elliott** [comment]
Thanks for double checking. The reason the distributor is accessing `/var/tempo/wal` is because of this line:

https://github.com/grafana/tempo/blob/fce278e853b7a0e6fb04f4e098d8e436be93a074/cmd/tempo/app/modules.go#L394

I don't believe `UsageReport` should depend on `Store`. Checking now.
