### ISSUE TITLE
S3 storage configuration: prefix and canned acl

### ISSUE THREAD

**Issue by mbaurnwal546** [grafana/tempo#1656]
**Is your feature request related to a problem? Please describe.**
Can we have the capability to provide s3 bucket prefix and canned acl (`canned_acl: bucket-owner-full-control`) in s3 storage configuration.

**Describe alternatives you've considered**
Jaeger is alternative option to use OpenSearch as storage option.

**Comment by joe-elliott** [comment]
Does that work? Wouldn't you still need to provide credentials that have the `canned_acl`? I wouldn't think a process could start up and request an ACL without credentials.

**Comment by mbaurnwal546** [comment]
canned_acl need to provide along with credentials. Can we expect these two(s3 bucket prefix and canned_acl) parameter ?

**Comment by mdisibio** [comment]
Hi, our understanding is that canned acls are configured on the bucket, and client apps (like Tempo) are unaware of them.  Tempo doesn't create S3 buckets automatically, they must be created before running Tempo. If you want to set ACLs on your bucket that should already be possible.   However, I am noting that the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acls.html) recommends disabling ACLs and using bucket or object policies instead.   Can you provide a link or more detail of how a client app uses the canned acl?
