### ISSUE TITLE
Performance: store traceid to time mapping

### ISSUE THREAD

**Issue by hanjm** [grafana/tempo#1659]
**Is your feature request related to a problem? Please describe.**

Currently, find trace by id will iterate all block list, when span volume is very large and retention long time like 7days, the performance is poor.
if we could store extral trace id mapping, it will only iterate a few of blocks, improve a lot.
https://github.com/grafana/grafana/pull/48068#issuecomment-1171232882
**Describe the solution you'd like**

store traceid to time mapping when ingestor.
model:
traceid, start, end.
write:
group by traceid in a batch. store min(timestamp) as start. max(timestamp) as end.
store boltdb, sync to object store.
read:
read boltdb get traceid time range first, if it has more than one records, use min(start) as start, max(end) as end.
**Describe alternatives you've considered**

**Additional context**

**Comment by joe-elliott** [comment]
I'm concerned about how this would work at scale. Do you have any size estimates for the boltdb in question? We currently are storing 54B traces in our Tempo ops cluster. I'm concerned about the size of the boltdb file and the code necessary to ship and coordinate it.

Also, tempo currently supports a time range on query (which reduces the blocks searched):

https://grafana.com/docs/tempo/latest/api_docs/#query

and there is effort to get this integrated into Grafana:

https://github.com/grafana/grafana/pull/48068

Perhaps this meets your needs?

You can also try increasing query_frontend.query_shards from default and scaling up queriers. As well as caching bloom filters.
