### ISSUE TITLE
Allow configuring S3 StorageClass

### ISSUE THREAD

**Issue by amitsetty** [grafana/tempo#1684]
Currently I can’t configure grafana tempo to use the SATA S3 StorageClass

Would want to add this as a configurable feature

**Comment by joe-elliott** [comment]
Can you give more information about how you would expect this feature to be enabled in Tempo? Is this something that can be configured on the bucket?

**Comment by ArpStorm1** [comment]
Hey @joe-elliott ,
I think what @amitsetty is meaning is to change the default storage class.
The default storage class is STANDARD, and it is the most expensive class in Amazon.
It would be great to have a configurable option to change that to STANDARD_IA or even GLACIER.

**Comment by joe-elliott** [comment]
Ok, did some research. I figured this was something that was configurable on the bucket, but it seems like this is set at upload time?

I am open to a PR to set this. I believe it would need to be set in two places:

https://github.com/grafana/tempo/blob/e177ad0b1e830501d991dc73991ea5d31df038e0/tempodb/backend/s3/s3.go#L110
https://github.com/grafana/tempo/blob/e177ad0b1e830501d991dc73991ea5d31df038e0/tempodb/backend/s3/s3.go#L141

Also, i'm thinking we need a method to generate `PutObjectOptions` given the current config. 

I would however warn against using storage classes such as Glacier as Tempo objects are accessed constantly.
