### ISSUE TITLE
Add a PodDisruptionBudget to our Ingesters

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1686]
A [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) tells k8s the maximum number of a given set of pods that can be down at a given time.

During a recent event in our ops cluster k8s was rescheduling ingester pods 3 or 4 at time which was causing down ingestion.

Let's add a PDB to our jsonnet with `maxUnavailable: 1`

**Comment by zalegrala** [comment]
https://github.com/grafana/tempo/issues/1571 also.

**Comment by joe-elliott** [comment]
Closing in favor of #1571
