### ISSUE TITLE
[Doc] Document load testing with K6 for Tempo

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#1711]
Based [upon this thread](https://grafana.slack.com/archives/C01D981PEE5/p1662006302803279) in the Tempo Slack channel, we should create a page for how to load test Tempo. 

Mario suggested these options: 

1. The [synthetic-load-generator](https://github.com/Omnition/synthetic-load-generator) is an awesome tool for generating real-looking traces. Although it's not built specifically for load testing, we've used it to load test Tempo many times in the past. It's also used in almost every Tempo example.

1. Similarly, the [TNS demo](https://github.com/grafana/tns/) can be adapted to send traces to Tempo.

1. There is a [k6 extension](https://github.com/grafana/xk6-distributed-tracing) for distributed traces. k6 is a fantastic tool for load testing, but the traces generated are not as good as in the other tools.

Initially, the page should start with the K6 content and then expand to the include the TNS and synthetic-load-generator examples. 

This page should live in either Deployment and operations section or possibly Configuration section (what to do after you've set up Tempo).

**Comment by hedss** [comment]
I have a strong opinion, weakly held, that we should be able to use k6 with recorded traces to be able to do really good load testing. This is part of the roadmap for the Brokkr system FE is building.
