### ISSUE TITLE
Bulk Trace export

### ISSUE THREAD

**Issue by rogeralsing** [grafana/tempo#1717]
**Is your feature request related to a problem? Please describe.**

Allow bulk export of traces via API.
I'm currently working on a tool that applies analytics on the trace data, to pinpoint bottlenecks, hot paths etc.
Right now I'm using the search API to find traces, and then read them one by one.

This works, but does not scale. as there is a high chance that the system might have more traces coming in, than the Tempo API manages provide.

TLDR; the benefit is that tools could be built that leverage Tempo data to provide additional value to having tracing.

**Describe the solution you'd like**

Any form of bulk retrieval API, be it using paging/offset/trace id between x and y/stream based export over e.g. Kafka , gRPC streaming. 

**Describe alternatives you've considered**
I can of course hammer the Tempo API with concurrent requests, but at least in our case with selfhosted Grafana, performance for other users degrade quickly

**Additional context**

**Comment by joe-elliott** [comment]
We are currently moving to our new backend format based on Apache Parquet. Given the wide range of tools designed to import and analyze parquet in object storage do you think this would meet your needs?

**Comment by rogeralsing** [comment]
I have no experience with Parquet, but if it keeps all the trace information and tags I suppose it will do what I need.
Thanks
