### ISSUE TITLE
Issue with Service Graph

### ISSUE THREAD

**Issue by vishnuraj555** [grafana/tempo#1719]
We have enabled the service graph and could see the span-metrics and service-graph process getting added. However, I see in the victoria metrics backend, only span metrics are present. the service graph metrics are not getting generated.

Can you assist why this behavior? Any documentation will also help.

We use OTEL collector for the same. Because of the same, I am not able to visualize the service graph using grafana.

My metric generator configuration:

[conf.txt](https://github.com/grafana/tempo/files/9495189/conf.txt)

**Comment by mapno** [comment]
Hi @vishnuraj555, the service graph processor has some requirement to be able to pair up spans. You can read about it [here](https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/#how-they-work). Can you confirm that your spans have the required `span.kind` tags?

**Comment by vishnuraj555** [comment]
Hi @mapno 

Thanks for the quick update.

Yes we have span.kind in the collector and is visible in the grafana. I am giving the screen-shot as well as the logs from collector here. Do we need to set any specific tag at the otel collector level?

If you have any documentation around it, will be helpful.


<img width="929" alt="Screenshot 2022-09-06 at 5 31 44 PM" src="https://user-images.githubusercontent.com/18710372/188630467-65b3bf8a-0f3f-4764-a9b0-5d57b1fcc19c.png">


Logs also attached below:



[span.txt](https://github.com/grafana/tempo/files/9496717/span.txt)
