### ISSUE TITLE
Include missing file data if querier fails to find trace by ID

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/tempo#1730]
**Is your feature request related to a problem? Please describe.**

In the event you have corruption within a folder, for instance if bloom files are missing, querier will fail to iterate over it and then log a somewhat opaque error like the following:

````
level=warn ts=2022-09-09T21:51:49.828334419Z caller=querier.go:246 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: bd96ed36-2e90-42f0-9d3f-995b3290be17: error retrieving bloom (single-tenant, bd96ed36-2e90-42f0-9d3f-995b3290be17): does not exist"
````

**Describe the solution you'd like**

A list of the bloom files or other files, or even a subset of those files if the list is long, would be helpful debugging info.

**Describe alternatives you've considered**

You can examine the folder to see if the bloom files do not miss a number.

**Additional context**

If this is irrelevant with the parquet backend, we can close.

**Comment by joe-elliott** [comment]
This is not a bad idea. I think we could probably wrap errors in these methods to include information about the requested objects:

https://github.com/grafana/tempo/blob/9a135a959b131754247487ff93a2ecaace88a036/tempodb/backend/raw.go#L116-L131

**Comment by joe-elliott** [comment]
Oof, scratch that. We check the return of a lot of these methods with statements like:
```
if err == backend.ErrDoesNotExist {
```
If we wrapped the error on the lines recommended above it would break these checks. Perhaps it would be better just to make the log change where we request the bloom filters:

https://github.com/grafana/tempo/blob/9a135a959b131754247487ff93a2ecaace88a036/tempodb/encoding/v2/backend_block.go#L56

https://github.com/grafana/tempo/blob/9a135a959b131754247487ff93a2ecaace88a036/tempodb/encoding/vparquet/block_findtracebyid.go#L150

**Comment by AlexDHoffer** [comment]
Cool I'll take a look
