### ISSUE TITLE
Separate retention for traces with exemplars 

### ISSUE THREAD

**Issue by amitsetty** [grafana/tempo#1750]
**Is your feature request related to a problem? Please describe.
Storing traces is very expensive. Having the capability to have a different retention time to those which are exemplars would allow to get rid of the majority of the traces and save storage after a given time (2 days for instance) while still being able to view traces from exemplars 

**Describe the solution you'd like**
Compactor learns to differentiate between and hold separate retentions for traces with exemplars and without

**Describe alternatives you've considered**
Sampling is some sort of half solution (just with the drawback of not holding all new info which will be important in my opinion for automations on very recent data for at least my user stories

**Additional context**
In reality I would want a full connection with Loki and with some tool that doesn’t exist to allow me to save traces from times where my system is not performing well based off of some sort of slo. This seems leagues ahead of where we are and way out of the current scope of the project but overall the idea is that I’m losing my traces way too early and while everything is emensely powerful I’d want to be able to continue enjoying my traces without the need for storing so many that I won’t look at

**Comment by joe-elliott** [comment]
> Compactor learns to differentiate between and hold separate retentions for traces with exemplars and without

We would either need a way to query a metrics backend or tag the trace in some manner to indicate this is an exemplar trace. In our internal cluster Tempo is compacting 90k traces/second. This would be quite a load for the metrics backend. If there was a way to add a tag to a trace that indicated it was an exemplar this would be significantly easier.

Also, generally, exemplars only live for hours while it's easy enough to keep a trace retention of a few days even in the largest cluster. How long do you keep your exemplars?

> In reality I would want a full connection with Loki and with some tool that doesn’t exist to allow me to save traces from times where my system is not performing well based off of some sort of slo. This seems leagues ahead of where we are and way out of the current scope of the project but overall the idea is that I’m losing my traces way too early and while everything is emensely powerful I’d want to be able to continue enjoying my traces without the need for storing so many that I won’t look at

This may not be as hard as you think. If the information is local to the trace then it would be "easy" to make a decision on whether or not to keep at compaction time. For instance, with regard to your SLOs, it would not be too difficult to write code that applied a longer retention to traces with a longer duration or ones that have specific tags. Though, it will be more costly then the current approach.

A similar idea was requested here: https://github.com/grafana/tempo/issues/1427. If someone is up for moving this idea forward we would accept the PR, but it will require some discussion on approach.

**Comment by amitsetty** [comment]
Hey @joe-elliott thanks for the response. 

It seems like the issue of not really being able to leverage the beautify of traces once exemplars expire will be addressed by traceql in some sort which will give me some reason to store the traces after exemplars expire. This is a step in the right direction and also serves so many more use cases. Guess it’s best for the project to continue focusing its energy there for now!
