### ISSUE TITLE
Vulture can search for traces it never generated

### ISSUE THREAD

**Issue by rfratto** [grafana/tempo#1761]
Vulture currently searches for traces assuming that traces are sent every 15 seconds (customized by `--tempo-write-backoff-duration`). 

However, if a single write takes twice as long as the write backoff duration (either due to a latency spike or a service disruption), one write interval will be skipped. This means that searching for a trace in this time span will always be reported as missing, since Vulture never generate a trace for that time window.

**Comment by zalegrala** [comment]
The current workaround is to restart the vulture when there is a known service disruption.

**Comment by rfratto** [comment]
> However, if a single write takes twice as long as the write backoff duration (either due to a latency spike or a service disruption), one write interval will be skipped. This means that searching for a trace in this time span will always be reported as missing, since Vulture never generate a trace for that time window.

Looking into it more, I don't think this is actually true. It generates a new goroutine to send traces so it should be fine. 

I have seen some instances where it queries for things that never get sent, but now I don't think it's because a given write took too long.

**Comment by rfratto** [comment]
> The current workaround is to restart the vulture when there is a known service disruption.

We force kill our pods every 60 minutes to do some chaos engineering, this wouldn't be a reliable workaround for us :)

**Comment by rfratto** [comment]
I'm not sure what might be going on here then. I'm seeing a few instances where Vulture queries for seeds that didn't get written:

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/630212/192404416-00b2e390-a689-403b-8834-45af0310ad28.png">

(I'm assuming it never got written because there's no `sending trace` line for this seed)

**Comment by rfratto** [comment]
Oh, never mind, it's late so I misread the code. There's only a new goroutine for the [long writes](https://github.com/grafana/tempo/blob/62e7fc1bf0fb59e8f16c7af1e6e1135273cc1fa4/cmd/tempo-vulture/main.go#L222), but the initial call to EmitBatches still happens in the [same goroutine](https://github.com/grafana/tempo/blob/62e7fc1bf0fb59e8f16c7af1e6e1135273cc1fa4/cmd/tempo-vulture/main.go#L130) as the ticker and can skip multiple intervals during an outage.

**Comment by rfratto** [comment]
It'd be possible to use bitflags in uint64s to track whether traces were sent for a given interval, though it'd be a bit of complicated code.

Assuming the defaults (336h search space, writing spans every 15s), you would only need 10KB of memory to track which intervals actually had metrics sent:

```
336 hours = 1,209,600 seconds 
1,209,600 seconds / 15/s interval = 80,640 intervals 

80,640 intervals / 64 = 1,260 uint64s 

1,260 uint64s = 10,080 bytes = 10KB  
```

It'd obviously be much easier to not search over a two week window (since errors can persist and make alerts fire longer), but I understand that's not a design goal of Vulture since Vulture wants to check that data doesn't get lost before the retention period elapses.
