### ISSUE TITLE
Ability to access status_message standard field from `span_metrics`

### ISSUE THREAD

**Issue by alsterg** [grafana/tempo#1764]
**Is your feature request related to a problem? Please describe.**
I'm trying to extract the status.message attribute from a span using span_metrics processor, but it doesn't seem to work. I can see in my traces that this attribute is set, but Tempo metric-generator will not pick it up. I wonder if it is the same issue as in this OpenTelementry bug: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14175

**Describe the solution you'd like**
I should be able to do:
```
          span_metrics:
            dimensions:
            - status.message
```
and pull the status.message out from Span attributes.

**Describe alternatives you've considered**
I tried to use OpenTelemetry Collector to do the same (with the attribute processor), but it is not feasible there too.

**Additional context**
I had a slack conversation with Koenraad, who acknowledge the issue:
"So it seems to be a field set on the Status object of a span (so next to status.code). The way the span metrics processor is designed we only look for field names in the span and resource attributes. status.message isn’t an attribute but a built-in field and can not be looked up this way. If you want you can open an issue for this, we can consider adding it so that if you specify status.message we now to look in the status object."

**Comment by joe-elliott** [comment]
I agree with Koenraad's take here. This shouldn't be too difficult to add if anyone wants to take it on.
