### ISSUE TITLE
Trace information lost after less than 1h, dispite of retention settings

### ISSUE THREAD

**Issue by devops-42** [grafana/tempo#1767]
**Describe the bug**
Tempo/Grafana behaves similar to #1168: Tempo receives traces which can be queried in Grafana. After about 1 hour, the trace information seems to be lost: Grafana returns error messages like:
```
failed to get trace with id: <traceID> Status: 404 Not Found Body: trace not found
```

**Environment:**
The setup is:
- tempo-distributed via helm chart
- Azure blob storage for persistence
- rendered `tempo.yaml` used by the services:
```

compactor:
  compaction:
    block_retention: 48h
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
  ring:
    kvstore:
      store: memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - grafana-tempo-tempo-distributed-gossip-ring
metrics_generator_enabled: false
multitenancy_enabled: false
overrides:
  per_tenant_override_config: /conf/overrides.yaml
querier:
  frontend_worker:
    frontend_address: grafana-tempo-tempo-distributed-query-frontend-discovery:9095
search_enabled: true
server:
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  http_listen_port: 3100
  log_format: logfmt
  log_level: info
storage:
  trace:
    azure:
      container-name: **REDACTED**
      endpoint-suffix: **REDACTED**
      storage-account-key: **REDACTED**
      storage-account-name: **REDACTED**
    backend: azure
    blocklist_poll: 5m
    cache: memcached
    local:
      path: /var/tempo/traces
    memcached:
      consistent_hash: true
      host: grafana-tempo-tempo-distributed-memcached
      service: memcached-client
      timeout: 500ms
    wal:
      path: /var/tempo/wal
```

As a first investigation I removed the `local` part from the configuration file to avoid, that tempo writes the WAL information into the ephemeral storage of the pod. After restarting all pods the situation remains unchanged.

Any ideas where my fault is?

Thanks for your help in advance!

**Comment by joe-elliott** [comment]
So your configuration looks basically correct. Your poll cycle is tight so the queriers should be aware of the blocks in the backend. Some things to check:
- Are you seeing the compactors log block deletions? i.e. is your data actually being deleted or is it just not being queried
- Are your queriers seeing the blocks in the backend? See what the value of the metric `tempodb_blocklist_length` is on your queriers. It will tell us if the queriers are even aware of the blocks.

**Comment by devops-42** [comment]
Hi @joe-elliott 

thanks for your response.

In the compactor log repeatedly these messages occur:
```
level=info ts=2022-09-29T07:42:35.320458023Z caller=poller.go:191 msg="writing tenant index" tenant=fake metas=0 compactedMetas=0
level=error ts=2022-09-29T07:42:35.351091189Z caller=tempodb.go:441 msg="failed to poll blocklist. using previously polled lists" err="failed to parse index_*****: invalid UUID length: 11"
```

The querier log has this triple:
```
level=info ts=2022-09-29T07:46:48.065704447Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=fake createdAt=2022-09-29T07:42:35.320499224Z metas=0 compactedMetas=0
level=error ts=2022-09-29T07:46:48.074754262Z caller=poller.go:179 msg="failed to pull bucket index for tenant. falling back to polling" tenant=index err="does not exist"
level=error ts=2022-09-29T07:46:48.086736449Z caller=tempodb.go:441 msg="failed to poll blocklist. using previously polled lists" err="failed to parse index_*****: invalid UUID length: 11"
```

When querying a distinct trace id the query-frontend logs:
```
level=info ts=2022-09-29T07:50:05.124362305Z caller=handler.go:119 tenant=single-tenant method=GET traceID=92e890dcbbf9435e url=/api/traces/65cd260b09eefeb426a9976df7d3e44d duration=10.843259ms response_size=0 status=404
```

What I noticed: `tenant` is named `fake` in compactor logs, but `single-tenant` in query-frontend. Could you tell me how to interpret the error messages? 

What I forgot to mention: We use Tempo in combination with Grafana and Loki. Loki is configured to persist the log information in Azure blob storage too, which seems to work as expected.

**Comment by joe-elliott** [comment]
It seems like you have a rogue file in your bucket that is causing polling to fail: `index_*****`. Try removing it.
