### ISSUE TITLE
Log span name when logging received spans in distributors

### ISSUE THREAD

**Issue by suraciii** [grafana/tempo#1788]
**Is your feature request related to a problem? Please describe.**

Currently distributor does not write span names into logs when logging spans by enabling `log_received_spans`, even with `include_all_attributes` on.

**Describe the solution you'd like**

Add span name into log context when logging span with all attributes.

For example:
``` diff
// modules/distributor/distributor.go:581
func logSpanWithAllAttributes(s *v1.Span, logger log.Logger) {
	for _, a := range s.GetAttributes() {
		logger = log.With(
			logger,
			"span_"+strutil.SanitizeLabelName(a.GetKey()),
			tempo_util.StringifyAnyValue(a.GetValue()))
	}

	latencySeconds := float64(s.GetEndTimeUnixNano()-s.GetStartTimeUnixNano()) / float64(time.Second.Nanoseconds())
	logger = log.With(
		logger,
+        	"span_name", s.Name,
		"span_duration_seconds", latencySeconds,
		"span_kind", s.GetKind().String(),
		"span_status", s.GetStatus().GetCode().String())

	level.Info(logger).Log("msg", "received", "spanid", hex.EncodeToString(s.SpanId), "traceid", hex.EncodeToString(s.TraceId))
}
```

**Additional context**
We're using span logs with Loki as a workaround for search traces, so span names in logs could improve the search efficiency.

**Comment by joe-elliott** [comment]
+1 to this addition. please submit a PR if you can.

if you are unable to i can do it.

**Comment by suraciii** [comment]
@joe-elliott PR opened :)
