### ISSUE TITLE
Ingesters not registering RPC endpoints on startup

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1792]
**Describe the bug**
Ingesters seem to not be registering RPC endpoints until well after startup. Sometimes several minutes. In particular we have seen failures on `/tempopb.Querier/SearchTagValues` and `/tempopb.Querier/SearchTags` although likely other endpoints are not being registered as well.

Ingesters log:
![image](https://user-images.githubusercontent.com/2272392/195111586-919dcca1-2df0-49fd-bdd4-41dd13614b85.png)

Queriers log:
![image](https://user-images.githubusercontent.com/2272392/195111717-2960ebe8-de79-450c-a9f1-53b89ac80d94.png)

**To Reproduce**
1. Restart an ingester and use the Grafana UI to hit the named endpoints above.

**Comment by mdisibio** [comment]
Is it possible the error is actually [backend.ErrDoesNotExist](https://github.com/grafana/tempo/blob/main/tempodb/backend/backend.go#L12) ?  Unsure if we can rule that out based on the logs, but the startup routine for the ingester is quite complex for replaying/rediscovering/etc and a new bug in this area wouldn't be surprising.

**Comment by joe-elliott** [comment]
That's a good point. This may be related to the recent changes to use the parquet files for search/search tags/search tag values. Also, I can reproduce this simply by starting up `./example/docker-compose/tempo-search` and visiting the Grafana UI at localhost:3000:

![image](https://user-images.githubusercontent.com/2272392/195416810-5597740b-6714-4d5a-8639-9b1c709fef10.png)
