### ISSUE TITLE
[Feature] Configurable max label key/value length in metrics generator

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1804]
**Is your feature request related to a problem? Please describe.**
Mimir and other metrics backends often have limits on various elements of the metrics they consume. A common one is the maximum length of a label key or value. When the maximum value is exceeded pushes fail with:

```
code="400 Bad Request" response="received a series whose label value length exceeds the limit, value: '/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435' (truncated) series: 'traces_spanmetrics_size_total{__metrics_gen_instance=\"metrics-generator-8788cc79d-cr96f\", http_method=\"GET\", http_target=\"/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:63435/112.124.42.80:634' (err-mimir-label-value-too-long). To adjust the related per-tenant limit, configure -validation.max-length-label-value, or contact your service administrator.\n"
```

**Describe the solution you'd like**
Add a maximum label value length that truncates any span attribute values before sending.

**Comment by krishnaindani** [comment]
hey, could you guide me on this? Would like to try it

**Comment by mapno** [comment]
Hi @krishnaindani. The idea here is that we sanitise the metric labels as we build the metrics, before they're sent to the metrics backend.

The generator uses a [custom registry](https://github.com/grafana/tempo/tree/main/modules/generator/registry) to build and store the metrics it generates with its processors—spanmetrics and servicegraphs. That pkg contains all the metrics types that are used. We should validate and sanitise the label values that are pushed to counters and histograms.

I didn't find references in the specification for the valid length labels, so try finding what metrics backends have for defaults (e.g. Prometheus, Mimir, etc). Also, IMO it should be configurable.

**Comment by joe-elliott** [comment]
Agree, it needs to be configurable. Mimir default max label value length is 1024 so I think that's a good default for us as well.

**Comment by kvrhdn** [comment]
As this is impacting one of our systems, I've put together a quick PR: https://github.com/grafana/tempo/pull/1897
I hope you don't mind Krishna.
