### ISSUE TITLE
Tempo-vulture doesn't support the config.expand-env argument

### ISSUE THREAD

**Issue by NickLarsenNZ** [grafana/tempo#1824]
When I patch the distributed components to expand env vars, I get this error from vulture (other components are fine with it).

```
flag provided but not defined: -config.expand-env
```

In my case, I don't have any configuration for vulture that relies on environment variables, but the consistency across components would be good.

_Originally posted by @NickLarsenNZ in https://github.com/grafana/tempo/issues/788#issuecomment-1286988808_

**Comment by joe-elliott** [comment]
> In my case, I don't have any configuration for vulture that relies on environment variables, but the consistency across components would be good.

That's fair. I suppose we generally consider vulture an internal tool even though we make it available to anyone who is interested in running it.

However, vulture isn't even capable of loading a config file. It only takes cli params. I'm unsure what value adding the ability to expand env vars would bring.
