### ISSUE TITLE
[Support/Bug] - Using hundreds of gigabytes of storage for traces

### ISSUE THREAD

**Issue by jdziat** [grafana/tempo#1841]
**Describe the bug**
We're using the distributed tempo chart in our environment to store traces within a S3 bucket. Currently we have a single application using the service and it is generating 100's of gigs worth of traces in our S3 Bucket. I'm trying to narrow down if this is expected behavior or if compaction isn't happening. When looking at the logs we see:

```
level=info ts=2022-10-27T13:28:34.237560244Z caller=compactor.go:239 msg="flushed to block" bytes=3823332 objects=7206 values=29981609
level=info ts=2022-10-27T13:28:35.397919164Z caller=compactor.go:239 msg="flushed to block" bytes=3827169 objects=7301 values=29999811
level=info ts=2022-10-27T13:28:36.563540912Z caller=compactor.go:239 msg="flushed to block" bytes=3842299 objects=7256 values=29999912
level=info ts=2022-10-27T13:28:37.629354262Z caller=compactor.go:239 msg="flushed to block" bytes=3854634 objects=7516 values=29977973
level=info ts=2022-10-27T13:28:38.543665916Z caller=compactor.go:239 msg="flushed to block" bytes=3852234 objects=7637 values=29999221
level=info ts=2022-10-27T13:28:39.359768848Z caller=compactor.go:239 msg="flushed to block" bytes=3810607 objects=7043 values=29999987
level=error ts=2022-10-27T13:28:39.762015282Z caller=compactor.go:120 msg="error during compaction cycle" err="error shipping block to backend, blockID ced0ae5b-1d89-4599-be0b-85fe26b55002: error completing block: error completing multipart upload, object: single-tenant/ced0ae5b-1d89-4599-be0b-85fe26b55002/data.parquet, obj etag: : Your proposed upload is smaller than the minimum allowed size"
```
Does that mean we have to increase the size of our compaction_window? I'd also like to know what's a typical trace size, that would help us diagnose and cost this out going forward. I know there are a ton of variables in regards to trace size just trying to get a general idea.

**Expected behavior**
I'd expect that storage would be closer to loki/prometheus in regards to compacted size.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**

**Comment by mdisibio** [comment]
Hi I think you are running into #1769.  Can you try settings like this and see if it helps?

```yaml
storage:
    trace:
        block:
            row_group_size_bytes: 1e+08
```
 
Also check that your S3 bucket has a lifecycle policy to delete incomplete multipart uploads.  These failures are where some of the block has been written but not finished, and an incomplete multipart upload remains in the bucket (not visible in the S3 UI)

**Comment by jdziat** [comment]
Great thanks @mdisibio, trying that now.

**Comment by jdziat** [comment]
@mdisibio That fixed the issue and it's definitely behaving as expected now. Thanks for the help!
