### ISSUE TITLE
AWS S3 Object Lock Retention

### ISSUE THREAD

**Issue by guimalfp** [grafana/tempo#1845]
Good evening, 

New to the community, I am looking to leverage AWS S3 bucket as my backend. The catch is that I must enable object lock on the bucket with retention. Once the retention is turned on, for immutability purposes, Tempo is unable to write the traces to S3, with the following error:

>  "err="error copying block from local to remote backend: error writing object to s3 backend, object single-tenant/c<GUID>/data: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters""

I have not been able to track down a similar issue or whether immutability is not supported. I am currently running version 1.4.1.

**Comment by joe-elliott** [comment]
In Tempo objects are generally treated as immutable. I suppose there are two possible exceptions depending on what s3 considers "immutable".

- When we create a block we do a multipart upload (both ingester and compactor). This appears to be what you are running into.
- When a block is ready to be deleted we rename `meta.json` to `meta.compacted.json`.

I don't know much about the s3 object lock feature. It's possible there are settings on the minio go client that will enable you to use this feature along with Tempo, but will require some research.
