### ISSUE TITLE
[TraceQL] 2.0 to do

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1854]
Tracking issue for all the changes we want to do to TraceQL to make it release ready!

**Parsing/Correctness**

- [x] Correctly handle empty queries like `{}` and `{ }` https://github.com/grafana/tempo/pull/1993
- [x] Time range isn't handled correctly (startTime doesn't seem to work)
- [ ] Add additional validation to block unsupported queries, e.g. we can't handle arithmetics and nested pipelines yet

**Performance**

- [x] Pass `SearchOptions` down to storage layer to do block sharding as well
- [ ] ~~Load data in two phases? I.e. don't read span ID/name/etc unless needed~~

**Autocomplete**

- [x] Return values with their type, e.g. `{ .http.status_code = ` should autocomplete to `200` and not `"200"` #1956

**Clean up**

- [ ] `TraceSearchMetadata`: refactor `durationMs` to `durationNs` to be more consistent with the spans object

**Stretch / nice to have**

- [ ] Implement arithmetics
- [x] Expressions without spaces aren't parsed correctly, e.g. `.foo="bar"` is treated as one attribute instead of a binary expression. https://github.com/grafana/tempo/pull/1941

**Comment by joe-elliott** [comment]
I would like to close this in favor of individual issues to clean up some of the "unsupported" traceql options. e.g.

https://github.com/grafana/tempo/issues/1949
https://github.com/grafana/tempo/issues/2015

Everything else in this issue is done for 2.0.
