### ISSUE TITLE
[Service graph] Add prefix to differentiate client and server attributes

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#1860]
In the service graph processor, when [adding custom dimensions to metrics](https://github.com/grafana/tempo/blob/58637f39cb91d707a43a1ba246d9b1ff97c1548b/modules/generator/processor/servicegraphs/servicegraphs.go#L224-L230), values can be overridden if parent and children span have the same attribute but with different values. The attributes of the last span to be processed are the ones selected for the metrics. This results in inconsistent behaviour.

We should a prefix to the label metrics to differentiate between values coming from the parent span and the children span.

**Comment by domasx2** [comment]
this has become important for app o11 efforts, we want to identify service by both service name and service namespace, so should be able to have namespace labels for both client and server

**Comment by zalegrala** [comment]
Do we have an update as to the next steps here?  I see the PR is up, but do we have someone who is assessing the impact to existing customers and planning to communicate that impact?

**Comment by gouthamve** [comment]
So while we do have a solution for migration of customers. However, this will also break functionality in the service graph view. I think the best way to proceed here is a config option similar to `enable_client_server_prefix: true`. 

And then in the future deal with how to align the service graph view to use these new metrics.
