### ISSUE TITLE
Tempo monitoring not pulling in cluster name

### ISSUE THREAD

**Issue by B3DTech** [grafana/tempo#1885]
Tempo distributed deployed via helm.  I took the rules from the mixin and added them to the cluster.  Used the dashboard provided in the mixin and there is a lot not working.

The dashboard variable: 

label_values(tempo_build_info, cluster)

tempo_build_info is there, but there is no cluster label

Looking at the scrape configs and rules, I'm not seeing anything that would be dropping the cluster label.  Any ideas?

**Comment by zalegrala** [comment]
Thanks for the report.  The `cluster` label is added by prometheus at scrape time.  Its tricky to work up a generic example, but the following configuration should get you going when added to the prometheus configuration.

```yaml
global:
  external_labels:
    cluster: clusternamegoeshere
```
