### ISSUE TITLE
Allow more than 256 max shards on trace by id lookup

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1905]
This function: 

https://github.com/grafana/tempo/blob/cf6a9337e7ce58b75bc9e98b50db50c5953eaf4f/modules/frontend/tracebyidsharding.go#L228

Is responsible for breaking up the the guid space into a smaller number of evenly sized shards. Currently, due to the way it is written, the maximum number of possible shards is 256. Let's improve this function to allow for an arbitrary number of shards. 

This constant will also have to change:
https://github.com/grafana/tempo/blob/cf6a9337e7ce58b75bc9e98b50db50c5953eaf4f/modules/frontend/tracebyidsharding.go#L27

and it should be confirmed that this method:
https://github.com/grafana/tempo/blob/cf6a9337e7ce58b75bc9e98b50db50c5953eaf4f/modules/frontend/tracebyidsharding.go#L196

can handle the new number of shards correctly.

**Comment by noelukwa** [comment]
I want to give this a shot @joe-elliott

**Comment by mapno** [comment]
Go for it @noelukwa! Let us know if you have any questions.

**Comment by mghildiy** [comment]
Is is still open?

**Comment by joe-elliott** [comment]
@mghildiy Yup, feel free to give it a shot.

**Comment by mghildiy** [comment]
How do we get to know what is 'arbitrary number of shards' now? Does it come as input to the function or some configuration?

**Comment by noelukwa** [comment]
@mghildiy please accept my apologies for the late response, I was actually working on this already. I’ll open a draft PR  in a couple hours with my progress.

**Comment by mghildiy** [comment]
@noelukwa , thanks for update. I am in middle of debugging the code, but havent made any concrete changes so far.
Please go ahead with your PR.

**Comment by joe-elliott** [comment]
@noelukwa any progress here? I am interested in this feature myself.

**Comment by joe-elliott** [comment]
@noelukwa apologies for stepping on toes here, but we need this fix internally for our larger clusters. Thank you for you interest in contributing to Tempo. We appreciate any efforts you made here :pray:

**Comment by noelukwa** [comment]
No hard feelings at all, planned to make out time to finish it but i've been caught up with work, please feel free to reassign to another person
