### ISSUE TITLE
unable to get version from tempo

### ISSUE THREAD

**Issue by PietroPasotti** [grafana/tempo#1908]
**Describe the bug**
It could be that I'm misunderstanding what version means in an oci image, but I cannot programmatically determine the tempo version from the single binary packaged with grafana/tempo:1.5.0.

**To Reproduce**
1. deploy grafana/tempo:1.5.0 via docker or on kubernetes
2. run `tempo -version`

**Expected behavior**
I would expect to see `version: 1.5.0` somewhere, instead I see:

```
tempo, version  (branch: HEAD, revision: fd5743d5d) 
  build user:                                       
  build date:                                       
  go version:       go1.18.5                        
  platform:         linux/amd64                     
```

note that the revision matches the hash of the 1.5.0 commit https://github.com/grafana/tempo/releases/tag/v1.5.0

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: directly from grafana/tempo:1.5.0 oci image.

**Additional Context**
Nothing I can think of.

**Comment by joe-elliott** [comment]
Thanks for the report. I'm seeing the same thing when looking at the `1.5.0` build. Tempo also emits a metric `tempo_build_info` which should contain information like the version, but this appears to be broken on `1.5.0` as well. It seems our regular builds off the tip of main are tagged correctly, but the versioned builds are not.

I suppose the good news, as you pointed out, is that the revision is correct so we have confirmation of the commit it was built from.

Will keep an eye on this when we build 2.0. Thanks!

**Comment by electron0zero** [comment]
fixed in https://github.com/grafana/tempo/pull/2319#issuecomment-1501883588
