### ISSUE TITLE
Why tempo http request params and tempo proto are completely inconsistent

### ISSUE THREAD

**Issue by buhuipao** [grafana/tempo#1910]
**Describe the bug**
I use tempo with grafana docker container, I implement the tempo server with rust, follow the docs: https://grafana.com/docs/tempo/latest/api_docs/#search-tag-values.

All tempo structs were generated by https://github.com/grafana/tempo/blob/v1.3.2/pkg/tempopb/tempo.proto. Like below image:
![image](https://user-images.githubusercontent.com/14309948/203736759-0102ea35-8aab-4ca3-8149-8243df2f5311.png)

But, the tempo plugin only support data formatter like below:
 
<img width="940" alt="image" src="https://user-images.githubusercontent.com/14309948/203748858-69ae7066-ec06-42b6-a8a5-0b7621685bcf.png">

**Environment:**
grafana latest docker image and container, like 
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/14309948/203736088-aca2d74d-e3e8-4304-9f87-6d55a6a8996a.png">

**Additional Info**
The API https://grafana.com/docs/tempo/latest/api_docs/#query has some problem. I implement this API with below response.
<img width="842" alt="企业微信截图_40be1a9a-02e4-4360-8ed0-ee0e6fcec8c9" src="https://user-images.githubusercontent.com/14309948/203738713-3300affa-6ae7-490d-83a6-c1f8893dbbcd.png">

But grafana tempo plugin call the http api with `HTTP/1.1` and with `protobuf` headers.
```
protocol=HTTP method=GET  version=HTTP/1.1 

{
  "host": "docker.for.mac.host.internal:9009", 
  "user-agent": "Grafana/9.2.1", 
  "accept": "application/protobuf", 
  "accept-encoding": "gzip",
  "x-request-id": "e31881fe-d6e7-451c-a68e-5f3a3642aa86"
}
```

Tempo plugin can't parse the response that my server response, the plugin only support data like below:
<img width="1782" alt="企业微信截图_57cb87bd-f1d2-4908-ae61-d6c322314c46" src="https://user-images.githubusercontent.com/14309948/203747466-9d5fbb9c-520a-4e98-b011-3dd125ec6fa8.png">

**Comment by mapno** [comment]
Hi @buhuipao. Making sure I understood: you've implemented Tempo's query API in Rust and you're having trouble making it work with Grafana, is that it? And the problem is camelCase vs snake_case?

The Tempo query API is a bit messy on its usage of JSON and protobuf. ID lookups are done using protobuf, but search only support JSON. That's why you're seeing both formats being used.

**Comment by buhuipao** [comment]
Hi @mapno , Yes. Thanks for you reply, you success understood my problems.
In addition to the above problems, I also found that the field not match of the searchTrace API. Like below:
<img width="1511" alt="企业微信截图_a12e049d-fa77-4f69-bd66-9c7fc15552b4" src="https://user-images.githubusercontent.com/14309948/203937905-4bc50b03-29fd-4978-8438-31398e86967f.png">

![企业微信截图_2fdd35eb-0504-4899-b929-0257bc017c4e](https://user-images.githubusercontent.com/14309948/203937944-5eede6c3-306a-4174-8f71-dcbc014c7314.png)

**Comment by mapno** [comment]
That's because the search endpoints use JSON as marshalling format, and thus it uses camelCase instead of snake_case. Make sure you marshal the response to JSON.
