### ISSUE TITLE
Getting 500 Internal server error 

### ISSUE THREAD

**Issue by vikram0602** [grafana/tempo#1925]
Hi Tempo team,

We are running the tempo rpm locally on our centos server and from few days we are getting 500 server error for all our traces.

![image](https://user-images.githubusercontent.com/10576924/205104208-23190290-9505-4151-89c4-b0e499c3bbc3.png)

I see you have some documentation regarding this
https://grafana.com/docs/tempo/latest/troubleshooting/bad-blocks/

But I am not sure how to find/delete the corrupted blocks.
I am fairly new to tempo, so any input on how to fix this will be great. 

Below is our config

![image](https://user-images.githubusercontent.com/10576924/205105228-8c9a9609-db35-4571-9f1d-395aa11bb918.png)

Thanks,

**Comment by joe-elliott** [comment]
Please check your querier logs. They should indicate the block guids that they are having trouble with. You can then remove those blocks specifically from object storage.
