### ISSUE TITLE
Ability to remove dimension from intrinsicDimensions

### ISSUE THREAD

**Issue by altanozlu** [grafana/tempo#1932]
**Is your feature request related to a problem? Please describe.**
We had a lot of prometheus OOM crash lately now i've checked and the reason is status_message field and as far as i see there is no option to disable intrinsicDimensions
response from tsdb analyze:
```
Highest cardinality labels:
41449 status_message
```

**Describe the solution you'd like**
I'd like to be able to change intrinsicDimensions

**Comment by joe-elliott** [comment]
Thank you for the report. When we added `status_message` we believed that it was 1:1 with StatusCode, but apparently that's not the case. Can you give some examples of status messages? I think we need to correct this before 2.0 or metrics generator will become unusable for some people.

cc @stoewer

**Comment by joe-elliott** [comment]
yeah, guid in the status message. oof. we will get this cleaned up for 2.0
