### ISSUE TITLE
Complete writing a batch even if some spans refused

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1957]
**Describe the bug**
Currently if an ingester refuses traces b/c a trace is too large it will stop writing the current batch and return an error. The end result is that the first part of the batch was written but everything after the "trace too large" error is dropped. Let's continue writing the batch even if we receive a trace too large error.

Loop to write traces:
https://github.com/grafana/tempo/blob/909b487d4bac42797a786a10796664b4cfcd0746/modules/ingester/instance.go#L167

Trace too large returned here:
https://github.com/grafana/tempo/blob/909b487d4bac42797a786a10796664b4cfcd0746/modules/ingester/instance.go#L210

**Comment by 97amarnathk** [comment]
@joe-elliott can I pick this up ?

**Comment by joe-elliott** [comment]
Absolutely! The team is going to be pretty barebones for the next 2 weeks due to the holidays so if you don't get an immediate review don't worry. I promise I will get to all PRs when I get back.

Thanks for giving it a shot.

**Comment by 97amarnathk** [comment]
@joe-elliott 1 small implementation doubt.

Since this is now a bulk operation how should the ingester convey back the traces which failed ?

**Comment by mapno** [comment]
Hi @97amarnathk!

> Since this is now a bulk operation how should the ingester convey back the traces which failed ?

The error in non-retryable, so we're good returning a list of the traces that failed (i.e. similar to what we already do, but for multiple traces). I don't think we need a more comprehensive approach than that.

**Comment by 97amarnathk** [comment]
Got it.
I have implemented multierror handling for this here: https://github.com/grafana/tempo/pull/1962

Do go through it whenever possible

**Comment by bilbof** [comment]
keepalive
