### ISSUE TITLE
Clarify that Tempo search is nondeterministic in the docs

### ISSUE THREAD

**Issue by 09jvilla** [grafana/tempo#1988]
When you do a search for a fixed time window in the past the initial search gets you a list of traces. If you search again, you’ll get a different list (assuming the possible number of results for your search is greater than the number of results you have your search set to return). 

This caused a user some confusion, as they expected the same search would always return the same results (i.e. that search was deterministic). 

This issue is about making clear to users in the docs that Tempo's search is non-deterministic, meaning that different results can be returned for the same search. All of those results are of course valid results for the search run, though. So if there are 10k traces that satisfy your search criteria, if you run that search multiple times and the search is set to return 1k results, you'll get a different set of 1k each time. 

Under the hood - here's what Tempo is doing (to explain why it doesn't always return the exact same set of results):

When performing a search, Tempo does a massively parallel search over the given time range, and takes the first N results. Even identical searches will differ due to things like machine load and network latency. This approach values speed over predictability and is quite simple; enforcing that the search results are consistent would introduce additional complexity (and increase the time the user spends waiting for results). TraceQL, when released, will follow the same behavior.

**Comment by knylander-grafana** [comment]
I've added a section to the Find traces using Tempo search section of tempo-in-grafana.md explaining about non-deterministic search. Most of the text used is from this ticket, so thank you for the summary and content. Good starting point!
