### ISSUE TITLE
[TraceQL] Support Not Regex (!~)

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#1990]
**Is your feature request related to a problem? Please describe.**
Add support for the NotRegex operator (!~).  It is part of the language grammar and parses, but returns an `operation unsupported` error.

**Comment by mdisibio** [comment]
@kousikmitra Sure thing, thanks 👍

**Comment by kousikmitra** [comment]
@mdisibio have raised a PR. Let me know if missed anything!! Thanks. 🙌
