### ISSUE TITLE
Expression to Find Live Traces For Any One Of The Component/Services In Namespace.

### ISSUE THREAD

**Issue by prakash-rajan-mindcurv** [grafana/tempo#1994]
**Is your feature request related to a problem? Please describe.**
I'm not able to find the Prometheus expression for Tempo Ingester Live Traces for a particular component/service in the namespace.

**Describe the solution you'd like**
Currently, I'm using `**tempo_ingester_live_traces**`  expression to get all live traces but am not able to get live traces for particular component/services in the namespace.

**Comment by joe-elliott** [comment]
The metrics generator is capable of remote writing metrics based on spans consumed. It can be broken down by arbitrary dimensions and would likely be able to give you the information you need.

Would this be sufficient?

**Comment by prakash-rajan-mindcurv** [comment]
Hi @joe-elliott, Thanks for the reply.

This is fine, cloud you please share the expression to get accurate traces? Currently, I'm using `sum by (cluster, namespace) (avg_over_time(tempo_ingester_live_traces[5m])) == 0 ` which is provided only if traces missing in the whole cluster, but I want particular components/services in the namespace. I couldn't find it in documents or in the internet.

**Comment by mapno** [comment]
Hi @prakash-rajan-mindcurv, can you detail a bit more what you want to do? `tempo_ingester_live_traces` is a operational metric, mainly used to measure and configure `overrides.max_traces_per_user`. It's not intended to measure per-service or similar metrics. It's only labelled with the tenant that owns those traces.

For user-level metrics, the [metrics-generator](https://grafana.com/docs/tempo/latest/metrics-generator/) is commonly used. This is a component that will derive metrics from ingested spans. You can add any additional label to these metrics, as long as they are present in the traces (eg. `cluster`, `environment`, `namespace`, etc)

**Comment by mapno** [comment]
The official docs are a good place to get started: https://grafana.com/docs/tempo/latest/metrics-generator/

**Comment by rajushrajan** [comment]
Could you please advise on how we can detect if none of the traces are being written? Is there a way to set up an alert that triggers if no traces are recorded for more than 15 minutes? Specifically, I would like to receive an alert if traces are missing for any particular service. We have checked possibilities with metrics-generator, but could not find any.

Is it possible to implement a solution for this?

**Comment by joe-elliott** [comment]
if you write metrics to prometheus and use alert manager you should be able to write promql queries that detect if spans from a given service have stopped being sent.

https://prometheus.io/docs/alerting/latest/alertmanager/

**Comment by rajushrajan** [comment]
@Joe Thanks for the reply.  I could not find queries to alert if spans from a given service have stopped being sent.
can you help me with an example promql query

**Comment by joe-elliott** [comment]
Something like?
```
sum(rate(traces_spanmetrics_calls_total{service="foo"}[1m])) < 1
```

Apologies, this is not something I can really help you with. Please refer to prom/alertmanager documentation/forums/etc.

**Comment by rajushrajan** [comment]
Hi @joe-elliott , I apologize for the delay in my response. I have tested the query you provided, but unfortunately, it is not functioning as expected.

Could you please suggest an alternative method to receive notifications when there are no traces for any components of the cluster?
