### ISSUE TITLE
Tempo Ingester: panic: runtime error: slice bounds out of range [24620:2304]

### ISSUE THREAD

**Issue by cha2lenger** [grafana/tempo#1996]
**Describe the bug**
Tempo ingesters are crushing with the following output in logs:
```
level=info ts=2023-01-13T16:05:12.666673244Z caller=rescan_blocks.go:34 msg="beginning replay" file=dd7bee79-1532-465e-b78e-96a65447e6c2:63bc6bdfbaa28c6e6bd85e47:v2:none: size=510398244
level=info ts=2023-01-13T16:05:15.534803846Z caller=rescan_blocks.go:64 msg="replay complete" file=dd7bee79-1532-465e-b78e-96a65447e6c2:63bc6bdfbaa28c6e6bd85e47:v2:none: duration=2.868116076s
level=info ts=2023-01-13T16:05:15.534970865Z caller=rescan_blocks.go:34 msg="beginning replay" file=f2f740dc-b379-4d00-86a4-6749bfaccf46:63bc6bdfbaa28c6e6bd85e47:v2:none: size=2957312
panic: runtime error: slice bounds out of range [24620:2304]

goroutine 465 [running]:
github.com/google/flatbuffers/go.(*Table).ByteVector(0x7f7c7734d108?, 0x51?)
        /drone/src/vendor/github.com/google/flatbuffers/go/table.go:35 +0xe5
github.com/grafana/tempo/pkg/tempofb.(*KeyValues).Key(0xc000b91878)
        /drone/src/pkg/tempofb/KeyValues.go:39 +0x3c
github.com/grafana/tempo/pkg/tempofb.(*SearchBlockHeaderMutable).AddEntry(0xc000818030, 0xc059435184?)
        /drone/src/pkg/tempofb/SearchBlockHeader_util.go:30 +0xc5
github.com/grafana/tempo/tempodb/search.newStreamingSearchBlockFromWALReplay.func1({0xc0582dc010?, 0xc0582c0b10?, 0x900?})
        /drone/src/tempodb/search/rescan_blocks.go:87 +0x7c
github.com/grafana/tempo/tempodb/wal.ReplayWALAndGetRecords(0xc00081c008, 0x86?, 0xc000b91ac0)
        /drone/src/tempodb/wal/replay.go:52 +0x2d5
github.com/grafana/tempo/tempodb/search.newStreamingSearchBlockFromWALReplay({0xc0009f4000?, 0xc04131a300?}, {0xc0001504f6, 0x46})
        /drone/src/tempodb/search/rescan_blocks.go:85 +0x165
github.com/grafana/tempo/tempodb/search.RescanBlocks({0xc000ca6540?, 0xc041332560?})
        /drone/src/tempodb/search/rescan_blocks.go:38 +0x4dc
github.com/grafana/tempo/modules/ingester.(*Ingester).replayWal(0xc0002a1500)
        /drone/src/modules/ingester/ingester.go:354 +0x1dc
github.com/grafana/tempo/modules/ingester.(*Ingester).starting(0xc0002a1500, {0x25251d0, 0xc0413012c0})
        /drone/src/modules/ingester/ingester.go:110 +0x2c
github.com/grafana/dskit/services.(*BasicService).main(0xc04130a460)
        /drone/src/vendor/github.com/grafana/dskit/services/basic_service.go:157 +0x78
created by github.com/grafana/dskit/services.(*BasicService).StartAsync.func1
        /drone/src/vendor/github.com/grafana/dskit/services/basic_service.go:119 +0x105
```

**To Reproduce**
Nothing special here, just deploy them and start pushing some traces via Tempo OTLP endpoint.

**Expected behavior**
Well, expect tempo ingesters to be up and running.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm (tempo-distributed-0.27.10/1.5.0)

**Additional Context**

**Comment by joe-elliott** [comment]
This looks like a corrupt flatbuffer search file that Tempo is attempting to reload on startup. Did the ingester shutdown gracefully? I would recommend just deleting the offending file and the ingester should start up fine.

**Comment by cha2lenger** [comment]
Joe, thank you for quick reply. How do these files become corrupted? I see it happening over and over again.

**Comment by cha2lenger** [comment]
Another question: do I see this behavior because I have search feature enabled?
```
search_enabled: true

**Comment by joe-elliott** [comment]
If the Tempo ingester does not shut down gracefully it has a chance of writing a corrupt file. Are the ingesters OOMing or otherwise shutting down unexpectedly?

fwiw
- 2.0 default behavior will be to use parquet files instead of these and no longer create flatbuffer files
- 2.1 will remove flatbuffer files completely in favor of parquet

> Another question: do I see this behavior because I have search feature enabled?

Yes, if you disable that feature then Tempo will no longer make flatbuffer search files (or it may make 0 length files. not 100% sure).

**Comment by cha2lenger** [comment]
Joe, I do not see any traces of OOM. But I'll do some extra tests and report the results here. 

Meanwhile I currently have two instances of ingesters out of eight crushed because of this issue. As the result all eight of them report 503 in response to their health check: `msg="GET /ready (503) 229.675µs"`. Is there any configuration parameter I can tune in order to keep ingesters fleet healthy even if two of them out of eight are down?

Thank you.
