### ISSUE TITLE
Initialise stale counter series at 0

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#2006]
The metrics-generator has a mechanism to remove series that have become stale—ie. have not received a new value in some time. The main objectives are keeping resources down and make room for more frequent series.

This is a problem for series that are removed frequently, because `traces_spanmetrics_calls_total` gets initialised at the value of the first scrape once the series gets registered, and Prometheus skips the jump from `null` to a given value. In order not to lose that first value, we need to push a first value of `0` when a new series is added to the counter.

**Comment by DerrickMartinez** [comment]
When is this going to be included in a release?

**Comment by joe-elliott** [comment]
This will be included in the 2.1 release. We don't have a date set explicitly, but I expect it in 1 - 2 months.
