### ISSUE TITLE
Cut a new 1.x release

### ISSUE THREAD

**Issue by thomaschaaf** [grafana/tempo#2012]
**Is your feature request related to a problem? Please describe.**
I just stumbled over this issue: https://github.com/grafana/tempo/issues/1746 when trying tempo and because it was resolved in october I believed it would be already in the current version.

**Describe the solution you'd like**
Release a new version

**Describe alternatives you've considered**
I tried using the latest build in docker but I can't get it to run. Likely because that is tempo 2.0.

**Additional context**

**Comment by joe-elliott** [comment]
Hey @thomaschaaf. I agree that it's been too long since our last release, but there will be no more 1.x releases. We are cutting a 2.0rc.0 today though!

It will come with breaking changes so keep an eye out on the changelog. There will also be a blogpost that goes into detail on the changes.
