### ISSUE TITLE
Cannot deploy tempo in OKD

### ISSUE THREAD

**Issue by yasharne** [grafana/tempo#2029]
**Describe the bug**
I have deployed tempo-distributed on openshift with Grafana's helm charts.
all of the pods are in the CrashLoopBackoff state:
![image](https://user-images.githubusercontent.com/7656049/215490521-4a7665fd-b0b1-4700-ae12-8c24cd88f4db.png)

When I see the logs, all of them have this error:
```
exec /tempo: exec format error
```

**To Reproduce**
1. Install tempo distributed using helm

**Environment:**
 - Infrastructure: Openshift 4.11.0 
 - Deployment tool: helm
 - version: 1.5.0

**Comment by joe-elliott** [comment]
There appears to be something fundamentally incompatible between the binary in the docker image and the OS/hardware you are  running on. This is far from a specialty of mine, so I'm not sure how much I can help. Is there anything unique about the environment you are running on that you can share?

We currently build Tempo images for two architectures:
![image](https://user-images.githubusercontent.com/2272392/215493575-1a887d36-63e1-478c-9f4f-998aa486997b.png)

**Comment by yasharne** [comment]
I found the issue; I was pulling the image on my M1 laptop, then pushed it to the OKD's ImageStream; that's why I had that error
