### ISSUE TITLE
metrics-generator not generating service-graph metrics

### ISSUE THREAD

**Issue by Juandavi1** [grafana/tempo#2051]
from #1509

Hi ! I'm trying to do it but I can't achieve :( 

These are generator logs 

<img width="1797" alt="image" src="https://user-images.githubusercontent.com/18731612/216137641-73e24475-d00a-43e8-977d-b5310f4cf1bf.png">

These are generator metrics 

![image](https://user-images.githubusercontent.com/18731612/216138266-57304788-2bc2-4ae7-aa93-fc58a0820310.png)

I'm trying with two example spans 

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/18731612/216137217-9e66b94b-bbfe-4627-9231-4deaa521c23b.png">

So, this is the grafana result 

![image](https://user-images.githubusercontent.com/18731612/216138590-7b0787c9-1847-434b-b3e7-cc0946784484.png)

there aren't service graph info :( 

![image](https://user-images.githubusercontent.com/18731612/216139346-464e9676-6b3b-4d82-bec1-8db8a548f651.png)

This is our version tempo version 

<img width="695" alt="image" src="https://user-images.githubusercontent.com/18731612/216139733-9feea01a-acc8-4b4a-abd6-ac681f037946.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/18731612/216139871-8d7a5c98-7807-40a8-a744-c0d7b0baae16.png">

Environment:

Infrastructure: Kubernetes
Deployment tool: helm

I would appreciate any help ! 

Awesome project !! 
thanks a lot !

**Comment by Juandavi1** [comment]
Hi ! 

we are trying to set the remote write but we got this error 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/18731612/216396085-06669e16-1f93-4ea3-912e-125a32bc0f63.png">

Is this config right ? 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/18731612/216396273-d06d67f0-035f-4145-85b2-60a9e4157947.png">


thanks a lot !

**Comment by Juandavi1** [comment]
yyess ! that was!! Thanks a lot

**Comment by joe-elliott** [comment]
np, glad you found it
