### ISSUE TITLE
Allow to configure subpaths within S3 buckets

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#2100]
**Is your feature request related to a problem? Please describe.**

Tempo's S3 config does not support using specific folder within an S3/GCS/Azure bucket to use as its root folder. This doesn't allow cleanly sharing buckets with other apps.

**Describe the solution you'd like**

Tempo should add support for subpaths within S3/GCS/Azure buckets.

**Describe alternatives you've considered**

Bucket names with `/` are not allowed per S3's [bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html).

**Additional context**

Similar issues in Mimir https://github.com/grafana/mimir/issues/1682 and Loki https://github.com/grafana/loki/issues/5889

**Comment by shrey** [comment]
I'd like to take this issue up!

**Comment by WildCatFish** [comment]
Hi, @shrey is there any update on this issue?
We are having the same difficulty.

**Comment by kousikmitra** [comment]
Hi, I would like to pick this up since there no reply from assigned user. Let me know if I can work on this.

One question,

* Should this change only effect s3 and not gcs or azure?
* I did a little dig up, and I hope this is the package `tempodb/backend/s3` that will need necessary changes. Please let me know if I am on right track!

**Comment by kousikmitra** [comment]
> @kousikmitra We would love to have you give this a shot. Thanks for taking an interest!
> 
> > Should this change only effect s3 and not gcs or azure?
> 
> It would be cool if we made it to all 3 backends at once. However, we appreciate any contribution and if s3 is all you can carve out some time to for, we understand.

@mapno I would love to make the change for other backends. If thats ok I will create another ticket and work on it.

**Comment by mapno** [comment]
Please, go ahead. Thanks for contributing to Tempo!

**Comment by kousikmitra** [comment]
@mapno I have raised a PR with this changes. Can you please reopen the issue and update the description?

**Comment by mapno** [comment]
Done!
