### ISSUE TITLE
TraceQL simple attribute search doesn't return traces

### ISSUE THREAD

**Issue by ovidiubuligan** [grafana/tempo#2102]
Classic search returns more `error=true` traces :  
![image](https://user-images.githubusercontent.com/4757459/218112389-f26b5a44-6e52-4204-9a62-57c69c8acbcb.png)

Too few error=true traces . I am sure there are more than 4  `error=true`  traces :
![image](https://user-images.githubusercontent.com/4757459/218112129-805e7a30-dd9f-46cc-a8d9-169b8ea64f19.png)

**Expected behavior**
More traces should be returned when matching attribute `error=true`

**Environment:**
 - Infrastructure:  Kubernetes
 - Deployment tool:  helm microservices 1.0.1

**Additional info**
It looks like totally different trace sets are returned by the 2 queries . 
Can someone share some insight on how attribute search works ?

**Comment by joe-elliott** [comment]
Sadly error is in kind of a gross spot at the moment. The old search translates `error=true` into a query that makes sense over OTel data, but TraceQL does not. OTel has a field called [Status](https://github.com/open-telemetry/opentelemetry-proto/blob/e6dfd7f4cefdc2e8844fa3dfcd8b307477d59937/opentelemetry/proto/trace/v1/trace.proto#L251) which contains the per span success or error status. To query it please write:

`{ status = error }`

Here's some docs on the [intrinsic fields](https://grafana.com/docs/tempo/next/traceql/#intrinsic-fields) and a [Grafana issue](https://github.com/grafana/grafana/issues/59607) on better representing these fields to help reduce confusion.

The query you did write (`{.error = true}`) is searching for a resource or span level attribute of type boolean with the value `true`.

**Comment by ovidiubuligan** [comment]
Thank you , this solves my confusion perfectly .
