### ISSUE TITLE
DNS issue with missing period for resolver in nginx config causes pod crash backoff

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/tempo#2103]
Describe the bug

Nginx pod stuck in crash back off lookup with DNS issue:

[emerg] 1#1: host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/nginx.conf:25
nginx: [emerg] host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/nginx.conf:25

The solution is in this issue - which resolved the same issue with the Loki nginx container.

The problem being a missing . after the dns hostname in the nginx ConfigMap:

resolver kube-dns.kube-system.svc.cluster.local;
vs
resolver kube-dns.kube-system.svc.cluster.local.;

https://github.com/grafana/loki/issues/7287#issuecomment-1292594799

To Reproduce

Install Loki Distributed via helm, nginx config in values is stock. I’m installing in Rancher Desktop on K3S using containerd on my MacBook.

Expected behavior

There should be no DNS related errors in the container and it should start without issue.

**Comment by zalegrala** [comment]
Is the issue you are having with Loki, or with Tempo?

**Comment by MaxDiOrio** [comment]
Sorry about that - BOTH!  I opened the ticket in Loki first and copy/pasted but missed the reference to Loki here.  But both have the exact same issue.

**Comment by zalegrala** [comment]
I think if you set `.Values.global.clusterDomain` to `cluster.local.`, you'll be able to get past the error.

**Comment by MaxDiOrio** [comment]
The extra dot at the end should go into the template shouldn’t it?  {.Values.global.clusterDomain}.  It’s not really logical to have it in the .Values.global.clusterDomain, which should not have the dot at the end.

It was added to the template in Loki and should be consistent across Grafana products.

**Comment by zalegrala** [comment]
Sometimes I think its a good idea to be able to specify when you are using a root domain.  Just thinking about the use of maybe `coredns.kube-system.svc` for example, you might not want to care.  That doesn't really apply here it looks like since we use that variable elsewhere, but presumably we shouldn't have to.

I've opened https://github.com/grafana/helm-charts/pull/2202 to align with the `loki` chart, thanks for the suggestion, and for raising the issue.  The Tempo team hasn't moved the chart to this repo yet, so issues and PRs can go to the `helm-charts` repo for now until we move.

For my own curiosity, I assume `coredns` is your resolver?  Are there modifications to the `Corefile` that cause this to happen?  Mostly wondering why we haven't seen this before, and also because I keep a TLD and don't see this in my environment.   I always avoid search domains, and wondering if that's why this comes up.

**Comment by MaxDiOrio** [comment]
I’ve built a test environment on my laptop using Rancher Desktop and k3s running on containerd.  It does use coredns and I haven’t done any modifications to it at all - completely stock.

I didn’t see this on my production Rancher clusters using K8S.

**Comment by zalegrala** [comment]
I've not used k3s locally, but I use k3d on my laptop regularly and haven't run into this.  Do you have any other clues as to why this is showing up only now?

**Comment by zalegrala** [comment]
May I see the Corefile configmap, and also the /etc/resolv.conf from the host.  If this is k3s, I believe /etc/resolv.conf will be at play here.

**Comment by zalegrala** [comment]
I'm also not sure how containerd works on a mac.  Do you have details about how that works?

**Comment by MaxDiOrio** [comment]
This is my first time attempting to use Rancher Desktop (we use Rancher for cluster management), so I can’t answer about timing of this issue showing up.  But clearly, it’s not just me per the linked issue.

Within Racher Desktop, you can chose either Docker or containerd.  I believe it uses Lima as the virtualization, which includes support for containerd.

```
cat /etc/resolv.conf
search tempo.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5
```

```
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.1.57 lima-rancher-desktop
```

**Comment by zalegrala** [comment]
I think `ndots: 5` is probably also causing issues here.  Check out this post.

https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

**Comment by zalegrala** [comment]
Hello, are you able to test changing the `ndots` configuration in your `resolv.conf` for this?

**Comment by zalegrala** [comment]
I'm going to close this out.  I'd like to see a test using my suggestion above since I believe this to be a resolver issue, but without research in that area, I don't think we should make the change in the chart.  I'm happy to discuss further if helpful, so feel free to reopen the issue.
