### ISSUE TITLE
Metric Data generation is failing from metric generator

### ISSUE THREAD

**Issue by sree-warrier** [grafana/tempo#2106]
**Describe the bug**
Using metric generator to get the span related metrics, we are plotting the same in the Dashboards for getting  p99, p95 metrics. But at some point metric data is not getting generated. We have tried to change the scaling features of metric-generator and also we have updated the configs but still issues are seen. We are using victoria metrics as the backend for Metric Generator. Once we are noticed the issues we used to restart the metric-generator pods to resolve the issue after that metric data starts to pump in. We are unable to understand the cause of the issue, no logs are shown related to it.  Due to this issue our APM and service-graphs are showing improper data. 

**To Reproduce**
1. Using Distributed Tempo Helm charts
2. We have tried scaling from 1 replica to 5
3. Sample Metric generator config 

config:
    registry:
      collection_interval: 15s
      external_labels: {}
      stale_duration: 15m
    processor:
      service_graphs:
        # -- Additional dimensions to add to the metrics. Dimensions are searched for in the
        # -- resource and span attributes and are added to the metrics if present.
        dimensions: []
        histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
        max_items: 800000
        wait: 20s
        workers: 20
      span_metrics:
        # -- Additional dimensions to add to the metrics along with the default dimensions.
        # -- Dimensions are searched for in the resource and span attributes and are added to the metrics if present.
        dimensions: []
        histogram_buckets: [0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.02, 2.05, 4.10]
    storage:
      path: /var/tempo/wal
      wal:
      remote_write_flush_deadline: 2m
      # -- A list of remote write endpoints.
      # -- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
      remote_write:
        - url: "http://victoria -metric-endpoint/insert/60/prometheus/"
          send_exemplars: true
  service:
    # -- Annotations for Metrics Generator service
    annotations: {}

**Additional Context**

Sample Metrics : 

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/52820728/219278549-c5e0c4b5-6f32-4bc8-9b29-3a5e91e25bec.png">

**Comment by joe-elliott** [comment]
Thanks for reporting this issue! Some things to check:

- Metrics `tempo_distributor_forwarder_pushes_total` and `tempo_distributor_forwarder_pushes_failures_total`. Let's see if the distributor is having any issues pushing to the generators. It's possible the distributor -> generator queue is getting backed up and you're dropping data points.
- You are saying that you scaled to 5 generators. Can you use CPU or memory to confirm that all 5 generators are being used equally? You can also use the metric `tempo_metrics_generator_bytes_received_total`.

**Comment by sree-warrier** [comment]
Hi @joe-elliott,

Not seeing these 2 metric names tempo_distributor_forwarder_pushes_failures_total and tempo_metrics_generator_bytes_received_total in our Prometheus UI. But seeing tempo_distributor_metrics_generator_pushes_failures_total and tempo_distributor_metrics_generator_pushes_total. 

Now I am confused with the metrics names now, does it changes with every version. We have enabled service monitoring at tempo level. But the mentioned metric names are not seen. We are using tempo version 1.5 and tempo-distributed-0.26.1 chart version. Let me know if these are correct metric name, shall share the metric data too.

**Comment by joe-elliott** [comment]
Apologies, I mixed up the metric names. I thought we had moved everything to `tempo_distributor_forwarder_pushes_failures_total` but I was wrong. The correct metric name is the one you mentioned: `tempo_distributor_metrics_generator_pushes_failures_total`

**Comment by sree-warrier** [comment]
@joe-elliott we have upgraded the Tempo to 2.0 and past 10-12 days we are not facing any metric loss. Had made few changes with worker, stale_duration and collection_interval. Seems to be fine at the moment, if still issues are seen will update here to find the right cause. 

More over have few queries related to metrics names, seems most of the metric name has been changed now I am not seeing `tempo_distributor_metrics_generator_pushes_failures_total` metric name. Any reference to see the metric name 2.0 is using ?

**Comment by joe-elliott** [comment]
I'm still seeing `tempo_distributor_metrics_generator_pushes_failures_total` published internally so Tempo 2.0 should still be using it. The metric, however, is likely not created until it is incremented at least once. So if you are not seeing the metric it means there's been no failures.

Awesome to hear that 2.0 helped!

**Comment by sree-warrier** [comment]
@joe-elliott thanks for the update.
