### ISSUE TITLE
GCS client should implement expoential backoff when observing 503 errors from the API

### ISSUE THREAD

**Issue by zalegrala** [grafana/tempo#2107]
**Is your feature request related to a problem? Please describe.**
After a quick look, I don't see a mechanism to backoff during API errors.  In such a case, we may be compounding a rate limiting issue on Google side by not backing off slightly.

**Describe the solution you'd like**
We should have a way to temporarily reduce the calls to the API in order to let the rate-limiter recover.

**Additional context**

**Comment by mapno** [comment]
Fixed by https://github.com/grafana/tempo/pull/2111
