### ISSUE TITLE
Allow to configure RequestPathStyle within S3

### ISSUE THREAD

**Issue by yeabow** [grafana/tempo#2109]
**Is your feature request related to a problem? Please describe.**
Tempo's S3 config does not support set minio's BucketLookupType，for examples: The Volcano Engine product TOS S3 protocol request style only supports virtual host（https://www.volcengine.com/docs/6349/147050）

**Describe the solution you'd like**
expose the configuration

**Comment by joe-elliott** [comment]
I'm good on this if someone wants to wire up the config.
