### ISSUE TITLE
[DOC] Restructure "tempo in grafana" page to have sections that match the tabs in the Explore view

### ISSUE THREAD

**Issue by 09jvilla** [grafana/tempo#2125]
If you look at this page: 
https://grafana.com/docs/tempo/latest/getting-started/tempo-in-grafana/

the headers roughly match the different tabs available to the user in the explore view:

- view by trace id
- log search
- use traceql to dig deep into trace data 
- find traces using tempo search
- apm dashboard
- metrics from spans
- view json file
- linking traces and metrics

But I think it could be even clearer to the user if the structure of the page actually matched exactly the naming on the tabs in the explore view, and at the top of the page was explicit about "here are your options". 

Something like, "when you explore a tempo datasource, you'll have the following modes to choose from"

1. search
2. traceid
3. json file
4. service graph
5. loki search
6. traceql

Each of those 6 items becomes its own header, and then you drop in the content below them that explains what that mode lets you do. 

The content under the existing "linking traces and metrics" section needs to get broken out separately, and "metrics from spans" content feels a tad redundant with what we have under the service graph bit, but maybe the bit about exemplars goes under the "linking traces and metrics" standalone section. 

Note we have an active github issue to reduce the number of modes (6 is a lot!), so if this is a lot of work to refactor, maybe we just wait and fix this when we complete https://github.com/grafana/grafana/issues/57407

**Comment by Eve832** [comment]
Hi @knylander-grafana, can you please take a look and update this ticket?

**Comment by GrafanaWriter** [comment]
Looks like Tempo issues weren't automatically being added to triage. @knylander-grafana - FYI

**Comment by knylander-grafana** [comment]
The updated Explore editor is live in Ops: 
![image](https://user-images.githubusercontent.com/104772500/231225635-994074a8-9fab-481a-8886-151fc4a29507.png)

We can refactor this page pretty easily. I'll see about finishing the TOC review (PR https://github.com/grafana/tempo/pull/2320) and then tackling this restructure for both Cloud docs and Tempo docs.
