### ISSUE TITLE
Add an easy way to push spans

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#213]
Add an http endpoint that accepts a POST request with json encoded spans.  The spans should have a simplified data model and be designed to easily pushed from bash/javascript/python/whatever.

**Comment by calvernaz** [comment]
Hi @joe-elliott, I started looking into this because I like the idea of pushing spans easily, but I'm wondering how different this is from using Zipkin with HTTP. To be specific, this is what I mean:

1. Start Tempo with this configuration:
```
distributor:
  receivers:
    zipkin:
```

2. Then send an HTTP request from bash (note the target port "9411" for zipkin)

```
echo '[                                                                                                                                                     0 (0.291s) < 00:38:38
      {
        "id": "352bff9a74ca9ad2",
        "traceId": "5af7183fb1d4cf",
        "timestamp": 1556604172355737,
        "duration": 1431,
        "kind": "SERVER",
        "localEndpoint": {
          "serviceName": "backend",
          "ipv4": "192.168.99.1",
          "port": 3306
        },
        "remoteEndpoint": {
          "ipv4": "172.19.0.2",
          "port": 58648
        },
        "tags": {
          "http.method": "GET",
          "http.path": "/api"
        }
      }
    ]' | http POST :9411
HTTP/1.1 202 Accepted
Content-Length: 0
Date: Sat, 07 Nov 2020 10:04:55 GMT

```

3. Watch the trace in Tempo query:

<img width="1504" alt="Screenshot 2020-11-07 at 10 05 35" src="https://user-images.githubusercontent.com/1269712/98438246-dc8e2b80-20e0-11eb-8227-7878b699ceb2.png">

There is a chance what you propose is more generic, but I want to be sure

**Comment by joe-elliott** [comment]
That is extremely cool.  I did not know you could do that.  I was hoping to get down to something like this (tags being optional):
```
 {
        "id": "352bff9a74ca9ad2",
        "traceId": "5af7183fb1d4cf",
        "timestamp": 1556604172355737,
        "duration": 1431,
        "tags": {
          "http.method": "GET",
          "http.path": "/api"
        }
      }
```

Will zipkin accept this?  Also is there a way to set the operation name?

**Comment by calvernaz** [comment]
Let me try it later. Thanks

**Comment by calvernaz** [comment]
Hi @joe-elliott 

Answering your questions,

- Zipkin seems to accept that simple format
- the operation name would be the name field (example below)

Example
```
echo '[{                                                                                                                                           
 "id": "352bff9a74ca9ad2",
 "traceId": "5af7183fb1d4cf",
 "timestamp": 1556604172355737,
 "duration": 1431,
 "name": "creditAmount",
 "tags": {
     "http.method": "GET",
     "http.path": "/api"
  }
}]' | http POST :9411
```

<img width="1357" alt="Screenshot 2020-11-09 at 21 06 06" src="https://user-images.githubusercontent.com/1269712/98596487-6ac80480-22cf-11eb-8e09-83e9cdecd9ea.png">

**Comment by calvernaz** [comment]
So maybe this can be closed because we have an alternative ?

**Comment by joe-elliott** [comment]
Nice.  Thanks for the research!  This is exactly what I was looking for.

I will leave this open for now, because I want to document this clearly before closing, but it's nice to see the functionality already exists.

**Comment by annanay25** [comment]
Nice, this can be super useful. Can we turn this into a `curl -X POST -d [...]` ?

**Comment by bombsimon** [comment]
> Nice, this can be super useful. Can we turn this into a `curl -X POST -d [...]` ?

This should be equivalent:

```sh
curl -X POST http://localhost:9411 -H 'Content-Type: application/json' -d '[{
 "id": "352bff9a74ca9ad2",
 "traceId": "5af7183fb1d4cf",
 "timestamp": 1556604172355737,
 "duration": 1431,
 "name": "creditAmount",
 "tags": {
     "http.method": "GET",
     "http.path": "/api"
  }
}]'
```
