### ISSUE TITLE
Tempo ApmTable not working for spans containing *

### ISSUE THREAD

**Issue by FischlerA** [grafana/tempo#2140]
**Describe the bug**
The ApmTable does not properly work when multiple spans are retrieved and the span names contains a '*'. The issue is cause by the use of the regex expression to retrieve multiple spans, when querying only a single span with a * in the name it works fine. The issue is, that special characters are not automatically escaped by the query that gets run for the ApmTable.

**To Reproduce**
- Have multiple spans with a '*' in the name
- Run a query without a filter to retrieve multiple

**Expected behavior**
I expected all of the spans to returned, regardless of the contained symbols.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
We are using grafana-enterprise:9.2.4 with tempo-distributed helm chart version 1.2.0

**Comment by FischlerA** [comment]
@joe-elliott no problem :) Should we close this issue then as it is part of the grafana issues now?

**Comment by joe-elliott** [comment]
oops, yup, i meant to  do that :)
