### ISSUE TITLE
Missing example in Github repo

### ISSUE THREAD

**Issue by Depechie** [grafana/tempo#2147]
On the readme page for Docker Compose examples, there is a description for Loki derived fields. But this sample is no longer on the main branch.

Impacted readme link
[https://github.com/grafana/tempo/tree/main/example/docker-compose](https://github.com/grafana/tempo/tree/main/example/docker-compose)

Missing sample link [Loki Derived Fields](https://github.com/grafana/tempo/blob/main/example/docker-compose/loki/readme.md)

**Comment by joe-elliott** [comment]
Thanks for the heads up! Will remove.

**Comment by Depechie** [comment]
@joe-elliott I was actually looking for that sample... seeing it has been removed, is it hosted somewhere else? Or is there another example covering this?

**Comment by joe-elliott** [comment]
If you're looking for an example of setting this up I would recommend checking out this repo:

https://github.com/grafana/intro-to-mlt

It runs Mimir/Tempo/Loki with all kinds of correlations configured between them. You can find examples of loki derived fields, mimir exemplars and tempo traces to logs here:

https://github.com/grafana/intro-to-mlt/blob/main/grafana/provisioning/datasources/datasources.yaml#L39

Heads up that I wasn't able to get exemplars to work in main. My PR to fix is here:

https://github.com/grafana/intro-to-mlt/pull/30
