### ISSUE TITLE
Erroneous `TRACE_TOO_LARGE` on distributor for services with a high number of req/s

### ISSUE THREAD

**Issue by braunsonm** [grafana/tempo#2160]
**Describe the bug**
I was wondering if anyone on the Tempo team can confirm the behaviour I'm seeing. We have a service with a very high request/second rate that exports large batches of traces and spans in the same request to `/zipkin/spans` on the distributors we have deployed. We have bumped up the `max_bytes_per_trace` to a pretty large (probably too large) 50MB. Yet we are still getting the following in our logs:

```
TRACE_TOO_LARGE: max size of trace (524288000) exceeded while adding 242475 bytes to trace <TRACE> for tenant example
```

We are definitely not sending individual traces that are >50MB. Is it possible that when using the `/zipkin/spans` endpoint that this is treating the batched traces all under the same `max_bytes_per_trace` value? For instance we batch hundreds of traces together before they are sent to the endpoint and what I think is happening here is tempo is using the configuration limit for the entire batch, instead of applying it per trace.

**To Reproduce**
1. Create a service that generates a large number of spans and batches them all together, at least more than the default 5MB limit
2. Batch send all the traces at once (or updates to an existing) using the `/zipkin/spans` endpoint
3. Notice the error even if your traces are <5MB

**Expected behavior**
The quota limit should be applied per trace, not for the batches

**Environment:**
 - Tempo 2.0.0

**Comment by joe-elliott** [comment]
The code that is currently rejecting your trace is here:

https://github.com/grafana/tempo/blob/dcfd9e9669a93559166fe2f8f69e56900a240f9e/modules/ingester/trace.go#L57

When we accept a trace in the ingester we build the struct linked above and hold it in a [map](https://github.com/grafana/tempo/blob/dcfd9e9669a93559166fe2f8f69e56900a240f9e/modules/ingester/instance.go#L100). This code generates the map key:

https://github.com/grafana/tempo/blob/dcfd9e9669a93559166fe2f8f69e56900a240f9e/modules/ingester/instance.go#L531

I suppose it's possible there's a collision occurring and multiple traces are getting mapped to the same key. It seems unlikely but with enough live traces it will eventually happen. It would be interesting to see what your `tempo_ingester_live_traces` metric is at when this issue occurs.

Can you query Tempo for the trace that was rejected and share it?

**Comment by braunsonm** [comment]
I can't query for the trace that Tempo is rejecting because the search fails with the same error about the size being too large.
```
received message after decompression larger than max (5136360 vs 4194304)
```

My  `tempo_ingester_live_traces` is pretty low, seems to max out at 150.

And if I `rate(tempo_distributor_bytes_received_total[5m])` the values hover around 130KB to 300KB. It doesn't seem nearly enough bytes to be getting traces rejected with my `max_bytes_per_trace` set to 50MB

**Comment by joe-elliott** [comment]
> My tempo_ingester_live_traces is pretty low, seems to max out at 400.

That seems way to low to have regular collisions. Highly unlikely to be the cause.

> Not sure if relevant but I get this error on the distributor and you linked code in the ingestor

The distributor is just propagating that error back from the ingester.

> And if I rate(tempo_distributor_bytes_received_total[5m]) the values hover around 260KB to 600KB. It doesn't seem nearly enough bytes to be getting traces rejected with my max_bytes_per_trace set to 50MB.

It's possible you are reusing a long running trace id. One way to determine that would be to enable "log received spans" in the distributor. This will create a lot of log traffic but you will clearly see all spans passed to the distributors. You could use this to see if  you are sending to the trace id over a long period of time.
```
distributor:
  log_received_spans:
    enabled: true
```

Another next step is to retrieve the trace in question and use it as a clue of what may be going wrong. If Tempo is refusing to return the trace then it is likely it has a ton of spans under the same trace id. You can use the [Tempo CLI](https://grafana.com/docs/tempo/latest/operations/tempo_cli/) to retrieve the trace directly from the blocks:

```
go run ./cmd/tempo-cli query blocks <trace id> <tenant id> --backend=<s3|gcs|azure|local> --bucket=<bucket name or path>
```

**Comment by braunsonm** [comment]
So I ran the command @joe-elliott and it pulled back a file that is 7.5GB... 
It helped us find the problem as you suspected there is an app that was reusing the same trace ID. Going to keep the Tempo CLI in my back pocket for future issues, would be great to see that published or included as part of the `tempo` binary in the future. 

Thanks again.
