### ISSUE TITLE
Dynamic Sampling

### ISSUE THREAD

**Issue by altanozlu** [grafana/tempo#2166]
**Is your feature request related to a problem? Please describe.**
In one of our services we want to sample every route, user, app version by another ratio, the problem is generated metrics won't reflect the reality.

**Describe the solution you'd like**
using float64 attribute named `X-SampleRatio` we can multiply all the metrics by `1.0/ratio` 

**Additional context**
It's just like what HoneyComb does in https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/main/deterministic_sampler.go and https://docs.honeycomb.io/manage-data-volume/sampling/

If it's okay i would like to implement it.

**Comment by joe-elliott** [comment]
I'm fine with this, but what clients produce `X-SampleRatio`? Also, when you add this please make it configurable with default to off for backwards compat.

Jaeger passes similar data through it's root span that can be used to "undo" sampling when generating metrics:
![image](https://user-images.githubusercontent.com/2272392/222778848-a6ca7871-d118-40fd-a0cb-6e294319c014.png)

We have been wanting to implement this for awhile, but have been waiting on OpenTelemetry to define the semantic conventions and implement it in their clients.

**Comment by altanozlu** [comment]
It's the custom sampler in OTEL which produces `X-SampleRatio`, i don't think anyone uses `X-SampleRatio` as a span attribute but yea it should be off by default. if `X-SampleRatio` isn't provided it'll be 1 as default.
