### ISSUE TITLE
Ingesters sometimes fail to flush

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#217]
Ingesters sometimes fail to flush with this message:
```
msg="failed to flush user" err="remove /var/tempo/wal/b0c58d18-03d5-4f25-b24a-3359886d0c8d:1: no such file or directory"
```

This is innocuous in that it means that the wal file was already cleared, but should still be investigated.

**Comment by calvernaz** [comment]
I can replicate this same error artificially by removing the file manually while the ingester is about to flush user traces.

1. Put a breakpoint here [tempodb.go](https://github.com/grafana/tempo/blob/master/tempodb/tempodb.go#L198)
2. Push some spans and wait (`MaxBlockDuration`) for a block to be considered complete.
3. Once we have a breakpoint hit (step 1), remove the file under the WAL.
4. Step continue on debugging and the error will appear.

Now, my theory is this might happen in a situation where we are flushing the user traces and replaying the WAL (ingester restart). When replaying the WAL we are clearing previous blocks (https://github.com/grafana/tempo/blob/master/modules/ingester/ingester.go#L272)

Could it be a race condition between the ingester flush to the backend and the WAL replay? Happy to investigate further if this makes sense or if you have any other clues.

**Comment by joe-elliott** [comment]
The WAL only replays on startup so it should have no impact here.  My guess is this is related to the queue of flush jobs created in the ingester.  Probably a race condition, or broken logic related to to that queue.

I'm wondering if we are flushing blocks twice occasionally or something.

**Comment by joe-elliott** [comment]
Unsure why, but this appears to have gone away with our latest internal build.  It was built off of https://github.com/grafana/tempo/commit/670cf4b7f5aec8787dc7472d1322ef9f05a88630

Will continue to leave this open for awhile in case it comes back.

![image](https://user-images.githubusercontent.com/2272392/99674140-a4251080-2a43-11eb-89b0-e035a4fb83b4.png)

**Comment by joe-elliott** [comment]
Ok, we have observed it again:

![image](https://user-images.githubusercontent.com/2272392/99701333-51a71c80-2a62-11eb-8a23-6ca836c8f8d4.png)

We can also see that they are correlating with a spike in ingestion to 200k+ spans/second.  So that suggests it is a race condition and the timing was impacted by stress.

**Comment by calvernaz** [comment]
I'm actively monitoring this (that's why I'm jumping around between large spans and this) - I still can't reproduce all the time, but I figure so far that when it happens it's because two flush operations for the same block are queued and the second one fails.

Hopefully I'll come back with a fix or at least with the issue fleshed out.

**Comment by calvernaz** [comment]
From the investigation, this is what I think it's happening - unfortunately, is a bit hard to represent the condition of how it happens.

```
Ingester -- loop
 - sweepUsers
  |- sweepInstance
    |- CutCompleteTraces
    |- CutBlockIfReady          -- goroutine -- i.completeBlocks = append(i.completeBlocks, completeBlock)
    |- ClearFlushedBlocks

Ingester -- loop
 - sweepUsers
  |- sweepInstance
    |- CutCompleteTraces
    |- CutBlockIfReady
    |- ClearFlushedBlocks
    |- GetBlockToBeFlushed
      |- Enqueue block to flush  (/wal/6b7ecd72-a30a-4aa4-b0db-b0b0b5f28eda:single-tenant)                                                    
                                 
                                      --- goroutine --- flushLoop()
                                           - flushUserTraces
                                            |- Write
Ingester -- loop
  - sweepUsers
  |- sweepInstance                               //
    |- CutCompleteTraces                         // between write and flushed there is a double enqueueing of the same block
    |- CutBlockIfReady                           //
    |- ClearFlushedBlocks
    |- GetBlockToBeFlushed
      |- Enqueue block to flush   (/wal/6b7ecd72-a30a-4aa4-b0db-b0b0b5f28eda:single-tenant)                                          
                                           |- Flushed  (/wal/6b7ecd72-a30a-4aa4-b0db-b0b0b5f28eda:single-tenant)
                               
```

This is probably not the only way double enqueueing can happen.

**Comment by joe-elliott** [comment]
Yup, `sweepInstance` puts an instanceid in a queue, `flushLoop` picks it up and then iterates through all flushable blocks on that instance and attempts to flush them all.  If it takes longer to write the block then the flush loop time then it will queue the same instanceid again and will attempt to flush it again.  It is even likely that we are at times attempting to flush the same block at the same time.

We're not losing data, but we're probably being quite wasteful.   Thank you for the research.
