### ISSUE TITLE
[Metrics-generator] Use semantic Prometheus translation of attributes/labels

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#2177]
In the metrics-generator, to convert span and resource attributes to Prometheus labels, we just [_sanitize_](https://github.com/grafana/tempo/blob/main/modules/generator/processor/spanmetrics/spanmetrics.go#L131) them. Which involves of substituting `.` with `_`.

While that is correct, the [Prometheus spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes-1) further specifies how some resource attributes should be used. This means, that in order to properly follow the spec, we need to change two translations
- [ ] span `service.instance.id` to metric `instance`
- [ ] span `service.name` to metric `job`
- [ ] span `service.namespace` to metric `job`, if `service.name` is not present

**Comment by Jxlam-pdx** [comment]
This is a dup of #199
