### ISSUE TITLE
local-tempo exiting with code 137

### ISSUE THREAD

**Issue by joosthooz** [grafana/tempo#2198]
**Describe the bug**
When running a local example docker-compose instance, the `local-tempo` image crashes with code 137 when I'm sending a fairly large volume of spans (about 15.000 spans in a trace of about 0.8 seconds). This trace is generated by Apache Arrow with ARROW_TRACING_BACKEND=otlp_http, running a data conversion job using pyarrow (converting about 750 MB of data from csv to parquet). I've set `grpc_server_max_recv_msg_size`, `grpc_server_max_send_msg_size`, and `max_bytes_per_trace` to very large numbers because they were causing problems first. 
(Note: Traces like these are ingested by a local Jaeger instance without problems.) 

Error messages include:
```
{"error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup tempo on 127.0.0.11:53: server misbehaving\"","interval":"35.010326599s"}
```
and
```
{"error":"rpc error: code = Unavailable desc = error reading from server: read tcp 172.25.0.4:59302->172.25.0.2:4317: read: connection reset by peer","interval":"5.530719487s"}
local-tempo-1 exited with code 137
```

**To Reproduce**
1. pull latest tempo
2. Update values above in `example/docker-compose/shared/tempo.yaml`
3. run `docker-compose up` in `example/docker-compose/local`
4. Run the program that sends the large trace in another terminal
5. Observe error messages in docker-compose window

**Expected behavior**
I expect the trace to be ingested by Tempo and showing up in the Grafana webUI.

**Environment:**
 - Laptop with SSD and 32G RAM

**Additional Context**

**Comment by joe-elliott** [comment]
I believe exit code 137 is provided by the kernel when it kills a process that is consuming too much memory, but I am unsure what memory limitations are imposed by running in docker compose. Perhaps try one of these settings:

https://stackoverflow.com/questions/61416158/increase-memory-of-docker-container-with-docker-compose-on-windows

**Comment by joosthooz** [comment]
Thank you for the response, adding a `mem_limit` to the Tempo service in the `docker-compose.yaml` file seems to help; i'm no longer seeing the crashes!
However, I'm not able to find the traces in Grafana. The webUI says that search is not enabled in Tempo, but I can't find the instructions for how to enable it. In this doc page https://grafana.com/docs/tempo/latest/getting-started/tempo-in-grafana/, there is a link to where this information should be: https://grafana.com/docs/tempo/latest/configuration/#search, but the "search" section in that page is missing.

**Comment by joe-elliott** [comment]
I believe [Grafana 9.4](https://grafana.com/blog/2023/02/28/grafana-9.4-release/) has TraceQL and tags based Search enabled by default. What version are you running?

**Comment by joosthooz** [comment]
I'm deploying the docker-compose local example from latest main, the Grafana webUI that gets deployed along with that says it is version 9.3.2. When I navigate to Explore -> (Query type) search, it says "Unable to connect to Tempo search"

**Comment by joosthooz** [comment]
If I change the image version in the docker-compose file to run Grafana 9.4.3, it says the same. If I click e.g. "service Name", it will say "No options found"...

**Comment by joe-elliott** [comment]
On Tempo's side check:

- logs for obvious errors,
- the metric `tempo_distributor_spans_received_total` to see if tempo is receiving anything
- use the `log_received_spans` feature of the [distributor](https://grafana.com/docs/tempo/latest/configuration/#distributor) to see exactly what tempo is ingesting

On Grafana side double check that your data source is setup correctly. It sounds kind of like it's not pointed at Tempo correctly.

**Comment by joosthooz** [comment]
Hi, using the received span logger I've managed to find traceIDs and I can view my traces in Grafana! Thank you for the help. The search tab is still not working, but I should probably create a new issue for that.
