### ISSUE TITLE
Autocomplete returning both integer and string types for `status` field

### ISSUE THREAD

**Issue by 09jvilla** [grafana/tempo#2200]
For the `status` field, Tempo autocomplete returns both strings (`unset`, `error`, `ok`) and integers `0`, `1`, `2`. This causes a confusing result when users looks at the possible values for `status` (see screenshot) - they're left wondering if status should be treated as an integer or a string for the purposes of building a TraceQL query?

<img width="716" alt="status-autocomplete" src="https://user-images.githubusercontent.com/9610816/224867452-5c3d6e60-f178-4f74-bf90-110c8f6bd139.png">

It appears that numerical comparison operators (`=`) aren't working with the integer values (`0`). 

<img width="922" alt="autocomplete-status-fail" src="https://user-images.githubusercontent.com/9610816/224867838-b8b6edee-efdf-40ce-8d5f-82270ca26870.png">

**Comment by joe-elliott** [comment]
currently we collect "virtual tag" values here:

https://github.com/grafana/tempo/blob/main/modules/querier/querier.go#L394

but then we continue processing? should we just stop after this loop if any values are found?
