### ISSUE TITLE
migrate from jaeger-sdk to otel-sdk

### ISSUE THREAD

**Issue by frzifus** [grafana/tempo#2224]
**Is your feature request related to a problem? Please describe.**

Currently all [tempo components](https://github.com/grafana/tempo/blob/d5e734c40216ad0db00c7c54cbe1ef685d90681a/docs/sources/tempo/operations/monitoring.md#traces) are instrumented using the [Jaeger-SDK that is at end of life](https://github.com/jaegertracing/jaeger-client-go#-this-library-is-deprecated). This requires additional configurations to collect those traces and might leads to future security issues. 

**Describe the solution you'd like**
Migrate to OTEL-sdk. ^^

**Describe alternatives you've considered**

**Additional context**

**Comment by joe-elliott** [comment]
Yes! I agree we need to move forward to the OTEL clients. At one point there was an attempt to do this:

https://github.com/grafana/tempo/blob/944e5ae0e82d61b0042a3dd941cbf8310944063d/cmd/tempo/main.go#L230

but for some reason context was not propagating between services and the work got shelved. If you, or anyone else, would like to take up figuring out the last bits we would be grateful.

**Comment by frzifus** [comment]
I would like to look at it more closely. But I will not be able to do that in the next weeks. :pensive:
