### ISSUE TITLE
Undeterministic results when filtering on error field

### ISSUE THREAD

**Issue by ogxd** [grafana/tempo#2225]
**Describe the bug**
When filtering on the error field, we have little to no results, and it varies from time to time.
When using TraceQL, we don't have a single result, while there should be many traces with a span error=true.
![image](https://user-images.githubusercontent.com/12692438/225889246-38eca7d1-d869-483b-a9ec-b2b295c5964e.png)

**Expected behavior**
List all traces filters by the error field

**Environment:**
 - Infrastructure: Kubernetes
 - Grafana v9.3.6

**Additional Context**
Here is a video repro:
https://user-images.githubusercontent.com/12692438/225888644-10dc9898-21ad-4484-aa8f-2d237137eca1.mov

**Comment by joe-elliott** [comment]
I think there a couple of issues here:

1) Looking through the code I don't think we correctly support `error=true` on `vparquet` blocks. This is likely a legitimate bug. On tags based search I would recommend searching for `status.code=error` for equivalent results.

2) When first building Tempo tags based search we attempted to support a number of "Jaeger-isms" like `error=true`, but this has only caused issues long term. TraceQL drops all of these "Jaeger-isms" and accurately translates your query directly into the OTEL data model. In OTEL you are searching for the [status span intrinsic](https://github.com/open-telemetry/opentelemetry-proto/blob/4b23e936e1c7b76244ac0c3f77e023b42dad7c6e/opentelemetry/proto/trace/v1/trace.proto#L256). In this case I recommend searching for:
```
{ status = error }
```

3) The final piece of the puzzle is that the "error" attribute you are seeing in Grafana [isn't real](https://github.com/grafana/grafana/issues/59607). Your span doesn't actually have an attribute named "error" and so TraceQL will not find it. We are working with Grafana to get it corrected in the frontend. Other attributes that Grafana creates that aren't real:

- `status.code`: use `{ status = error }` instead 
- `span.kind`: use `{ kind = client}` instead. Support for kind [being added here](https://github.com/grafana/tempo/pull/2217) and will be in 2.1

What's happening next that will help:

- The old search api is being phased out. Grafana will continue to have a similar "easy search" interface that has all the same options as the current search, but will build a TraceQL query.
- Grafana will correctly represent your spans to reduce confusion.

Thanks for your patience on this!

**Comment by ogxd** [comment]
Thank you @joe-elliott for these in-depth explanations and the workaround!
