### ISSUE TITLE
[Trace Explorer] Autocompletion suggests fields `span.name` and `.name` but queries fail

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2233]
**Describe the bug**

Autocompletion suggests `span.name` and `.name` but:
* Autocompletion for the value of `.name` and `span.name` don't work
* Queries return no entry instead of returning the same entries as a query on `name`

Note that the same problem exists for `span.status`

**To Reproduce**

* Ingest traces including server kind spans named `POST /api/orders`
* Navigate to Grafana Explore Tempo and select the TraceQL tab
* Type the following TraceQL queries:
   * `name=`
      * Autocompletion suggest enad of attribute name `name`
      * Autocompletion suggests value `POST /api/orders`
      * Query on `name="POST /api/orders"` returns entries
   * `.name=`
      * Autocompletion suggest end of attribute name `.name`
      * Autocompletion DOESN'T suggest any value
      * Query on `.name="POST /api/orders"` returns NO entry
   * `span.name=`
      * Autocompletion suggest end of attribute name `span.name`
      * Autocompletion DOESN'T suggest any value
      * Query on `span.name="POST /api/orders"` returns NO entry

**Expected behavior**

TraceQL queries on `name="POST /api/orders"`, `.name="POST /api/orders"`, and `span.name="POST /api/orders"` should return the same entries.

**Environment:**
 - Infrastructure: Grafana Cloud as of 2023-03-19

**Screenshot**

* works as expected
<img width="2242" alt="image" src="https://user-images.githubusercontent.com/459691/226182944-fa86a792-9b4f-40d4-93eb-8ea2dee5ef1d.png">

* fails
<img width="2242" alt="image" src="https://user-images.githubusercontent.com/459691/226183157-99a7f3dd-e1ea-4ff5-a857-654a1dacbc6a.png">

**Comment by cyrille-leclerc** [comment]
The same problem exists for `span.status`.
@joe-elliott shall I create a dedicated bug report for `span.status`?

**Comment by joe-elliott** [comment]
No, we can fix all these with this one issue. Thanks cyrille!
