### ISSUE TITLE
Provide optional matchers to tag(s) search

### ISSUE THREAD

**Issue by alex5517** [grafana/tempo#2235]
**Is your feature request related to a problem? Please describe.**
Not related to a problem per se.

**Describe the solution you'd like**
I would like to be able to filter /api/search/tags and /api/search/tag/<tag>/values by providing optional matchers like you can for Mimir /api/v1/label/{name}/values

The reasoning for this is for multi tenancy setup it is not desirable for each tenant to be able to see the service names of other tenants and the values.

**Comment by mapno** [comment]
This was addressed in https://github.com/grafana/tempo/issues/1868. It's currently behind the feature flag `autocomplete-filtering.enabled`
