### ISSUE TITLE
[Trace Explorer] Trace view reports an attribute `status.code` that doesn't exist in the actual OTel span and doesn't work in TraceQL

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2249]
**Describe the bug**

The trace view reports an attribute `status.code` that doesn't exist in the actual OTel span and doesn't work in TraceQL.
It seems to be a surrogate to display the span status ( unset(0), ok(1), error(2) ) but this visualization is misleading as using this attribute in TraceQL fails: `{span.status.code = 2}` returns zero results even if there are traces with `error` status.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/459691/226764097-a77da915-78c4-43b9-a4fe-eaa095db156e.png">

**Environment:**
 - Grafana Cloud Traces 2023-03-22

**Comment by joe-elliott** [comment]
This is a grafana issue and is documented here: https://github.com/grafana/grafana/issues/59607
