### ISSUE TITLE
The `metrics-generator` is an optional component but distributor is not aware of it.

### ISSUE THREAD

**Issue by ShimonOhayon** [grafana/tempo#2259]
**Describe the bug**
When opting not to deploy the `metrics-generator` the distributor fail to forward requests to it even tho it's require or configured to.
This causes spamming the logs with unnecessary warnings:

`level=warn ts=2023-03-27T07:58:35.839942279Z caller=forwarder.go:221 msg="failed to forward request to metrics generator" err="DoBatch: InstancesCount <= 0"`

**To Reproduce**
1. Start Tempo 2.0.1
2. Do not deploy metrics-generator
3. Watch distributor logs 

**Expected behavior**
No attempts to forward requests to that component
No warning in logs.
The distributor is metrics-generator "aware"

**Environment:**
 - Infrastructure: Kubernetes 1.24
 - Deployment tool: helm:
 ```
  repository       = "https://grafana.github.io/helm-charts"
  chart            = "tempo-distributed"
  version          = "1.2.7"
 ```

**Additional Context**
tempo image = `image: docker.io/grafana/tempo:2.0.1`

I search this repository to look for an open or closed issue that address it with no finding.
There is nothing in the documentation that address it.

**Comment by ShimonOhayon** [comment]
Hi @joe-elliott 
It's seems like this is the problem,
these override are there by [default](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L1121) in the  `values.yaml` in the helm chart mentioned above,


Also i can confirm they are there on the actual config-map deployed.

Since the `metrics generator` component is disabled by [default](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L217)
```
metricsGenerator:
  # -- Specifies whether a metrics-generator should be deployed
  enabled: false
```

I believe it's a inconsistency in the helm chart itself in not in the code here. Probably additional condition is needed.
So with this info it's seems like this issue belong elsewhere.

Also i assume Is it safe to have empty list for the `metrics_generator_processors` under the `global_overrides` ?

**Comment by ShimonOhayon** [comment]
I can confirm that overriding the default values file with these values, solve the issue for now:

```
global_overrides:
  metrics_generator_processors:
 
```
In my opinion the [current](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L1121) value should be added only if metric generator is enabled

**Comment by joe-elliott** [comment]
Yup, that's a good point. I will file an issue in the helm-charts repo for the tempo-distributed helm chart. If metrics-generators are not scaled up by default then we shouldn't configure the distributors to attempt to send to them.

**Comment by ShimonOhayon** [comment]
Thanks. Closing here
