### ISSUE TITLE
TraceQL dont support to query using variable like "{xxx,yyy}"

### ISSUE THREAD

**Issue by chenshijian73-qq** [grafana/tempo#2272]
if pod have mutil values,just like {xxx,yyy}(the variable 'pod' set in panel variables, and checed option of Multi-value)
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/116276614/228443625-136a37d9-b3ce-4948-bf42-b4438b3a7a2d.png">
then cant get any result. only support single value.
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/116276614/228443255-904c1dea-bad7-446c-b0a6-7a36a55515a2.png">
it support the format like key=~"xxx|yyy",but the variable from panel is "xxx,yyy"

**Comment by mapno** [comment]
Hi @chenshijian73-qq. You need to use this advanced formatting option https://grafana.com/docs/grafana/v8.4/variables/advanced-variable-format-options/#pipe

`{.service.instance.id =~ '${pod:pipe}'` will do what you want.

Note: consider using scope (`resource` and `span`) in attributes whenever possible. This will speed up search significantly.

**Comment by mapno** [comment]
Closing as resolved. Please re-open if it is not.
