### ISSUE TITLE
Unable to run tempo from a sub path

### ISSUE THREAD

**Issue by vishynit** [grafana/tempo#2275]
**Describe the bug**
I am trying to run tempo from a subpath /tempo using arguments - http-api-prefix: /tempo. It seems like it is not working.

**To Reproduce**
1. Get Tempo values.yaml via Helm Chart
2. Add extraArgs: http-api-prefix: /tempo in yaml file
3. Install using the updated file.

**Expected behavior**
The API should be available on subpath - /tempo/metrics, /tempo/ready, /tempo/status etc but it is still available in root context.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Additional Context**
I want to run tempo from a sub path in order to configure ingress with the same path.

**Comment by joe-elliott** [comment]
The http api prefix applies to all paths that begin wit h`/api`:

https://grafana.com/docs/tempo/latest/api_docs/

It does not apply to "maintenance" or "admin" style endpoints. Does this meet your needs?

**Comment by vishynit** [comment]
@joe-elliott 
I want the api /v1/traces to be prefixed with /tempo and so the final endpoint would be http://tempo:4318/tempo/v1/traces. Is there any way I can do this?

I have a grafana, loki, victoria metrics and tempo deployed on a same k8 cluster. My main requirement is to have a path based Ingress configured. Please guide on /v1/traces and other related api's of tempo can be setup on a sub path.

![image](https://user-images.githubusercontent.com/52401068/229572399-e41dbac3-1007-40f0-bea9-8b9309e6df13.png)

**Comment by joe-elliott** [comment]
The endpoint you are looking for is: `/api/traces/<trace id>`. This endpoint should honor the api prefix. Does this not work:

```
http_api_prefix: /tempo
```
