### ISSUE TITLE
TraceQL only supports single value with * query, when multi-value query, if there is a value with *, it will reutrn "no data"

### ISSUE THREAD

**Issue by chenshijian73-qq** [grafana/tempo#2279]
# Describe the bug
(the variable "a" set in panel, query using promethues datasource.)
For example,
a = "/api/xxx/\*/yyy"
TraceQL query: {name="$a"} 
get data successfully. but if 
a = "/api/xxx/\*/yyy,/api/zzz"
The following kind of TraceQL query get nothing
{name=\~"${a:pipe}"} 
{name=\~"${a:regex}"} 
{name="${a:pipe}"} 

# Expected behavior
traceQL support to query using multi-values with *

**Comment by chenshijian73-qq** [comment]
yes, using * as actual value. I know using .* can solve this problem,but my problem is the values come from variable setting in panel，I can't modify the value.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/116276614/228799024-bc18befb-ba25-4c19-8348-0639333300ad.png">

**Comment by chenshijian73-qq** [comment]
> Are you using `*` as actual value, or to match _anything_?
> 
> TraceQL uses Golang regex. To match _anything_ you have to use `.*`, instead of `*`. Then, `api|xxx|.*|yyy|api|zzz` and `.*` are equivalent, since `.*` will match anything.

yes, using * as actual value. I know using .* can solve this problem,but my problem is the values come from variable setting in panel，I can't modify the value.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/116276614/228799024-bc18befb-ba25-4c19-8348-0639333300ad.png">

**Comment by joe-elliott** [comment]
Is this a Grafana traces panel templating issue? or a TraceQL issue?

**Comment by chenshijian73-qq** [comment]
> Is this a Grafana traces panel templating issue? or a TraceQL issue?

i think it is  a TraceQL issue. 
a = "/api/xxx/*/yyy,/api/zzz"
{name=~"${a:regexp}"} converts the contents of a into a = "\/api\/xxx\/\*\/yyy|\/api/\zzz", and then report a format error when querying

**Comment by chenshijian73-qq** [comment]
> > Is this a Grafana traces panel templating issue? or a TraceQL issue?
> 
> i think it is a TraceQL issue. a = "/api/xxx/*/yyy,/api/zzz" {name=~"${a:regexp}"} converts the contents of ’a‘ just like this a = "\/api\/xxx\/\*/\yyy|\/api/\zzz", and then report a format error when querying

**Comment by joe-elliott** [comment]
> and then report a format error when querying
what error is being reported?

If the query is this:
```
{ a = "\/api\/xxx\/\*\/yyy,\/api\/zzz" }
```
There are two errors that I can see:
1) `a` is not a valid identifier. likely you mean `span.a`
2) `\/` is not a valid escape sequence. just use `/`.

This feels like a Grafana templating issue and not a traceql issue. Using explore can you construct the query you want? Does the issue only occur when using the Grafana traces view panel? Is Grafana inserting the escape sequences unnecessarily?

**Comment by chenshijian73-qq** [comment]
> 

yes, using explore can do what i want. So the problem is that i want to use the grafana traces view panel.
but if dont use the escape sequences, 
```
{ a = "/api/xxx/*/yyy"}
the query: {name="${a}"} can get data
```
```
{ a = "/api/xxx/*/yyy, /zzz/ddd"}
the query: {name=~"${a:pipe}"}  report the error
```
