### ISSUE TITLE
Version info is missing from startup log and status endpoint

### ISSUE THREAD

**Issue by electron0zero** [grafana/tempo#2283]
**Describe the bug**
version is missing from status endpoint, and startup log messages

![image](https://user-images.githubusercontent.com/9503187/228927402-413e5705-6a0a-470f-ba43-797e358ea30a.png)

![image](https://user-images.githubusercontent.com/9503187/228933989-50176e5d-1cff-4011-9338-d1ad12a59b80.png)

**To Reproduce**
1. Start Tempo (SHA or version)
2. check logs or `/status` for any component

**Expected behavior**
shows version info correctly in startup log and status endpoint

**Environment:**
anywhere with the official tempo builds (tested with docker image)

**Additional Context**

**Comment by joe-elliott** [comment]
Similar to: https://github.com/grafana/tempo/issues/1908

**Comment by electron0zero** [comment]
fixed in https://github.com/grafana/tempo/pull/2319#issuecomment-1501883588
