### ISSUE TITLE
[TraceQL] Support empty spansets as a valid return

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2288]
**Describe the bug**
Currently TraceQL is built around the idea of passing a  set of spans through a pipeline of filters. if any spans survive the filter then the spanset matches the query and is returned to the frontend. 

There are, however, corner cases where an empty spanset should indicate a match to a query. For instance:
```
{ false } | count() = 0
```
feels like it should match every trace, but due to the behavior described above this will return nothing.

**Comment by mapno** [comment]
I'm not convinced this is a bug. IMO it's working as expected.

The query is just a weird double negation:
`{ false }` - don't match anything
`| count() = 0` - where this happens 0 times

I'd expect this to return nothing if the selector doesn't match any spans. I don't like the right-hand side of the pipe, affecting the left-hand side. That's not how piping usually works.

**Comment by joe-elliott** [comment]
When I was initially building TraceQL I was thinking of the language as passing sets of spans through a pipeline of operators. Those spansets that contained spans at the end the pipeline would indicate a selected trace. However, the operation `count() = 0` feels like a meaningful thing in the language. 

Shouldn't this be legal?
```
{ resource.service.name = "foo" } | count() = 0
```
i.e. show me all traces that never have a service name "foo"

**Comment by mapno** [comment]
I agree with your thoughts here. `count() = 0` should totally be supported. It seems very useful to encourage a discovery flow with traces by _taking things out_. That's a pattern that I use very frequently with logs.

But, I believe we should stick to the concept of passing sets of spans through pipes. Ie. the original example `{ false } | count() = 0` should return no results. Otherwise the operator would be retroactively affecting what the selector returns.

**Comment by mdisibio** [comment]
> { resource.service.name = "foo" } | count() = 0

Yeah I'm also on the fence if that query should work as-is. There are some large implications to make that work.  The spanset selector `{ resource.service.name = "foo" }` would have to return something for every trace whether it matched or not.  This is a large departure from current behavior and I think not desirable.  Also means we couldn't efficiently jump around the block.    We could make the engine logic change that I think you are thinking of work with a query like `select(resource.service.name) | { resource.service.name = "foo" } | count() = 0` which is explicitly selecting everything, and then empty spansets could be passed on. (Not necessarily proposing this approach, just voicing some thoughts).
