### ISSUE TITLE
Enhance the endpoint to retrieve resource attribute names and values

### ISSUE THREAD

**Issue by jpkrohling** [grafana/tempo#2297]
The App O11y squad is building a plugin that will help users filter data related to services. We'd need to be able to retrieve the resource attribute names for a given service, and which values are available for the combination of (service.name + resource attribute name).

What we need is close to two of the endpoints that exist already and are part of this doc:
https://grafana.com/docs/tempo/latest/api_docs/#search-tags

**Comment by jpkrohling** [comment]
cc @cedricziel

**Comment by joe-elliott** [comment]
A PR for this is up now:
https://github.com/grafana/tempo/pull/2253

**Comment by jpkrohling** [comment]
That was quick!
