### ISSUE TITLE
Document traces to logs in Tempo

### ISSUE THREAD

**Issue by gouthamve** [grafana/tempo#2303]
This page lists how to do Logs to Traces and Metrics to traces: https://grafana.com/docs/tempo/latest/getting-started/tempo-in-grafana/

It should also document how to do Traces to logs, with some sensible defaults to configure: https://grafana.com/docs/grafana/next/datasources/tempo/#trace-to-logs

**Comment by knylander-grafana** [comment]
Completed: https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#trace-to-logs
