### ISSUE TITLE
Add query parameter to Search API to configure the spans per span set

### ISSUE THREAD

**Issue by stoewer** [grafana/tempo#2308]
**Is your feature request related to a problem? Please describe.**

When the Search API returns traces from TraceQL queries, each returned `spanSet` contains the matching spans within each trace. The maximum number spans in the `spanSet` is limited by [spansPerSpanSet](https://github.com/grafana/tempo/blob/97daaacebb58e6e0005f1c380894082dd1081753/pkg/traceql/engine.go#L22), which is currently set to 3.

**Describe the solution you'd like**

The `spansPerSpanSet` should be configurable with a query parameter to adjust the maximum number of matched spans returned in a `spanSet`.

**Additional context**

Together with #2307 this enables the UI to implement a feature to show more matched spans on demand.

**Comment by mghildiy** [comment]
I would like to take it.

**Comment by joe-elliott** [comment]
@mghildiy go for it!

**Comment by mghildiy** [comment]
In api/http.go, I see:

**PathTraces          = "/api/traces/{traceID}"**

I guess this is the enpoint to which we need to add new query paramter?

**Comment by mapno** [comment]
That's the endpoint for ID lookups. For search, [`/search`](https://grafana.com/docs/tempo/latest/api_docs/#search) is used. That's where you need to add the query param.

**Comment by mghildiy** [comment]
I have added new field in SearchRequest:

`uint32 SpansPerSpanSet = 9;`

'make tempo' runs  fine, but I dont see tempo.pb.go updated.

Any extra step needed for protos?

**Comment by mapno** [comment]
You need to run `make gen-proto` to regenerate the go proto files.

**Comment by mghildiy** [comment]
I couldn't get it working on windows, so for testing purposes I manually modify tempo.pb.go :).

**Comment by mghildiy** [comment]
I have added the new query parameter to configure spans per span set.

But this one too has same issues as #2307 regarding actual reflection in final result of the query processing.
Spans returned inside spanset at:

https://github.com/grafana/tempo/blob/main/pkg/traceql/engine.go#L83

doesn't reflect the filtering done by filter function fetchSpansRequest.Filter

https://github.com/grafana/tempo/blob/main/pkg/traceql/engine.go#L62-L66

I can commit the changes done for query parameter though,

**Comment by mghildiy** [comment]
I have a question. 

In engine_test:TestEngine_Execute, test query is:

`Query: `{ .foo = .bar }``

My understanding is that query is meant to search for all the spans which have both foo and bar attributes, and both have same value

If yes, then I see that even a span below:

```
&mockSpan{
	id:                 []byte{4},
	startTimeUnixNanos: uint64(now.UnixNano()),
	durationNanos:      uint64((100 * time.Millisecond).Nanoseconds()),
	attributes: map[Attribute]Static{
		NewAttribute("foo"): NewStaticString("value"),
		NewAttribute("bar"): NewStaticString("diff"),
	},
},
```
...is fetched in the response.

It shouldn't be part of the response as bar's value is different from foo's, isn't?

**Comment by mghildiy** [comment]
I have created [PR](https://github.com/grafana/tempo/pull/2411). 
Test engine_test:TestEngine_Execute is failing due to reasons I have mentioned above.
Please have a look.

**Comment by mghildiy** [comment]
To solve the CLA issue, I created a new [PR](https://github.com/grafana/tempo/pull/2474).
