### ISSUE TITLE
I use loki+tempo+grafana as my observability

### ISSUE THREAD

**Issue by andyzheung** [grafana/tempo#2322]
loki use: 2.5.0
tempo use: 2.0.1

I use helm chart to deploy it:
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
dev-loki        loki            8               2023-04-11 09:57:11.788425044 +0800 CST deployed        loki-simple-scalable-1.4.3      2.5.0

NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
tempo     tracing         1               2023-04-10 20:37:54.705969953 +0800 CST deployed        tempo-distributed-1.2.10        2.0.1 

tempo use this microservice mode:
https://github.com/grafana/tempo/tree/v2.0.1/example/helm

but I use tracing function on grafana, alway met 404.
![image](https://user-images.githubusercontent.com/22912347/231047951-189f1233-cbd4-4e7b-acba-c3d943d9e933.png)

I onlly can find error logs in frontend pod
![image](https://user-images.githubusercontent.com/22912347/231048216-1c405bbb-7e58-467a-a382-4ef52b765e7e.png)

Add this to loki gateway deploy:
containers:
      - env:
        - name: JAEGER_ENDPOINT
          value: http://tempo-distributor.tracing:14268/api/traces
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"

**Comment by zalegrala** [comment]
We have a getting started with Helm document that could be helpful.  https://grafana.com/docs/helm-charts/tempo-distributed/next/get-started-helm-charts/

Also, it might be worth turning on `log_received_spans` in the configuration to ensure that traces are arriving on the distributor.  https://grafana.com/docs/tempo/latest/configuration/#distributor
