### ISSUE TITLE
Tempo TraceQL alerting

### ISSUE THREAD

**Issue by Cedric-lefebvre-mgx** [grafana/tempo#2331]
**Describe the bug**
Cannot create any alert for Tempo in Grafana, tempo is not available in the Grafana managed alert dropdown or the other categories of alerts like "Mimir or loki alerts".

**To Reproduce**
- Open grafana
- Try to create an alert 

**Expected behavior**
Able to create an alert

**Environment:**
 - Infrastructure: EKS, running the whole Grafana stack
 - Deployment tool: helm

**Comment by joe-elliott** [comment]
This feature will likely not come for awhile. Your best bet right now is to use the metrics generator component to write metrics to a prometheus compatible endpoint and build alerts from that.

**Comment by Cedric-lefebvre-mgx** [comment]
Ok thanks
