### ISSUE TITLE
Add Logqlv2 example

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#234]
Once LogqlV2 exists add a demo that incorporates the new features.

**Comment by mdisibio** [comment]
There are a couple existing references to this:
* https://grafana.com/blog/2021/02/03/auto-instrumenting-a-java-spring-boot-application-for-traces-and-logs-using-opentelemetry-and-grafana-tempo/
* https://github.com/grafana/tns#logqlv2
