### ISSUE TITLE
Add TNS Demo Example

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#235]
Let's create/document an example using the TNS Demo https://github.com/grafana/tns  This covers multiple features at the same time.

* Exemplars
* Logqlv2 (i.e. logfmt with where clauses)
* Consistent metadata (same custom metadata in logs and span tags)
* Metrics -> Logs
* Logs -> Traces
* Traces -> Logs ?

**Comment by joe-elliott** [comment]
@mdisibio is a genius and will pick a place for this.

**Comment by annanay25** [comment]
Fixed by #580
