### ISSUE TITLE
TraceQL does not support fuzzy mismatches，only supoort =~, not !~ or !~=

### ISSUE THREAD

**Issue by chenshijian73-qq** [grafana/tempo#2351]
**Describe the bug**

TraceQL does not support fuzzy mismatches，only supoort =~, not !~ or !~=

**To Reproduce**
I want to filter out matching fields like ‘xxxhelloxxx’ with keyworld 'hello'
=~ only support get content matching keyword, just like 'name=~"hello"'
but whatever i try to get content not matching keyword, just get expr error. 

**Expected behavior**

TraceQL suport !~ or other method.

**Environment:**
 - Infrastructure:  Kubernetes
 - Deployment tool: helm
 - tempo: 2.0.1
 - grafana：9.0.5

**Additional Context**

**Comment by joe-elliott** [comment]
Thanks for filing an issue. We already have one to support !~ : https://github.com/grafana/tempo/issues/1990

Agree this should be on the shortlist. Likely not too hard to get in.

**Comment by joe-elliott** [comment]
Fixed by #2410
