### ISSUE TITLE
Shutting down tempo always takes at least 30 seconds

### ISSUE THREAD

**Issue by bouk** [grafana/tempo#2353]
**Describe the bug**

Shutting down the tempo service takes 30 seconds. This is annoying when rebooting because it holds up the reboot. I assume it's because [of this code in the distributor](https://github.com/grafana/tempo/blob/469c3337763d7ce75bdcdf74dce0730932753b3e/modules/distributor/receiver/shim.go#L253-L278) that just sleeps for 30 seconds

**To Reproduce**

1. Run tempo
2. SIGTERM tempo
3. It takes 30 seconds

**Expected behavior**

It should shut down when all requests have been properly processed

**Environment:**

I'm running tempo in a systemd service on NixOS, the configuration for it can be found here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/tracing/tempo/default.nix

```
tempo, version 2.0.0 (branch: <release>, revision: 2.0.0)
  build user:
  build date:
  go version:       go1.19.5
  platform:         linux/amd64
```

**Comment by joe-elliott** [comment]
Oof, that's no good. Ideally we'd review the comment and determine if that sleep is even necessary anymore. For an easier win, I'm fine with making that configurable. 30s is a LONG time to wait for requests to finish processing.

**Comment by bouk** [comment]
Still a problem I believe

**Comment by litetex** [comment]
Just stumble upon this and yes this problem is still present in the latest version

The default timeout also conflicts with docker compose (if you deploy it that way) [default stop_grace_period](https://docs.docker.com/compose/compose-file/05-services/#stop_grace_period) of 10s which always causes a ``SIGKILL`` to be performed...
