### ISSUE TITLE
Strange error for ingestion rate limit and context error in ingester when searching Tempo in Grafana

### ISSUE THREAD

**Issue by ErgoPr0xy** [grafana/tempo#2354]
**Describe the bug**
I ran into a RATE_LIMITED error earlier today on my distributor and saw that I need to increase the "max_traces_per_user:" override. 

I did this and it didn't seem to fix anything, I then put it in the overrides.yaml config file and I got a new error:

>caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (50000000 bytes) exceeded while adding 10711 bytes"

As you can see above I added:
 >__ingestion_rate_limit_bytes: 50000000__ 
 
 to the overrides.yaml as well. 
 
This error is very weird, 50000000 bytes exceeded while adding 10711 bytes? Is this looking at a total elsewhere? I tried checking this metric __ingestion_rate_limit_bytes__ but I don't see it in prom. I've bumped it all the way up to 200000000 and I still have the same issue. 

Then every time I run a search in grafana using explorer I get a bunch of lines with the following error in the ingester:
>level=error ts=2023-04-20T09:41:30.011433224Z caller=instance_search.go:297 msg="error searching local block" blockID=d089a36b-f221-4091-9704-f6a4fc3e6dc9 err="searchRaw next failed: join iterator peek failed: [EndTimeUnixNano] context done context canceled"

I did a rollout/restart of the deployment + ingester statefulset too just in case as that has fixed things before (not needed for overrides.yaml)

**To Reproduce**

1. Run tempo-distributed with my configs
2. Not sure how to reproduce unless you can push traces above the rate limits to trigger the behavior? 

**Expected behavior**

It applies the overrides and no longer gives errors
Ingester does not freak out when running a search
It has been stable for a few months now but it seems to destabilize every time we need to make a change to the config

**Environment:**
 - Infrastructure: GKE Kubernetes v1.24.10-gke.2300
 - Deployment tool: helm
 - Chart: tempo-distributed-1.2.0
 - Image: docker.io/grafana/tempo:2.0.0

**Additional Context**

My configs right now

overrides.yaml

```yaml
overrides:
  "*":
    max_traces_per_user: 50000
    ingestion_rate_limit_bytes: 200000000
```

tempo.yaml

```yaml
compactor:
  compaction:
    block_retention: 48h
    compacted_block_retention: 1h
    compaction_cycle: 30s
    compaction_window: 1h
    max_block_bytes: 107374182400
    max_compaction_objects: 6000000
    max_time_per_tenant: 5m
    retention_concurrency: 1
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 20971520
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
distributor:
  log_received_spans:
    enabled: true
    filter_by_status_error: false
    include_all_attributes: false
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  ring:
    kvstore:
      store: memberlist
ingester:
  complete_block_timeout: 168h
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - tempo-gossip-ring
multitenancy_enabled: false
overrides:
  per_tenant_override_config: /conf/overrides.yaml
  max_search_bytes_per_trace: 20000
  metrics_generator_processors: [service-graphs]
querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095
  max_concurrent_queries: 20
  search:
    external_endpoints: []
    external_hedge_requests_at: 8s
    external_hedge_requests_up_to: 2
    prefer_self: 10
    query_timeout: 30s
query_frontend:
  search:
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600
server:
  grpc_server_max_recv_msg_size: 8000000
  grpc_server_max_send_msg_size: 8000000
  http_listen_port: 3100
  log_format: logfmt
  log_level: info
storage:
  trace:
    backend: gcs
    blocklist_poll: 5m
    cache: memcached
    gcs:
      bucket_name: bucket-name
    local:
      path: /var/tempo/traces
    memcached:
      consistent_hash: true
      host: tempo-memcached
      service: memcached-client
      timeout: 500ms
    wal:
      path: /var/tempo/wal
metrics_generator:
  ring:
    kvstore:
      store: memberlist
  processor:
    service_graphs:
      wait: 5s

**Comment by ErgoPr0xy** [comment]
Upgrade to 2.0.1 - same errors in the distributor and ingester

wiped the tempo-distributed install and re-installed

Ingestion rate limits

```yaml
overrides:
  "*":
    max_traces_per_user: 50000
    ingestion_burst_size_bytes: 100000000
    ingestion_rate_limit_bytes: 50000000
```
RATE_LIMITED errors are gone

Still getting search errors in the Tempo ingester:

***level=error ts=2023-04-25T09:38:35.282750637Z caller=instance_search.go:202 msg="error searching local block" blockID=67d28258-f63a-4a07-92d0-5c7f07782610 block_version=vParquet err="error searching block [67d28258-f63a-4a07-92d0-5c7f07782610 0]: searchRaw next failed: join iterator peek failed: [StartTimeUnixNano] context done context canceled"
level=error ts=2023-04-25T09:38:35.282925083Z caller=instance_search.go:314 msg="error searching local block" blockID=0fab9701-43d1-4b27-ba40-8859c5ee0014 err="searchRaw next failed: join iterator peek failed: [StartTimeUnixNano] context done context canceled"
level=error ts=2023-04-25T09:38:44.613084224Z caller=instance_search.go:314 msg="error searching local block" blockID=0fab9701-43d1-4b27-ba40-8859c5ee0014 err="rawToResults next failed: join iterator seekAll failed: [TraceID] context done context canceled"
level=error ts=2023-04-25T09:41:54.158154804Z caller=instance_search.go:314 msg="error searching local block" blockID=0fab9701-43d1-4b27-ba40-8859c5ee0014 err="rawToResults next failed: join iterator seekAll failed: [StartTimeUnixNano] context done context canceled"
level=error ts=2023-04-25T09:42:08.327859319Z caller=instance_search.go:314 msg="error searching local block" blockID=0fab9701-43d1-4b27-ba40-8859c5ee0014 err="searchRaw next failed: join iterator peek failed: [StartTimeUnixNano] context done context canceled"
level=error ts=2023-04-25T09:42:08.328476968Z caller=instance_search.go:202 msg="error searching local block" blockID=67d28258-f63a-4a07-92d0-5c7f07782610 block_version=vParquet err="error searching block [67d28258-f63a-4a07-92d0-5c7f07782610 0]: searchRaw next failed: join iterator peek failed: [StartTimeUnixNano] context done context canceled"***

I'll try reinstalling again with block_version v2

Any other logs I can provide? Has anyone seen this before, any ideas?

**Comment by joe-elliott** [comment]
> I ran into a RATE_LIMITED error earlier today on my distributor and saw that I need to increase the "max_traces_per_user:" override.

Max traces per user is way to prevent memory from spiking in the ingesters in the face of many traces per second. You want to increase `ingestion_burst_size_bytes` and `ingestion_rate_limit_bytes`. We generally prefer to keep these numbers the same.

> Then every time I run a search in grafana using explorer I get a bunch of lines with the following error in the ingester:

Does the search work? When initiating a search the query frontend creates a lot of jobs. Once the conditions of the search are satisfied it cancels all the others which can create a lot of context cancelled logs. I agree this can be improved.

> I'll try reinstalling again with block_version v2

I would recommend staying with `vParquet` unless you very specifically want trace by id lookup only.

**Comment by ErgoPr0xy** [comment]
@joe-elliott thanks for the reply

>Max traces per user is way to prevent memory from spiking in the ingesters in the face of many traces per second. You want to increase ingestion_burst_size_bytes and ingestion_rate_limit_bytes. We generally prefer to keep these numbers the same.

This did not work on our running instance of tempo-distributed unfortunately - at least in our case - I bumped both of those ingestion limits up to 1GB before reinstalling and I was still being rate limited. Any metric I can hunt down to see what limit is causing this in the future? 

>Does the search work? When initiating a search the query frontend creates a lot of jobs. Once the conditions of the search are satisfied it cancels all the others which can create a lot of context cancelled logs. I agree this can be improved.

Thanks for that. Search does work, we had a span that wasn't coming up for other reasons so it threw me off, apologies. 
Seems similar to the memberlist "errors" that popped up a version or two ago. 

>I would recommend staying with vParquet unless you very specifically want trace by id lookup only.

vParquet it is!
