### ISSUE TITLE
Add the ability to search all blocks in the tempo cli

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#236]
**Is your feature request related to a problem? Please describe.**
Need the ability to search all blocks directly for an id

**Describe the solution you'd like**
The tempo-cli should be extended to search all blocks for a specified tenant for a given trace id.  It should show all found instances of the id and include information about the found traces to determine if they are equal.  Perhaps just dump them in their entirety?

**Describe alternatives you've considered**
Nothing!

**Additional context**
This needs to exist to help in debugging efforts.

**Comment by kvrhdn** [comment]
I think this issue is fixed with https://github.com/grafana/tempo/pull/876 right?

**Comment by joe-elliott** [comment]
Ha, yes.

I didn't realize we had an issue for this. Thanks!
