### ISSUE TITLE
Tempo times out returning traces with spans > 100k

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#237]
**Describe the bug**
Tempo struggles to return traces larger than 100k spans.  Querying these traces causes Tempo to timeout.  

**To Reproduce**
Push an enormous trace of over 100k spans.  Just make it 200k for fun.

**Expected behavior**
This trace would be returned.

**Comment by calvernaz** [comment]
Hi,

I'm trying to investigate this issue and reproduce the timeout. I code the following to reproduce:

https://gist.github.com/calvernaz/b96606deb62df63206df682dfe38b489

However I don't see the same timeout, it can be for many reasons (by not be using a remote backend, etc). The image above is an example of a trace with 190+ spans.

<img width="1619" alt="Screenshot 2020-11-13 at 12 07 49" src="https://user-images.githubusercontent.com/1269712/99071014-40b16380-25a9-11eb-9ae4-d9582cd27e1d.png">

I do see however some errors in the background like the one below:

```
tempo-query_1 | {"level":"error","ts":1605221407.3580449,"caller":"zap/logger.go:33","msg":"failed to flush Jaeger spans to server: write udp 127.0.0.1:59929->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\tgithub.com/uber/jaeger-client-go@v2.23.1+incompatible/log/zap/logger.go:33\ngithub.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\tgithub.com/uber/jaeger-client-go@v2.23.1+incompatible/reporter.go:288\ngithub.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\tgithub.com/uber/jaeger-client-go@v2.23.1+incompatible/reporter.go:298"}
```

So I have a couple of questions:

- Do you think I should give more time between pushing the spans and flushing them to the backend? Maybe the querier is hitting in-memory data?
- Testing this in a non-local backend is more likely to reproduce the timeout?

**Comment by joe-elliott** [comment]
My guess has always been that this occurs when recombining the trace.  Out of curiosity how long did it take to return that trace?

Try to push half the trace, wait 60 seconds and then push the second half.  See if it querying it takes significantly longer.  This will cause the ingester to flush the first half from its "active traces" and force it to attempt to recombine the trace.

It's also possible that replication factor two would cause the issue.

**Comment by calvernaz** [comment]
> My guess has always been that this occurs when recombining the trace. Out of curiosity how long did it take to return that trace?

Aroude 12-13 secs.

> Try to push half the trace, wait 60 seconds and then push the second half. See if it querying it takes significantly longer. This will cause the ingester to flush the first half from its "active traces" and force it to attempt to recombine the trace.

Kewl, thanks!

**Comment by calvernaz** [comment]
This one will be interesting to investigate, I'm getting a few errors before I get to experience the timeout:

```
tempo_1                     | level=warn ts=2020-11-16T07:42:51.821048827Z caller=logging.go:71 traceID=7a260db957e6ea17 msg="GET /api/traces/00000000000000007cb76f716faaf4cd (500) 2.947317854s Response: \"error querying ingesters in Querier.FindTraceByID: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (8557722 vs. 4194304)\\n\" ws: false; Accept-Encoding: gzip; User-Agent: Go-http-client/1.1; "
tempo-query_1               | {"level":"error","ts":1605512571.8220606,"caller":"app/http_handler.go:435","msg":"HTTP handler, Internal Server Error","error":"grpc stream error: rpc error: code = Unknown desc = failed to unmarshal trace json, err: invalid character 'e' looking for beginning of value. Tempo response body: error querying ingesters in Querier.FindTraceByID: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (8557722 vs. 4194304)\n","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).handleError\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:435\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getTrace\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:380\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\ngithub.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\tgithub.com/opentracing-contrib/go-stdlib@v0.0.0-20190519235532-cf7a6c988dc9/nethttp/server.go:140\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.4/mux.go:210\ngithub.com/jaegertracing/jaeger/cmd/query/app.additionalHeadersHandler.func1\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/additional_headers_handler.go:28\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\ngithub.com/gorilla/handlers.CompressHandlerLevel.func1\n\tgithub.com/gorilla/handlers@v1.4.2/compress.go:148\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2843\nnet/http.(*conn).serve\n\tnet/http/server.go:1925"}
```

I have a follow-up question regarding the trace combining process; the following code seems to check the ingesters first for a particular trace id (in parallel) and then checks in the backend store if it's not found in the ingesters. Is it possible that part of the trace has been flushed to the backend store, and the other part still in the ingesters? From the code, it's either in the ingesters or in the backend.


```
// get responses from all ingesters in parallel
responses, err := q.forGivenIngesters(ctx, replicationSet, func(client tempopb.QuerierClient) (interface{}, error) {
	return client.FindTraceByID(opentracing.ContextWithSpan(ctx, span), req)
})
if err != nil {
	return nil, errors.Wrap(err, "error querying ingesters in Querier.FindTraceByID")
}

var completeTrace *tempopb.Trace
for _, r := range responses {
	trace := r.response.(*tempopb.TraceByIDResponse).Trace
	if trace != nil {
		completeTrace = tempo_util.CombineTraceProtos(completeTrace, trace)
	}
}

// if the ingester didn't have it check the store.
if completeTrace == nil {
	foundBytes, metrics, err := q.store.Find(opentracing.ContextWithSpan(ctx, span), userID, req.TraceID)
	if err != nil {
		return nil, errors.Wrap(err, "error querying store in Querier.FindTraceByID")
	}
...
```

**Comment by joe-elliott** [comment]
We have seen those grpc error logs as well occasionally, but have not had time to track them down.  Thank you for digging into this.

Regarding your second question:  yes.  Currently the querier will stop if it finds the trace in the ingesters, but agree it should move forward and search the backend as well.  This might be a bit tricky to do before we get a query-frontend because for high volume installations because it will spike query times significantly.  

Made #344 to document.

**Comment by joe-elliott** [comment]
I've done some some more experimentation on our side and have found:

- Upping the grpc send/recv sizes _does_ allow for larger trace returns (thx @calvernaz):
Default is 4MB.  The below is 15MB.
```
server:
    grpc_server_max_recv_msg_size: 1.572864e+07
    grpc_server_max_send_msg_size: 1.572864e+07
```
- After upping this limit the next barrier appears to be in the translation from otlp => jaeger (see below snippet).  In my investigation I saved and recalled a ~200k span trace.  The querier was able to return it in 11 seconds, but it took a full 70 seconds to finish this method.

https://github.com/grafana/tempo/blob/master/cmd/tempo-query/tempo/plugin.go#L72-L95

**Comment by joe-elliott** [comment]
Added tracing to the GRPC plugin and found the following.  Will submit a PR shortly with my changes.

So this trace is showing
- 7 seconds to pull the trace from the ingester
- 19 seconds to pull from the querier
- and then otlp to Jaeger translation didn't start til 68 seconds

There's a lot of missing time here and I think that we're losing it to json marshalling/unmarshalling.  I want to leave the querier HTTP endpoint, but we need a GRPC one for the the tempo-query plugin to use.

![image](https://user-images.githubusercontent.com/2272392/99731475-f1c56b80-2a8b-11eb-9d80-3c5734af9cb7.png)

**Comment by calvernaz** [comment]
Good job @joe-elliott! Thanks

**Comment by joe-elliott** [comment]
We have seen multiple hundreds of thousands of traces returned successfully internallly.   We have added proto as well between frontend and queriers.   The last thing that can be done is #382.  Closing.

**Comment by 96Jerry** [comment]
Have you guys ever encountered out-of-memory issues when retrieving large traces with many spans?
