### ISSUE TITLE
[tempo-query] Remove `tenant_header_key` config header option

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#2381]
It's highly misleading. While you can configure the plugin to use different headers to pass the tenant ID, Jaeger Query will only [propagate the bearer token](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/grpc/shared/grpc_client.go#L44) to the storage plugin. So, the only real option is using the default `bearer.token`. We should remove that config option.

**Comment by neverbeenthisweeb** [comment]
Hi @mapno , I am interested to work on this issue.

**Comment by kousikmitra** [comment]
Hi @neverbeenthisweeb apologies, I did not see your comment before, I had already made the change so raised the PR.

**Comment by neverbeenthisweeb** [comment]
@kousikmitra no worries

**Comment by pavolloffay** [comment]
> It's highly misleading. While you can configure the plugin to use different headers to pass the tenant ID, Jaeger Query will only [propagate the bearer token](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/grpc/shared/grpc_client.go#L44) to the storage plugin

This is not true, the tenant header is configurable. We even the config in the tempo-operator. 

```console
docker run --rm -it jaegertracing/all-in-one:1.48.0 --help | grep multi-tenancy                                                                                   ploffay@fedora
      --multi-tenancy.enabled                                     Enable tenancy header when receiving or querying
      --multi-tenancy.header string                               HTTP header carrying tenant (default "x-tenant")
      --multi-tenancy.tenants string                              comma-separated list of allowed values for --multi-tenancy.header header.  (If not supplied, tenants are not restricted)

```
