### ISSUE TITLE
Update mixin dashboards to work with the single binary

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#242]
The docker-compose examples currently import the mixin dashboards, but they don't work for the single binary.  Fix this and update the docker-compose readme to encourage people to checkout the dashboards.

**Comment by annanay25** [comment]
Cortex mixin has a boolean that generates different selectors for single-binary & k8s deployments. 

https://github.com/grafana/cortex-jsonnet/blob/b3d8a89e6e81a30cb7a8388eb759382cbb8cc2f2/cortex-mixin/config.libsonnet#L24

Need something similar.
