### ISSUE TITLE
The rps of the service graph node are incorrect

### ISSUE THREAD

**Issue by gyz2009** [grafana/tempo#2445]
**Describe the bug**

The rps of the service graph node are incorrect
<img width="1390" alt="image" src="https://github.com/grafana/tempo/assets/30786213/fab0a13d-5d43-489b-bed7-99f8413aa474">

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 kubernetes
 - Deployment tool: [e.g., helm, jsonnet]
 helm

**Additional Context**

tempo version v2.0.1
grafana version v9.5.1

**Comment by joe-elliott** [comment]
What value do you expect to be here? And why?

Can you check the `traces_service_graph` metrics to see if they are consistent with your expectations?

**Comment by gyz2009** [comment]
Whether rps should be greater than or equal to the sum of the TOP 5 rates in the Service Graph Table？

**Comment by saikatd** [comment]
@joe-elliott we have been facing similar issues as well. 

- The prometheus datasource is reporting correct nos - rps, latency buckets
- the service graph associated table (table above service graph) is also reporting correct nos - rate, p90, error_rates, etc
- but, the service graph level rps and latency nos seem off. Especially rps which is way off.

Also, I was trying to find documentation around how service graph querying works in tempo.

- are the requests made towards tempo directly ? or,
- do we use prometheus to craft the service graph view ?

We are on the same versions as @gyz2009 mentioned

**Comment by joe-elliott** [comment]
> are the requests made towards tempo directly ? or do we use prometheus to craft the service graph view ?

The service graph and table are both created by querying prometheus for metrics.

Can you review metrics on the distributor and generator to see if spans are being dropped? I'd also look at `tempo_metrics_generator_processor_service_graphs_expired_edges` to see if edges are being expired before they are paired.

**Comment by satamas** [comment]
For those who are facing the same problem, it was fixed by the following commit: https://github.com/grafana/grafana/commit/43df362aedd58c4578e85ac81d3408e389c74c41.
