### ISSUE TITLE
[DOC] Tail-based sampling not working

### ISSUE THREAD

**Issue by lovesharepc** [grafana/tempo#2455]
I reference this doc https://grafana.com/docs/tempo/latest/configuration/grafana-agent/tail-based-sampling/
1. doc is old
current config need like this
```
      tail_sampling:
        decision_wait: 10s
        num_traces: 100
        expected_new_traces_per_sec: 10
        policies:
          [
            {
              name: errors-policy,
              type: status_code,
              status_code: { status_codes: [ERROR] },
            }
          ]
```

2. don't work 
I use otel/opentelemetry-collector-contrib:0.76.1
with same tail_sampling config
sampling can work 
use grafana agent is not 
grafana agent version 
```
root@grafana-agent:/# grafana-agent --version 
agent, version main-d9462f2 (branch: main, revision: d9462f27)
  build user:       root@buildkitsandbox
  build date:       2023-05-05T22:32:14Z
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,promtail_journal_enabled
```

**Comment by joe-elliott** [comment]
It will be very difficult for us to keep up with Agent docs going forward. I think we should mention the Agent in Tempo docs as a first class telemetry pipeline to be used with Grafana Cloud Traces/OSS Tempo and then link to their docs.

wdyt @knylander-grafana ?

**Comment by lovesharepc** [comment]
thank for reply 
actually, I hope is grafana agent can update include's opentelemetry collector to keep feature work
doc can just link to official doc

**Comment by knylander-grafana** [comment]
Doc PR - https://github.com/grafana/tempo/pull/3167
