### ISSUE TITLE
[DOC] TraceQL: documentation to filter traces where a span attribute exists

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2465]
**Is your feature request related to a problem? Please describe.**

When troubleshooting my application, I would like to search for traces having a specific attribute being defined.
For example, for the operation `getProduct`, I want to find traces containing SQL spans, traces that contain a span with an attribute `db.type`. 

I want to write this query without having to know what are the possible values for `db.type`, just saying that the attribute `db.type` is defined.

When using ElasticSearch & Kibana, it's the syntax `my_field: *` where `*` means "exist in any form".
I would like the [TraceQL docs](https://grafana.com/docs/tempo/latest/traceql/) to document how I can do the equivalent with Tempo.

cc @knylander-grafana

**Comment by faustodavid** [comment]
Hi @cyrille-leclerc, you can specify in your TraceQL that an attribute need to have value.

The following query will return all spans that have the attribute `db.type` defined:
```
{span.db.type!=""}
```

**Comment by joe-elliott** [comment]
This is a great tip but not entirely true. This will return any spans that have a string attribute named `span.db.type` that has a value besides "".
```
{span.db.type!=""}
```
Due to the way we assert types there is no way to see if an attribute of any type exists. We have an issue here:

https://github.com/grafana/tempo/issues/2188

I favor 
```
{ span.db.type != nil }
```
but others have expressed they like:
```
{ exists(span.db.type) }
```

**Comment by knylander-grafana** [comment]
@joe-elliott From what you said above, it sounds like the solution to be able to complete what Cyrille wants to do depends upon #2188. I'll add a note to your issue in progress that #2465 creates documentation for #2188.
