### ISSUE TITLE
[TraceQL] Enhance Autocomplete to Differentiate Resource and Span Attributes

### ISSUE THREAD

**Issue by faustodavid** [grafana/tempo#2471]
**Is your feature request related to a problem? Please describe.**
When using TraceQL, I noticed that when I write `{resource.}`, I receive suggestions for all possible attributes from both the resource and span scope. This can be overwhelming when I only want to see the attributes specific to either the resource or the span.
<img width="376" alt="image" src="https://github.com/grafana/tempo/assets/2423149/1b32c477-a3ed-428d-8c3c-233362ae7741">

**Describe the solution you'd like**
I would like to propose that typing `.` returns all possible attributes, typing `resource.` only displays the resource attributes, and typing `span.` only displays the span attributes. This would enhance the usability and make it easier to navigate and select the desired attributes based on the scope we are working with.

**Comment by joe-elliott** [comment]
Great call out! We added support here: https://github.com/grafana/tempo/pull/2282

and there's an issue here to add support in Grafana: https://github.com/grafana/grafana/issues/67011

Looks like there's a PR open!

**Comment by joe-elliott** [comment]
I'm normally terrible about closing issues b/c I want there to be discussion even if it's not something we agree with or have time to work on, but this one seems pretty covered.

Thanks @faustodavid!
