### ISSUE TITLE
[DOC] Missing "ListObjects" permission in the S3 configuration doc

### ISSUE THREAD

**Issue by chrisduong** [grafana/tempo#2489]
**Describe the bug**

When I deployed the Tempo with this S3 configuration doc https://grafana.com/docs/tempo/latest/configuration/s3/, I faced this error

```json
{"caller": "main.go:105", "err": "failed to init module services error initialising module: usage-report: failed to initialize usage report: unexpected error from ListObjects on tempo-traces-foo: Access Denied","level":"error","msg":"error running Tempo","ts":"2023-05-18T10:09:09.908963824Z"}
```

**Expected behavior**

The S3 configuration doc should add **s3:ListObjects** action into the policy. 

**Environment:**
 - Infrastructure: K8s
 - Deployment tool: Helm
 - Tempo version `2.1.1`

**Comment by joe-elliott** [comment]
cc @knylander-grafana

**Comment by absolutemikex** [comment]
I am running into this now - however, I added the policy and I am using IRSA. Is there anything else I can check?

`level=info ts=2023-05-19T18:22:40.23471841Z caller=main.go:215 msg="initialising OpenTracing tracer"
level=info ts=2023-05-19T18:22:40.243715669Z caller=main.go:102 msg="Starting Tempo" version="(version=2.1.1, branch=HEAD, revision=4157d7620)"
level=error ts=2023-05-19T18:22:40.396802855Z caller=main.go:105 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on BUCKET: Access Denied"`

**Comment by absolutemikex** [comment]
I am dumb - disregard. I remove my SA config accidentally from values. Appreciate all your hard work.

**Comment by Eve832** [comment]
Hi @knylander-grafana , can you please update the status of this ticket in your view in https://github.com/orgs/grafana/projects/69/

**Comment by z0rc** [comment]
@datsabk if you updated to 2.2.2, most likely it's #2888.

**Comment by datsabk** [comment]
@z0rc Saved my day man! I had started to doubt myself ! 

Looks like a regression due to AWS SDK version upgrade. There's nothing much happening in the Tempo Code really.

**Comment by ekristen** [comment]
This is still an issue, #2888 doesn't seem to fix anything.

**Comment by knylander-grafana** [comment]
I'm getting ready to update the S3 config docs to address some of this content. Here are some related S3 issues we'll take into consideration for updating the doc: 

* https://github.com/grafana/tempo/issues/2895
* https://github.com/grafana/tempo/issues/2888
* https://github.com/grafana/tempo/issues/2743

To update the docs, we're going to: 
* Review the S3 configuration and verify it works 
* Add ListObjects
* Add information about authentication
* Add troubleshooting for error failed to init module services error initializing module

**Comment by bouk** [comment]
`s3:ListObjects` is not a valid permission, `s3:ListBucket` is the one needed for listing objects in a bucket

**Comment by sunrabbit123** [comment]
@joe-elliott 

> `s3:ListObjects` is not a valid permission, `s3:ListBucket` is the one needed for listing objects in a bucket

This issue is not closed, and we ask that you reopen it.

In fact, `ListObjects` does not exist.

![image](https://github.com/grafana/tempo/assets/64676070/d1158bdb-57eb-4f4d-8f45-47c20aacf52a)

**Comment by joe-elliott** [comment]
Ah, thank you :pray:. 

I'm going to leave this issue closed since it specifically discusses adding "ListObjects" to the docs. If you are having issues getting auth configured to work with S3 please update to 2.3.1 (we've made some fixes) and open an issue if things are still not working.

**Comment by stefanandres** [comment]
For what it's worth, I encountered the same error, but it turns out my `aws_iam_policy_document` was wrong.

The actual error message was from a pod with the same kubernetes serviceAccount:
```
bash-4.2# aws s3 ls s3://$bucket

An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```
