### ISSUE TITLE
tempo_receiver_accepted_spans receiver label missing in 2.1.1

### ISSUE THREAD

**Issue by mike-brown-angi** [grafana/tempo#2491]
**Describe the bug**
When we upgraded from Tempo-distributed 2.0.1 to 2.1.1 (helm charts 1.2.7 to 1.4.1) the receiver label on the tempo_receiver_accepted_spans metric was removed.

**To Reproduce**
1. Run this query `increase(tempo_receiver_accepted_spans{}[5m])`
2. You will see that it no longer includes the receiver label

**Expected behavior**
Expected the metric to contain that label.

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm chart by way of flux

**Additional Context**
<img width="812" alt="before-upgrade" src="https://github.com/grafana/tempo/assets/85303670/cd13a69d-bf63-463f-a442-6a99a2ee58c7">
<img width="839" alt="after-upgrade" src="https://github.com/grafana/tempo/assets/85303670/9007aba0-5738-4515-a27c-576f1dc6a9a9">

**Comment by joe-elliott** [comment]
I'm not sure we have much control over that metric. It is published by the OTEL receivers.

**Comment by zalegrala** [comment]
Maybe this label got renamed to `transport`, or did transport exist before also?

**Comment by mike-brown-angi** [comment]
yeah, transport exists in 0.72.0 along with receiver, when tempo picked up 0.74.0 the receiver label went away for some reason.  I don't see it mentioned in the otel changelog, so I'm not sure if it actually went away in otel.   Will have to experiment with that version on it's own to see if that's actually the case or something has been missed in translation.
