### ISSUE TITLE
Documentation: in "2022-04 TraceQL Concepts.md", some example are contradicting OTel Semantic Conventions

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2496]
**Describe the documentation bug**

[tempo/docs/design-proposals/2022-04 TraceQL Concepts.md](https://github.com/grafana/tempo/blob/v2.1.1/docs/design-proposals/2022-04%20TraceQL%20Concepts.md) uses examples that are contradicting with the OTel Semantic Conventions, risking to create confusion for users.

Some contradiction in the ["Scoped attribute fields"](https://github.com/grafana/tempo/blob/v2.1.1/docs/design-proposals/2022-04%20TraceQL%20Concepts.md#scoped-attribute-fields) section, the examples refers to 
* `{ resource.namespace = "prod" }` rather than `resource.deployment.environment`  or `resource.service.namespace` or [`resource.k8s.namespace.name`](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/k8s/#namespace).
* `{ span.http.status = 200 }` rather than [`span.http.response.status_code`](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/)

**Comment by cyrille-leclerc** [comment]
@joe-elliott  @knylander-grafana is this inconsistency deserving a fix? I would be happy to submit a PR.

**Comment by joe-elliott** [comment]
This is not a priority for me, but I think it would be an improvement. If you submit the PR we will merge.
