### ISSUE TITLE
Metrics Generator discarding all spans

### ISSUE THREAD

**Issue by EStork09** [grafana/tempo#2507]
**Describe the bug**

Metrics Generator is discarding all spans
**To Reproduce**
1. Start Tempo with otel sidecars
2. Perform Operations and collect spans to forward to tempo
3. look at metrics generator to check span status

**Expected behavior**

Spans should be forwarded on to prometheus remote write endpoint

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Additional Context**

![image](https://github.com/grafana/tempo/assets/23393490/57c1cefa-eba0-4f83-8ffc-047cccb49f43)
![image](https://github.com/grafana/tempo/assets/23393490/757a136b-4880-42ba-ba4e-c6a58c512772)

This could easily not be a bug, but I cannot find out why the spans are instantly being discarded. There is no log to display the reason. All the spans and traces are coming from the other LGTM solutions (tempo, loki, mimir).

```
tempo.yaml: |

    compactor:
      compaction:
        block_retention: 168h
        compacted_block_retention: 1h
        compaction_cycle: 30s
        compaction_window: 1h
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
      ring:
        kvstore:
          store: memberlist
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
        tokens_file_path: /var/tempo/tokens.json
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
      - tempo-distributed-gossip-ring
    metrics_generator:
      processor:
        service_graphs:
          dimensions: []
          histogram_buckets:
          - 0.1
          - 0.2
          - 0.4
          - 0.8
          - 1.6
          - 3.2
          - 6.4
          - 12.8
          max_items: 10000
          wait: 300s
          workers: 10
        span_metrics:
          dimensions: []
          histogram_buckets:
          - 0.002
          - 0.004
          - 0.008
          - 0.016
          - 0.032
          - 0.064
          - 0.128
          - 0.256
          - 0.512
          - 1.02
          - 2.05
          - 4.1
      registry:
        collection_interval: 15s
        external_labels: {}
        stale_duration: 15m
      ring:
        kvstore:
          store: memberlist
      storage:
        path: /var/tempo/wal
        remote_write:
        - url: http://mimir-distributed-gateway.mimir/api/v1/push
        remote_write_flush_deadline: 1m
    multitenancy_enabled: false
    overrides:
      max_traces_per_user: 100000
      metrics_generator_processors:
      - service-graphs
      - span-metrics
      per_tenant_override_config: /conf/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: tempo-distributed-query-frontend-discovery:9095
      max_concurrent_queries: 20
      search:
        external_endpoints: []
        external_hedge_requests_at: 8s
        external_hedge_requests_up_to: 2
        prefer_self: 10
        query_timeout: 30s
      trace_by_id:
        query_timeout: 10s
    query_frontend:
      max_retries: 2
      search:
        concurrent_jobs: 1000
        target_bytes_per_job: 104857600
      tolerate_failed_blocks: 0
      trace_by_id:
        hedge_requests_at: 2s
        hedge_requests_up_to: 2
        query_shards: 50
    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      log_format: logfmt
      log_level: debug
    storage:
      trace:
        backend: s3
        block:
          version: vParquet
        blocklist_poll: 5m
        cache: memcached
        local:
          path: /var/tempo/traces
        memcached:
          consistent_hash: true
          host: tempo-distributed-memcached
          service: memcached-client
          timeout: 500ms
        s3:
          bucket: traces
          endpoint: minio.minio.svc.cluster.local
          insecure_skip_verify: true
          region: minio
        wal:
          path: /var/tempo/wal
    usage_report:
      reporting_enabled: true
```

**Comment by EStork09** [comment]
I found the problem, I am using tail sampling, which was causing all my spans to be after [30s](https://github.com/grafana/tempo/blob/main/docs/sources/tempo/configuration/_index.md?plain=1#L355).
But that also has discovered that there is a typo in the documentation.

I think this can be closed but is it worth adding a log for debug to display the reason for discarding the spans?

**Comment by joe-elliott** [comment]
Yup. For anyone else reading check @EStork09 link for a config option that allows you to adjust the slack window. 

> I think this can be closed but is it worth adding a log for debug to display the reason for discarding the spans?

We metric dropped spans due to outside ingestion slack here: `tempo_metrics_generator_spans_discarded_total`. It would be tough to add a log line for discarded spans unless it was at the debug level b/c it may be happening extremely frequently.

**Comment by EStork09** [comment]
Yeah, I think a debug or, and I don't think it is an option here, but a trace level if this was to be logged. Is the only reason for the metrics generator to drop spans is because of the ingestion time range slack? If that is the only reason then the metric is fine and logs would be fairly redundant and just noisy. If there is another reason for them to get dropped we could arguably add a label to the metric to track the reasons why?

**Comment by EStork09** [comment]
Ah, I am just dumb, thank you for your help!

**Comment by gayatrigunnala** [comment]
@joe-elliott and @EStork09 , I am facing the same issue; Not sure of the cause though;
Is there a config option to increase metrics_ingestion_slack
Please let me know.
tempo_metrics_generator_spans_discarded_total{reason="outside_metrics_ingestion_slack",tenant="single-tenant"} 8
tempo_metrics_generator_spans_received_total{tenant="single-tenant"} 8

Thanks in Advance

**Comment by mapno** [comment]
Hi @gayatrigunnala. `metrics_generator.metrics_ingestion_time_range_slack` is what you're looking for.

**Comment by gayatrigunnala** [comment]
Thank you
