### ISSUE TITLE
Spans may appear partially in `/api/search/` results

### ISSUE THREAD

**Issue by rayrapetyan** [grafana/tempo#2513]
**Describe the bug**
When searching traces using `/api/search`, results may contain incomplete values.

**To Reproduce**
1. Start Tempo (grafana/tempo:latest)
2. Perform operation:
```
curl -G -s "http://localhost:3200/api/search?tags=%20service.name%3D%22foo%22&limit=20&start=1685390400&end=1685390410" | jq
{
  "traces": [
    {
      "traceID": "c5c72587e994f2bc83fcf4c6c37412aa",
      "startTimeUnixNano": "1685390400012954766",
      "durationMs": 1806938
    },
    {
      "traceID": "f75b842f874630bbe5387702153f2eda",
      "rootServiceName": "foo",
      "rootTraceName": "foo.bar",
      "startTimeUnixNano": "1685390400007993342",
      "durationMs": 330
    }
  ],
  "metrics": {
    "inspectedBytes": "3145728",
    "totalBlocks": 1,
    "completedJobs": 1,
    "totalJobs": 1,
    "totalBlockBytes": "2426845"
  }
}
```
Note first trace has no `rootServiceName`/`rootTraceName` attributes. DurationMs (1806938) is also about twice less than it should be.

However, `/api/traces/c5c72587e994f2bc83fcf4c6c37412aa` returns all spans properly.

**Expected behavior**
First trace should contain all attributes and reflect a real Duration (1+ hour).

**Environment:**
 - Infrastructure: local docker
 - Storage: local
 
**Config:**
```
server:
  http_listen_port: 3200

# Distributors receive spans and forward them to the appropriate ingesters.
distributor:
  receivers:
    otlp:
      protocols:
        grpc:

ingester:
  trace_idle_period: 10s               # amount of time a trace must be idle before flushing it to the wal. (default: 10s)
  max_block_bytes: 5_000_000           # maximum size of a block before cutting it (default: 524288000 = 500MB)
  max_block_duration: 3m               # maximum length of time before cutting a block (default: 30m)

compactor:
  compaction:
    compaction_window: 1h              # Optional. Blocks in this time window will be compacted together. Default is 1h.
    max_block_bytes: 1_000_000_000     # Optional. Maximum size of a compacted block in bytes.  Default is 100 GB.
    block_retention: 336h              # Optional. Duration to keep blocks.  Default is 14 days (336h).
    compacted_block_retention: 1h      # Optional. Duration to keep blocks that have been compacted elsewhere. Default is 1h.

storage:
  trace:
    backend: local                     # The storage backend to use. Should be one of "gcs", "s3", "azure" or "local" (only supported in the monolithic mode)
    block:
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives (default = 0.01)
      v2_index_downsample_bytes: 1000  # number of bytes per index record (default = 1MiB)
      v2_encoding: zstd                # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2 (default: zstd)
    wal:
      path: /tmp/tempo/wal             # where to store the head blocks while they are being appended to
      v2_encoding: snappy              # wal encoding/compression. options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100                 # total number of workers pulling jobs from the queue (default: 400)
      queue_depth: 10000               # length of job queue. imporatant for querier as it queues a job for every block it has to search (default: 20000)

query_frontend:
  search:
    max_duration: 336h                # The maximum allowed time range for a search. (default: 168h)
```

**Comment by joe-elliott** [comment]
It's impossible to comment on exactly what happened to a single trace. With access to the trace itself, your backend storage, logs/metrics of Tempo and logs/metrics/configuration of the telemetry pipeline at best I could make some guesses.

One thing you can do is to query the blocks directly and see how many pieces this trace exists in in your backend:

```
./tempo-cli query blocks <trace id> <tenant id> --backend=s3|gcs --bucket=<bucket name> --org-id=<tenant>
```

**Comment by rayrapetyan** [comment]
How to specify a local storage folder when calling a `tempo-cli`?
Also, as I've mentioned above, `/api/traces/c5c72587e994f2bc83fcf4c6c37412aa` returns all spans, and duration of the root span is valid, so how `tempo-cli` may help? For sure it will return all data, because otherwise where else `/api/trace` gets complete data? Thanks.

**Comment by joe-elliott** [comment]
> How to specify a local storage folder when calling a tempo-cli?

I think you do `--backend=local --bucket=/path/to/backend`

> so how tempo-cli may help?

it will just show us how widely scattered this trace is throughout your blocks. Right now your traceql query is finding one fragment of it and returning. It may be interesting to see what those fragments look like.

**Comment by rayrapetyan** [comment]
Thanks for the `--bucket` clue!
So it returns a huge response (18MB in total) starting with:
```
total blocks:  278
........0.............................................................................................100...................................................................................................200..............................................................................
ab52fbcb-cb79-48f1-84f0-7479b4b05b51 :
```
Then goes `{"batches":` data equal to what `/api/traces/c5c72587e994f2bc83fcf4c6c37412aa` returns.

**Comment by joe-elliott** [comment]
> So it returns a huge response (18MB in total) starting with:

Every line that is:
```
<guid>:
```
is showing a different fragment of your trace in a different block. How many of these fragments exist? What is the total trace duration? Perhaps this is a long running trace that exists across a large number of blocks. In that case the behavior, while not ideal, is expected.

**Comment by rayrapetyan** [comment]
There are only two guids:
```
ab52fbcb-cb79-48f1-84f0-7479b4b05b51 :
```
and
```
498896cc-a7a5-48c5-a20b-f9f271e58074 :
```
Total trace duration is 1h and 6 minutes, 9526 spans.

I'm still not getting how `/api/search` works. I'm specifying a time range in a filter, how many blocks will it try to scan? Which config option controls that?

**Comment by joe-elliott** [comment]
> I'm still not getting how /api/search works. I'm specifying a time range in a filter, how many blocks will it try to scan? Which config option controls that?

It will scan all blocks that overlap with the time range until it finds enough results to reach your limit. When traceql is searching the blocks to match your criteria it is only able to use local information to determine if the trace should be returned. It is not able to go find the same trace id in a different block and evaluate the results on the whole. It only evaluates this fragment right here.

For "normal" traces this generally works fine without issues. For long running traces split across multiple blocks it's possible to write a query that matches one of the fragments but not others. In this case we still return the results but it can create scenarios like the one you are describing.

**Comment by rayrapetyan** [comment]
>until it finds enough results to reach your limit
Could you clarify what's that limit? Can it be increased?

**Comment by rayrapetyan** [comment]
Seems `limit` is about number of traces in resulting array, mine has just 2 so it's unrelated to my issue.
Meanwhile, something has changed on the back-end, duration is now almost valid (still less than 1h), and it's still missing rootServiceName/rootTraceName:

```
curl -G -s "http://localhost:3200/api/search?tags=%20service.name%3D%foo%22&limit=2&start=1685390400&end=1685390410" | jq
```
```
{
  "traces": [
    {
      "traceID": "c5c72587e994f2bc83fcf4c6c37412aa",
      "startTimeUnixNano": "1685390400012954766",
      "durationMs": 3494479
    },
    {
      "traceID": "f75b842f874630bbe5387702153f2eda",
      "rootServiceName": "foo",
      "rootTraceName": "foo.bar",
      "startTimeUnixNano": "1685390400007993342",
      "durationMs": 330
    }
  ],
  "metrics": {
    "inspectedBytes": "3145728",
    "totalBlocks": 1,
    "completedJobs": 1,
    "totalJobs": 1,
    "totalBlockBytes": "3996954"
  }
}
```

I definitely see a bug in a /api/search implementation but have no time to look into it unfortunately...
