### ISSUE TITLE
Tempo leaves tenant indexes on tenants with no blocks

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2520]
If a tenant's blocks are completely removed Tempo will still leave the `index.json.gz` in the root of the tenant's "folder". This tenant index correctly indicates there are no blocks for this tenant, but incurs a cost to Tempo.

During the polling phase Tempo components first list all tenants and then pull all tenant index's for all tenants. In a highly multitenant environment these "empty" tenant indexes can significantly impact Tempo.

Remove `index.json.gz` if there are no blocks.

**Comment by zalegrala** [comment]
I've got a PR up to help with this, but I think something else we need to handle is that the tenant list would still include the empty tenants, or those without an index or any blocks.  So I think this would mean we still make the call, which we probably don't want to make.  I think if we just delete the tenant directory this would be okay, but then I think we have a race with the ingesters.  Need to think some on that.

**Comment by zalegrala** [comment]
The PR now works to clean up old tenants, but there is one remaining issue.  Tenants that get cleaned up still show up in the metrics because the tenant list no longer contains them, so we don't learn that we should delete them from the registry.  A restart helps, but I'd like to find a better way.

**Comment by joe-elliott** [comment]
> Tenants that get cleaned up still show up in the metrics because the tenant list no longer contains them, so we don't learn that we should delete them from the registry. A restart helps, but I'd like to find a better way.

This is fine. This won't happen that often and publishing a 0 metric for a few days before the pods are rolled is no big deal. It's better than some complex logic we have to maintain that deregisters the metrics.
