### ISSUE TITLE
[DOC] Improve "Pushing spans with http" doc

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2522]
This document is quite out of date and could be improved:

https://grafana.com/docs/tempo/latest/api_docs/pushing-spans-with-http/

Some suggestions:
- Remove the "starting Tempo" section and link to a docker-compose example on how to quick start
- Switch the example from zipkin to a OTEL http. This didn't exist when this doc was created
- Consider updating the example to show more than just retrieving the trace by id
- Replace the screenshots with Grafana instead of the Jaeger UI

**Comment by tarunsamanta2k20** [comment]
Let me check once

**Comment by knylander-grafana** [comment]
Related to https://github.com/grafana/tempo/issues/1695

**Comment by knylander-grafana** [comment]
Updates are in this PR: https://github.com/grafana/tempo/pull/2937

**Comment by knylander-grafana** [comment]
Backport content to live docs: https://github.com/grafana/tempo/pull/2954
