### ISSUE TITLE
Tempo Trace Alerting

### ISSUE THREAD

**Issue by OSRSBlue** [grafana/tempo#2553]
Hey all,

I was curious if tempo supported alerting on traces or trace span events. I couldn’t find anything online and was curious on how others alert on span events.

Currently, I am thinking of logging the event to Loki with the trace and span identifier to be able to correlate the error log to the trace, but wasn’t sure if this was weird. This approach would allow me to write alerts against my Loki logs, which would solve my problem, but feels like duplicate work since similar data is being logged inside my tempo trace, but there is no way to alert on it.

I’m curious to hear others thoughts on how they handle alerting and the approach I am thinking of above. Let me know if you have feedback or tips on your alerting strategies on grafana traces.

**Comment by mapno** [comment]
Hi @OSRSBlue! Unfortunately, the feature you describe is not supported in Tempo.

> Currently, I am thinking of logging the event to Loki with the trace and span identifier to be able to correlate the error log to the trace, but wasn’t sure if this was weird.

This is a very common pattern. Grafana supports this workflow with [derived fields](https://grafana.com/docs/grafana/latest/datasources/loki/#configure-derived-fields).

Thanks for starting the discussion!
