### ISSUE TITLE
Compaction Errors & High network usage by Tempo

### ISSUE THREAD

**Issue by kj-mintoak** [grafana/tempo#2560]
**Describe the bug**
We are continuously getting errors in tempo in production for the last 20+ days which says :

caller=compactor.go:265 msg="unable to mark block compacted" blockID=xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx tenantID=single-tenant err="error copying obj meta to compacted obj meta: The specified key does not exist."

This is coupled with a high network usage by the tempo pods going up to 20MB+

**To Reproduce**
Not able to reproduce in lower environments

**Expected behavior**
No compaction errors & low network IO of around 500kb at peaks

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**

Getting these 2 errors repeatedly: 

level=error ts=2023-06-15T02:59:56.068090577Z caller=compactor.go:265 msg="unable to mark block compacted" blockID=xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx tenantID=single-tenant err="error copying obj meta to compacted obj meta: The specified key does not exist."

level=error ts=2023-06-15T02:55:20.744562923Z caller=compactor.go:147 msg="error during compaction cycle" err="unable to mark 3 blocks compacted"

**Comment by kj-mintoak** [comment]
Hi, thanks for the direction. We are running Tempo in a single binary mode with 3 replicas.  

> Check all compactor logs for the block ID xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and see if there were two compactors working on it at the same time. There should only every be 1 compactor working on a block at a time. This is kind of related to the previous check about the ring status, but another way to check for cluster inconsistency.

Yes, multiple pods are attempting to compact the same blocks. 

> Browse to /compactor/ring on any compactor pod and check the ring status. Verify that there are entries are Healthy state and there are the expected number of entries, 1 per compactor.

This is showing only 1 entry for each pod. 

The bucket is not used by any other service or user. From what I understand the hash ring is not correctly configured. We have configured memberlist as the ring store.

**Comment by mapno** [comment]
In monolithic mode the hash ring is not needed, as all components are running inside the same process.

> Unable to find the helm for simple scalable mode.

AFAIK, there isn't one. Our helm-charts are community driven and we only have charts for monolithic and distributed modes.

Is it possible that you're running multiple Tempos in monolithic type? That'd explain what you're describing. That won't work as a simple scalable replacement.

**Comment by kj-mintoak** [comment]
@mapno yes that's what we are doing. So that means we need to move to the distributed mode?

We are able to horizontally scale Loki monolithic mode so were attempting similar implementation on tempo.

**Comment by kj-mintoak** [comment]
Thanks for the clarification. We reduced it to single replica for now and the network usage went down. The compaction error also got resolved. 

Will also try if we can deploy in simple scalable mode without the helm.
