### ISSUE TITLE
Tempo tags filter in Search view not working as expected

### ISSUE THREAD

**Issue by lucasoares** [grafana/tempo#2566]
Hello.

I'm having trouble using the search panel with Tempo. The `error=true` filter is not working. But when I was writing this issue, I found few other issues with tempo search panel.

The first issue I found is that when I type anything in the tags text input, the service name changes automatically.

I can't think a better way to demonstrate it so I recorded a small video of the service name selector changing when I type in the tags text input.
[Screencast from 16-06-2023 19:32:31.webm](https://github.com/grafana/tempo/assets/10624972/769f75d2-f47b-4d60-9c6a-4475e153afd1)

I honestly have no idea how to reproduce it because it happens once a while. I think there is some request being made after changing the service name and typing the tags filter and it may be failing and returning the `service name` to another one? Because in the video you can see there is a little delay after I press the keyboard key (like multiple letters appears after some freezing).

Well, when this happened I changed the service name to the previous one `server-blip` and applied the filter, all spans were returned (the span filter I had was also ignored). I was trying to record this but the service name stopped changing automatically for a unknown reason (I will keep looking if this happens again with anyone of our team).

Other issue I found is having a service name selected (after refreshing the screen with cache-cleaning `ctrl+shift+r` and the service name not being changed anymore), but it being ignored when I apply the filter:
[Screencast from 16-06-2023 19:53:59.webm](https://github.com/grafana/tempo/assets/10624972/f2cd8e87-9fc4-4452-8a81-7e8ecd6e4391)

But now there is the starting error that brought me to write this issue:

I refreshed the screen again, cleaned any caching again, selected my service and typed the `error=true` tag filter. No results. Even having results with the `error` attribute as `true`:

> In this recorded I was surprised the service name didn't changed after editing the tags filter (thats why I typed `wtf` haha):
[Screencast from 16-06-2023 19:37:06.webm](https://github.com/grafana/tempo/assets/10624972/d0be827d-7479-4652-909c-105404e6ee34)

Request made (sometimes it doesn't send the name tag, even with a span name selected but in both cases it returns 0 series):
![image](https://github.com/grafana/tempo/assets/10624972/6bea5cce-cee5-416e-8d28-875f48f167e0)

I don't know if this is related to the #2343 but who knows

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm
 - Tempo Version: 2.1.1
 - Browser used: Chrome (Linux - Ubuntu)

Both Grafana and Tempo was installed this week without any complex/custom customization.

This is not the first time the search panel view have these issues with me or my team. I had the same issue in another grafana and tempo instance in a different environment and a different kubernetes instance. I just can't be sure if what I'm filtering is really being applied and I can't trust this search at all.

> I'm open to talk in slack and do a screen sharing if necessary.

EDIT: I just saw the search panel always call `api/search/tag/service.name/values` if I type something in the tags view and maybe if the request fails, the service name will return to the previou one. But changing it again only change in the view since it could not know if the other service name existed because the request failed? Don't know... I'm very lost to be honest hahaha

**Comment by joe-elliott** [comment]
So my advice would be to abandon the old search. There are a lot of UI issues like the ones you are highlighting that have been steadily patched but continue to persist. I would be 100% sure your Grafana instance is up to date b/c a lot of these have been fixed in the past, but 

The good news: TraceQL is easily able to distinguish between two cases. Based on you issue I'm not sure which one you're referring to.

My span status is in error:
```
{ status = error }
```

I have a custom attribute of type boolean named "error" that I want to search for:
```
{ span.error = true }
```

The existing search view is being replaced with a TraceQL builder that will help:

![image](https://github.com/grafana/tempo/assets/2272392/b6c64af5-7f8a-425f-b109-34dc80dcc26e)

Also note this issue we hope to resolve soon.

https://github.com/grafana/grafana/issues/59607

**Comment by lucasoares** [comment]
Ok! Never using search tab anymore then HAHAHA

With `{ status = error }` I was able to get correct results. Thanks.

**Comment by MrMegaMango** [comment]
tempo search isn't holding service name when additional tag is added.
TraceQL works for me, but not everyone in my company knows it. :sad_panda:

**Comment by MrMegaMango** [comment]
> The existing search view is being replaced with a TraceQL builder that will help
@joe-elliott Is the current search view not a TraceQL builder?

**Comment by joe-elliott** [comment]
This is an older issue that was referring to an older version of search in Grafana. This older version of search was "tags based" and built for the old `v2` backend.  It was never perfectly ported to the newer parquet backends.

The current Grafana search builder writes TraceQL queries for you and is much more reliable.
