### ISSUE TITLE
Docs feedback: /docs/sources/tempo/setup/linux.md

### ISSUE THREAD

**Issue by BenBurge** [grafana/tempo#2572]
When setting up Grafana and Tempo using these installation instructions (https://grafana.com/docs/tempo/latest/setup/linux/) you run into the following message about the search not being enabled.

![image](https://github.com/grafana/tempo/assets/13814339/1f09d850-6194-4274-a9fd-fa4b697a9bfb)

You need to add the following search_enabled: true option to the configuration in order to be able to search tempo in grafanaA

![image](https://github.com/grafana/tempo/assets/13814339/dfd509ad-0bc4-4655-848b-bac843162123)

It would be nice to add this to the installation steps since the configuration option isn't clearly stated anywhere in the documentation that I can find.

**Comment by knylander-grafana** [comment]
Thank you very much for the feedback. I'll add that information to the doc.

**Comment by joe-elliott** [comment]
`search_enabled` was removed in Tempo 2.0:

https://github.com/grafana/tempo/releases/tag/v2.0.0

**Comment by BenBurge** [comment]
> `search_enabled` was removed in Tempo 2.0:
> 
> https://github.com/grafana/tempo/releases/tag/v2.0.0

Aww, I see the problem.

In the install instructions it has us use 1.5 instead of 2.0 (https://grafana.com/docs/tempo/latest/setup/linux/)

![image](https://github.com/grafana/tempo/assets/13814339/951bbf93-290f-466a-8091-06154933989b)

So perhaps the version bit needs to be updated instead of adding in the removed field

**Comment by BenBurge** [comment]
> > `search_enabled` was removed in Tempo 2.0:
> > https://github.com/grafana/tempo/releases/tag/v2.0.0
> 
> Aww, I see the problem.
> 
> In the install instructions it has us use 1.5 instead of 2.0 (https://grafana.com/docs/tempo/latest/setup/linux/)
> 
> ![image](https://user-images.githubusercontent.com/13814339/247232943-951bbf93-290f-466a-8091-06154933989b.png)
> 
> So perhaps the version bit needs to be updated instead of adding in the removed field

@knylander-grafana - Please see the above changes instead of adding search_enabled to the documentation.

Thanks both @knylander-grafana and @joe-elliott!

**Comment by knylander-grafana** [comment]
I updated the docs. The changes should be live on the site shortly.
