### ISSUE TITLE
Tempo in a Class E pod CIDR GKE

### ISSUE THREAD

**Issue by suvl** [grafana/tempo#2573]
Due to having very limited IPs in the VRF we share with our datacenter, we are using Class E IPs for our pod CIDR in all our private GKE clusters. The nodes have RFC1918 class A private addresses but all pods use the public Class E IPs. They are non-routable from the DC or the internet, so we're good.

But while deploying Tempo, `compactor` and others fail to start due to this error:

```
level=error ts=2023-06-20T17:55:05.866363115Z caller=app.go:202 msg="module failed" module=compactor err="failed to start compactor, because it depends on module memberlist-kv, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expected: Running, failure: service &{0xc000715040 { true 10000000000 2 30000000000 1000000000 2 30000000000 0 false  7946  false [tempo-gossip-ring] 1000000000 60000000000 10 false 0 300000000000 20000000000 0 {[] 7946 2000000000 5000000000 false 0xc00009c960 tempo false {    false  }} 0xc00009c960 tempo [{ringDesc 0xd54640} {}]} 0xc0001270e0 0xc00009c960 0xc0003835e0 {[] {[] 0}} <nil> <nil> {0 0} map[] map[ringDesc:{ringDesc 0xd54640} usagestats.jsonCodec:{}] {0 0} map[] map[] {0 0} [] 0 [] 0 0 {0 0} map[] 0xc000723260 0xc00072b4a0 0xc00072b560 0xc00072b620 0xc00072b6e0 0xc00072b920 0xc00072b7a0 0xc00072b9e0 0xc00072b860 0xc000719440 0xc000719480 0xc00072bb60 0xc00072bc20 0xc00072bda0 0xc00072bce0 0xc00070a1c8 0xc000420380 0xc00070a1b8 0xc00070a1c0 0xc0007194c0 0xc000719500 10} failed: failed to create memberlist: Failed to get final advertise address: no private IP address found, and explicit IP not provided"
```

Just as a reference, here are the pod IPs:

```
tempo-compactor-5bf6dcdbb5-6pnjn        0/1     CrashLoopBackOff   12 (16s ago)     36m   240.1.79.196
tempo-distributor-784fc445c9-bn6vc      0/1     CrashLoopBackOff   12 (23s ago)     36m   240.1.78.6
tempo-ingester-0                        0/1     CrashLoopBackOff   12 (22s ago)     36m   240.1.78.11
tempo-ingester-1                        0/1     CrashLoopBackOff   11 (5m8s ago)    36m   240.1.79.197
tempo-ingester-2                        0/1     Completed          12 (5m15s ago)   36m   240.1.77.133
tempo-memcached-0                       1/1     Running            0                36m   240.1.79.194
tempo-querier-6748b544cb-q2rzp          0/1     Completed          12 (5m17s ago)   36m   240.1.79.195
tempo-query-frontend-76ddfd465c-2mzhl   1/1     Running            0                36m   240.1.78.10
```

How can we tell it to use these IPs as private IPs? Or else, give it an explicit IP coming from `.status.podIP`?

**Comment by joe-elliott** [comment]
I have never attempted this, but I believe you can use these to pin the memberlist IP:

```
memberlist:
  advertise_addr: ""
  bind_addr: []
```

Then use the [downward api](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) that you are referring to to get the pod ip.  

You can use env vars in Tempo config to inject the IP by setting the `--config.expand-env` flag:

https://grafana.com/docs/tempo/latest/configuration/#use-environment-variables-in-the-configuration

It may exist, but I'm currently not seeing an option to allow auto discovered public IPs.

**Comment by zalegrala** [comment]
If it helps, we also support IPv6, which may have less address contention in your environment if its supported.  [docs/sources/tempo/configuration/ipv6.md](https://github.com/grafana/tempo/blob/main/docs/sources/tempo/configuration/ipv6.md)
