### ISSUE TITLE
error running Tempo

### ISSUE THREAD

**Issue by LH8PPL** [grafana/tempo#2577]
**Describe the bug**
we are deploying Tempo on-premise with the distributed helm chart and connect to AWS S3 via PrivateLink.
im having the following error:
level=info ts=2023-06-20T12:38:44.891213365Z caller=main.go:102 msg="Starting Tempo" version="(version=2.1.1, branch=HEAD, revision=4157d7620)"
level=error ts=2023-06-20T12:40:14.89436955Z caller=main.go:105 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on bucket1: Get \"http://bucket1.s3.dualstack.eu-central-1.amazonaws.com/?delimiter=%2F&encoding-type=url&prefix=\": dial tcp xxx.xxx.xxx.xxx:80: i/o timeout"

**To Reproduce**
1. Start Tempo (Helm Version: 1.3.0, App Version: 2.1.1)
2. Perform Operations (Read/Write/Others)

**Expected behavior**

connect to:
bucket1.s3.eu-central-1.amazonaws.com

not connect to:
bucket1.s3.dualstack.eu-central-1.amazonaws.com

the option to connect to S3 without dualstack and/or disable the IPv6

**Environment:**
 - Infrastructure: OpenShift 4.10
 - Deployment tool: helm

**Additional Context**

storage:
  trace:
    block:
      version: vParquet
    backend: s3
    s3:
      access_key: 'q1w2e3r4t5y6u7i8'
      secret_key: 'q1w2e3r4t5y6u7i8o9p0zaxscdvfbgnhmj,k.l/;''
      bucket: 'bucket1'
      endpoint: "s3.eu-central-1.amazonaws.com"
      insecure: true
      forcepathstyle: false
      region: "eu-central-1"
  admin:
    backend: s3

**Comment by joe-elliott** [comment]
That does seem odd. I'm surprised it's not using the endpoint specified in the config. These values are directly pushed into the minio client here:

https://github.com/grafana/tempo/blob/2edbdfa0f2d5d99c12c07fc80af8ca0f81a2fdfe/tempodb/backend/s3/s3.go#L411

Perhaps drop the region option? Then maybe it will honor the endpoint provided?

**Comment by LH8PPL** [comment]
thanks for the replay,

tried that, and other variances but didn't work.

**Comment by joe-elliott** [comment]
So tracking this into minio some it looks like it rewrites your hostname here:

https://github.com/minio/minio-go/blob/691ae870325d3cd7c3fc426cbf8396342cd58907/api.go#L906

The logic is skipped if it doesn't look like an amazon endpoint here:

https://github.com/minio/minio-go/blob/691ae870325d3cd7c3fc426cbf8396342cd58907/api.go#L909

and there's a second check to see if it looks like an "amazon private link endpoint" here:

https://github.com/minio/minio-go/blob/691ae870325d3cd7c3fc426cbf8396342cd58907/api.go#L922

Here is the regex it uses to determine if a hostname is a "private link endpoint":

https://github.com/minio/minio-go/blob/691ae870325d3cd7c3fc426cbf8396342cd58907/pkg/s3utils/utils.go#L114

I don't know much about this. Should your hostname match this regex?

**Comment by joe-elliott** [comment]
Reopening. Accidentally closed this instead of #2565.

**Comment by antonio-tolentino** [comment]
Hi @joe-elliott,

I have successfully test the image tag **main-c633387**.
It seems that the parameter "**tolerate_failed_blocks**"  from **queryFrontend** is no longer available and I had to remove it from helm chart **config**  template to install this new image. 
Is there any defined date for a new release?

Thanks a lot for your help.

**Comment by joe-elliott** [comment]
> I have successfully tested the image tag main-c633387.

Are you saying main-c633387 fixed your issue? Likely an update to the minio s3 client.

> Is there any defined date for a new tempo release?

There is not. We tend to release every 3 months or so. On that cadence our next release would be late july/early august.

**Comment by antonio-tolentino** [comment]
Hi Joe,
Thank you so much for the explanations.
If you need anything from my side that helps you to improve Tempo let me know.

**Comment by LH8PPL** [comment]
Is there anything we can do about my issue?

**Comment by joe-elliott** [comment]
> Is there anything we can do about my issue?

If the latest Tempo release does not fix the issue then I'd file an issue with the [minio go client](https://github.com/minio/minio-go) to get some insight into this behavior.

**Comment by LH8PPL** [comment]
I'm using tempo image version 2.1.1

**Comment by zalegrala** [comment]
I believe the change that fixes this is in https://github.com/minio/minio-go/pull/1726, which has been updated in `main`, but we don't have a release for it yet.
