### ISSUE TITLE
Tempo failed to find `meta.json` path after adding prefix in S3 configuration.

### ISSUE THREAD

**Issue by WildCatFish** [grafana/tempo#2585]
**Describe the bug**
Tempo failed to find the meta.json file path after adding a prefix in S3 configuration.
We were watching issue #2100 which is what we desired to have. 
This `prefix` support was not in 2.1.1 release, so we build the Tempo from the source code.
And we found the blocks can be saved as expected with the `prefix`, but compaction and deletion of these blocks failed.

_with prefix_
> level=info ts=2023-06-21T16:49:25.6918833Z caller=retention.go:68 msg="marking block for deletion" blockID=a5916bb1-9132-4340-8410-4f4f56e50643 tenantID=single-tenant
level=error ts=2023-06-21T16:49:25.6945432Z caller=retention.go:71 msg="failed to mark block compacted during retention" blockID=a5916bb1-9132-4340-8410-4f4f56e50643 tenantID=single-tenant err="error copying obj meta to compacted obj meta: The specified key does not exist."
level=info ts=2023-06-21T16:49:25.7054214Z caller=poller.go:209 msg="writing tenant index" tenant=single-tenant metas=2 compactedMetas=0
level=info ts=2023-06-21T16:49:25.7059633Z caller=poller.go:209 msg="writing tenant index" tenant=single-tenant metas=2 compactedMetas=0
level=info ts=2023-06-21T16:49:25.7124402Z caller=poller.go:129 msg="blocklist poll complete" seconds=0.0205569
level=info ts=2023-06-21T16:49:25.7425927Z caller=poller.go:129 msg="blocklist poll complete" seconds=0.053963

![with-prefix-block](https://github.com/grafana/tempo/assets/53441280/3e85930a-a96b-4e72-a253-d145c75be0ba)
As shown there was no `meta.compacted.json`

_without prefix_

> level=info ts=2023-06-21T17:14:16.8284437Z caller=retention.go:68 msg="marking block for deletion" blockID=7ac206e8-a881-409e-956c-efa8b878adc8 tenantID=single-tenant
level=info ts=2023-06-21T17:14:16.8361876Z caller=poller.go:209 msg="writing tenant index" tenant=single-tenant metas=2 compactedMetas=1
level=info ts=2023-06-21T17:14:16.8361876Z caller=poller.go:209 msg="writing tenant index" tenant=single-tenant metas=2 compactedMetas=1
level=info ts=2023-06-21T17:14:16.8382732Z caller=retention.go:97 msg="deleting block" blockID=33f983f0-76ba-4564-9a7b-e8fa6e08008b tenantID=single-tenant
level=info ts=2023-06-21T17:14:16.8438316Z caller=poller.go:129 msg="blocklist poll complete" seconds=0.0153879
level=info ts=2023-06-21T17:14:16.8790127Z caller=poller.go:129 msg="blocklist poll complete" seconds=0.0505142

![without-prefix-block](https://github.com/grafana/tempo/assets/53441280/65b9d9ef-7db6-448e-889b-f9ea766aa789)

Remove the `prefix` from the configuration it seems everything is back to normal.

**To Reproduce**
1. download source code and build tempo from the `main` branch (Jun 23, 2023)
2. Starting with docker s3 example [https://github.com/grafana/tempo/blob/main/example/docker-compose/s3/docker-compose.yaml](url) instead of the latest tempo image, using the local build tempo.
3. setting the `prefix` in storage s3 configuration

**Expected behavior**
enable `prefix` should not affect the compaction and deletion process.

**Environment:**
 - Infrastructure: Openshift, laptop

**Additional Context**
I did some experiments on my local laptop, and this issue seems to be caused by the `MetaFileName`https://github.com/grafana/tempo/blob/c63338744d3842b54240e39a049ce688e910edb8/tempodb/backend/raw.go#L238, `CompactedMetaFileName`https://github.com/grafana/tempo/blob/c63338744d3842b54240e39a049ce688e910edb8/tempodb/backend/raw.go#L243 and `RootPath`https://github.com/grafana/tempo/blob/c63338744d3842b54240e39a049ce688e910edb8/tempodb/backend/raw.go#L248, these functions do not return the file name with the `rw.cfg.Prefix`

After some adjustments in these functions and `compactor.go`, tempo seems to work correctly. 

_after adjustments_
> level=info ts=2023-06-21T19:59:37.3055968Z caller=retention.go:68 msg="marking block for deletion" blockID=9ef75b3f-4dbd-4422-b3a1-95f259ad4333 tenantID=single-tenant
level=info ts=2023-06-21T19:59:37.3193817Z caller=poller.go:209 msg="writing tenant index" tenant=single-tenant metas=2 compactedMetas=1
level=info ts=2023-06-21T19:59:37.3199077Z caller=poller.go:209 msg="writing tenant index" tenant=single-tenant metas=2 compactedMetas=1
level=info ts=2023-06-21T19:59:37.3206734Z caller=retention.go:97 msg="deleting block" blockID=b4d20bb0-d4f8-418a-ba83-07be7d2337ea tenantID=single-tenant
level=info ts=2023-06-21T19:59:37.3258373Z caller=poller.go:129 msg="blocklist poll complete" seconds=0.0202405
level=info ts=2023-06-21T19:59:37.3634428Z caller=poller.go:129 msg="blocklist poll complete" seconds=0.057846
![fixed-block](https://github.com/grafana/tempo/assets/53441280/4bbe8d85-664c-413d-8fad-fae8ea3c794d)

**Comment by mapno** [comment]
Hi @WildCatFish. Thanks for raising this issue.

I checked the code, and you're completely right: the prefix wasn't added to the compactor methods. It seems that you've already researched quite a bit the root cause, do you want to contribute the PR with the fix? If not, we'll take care of it

**Comment by WildCatFish** [comment]
@mapno Sure, I would like to.

**Comment by mapno** [comment]
Go for it! If I'm not mistaken, the prefix will need to be added to this [methods](https://github.com/grafana/tempo/blob/main/tempodb/backend/s3/compactor.go)
