### ISSUE TITLE
Tempo2.1.1 msg="failed to forward request to metrics generator" err="failed to push spans to generator: rpc error: code = Unavailable

### ISSUE THREAD

**Issue by gpadidala** [grafana/tempo#2599]
Describe the bug
tempo-distributor failed to push spans to generator: rpc error

**To Reproduce**
1. Start Tempo
2. Perform Operations (Read/Write/Others)

**Expected behavior**
Push the spans metrics tempo-metrics-generator

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm(chart: tempo-distributed-1.2.10)
 - Tempo Version : 2.1.1

**Additional Context**
level=warn ts=2023-06-28T21:12:31.335286221Z caller=forwarder.go:221 msg="failed to forward request to metrics generator" err="failed to push spans to generator: rpc error: code = Unavailable desc = "
level=info ts=2023-06-28T21:12:31.457340214Z caller=distributor.go:544 msg=received spanid=df5118e8ea6db144 traceid=000000000000000095540f453bc49763
level=warn ts=2023-06-28T21:12:31.460199186Z caller=forwarder.go:221 msg="failed to forward request to metrics generator" err="failed to push spans to generator: rpc error: code = Unavailable desc = "
level=info ts=2023-06-28T21:12:31.503428481Z caller=distributor.go:544 msg=received spanid=95540f453bc49763 traceid=000000000000000095540f453bc49763
level=warn ts=2023-06-28T21:12:31.506055748Z caller=forwarder.go:221 msg="failed to forward request to metrics generator" err="failed to push spans to generator: rpc error: code = Unavailable desc = "
level=info ts=2023-06-28T21:12:31.518886073Z caller=distributor.go:544 msg=received spanid=d913c6eecf1ff960 traceid=000000000000000095540f453bc49763
level=warn ts=2023-06-28T21:12:31.52152894Z caller=forwarder.go:221 msg="failed to forward request to metrics generator" err="failed to push spans to generator: rpc error: code = Unavailable desc = "

data:
  tempo-query.yaml: |
    backend: 127.0.0.1:3100
    
  overrides.yaml: |
    
    overrides: {}
    
  tempo.yaml: |
    
    compactor:
      compaction:
        block_retention: 168h
        compacted_block_retention: 1h
        compaction_cycle: 30s
        compaction_window: 1h
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
      ring:
        kvstore:
          store: memberlist
    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        opencensus:
          endpoint: 0.0.0.0:55678
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        zipkin:
          endpoint: 0.0.0.0:9411
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
        tokens_file_path: /var/tempo/tokens.json
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
      - ***************-tempo-gossip-ring
    metrics_generator:
      processor:
        service_graphs:
          dimensions: []
          histogram_buckets:
          - 0.1
          - 0.2
          - 0.4
          - 0.8
          - 1.6
          - 3.2
          - 6.4
          - 12.8
          max_items: 10000
          wait: 300s
          workers: 10
        span_metrics:
          dimensions: []
          histogram_buckets:
          - 0.002
          - 0.004
          - 0.008
          - 0.016
          - 0.032
          - 0.064
          - 0.128
          - 0.256
          - 0.512
          - 1.02
          - 2.05
          - 4.1
      registry:
        collection_interval: 15s
        external_labels: {}
        stale_duration: 15m
      ring:
        kvstore:
          store: memberlist
      storage:
        path: /var/tempo/wal
        remote_write: 
          - url: https://***************.com/api/v1/push
            headers:
              X-Scope-OrgID: ***************-tempo
        remote_write_flush_deadline: 1m
    multitenancy_enabled: true
    overrides:
      max_traces_per_user: 100000
      ingestion_rate_strategy: global
      metrics_generator_processors:
      - service-graphs
      - span-metrics
      per_tenant_override_config: /conf/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: ***************-tempo-query-frontend-discovery:9095
      max_concurrent_queries: 20
      search:
        external_endpoints: []
        external_hedge_requests_at: 8s
        external_hedge_requests_up_to: 2
        prefer_self: 10
        query_timeout: 30s
      trace_by_id:
        query_timeout: 10s
    query_frontend:
      max_retries: 2
      search:
        concurrent_jobs: 1000
        target_bytes_per_job: 104857600
      tolerate_failed_blocks: 0
      trace_by_id:
        hedge_requests_at: 2s
        hedge_requests_up_to: 2
        query_shards: 50
    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      log_format: logfmt
      log_level: debug
    storage:
      trace:
        backend: azure
        azure:
          container_name: ***************-tempo
          storage_account_key: ${azurestorageaccountkey}
          storage_account_name: ${azurestorageaccountname}
        block:
          version: vParquet
        blocklist_poll: 5m
        cache: memcached
        local:
          path: /var/tempo/traces
        memcached:
          consistent_hash: true
          host: ***************-tempo-memcached
          service: memcached-client
          timeout: 500ms
        wal:
          path: /var/tempo/wal
    usage_report:
      reporting_enabled: true

**Comment by joe-elliott** [comment]
No error is a little weird, but let's check a few things.

- confirm that the distributor is aware of metrics generators. check the `/metrics-generator/ring` and make sure they are present
- check network connectivity between the distributors and metrics generators by opening the grpc port on the generators from the distributors

**Comment by gpadidala** [comment]
@joe-elliott 
1. All the 3 rings are up and running 
2. we had validate the connectivity between the pods with telnet for grpc port and its successful 

![image](https://github.com/grafana/tempo/assets/107822538/e8d38647-c9ee-4657-942a-02a28af934fd)
![image](https://github.com/grafana/tempo/assets/107822538/a79d5c86-64fb-4940-b68f-6a4d0e6f9144)
![image](https://github.com/grafana/tempo/assets/107822538/14374a8e-deaf-45e2-876f-094595653fce)

**Comment by joe-elliott** [comment]
So the error code is "unavailable". Are you aware of any stability issues with your generators? Perhaps we can check some metrics:

This will give us info from the distributor's perspective:
```
tempo_distributor_forwarder_pushes_total
tempo_distributor_forwarder_pushes_failures_total
```

This would tell us if the generator is receiving anything:
```
tempo_metrics_generator_spans_received_total
```

**Comment by gpadidala** [comment]
We are seeing Spans Received Metrics in distributor 
![image](https://github.com/grafana/tempo/assets/107822538/fecb40b2-8384-4c40-b421-2fae1589489c)

tempo_distributor_metrics_generator_clients  - this value is always 0
![image](https://github.com/grafana/tempo/assets/107822538/3c1f8fb5-9b4a-40d7-bbd2-43058df9fb10)

tempo_distributor_forwarder_pushes_total
tempo_distributor_forwarder_pushes_failures_total
tempo_metrics_generator_spans_received_total

Above all 3 are receiving Empty results : 

![image](https://github.com/grafana/tempo/assets/107822538/9bf35c13-5c5d-4850-a756-89f315a89cd4)

**Comment by nqminhdl** [comment]
hi @gpadidala, 

Have you managed to solve this issue? I experienced the same problem.
