### ISSUE TITLE
tempo gateway has wrong value in nginxConfig

### ISSUE THREAD

**Issue by waeldot** [grafana/tempo#2606]
**Describe the bug**
default value for nginxConfig has wrong location value
It is set to `/otlp/v1/traces` but it has to be set to `/v1/traces`

**values.yaml**
```
gateway:
  ...
  nginxConfig:
    ...
    file: |
      ...
      http {
        ...
        server {
          ...
          location = /otlp/v1/traces {
            proxy_pass       http://{{ include "tempo.resourceName" (dict "ctx" . "component" "distributor") }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:4318/v1/traces;
        ...
          }
      }
```

**To Reproduce**
1. install  tempo-distributed(helm chart version = 1.4.7)
2. enable gateway
3. send traces to the gateway 

**Expected behavior**
expected to be ingested, but emitted error with wrong URL messages 

**Environment:**
- tempo-distributed, chart version = 1.4.7
- opentelemetry-collector, chart version = 0.57.1

**Additional Context**

**Comment by rlex** [comment]
works fine for me if i add /otlp at the end of tempo-gateway address in otel-collector
