### ISSUE TITLE
TraceQL doc and query editing assistance to search by TraceID

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2607]
**Is your feature request related to a problem? Please describe.**

I can't find the syntax to search traces by TraceID.

**Describe the solution you'd like**

I would like assistance to search traces by TraceID with the following:

* Documentation in https://grafana.com/docs/tempo/latest/traceql/
* TraceQL auto completion assistance
* TraceQL visual builder assistance

**Describe alternatives you've considered**

The previous visual builder assistance provided assistance to query by TraceID thanks to a dedicated tab in the GUI

**Additional context**

**Comment by rlex** [comment]
just enter trace id in traceql field without any additional stuff and it will pull that trace.

But yeah, looks like it's not present in docs.

**Comment by knylander-grafana** [comment]
Hi, @cyrille-leclerc 

I'm writing the content that you requested. I do have some additional information in the Cloud and Grafana docs for the TraceQL editor that aren't included in the Tempo docs. I'll add links to that content to make sure someone wanting more information can find it. 

Search traces by Trace ID 
- The procedure for Searching traces by Trace ID is in the Grafana documentation: https://grafana.com/docs/grafana/latest/datasources/tempo/query-editor/#query-by-traceid 
- Add panels that help you search by Trace ID (and adding a link to Trace IDs via contextual menu) on Grafana dashboard panels - https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/traces/ 

TraceQL auto completion
- Autocompletion is documented in the [TraceQL query editor page in Tempo](https://grafana.com/docs/tempo/latest/traceql/query-editor/)
- This content was minimal, so I've updated it to add an actual procedure. 

TraceQL visual builder --if you mean the new Search tab that lets you use drop-down selection to build a query(see screenshot below)
- Documented in [Grafana](https://grafana.com/docs/grafana/latest/datasources/tempo/query-editor/#create-traceql-queries-using-search), [Grafana Cloud](https://grafana.com/docs/grafana-cloud/data-configuration/traces/traces-query-editor/), and [Tempo doc](https://grafana.com/docs/tempo/next/traceql/query-editor/#create-traceql-queries-using-search) (on the next branch, will be live with Tempo 2.2)
![image](https://github.com/grafana/tempo/assets/104772500/3f3fe2e9-dd63-46ed-a128-c1ea3f0cbcd7)

**Comment by knylander-grafana** [comment]
@cyrille-leclerc Would you review this PR? https://github.com/grafana/tempo/pull/2628

**Comment by cyrille-leclerc** [comment]
Thanks @knylander-grafana .

@joe-elliott did we consider that `traceId`, `spanId`, and maybe `spanStartTime` & `spanEndTime` could be added to the [Span Intrinsic Fields](https://grafana.com/docs/tempo/latest/traceql/#intrinsic-fields) exposed in TraceQL?

Reference: https://github.com/open-telemetry/opentelemetry-proto/blob/v1.0.0/opentelemetry/proto/trace/v1/trace.proto

**Comment by mjobin-mdsol** [comment]
Although some clarification was added to the documentation, I don't think this issue should be marked as closed.
I am also looking for a way to query by traceId in TraceQL

Thank you

**Comment by mapno** [comment]
Hi @mjobin-mdsol. To query by trace ID, simply paste the ID into the search box and it'll retrieve the trace from Tempo.

**Comment by bvillanueva-mdsol** [comment]
Hi @mapno, as I perceived on the traceql output UI format, it gives all the traces that falls under the traceql conditions but also highlights the specific spans that falls under the condition. I think for @mjobin-mdsol scenario, he wants to take advantage on highlighting the spans under a specific traceid so it will direct him to the specific span right away in case the trace is big. 

Would that be a good use case for traceql?

**Comment by mapno** [comment]
Ah, I see. Could [span filters](https://grafana.com/docs/grafana/latest/datasources/tempo/span-filters/) cover that use case? It's not as powerful as TraceQL, but works pretty great for highlighting spans in traces.
