### ISSUE TITLE
failed to poll blocklist & failed to mark block compacted during retention

### ISSUE THREAD

**Issue by wolf666666** [grafana/tempo#2619]
Hi, I have a lot error messages suddenly. i have 6 tempo-compactor instances, some of then have a lot error message from yesterday. I have no idea how to handle them. Here is the error message:
one is
"failed to poll blocklist. using previously polled lists" err="We encountered an internal error. Please try again."
another is
"failed to mark block compacted during retention" blockID=xxxxxxxxxxxxxx

I saw these error messages some months ago, it resolved them by delete the S3 buckets, but now i can not delete the buckets as the user are using the data.
I try to find the reason, i checked the instances status and i also checked the compactor ring status, they are all ok, i have no idea how to resolve them. Could you give some suggestions?

**Comment by mapno** [comment]
Hi @wolf666666. Those errors seem to come from S3 itself. Transient errors during compaction/retention shouldn't be a major issue. Are compactor still able to work or are they getting these errors constantly?

**Comment by wolf666666** [comment]
Hi @mapno These error appeared every 5 minutes for 2 day, this morning it seems there are disappeared, i don't know why

**Comment by mapno** [comment]
Let us know if it starts happening again. It's possible that there were some transient issues with S3
