### ISSUE TITLE
(Helm chart) Completely disable metrics generator by default

### ISSUE THREAD

**Issue by Hronom** [grafana/tempo#2633]
**Describe the bug**
I'm constantly getting in logs `failed to forward request to metrics generator` from `tempo-distributor`, but I use default values from `tempo-distributed` and not enable `metrics generator`.

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**
Not getting in logs `failed to forward request to metrics generator` from `tempo-distributor` when use default values from `tempo-distributed` where `metrics generator` disabled by default.

**Environment:**
- Kubernetes
- helm: `tempo-distributed`, version `1.4.8`

**Additional Context**
Current workaround is to make empty `metrics_generator_processors`:
```
  global_overrides:
    metrics_generator_processors: []
```
in default values chart they are set to this:
```
global_overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
```

**Comment by zalegrala** [comment]
You could likely set the replicas to 0 and that would be enough.

**Comment by Hronom** [comment]
@zalegrala the issues here that with default setup `tempo-distributor` still use `metrics generator`. But intention of default values in chart is to completely disable `metrics generator` as same as usage of it.

And seems like `tempo-distributor` trying to use `metrics generator` by default because of settings in `metrics_generator_processors`

**Comment by mrkwtz** [comment]
Ran into the same issue again, the application config defaults should align with the chart / resource defaults. You shouldn't enable them by default in the config and then disable the deployment of the metrics generator by default.

**Comment by zalegrala** [comment]
Hmm, I'd have to test this out to be sure, but are you suggesting that this default configuration is not working?

https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L222

Defaulting to `false` there I would expect that the generator does not get deployed.

And setting this to `0` still runs the generator also?

https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L226

**Comment by mrkwtz** [comment]
It has nothing to do with the generator itself. Because of the configuration it won't be deployed but because of this: https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L1230-L1232 the distributor is going to try to send information to the generator. Which will fail (because there is no generator deployed) and spam the logs with error messages.

**Comment by zalegrala** [comment]
I'll find some time this week to test this out.

**Comment by zalegrala** [comment]
I see the logs now.  There might be a change to make in the distributor, but nonetheless I agree that this should be fixed in the chart.  I've opened https://github.com/grafana/helm-charts/pull/2523 for this change.

**Comment by zalegrala** [comment]
This is in `1.6.0` of the `tempo-distributed` chart.  Thanks for the report.
