### ISSUE TITLE
[DOC] How to map otlp trace IDs to tempo trace IDs?

### ISSUE THREAD

**Issue by PietroPasotti** [grafana/tempo#2635]
**Describe the bug**
I've been struggling to map opentelemetry trace IDs to the IDs I can find in Tempo.

I'm using [the otlp python sdk](https://opentelemetry.io/docs/instrumentation/python/cookbook/#manually-setting-span-context) to start a root trace, then I print out its trace ID and get something like `28445758678336359253481741084892279171`
However when I try to search for that ID in the dashboard, it can't find it. Instead, it will show IDs like:

![image](https://github.com/grafana/tempo/assets/6230162/59309ba0-e989-4b2f-89e5-a410386bcadb)

It looks like a different format.

My question is: how do I map between opentelemetry-generated trace IDs to tempo's own trace IDs?

**Environment:**
 - Infrastructure: microk8s, laptop
 - Deployment tool: juju

**Additional Context**
-

**Comment by mapno** [comment]
Hi @PietroPasotti. Your IDs and the ones from Tempo are the same bytes but with different representations. If I'm not mistaken, the ID that the Python SDK uses is a 128-bit int, whereas Tempo uses hex encoding to represent the IDs.

The best solution is if you can print the trace IDs hex-encoded. Something like this

```python
trace_id=2604504634922341076776623263868986797
print(hex(trace_id))
```

**Comment by PietroPasotti** [comment]
Fantastic! Where should this be documented?

**Comment by hedss** [comment]
@PietroPasotti Hey there. The OpenTelemetry specification states that the trace and span IDs should be returned by the API as either a Hex and/or binary representation: https://opentelemetry.io/docs/specs/otel/trace/api/#retrieving-the-traceid-and-spanid so I'd say it's worth going back to the Python OTel maintainers and pointing this out (if it's not already been addressed).
