### ISSUE TITLE
Distributor perf: assert ingestion rate limits as early as possible

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#2640]
Ingestion rate limits are asserted in the [distributor](https://github.com/grafana/tempo/blob/main/modules/distributor/distributor.go#L323-L331) after the received traces have been [parsed by the receiver](https://github.com/grafana/tempo/blob/main/modules/distributor/receiver/shim.go#L280-L295), [marshalled](https://github.com/grafana/tempo/blob/main/modules/distributor/distributor.go#L276-L281) and [unmarshalled](https://github.com/grafana/tempo/blob/main/modules/distributor/distributor.go#L283-L289) back. This results in a unnecessary CPU and mem usage if the batch is finally dropped.

Ingestion rate limits should be moved up, so there's as little processing as possible before asserting them. The receivers are OTel components, so changing them to accept our rate limits seems more complex than desired. We prefer to keep with the upstream version of this components. What seems the best choice is at the top of the [`PushTraces`](https://github.com/grafana/tempo/blob/main/modules/distributor/distributor.go#L272) function.

**Comment by mghildiy** [comment]
Unmarshalling depends on marshalling for byes array, and then populates trace.Batches:

https://github.com/grafana/tempo/blob/283f2328cdcd8a0b67d646a55189a071bb877f13/modules/distributor/distributor.go#L278-L286
https://github.com/grafana/tempo/blob/283f2328cdcd8a0b67d646a55189a071bb877f13/pkg/tempopb/tempo.pb.go#L7862

...and traces size is then claculated from trace.Batches

https://github.com/grafana/tempo/blob/283f2328cdcd8a0b67d646a55189a071bb877f13/modules/distributor/distributor.go#L311

It is this traces size which is then used for checking ingestion rate limits.

So overall, in current state check for ingestion rate limit depend on marshalling- unmarshalling.

**Comment by joe-elliott** [comment]
> Our thought was that we can measure the len of bytes returned in...

I think we can do better than that and just count the proto bytes before we do any unmarshalling/marshalling. Can't we just move the loop around line 311 above line 278 where we convert?

**Comment by mghildiy** [comment]
[PR](https://github.com/grafana/tempo/pull/2703) created.

**Comment by mghildiy** [comment]
What category of PR would be this this? Change, feature, enhancement, bugfix?

**Comment by joe-elliott** [comment]
> Change, feature, enhancement, bugfix?

A little bit enhancement and little bit change. let's go with "enhancement", but we should note in the changelog any behavior changes to the metrics. I haven't seen the PR yet, but I believe this will impact the `tempo_distributor_(bytes|spans)_total` metric.
