### ISSUE TITLE
Regarding compatibility issues, I hope to reach your help.

### ISSUE THREAD

**Issue by FrankCy** [grafana/tempo#2642]
hi, I am now using the following version for integration:
spring boot：2.1.3.RELEASE
jdk: java version 1.8.0_321
tempo: tempo_2.0.0_linux_arm64.tar.gz
opentelemetry-javaagent: 0.9.0

The program cannot report the information to loki, the error is as follows:

[opentelemetry.auto.trace 2023-07-12 13:41:19:960 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.trace.v1.TraceService
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I have tried many versions of debugging, but there are still errors. Is there any dependency description or recommended version description? We use JDK8, and hope that the grafana tempo view that reports the data of the spring boot project can be displayed.

**Comment by FrankCy** [comment]
start command：
java -javaagent:/data/server/boot_pro/opentelemetry-javaagent-all-0.9.0.jar -Dotel.resource.attributes=service.name=spring-boot-tempo-loki -Dotel.traces.exporter=otlp -Dotel.javaagent.debug=true -Dotel.exporter.otlp.endpoint=192.168.163.172:9096 -jar spring-boot-tempo-loki-1.0-SNAPSHOT.jar

tempo configuration information：
auth_enabled: false
  
server:
  http_listen_port: 3200
  grpc_listen_port: 9096
  log_level: info

distributor:
  receivers:  # The receivers that the distributor supports.
    jaeger:
      protocols:
        thrift_http:
        thrift_compact:
        thrift_binary:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: inmemory

storage:
  trace:
    backend: local  # Using local storage.
    local:
      path: /tmp/tempo  # The path where data will be stored on the local filesystem.

**Comment by FrankCy** [comment]
[https://img-blog.csdnimg.cn/6cfef5bab92a45598cc1e6ebf7c16e11.png](url)

**Comment by joe-elliott** [comment]
> [opentelemetry.auto.trace 2023-07-12 13:41:19:960 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.trace.v1.TraceService

This suggests that you are pointing your application at some listening port/ip but it does not correctly implement the expected GRPC service.

Here is a simple example that uses the otel collector to send traces to tempo using otlp:
https://github.com/grafana/tempo/tree/main/example/docker-compose/otel-collector

It also looks like you're using Tempo 2.0. May as well upgrade to 2.1.

**Comment by FrankCy** [comment]
> > [opentelemetry.auto.trace 2023-07-12 13:41:19:960 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
> > io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.trace.v1.TraceService
> 
> This suggests that you are pointing your application at some listening port/ip but it does not correctly implement the expected GRPC service.
> 
> Here is a simple example that uses the otel collector to send traces to tempo using otlp: https://github.com/grafana/tempo/tree/main/example/docker-compose/otel-collector
> 
> It also looks like you're using Tempo 2.0. May as well upgrade to 2.1.


Thanks, I'll try it first

**Comment by FrankCy** [comment]
There is an error in the tempo log, what is the reason? Is there a problem with the configuration?
```log
level=info ts=2023-07-14T07:04:18.371267189Z caller=poller.go:195 msg="writing tenant index" tenant=blocks metas=0 compactedMetas=0
level=info ts=2023-07-14T07:04:18.371942024Z caller=poller.go:195 msg="writing tenant index" tenant=single-tenant metas=1 compactedMetas=0
level=error ts=2023-07-14T07:04:18.373400196Z caller=tempodb.go:450 msg="failed to poll blocklist. using previously polled lists" err="failed to parse blocks: invalid UUID length: 6"
```

**Comment by joe-elliott** [comment]
> level=error ts=2023-07-14T07:04:18.373400196Z caller=tempodb.go:450 msg="failed to poll blocklist. using previously polled lists" err="failed to parse blocks: invalid UUID length: 6"

Tempo polls the backend in order to create an up to date state. Part of that includes listing all of the block guids at:
```
<bucket>/<tenant id>/<block guids>
```
It then attempts to parse all of the block guids, but for some reason it is failing in the error message above. This usually suggests that there is a stray object sitting in object storage.

**Comment by FrankCy** [comment]
> > level=error ts=2023-07-14T07:04:18.373400196Z caller=tempodb.go:450 msg="failed to poll blocklist. using previously polled lists" err="failed to parse blocks: invalid UUID length: 6"
> 
> Tempo polls the backend in order to create an up to date state. Part of that includes listing all of the block guids at:
> 
> ```
> <bucket>/<tenant id>/<block guids>
> ```
> 
> It then attempts to parse all of the block guids, but for some reason it is failing in the error message above. This usually suggests that there is a stray object sitting in object storage.

Thanks, I'll take another look.

**Comment by FrankCy** [comment]
My app start command is as follows:
```shell
java -javaagent:/data/server/boot_pro/opentelemetry-javaagent-1.27.0.jar \
  -Dotel.logs.exporter=otlp \
  -Dotel.semconv-stability.opt-in=http \
  -Dotel.instrumentation.micrometer.base-time-unit=s \
  -Dotel.instrumentation.log4j-appender.experimental-log-attributes=true \
  -Dotel.instrumentation.logback-appender.experimental-log-attributes=true \
  -Dotel.exporter.otlp.protocol=grpc \
  -Dotel.metrics.exporter=none \
  -Dotel.javaagent.debug=true \
  -Dotel.exporter.otlp.endpoint=http://192.168.163.172:4317 \
  -Dotel.service.name=opentelemetry-java \
  -Dotel.resource.attributes=deployment.environment=dev,service.namespace=test,service.version=1.1 \
  -jar opentelemetry-java-1.0-SNAPSHOT.jar
```

The tempo configuration in Grafan is as follows:
![image](https://github.com/grafana/tempo/assets/7959694/4801b79d-b358-4333-b02c-049472b1935c)

Similarly, port 4318 is also independently configured with a database. Although Save&Test has no errors, no data is still obtained.

[Test project address](https://github.com/FrankCy/spring-boot-tempo-loki)

tempo-config.yaml
```yaml
auth_enabled: false
  
server:
  http_listen_port: 3200
  grpc_listen_port: 9096
  log_level: info

distributor:
  receivers:  # The receivers that the distributor supports.
    jaeger:
      protocols:
        thrift_http:
        thrift_compact:
        thrift_binary:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: inmemory

storage:
  trace:
    backend: local  # Using local storage.
    local:
      path: /tmp/tempo  # The path where data will be stored on the local filesystem.
```

Where is the configuration problem? I want to view the tempo view in grafana to monitor our engineering links. It is currently in the exploratory stage.

**Comment by FrankCy** [comment]
How should the "pipelines" mentioned in the log be configured?
```shell
[otel.javaagent 2023-07-17 08:35:43:805 +0000] [OkHttp http://192.168.163.172:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export logs. Server responded with UNIMPLEMENTED. This usually means that your collector is not configured with an otlp receiver in the "pipelines" section of the configuration. If export is not desired and you are using OpenTelemetry autoconfiguration or the javaagent, disable export by setting OTEL_LOGS_EXPORTER=none. Full error message: unknown service opentelemetry.proto.collector.logs.v1.LogsService
```

**Comment by FrankCy** [comment]
THK.You can already see the link log, although there are still some things I don’t understand, thank you very much.
