### ISSUE TITLE
[Tempo-distributed] Service name and Span name labels do not show in Grafana

### ISSUE THREAD

**Issue by deathsaber** [grafana/tempo#2646]
**Describe the bug**
We recently migrated from tempo single-binary to tempo-distributed with S3 as the backend object storage. We are using tempo 2.1.1. With tempo-distributed, we started noticing a weird issue where label names disappear in the dropdowns after about an hour. While the labels do show up if traces are continuously being sent, when the traces stop coming in, the labels disappear after an hour. I can run searches and the traces do show up (meaning tempo has not lost data) but the labels still stay unpopulated. Please see screenshot below.

![image](https://github.com/grafana/helm-charts/assets/20237354/6646e17a-de5c-4b28-ba30-c990e51e424d)

**To Reproduce**
1. Install tempo-distributed helm chart with S3 as object storage with the following config -
```
ingester - 3 replicas
distributor - 3 replicas
querier -1 replica
compactor - 1 replica
query-frontend - 1 replica
```
2. Send traces to tempo.
3. After an hour or so, query tempo for data within last 2 hours.

**Expected behavior**
The service name and span name label dropdowns show a list services and spans.

**Environment:**
 - Infrastructure: kubernetes (EKS)
 - Deployment tool: helm

**Additional Context**
I looked through the query frontend logs and it shows 200 success calls for /api/search/tag but seems no data is returned.
```
level=debug ts=2023-07-12T13:25:03.558028555Z caller=logging.go:101 traceID=0a7ca9ae58f3e96e msg="GET /api/search/tag/service.name/values (200) 4.958505ms"
level=info ts=2023-07-12T13:25:05.921704781Z caller=handler.go:124 tenant=single-tenant method=GET traceID=577773ad8f246fcc url=/api/search/tag/name/values duration=2.615203ms response_size=2 status=200
level=debug ts=2023-07-12T13:25:05.921852173Z caller=logging.go:101 traceID=577773ad8f246fcc msg="GET /api/search/tag/name/values (200) 2.819986ms"
```
I came across this issue https://github.com/grafana/tempo/issues/2565 which seems to be related to the problem I am facing but I am not entirely sure. Any advice and guidance will be really great on how to solve this. I have provided the tempo config values below. Is there a config that I somehow missed which might be the culprit?
```
    compactor:
      compaction:
        block_retention: 720h
        compacted_block_retention: 720h
        compaction_cycle: 30s
        compaction_window: 1h
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
      ring:
        kvstore:
          store: memberlist
    distributor:
      log_received_spans:
        enabled: true
        filter_by_status_error: true
        include_all_attributes: true
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        tokens_file_path: /var/tempo/tokens.json
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
      - tempo-distributed-gossip-ring
    multitenancy_enabled: false
    overrides:
      max_bytes_per_tag_values_query: 50000000
      metrics_generator_processors:
      - service-graphs
      - span-metrics
      per_tenant_override_config: /conf/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: tempo-distributed-query-frontend-discovery:9095
      max_concurrent_queries: 20
      search:
        external_endpoints: []
        external_hedge_requests_at: 8s
        external_hedge_requests_up_to: 2
        prefer_self: 10
        query_timeout: 30s
      trace_by_id:
        query_timeout: 10s
    query_frontend:
      max_retries: 2
      search:
        concurrent_jobs: 1000
        target_bytes_per_job: 104857600
      trace_by_id:
        hedge_requests_at: 2s
        hedge_requests_up_to: 2
        query_shards: 50
    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      log_format: logfmt
      log_level: debug
    storage:
      trace:
        backend: s3
        block:
          version: vParquet
        blocklist_poll: 5m
        cache: memcached
        local:
          path: /var/tempo/traces
        memcached:
          consistent_hash: true
          host: tempo-distributed-memcached
          service: memcached-client
          timeout: 500ms
        s3:
          bucket: tempo-traces-bucket
          endpoint: s3.us-east-1.amazonaws.com
          region: us-east-1
        wal:
          path: /var/tempo/wal
    usage_report:
      reporting_enabled: false
```

**Comment by joe-elliott** [comment]
Currently Tempo will only return label values and names for traces in the ingesters. This includes the wal and complete blocks.

We have a feature request for it here:
https://github.com/grafana/tempo/issues/1705

The code wouldn't be too difficult to write, but the performance would be quite slow unless Tempo were only receiving a small amount of data. It's on our radar, but improvements like parquet page level caching and parquetv3 would both go a long way to make this possible at larger scales.

If someone is interested in this improvement we'd take a PR as long as it was gated behind a flag.

**Comment by deathsaber** [comment]
Thanks, @joe-elliott . I saw that issue you linked and looks like unless tempo starts querying for labels in object storage, we'll always end up losing labels after around 45 minutes by default. (30m for tempo ingester to create blocks + 15m for tempo to retain the blocks in ingester). 
As a temporary workaround, I increased the complete_block_timeout of the ingester to around 3 days and briefed my team that if their apps stopped sending traces then, the labels would only be visible to them for 3 days and, if they need data from prior to 3 days, then they gotta write trace QL queries instead of using the service and span name dropdowns.
I know this works as I can now see labels for apps which stopped sending traces over 24hours back but, would like your input on whether increasing complete_block_timeout is a feasible temporary solution (as it would mean tempo stores these blocks for 3 days so, will eat up space like crazy). I am currently running tempo ingester with an EBS persistent volume with around 64 GB of storage size. Should I increase this value?

**Comment by joe-elliott** [comment]
> would like your input on whether increasing complete_block_timeout is a feasible temporary solution
The biggest negative is that attribute lookup might slow down b/c it will search all these blocks. It might also slow down traceql searches. I'm not 100% sure that ingester blocks are excluded based on time range or if they are all searched.

>  I am currently running tempo ingester with an EBS persistent volume with around 64 GB of storage size. Should I increase this value?

This entirely depends on your ingestion rate. You tell me :)

**Comment by deathsaber** [comment]
Hey @joe-elliott . You are right.  How much of persistent storage I use depends on how much data is initially being read  and processed. Hence, my PV size would change. 
Thanks a lot for the insights 😄

**Comment by joe-elliott** [comment]
Closing in favor of the mentioned issue: #1705
