### ISSUE TITLE
Update parquet-go dependency to parquet-go/parquet-go

### ISSUE THREAD

**Issue by stoewer** [grafana/tempo#2648]
The repository segmentio/parquet-go has been [archived](https://github.com/segmentio/parquet-go#project-has-been-archived). The active development of the library was moved to the new [parquet-go GH organization](https://github.com/parquet-go). 

The parquet-go dependency and import paths should be updated to the `github.com/parquet-go/parquet-go` package.

**Comment by mdisibio** [comment]
Update:  I verified that all Tempo tests pass on the new dependency and benchmarks are +/- a few %.  We should target this after releasing 2.2.
