### ISSUE TITLE
Traces showing "404 not found" for ~30 minutes after trace ingest

### ISSUE THREAD

**Issue by hbjydev** [grafana/tempo#2650]
**Describe the bug**
I'm trying to instrument some apps with Tempo and for about 30 minutes post-ingest, none of my traces are readable. They show up in search, but when I try to open the detail view for them in Grafana, they come back with a 404, and Tempo's logs show a lot of 'searching for block in <...> found=false' messages.

My feeling on this is there's a weird race condition I'm hitting here where one instance ingests the trace then no instance is able to read it for a while after.

**To Reproduce**
1. Start Tempo v2.1.1 in monolithic mode with 3 instances (running on AWS graviton instances, so using ARM Docker image)
2. Ingest a trace over OTLP/HTTP via OpenTelemetry (we're using Python to do this through setting up the post_fork hook in Gunicorn)
3. Search for the trace by service name in the Search tab on Grafana
4. See the trace in the list, click on its ID
5. The details pane opens to the right but comes back with a 404 error.

![image](https://github.com/grafana/tempo/assets/22327045/6b2bc55f-5f97-45ba-bc20-a4e69d1a4752)

> failed to get trace with id: c68230d7c5d365a362fe4f08c8a9f346 Status: 404 Not Found Body: trace not found

**Expected behavior**
As soon as the trace is ingested it should be available for querying.

**Environment:**
 - Infrastructure: Kubernetes v1.26 (EKS)
 - Deployment tool: helm via the CDK stack we use to deploy the cluster itself (we're using the `tempo` chart with chart version `1.3.1`)

**Additional Context**
I get a lot of messages like this in the logs:
```
level=info ts=2023-07-13T14:40:33.642503138Z caller=tempodb.go:332 org_id=[redacted] msg="searching for trace in block" findTraceID=c68230d7c5d365a362fe4f08c8a9f346 block=8593f0d8-dd03-4277-82a7-109baad33da4 found=false
```
Followed by:
```
level=info ts=2023-07-13T14:40:33.664407886Z caller=handler.go:124 tenant=[redacted] method=GET traceID=018d028be59f3b8c url=/api/traces/c68230d7c5d365a362fe4f08c8a9f346 duration=199.861982ms response_size=0 status=404
```

Our only config changes from the Helm chart (`grafana/tempo`) defaults are:
- Enabling multitenancy
- Using S3 for object storage (nothing special here, using IAM service account roles in EKS to provide perms to buckets)
- Enabling the metrics generator with remote write to our Mimir instance

**Comment by joe-elliott** [comment]
So a given trace should be available for querying by trace id immediately after ingestion. Traces are not available for retrieval via TraceQL until 10 or so seconds after spans stop coming in.

I'm surprised you're seeing such a large gap between ingestion and ability to find it via id. I find it even stranger that you are able to find these by searching for them and then they are not retrievable by id.

> Start Tempo v2.1.1 in monolithic mode with 3 instances

Oh, here we are. So the single binary helm chart does not support horizontal scaling. We do have the concept of "scalable-single-binary", but it's not as well tested as the fully distributed setup.

If you expect to need to scale various components my advice would be to attempt the `tempo-distributed` helm chart.

**Comment by hbjydev** [comment]
Ah, gotcha. Thank you for that. I'll test again on Monday.

If that's the case, there should probably be a warning log on boot or even a crash to validate that `ring` config is not present if the target isn't set (or is set to `all`)?

**Comment by joe-elliott** [comment]
> If that's the case, there should probably be a warning log on boot or even a crash to validate that ring config is not present if the target isn't set (or is set to all)?

Yeah. I agree with this. We do have config checking functionality here: https://github.com/grafana/tempo/blob/main/cmd/tempo/app/config.go#L138

This just warns but it's better than nothing. I think logging an error and exiting would also make sense.

**Comment by joe-elliott** [comment]
It looks like we already override ring config if target is set to single binary:

https://github.com/grafana/tempo/blob/d5b5338dc7ed6f49633e5f22f22c56a3447f3f0a/cmd/tempo/main.go#L198

**Comment by hbjydev** [comment]
Hi there :)

This is sorted out for me, switched to the -distributed chart. Thanks @joe-elliott
