### ISSUE TITLE
Make status message searchable in TraceQL

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2655]
Span status code is already searchable using the following statements:

```
{ status = ok }
{ status = error }
{ status = unset }
```

However the status message is not:

https://github.com/open-telemetry/opentelemetry-proto/blob/afcd2aa7f728216d5891ffc0d83f09f0278a6611/opentelemetry/proto/trace/v1/trace.proto#L260

Add support for status message.

**Comment by mdisibio** [comment]
This should be as simple as a new string intrinsic pointed at the column.  `statusMessage` is an obvious choice for naming.

**Comment by Bruno-DaSilva** [comment]
FYI The StatusCode enum is searchable (ok/error/unset) but the `status.code` (type int) field is not.

**Comment by Bruno-DaSilva** [comment]
Ah sorry i thought there was an additional status.code field on top of the enum, whoops. Yes just message is needed :)
