### ISSUE TITLE
TraceQL: Support Parent and Ancestor structural operators

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2670]
Currently TraceQL supports descendant `>>` and child `>` operators. These operators are evaluated on two spansets and return the spans from the right hand side. i.e. `{ span.http.target = "/customers" } >> { status = error }` returns spans with the error status below the `span.http.target` endpoint.

However, it might be useful to find all `/customer` spans that have errors somewhere beneath them. This is not possible with the current operators but could be acheived using something like:

`{ status = error } << { span.http.target = "/customers" }`

By reversing the operator we keep the behavior that structural operators always return spans from the right hand side. We also retain the meaning of the direction of the arrow and count of arrows.

Ancestor:
```
{} << {}
```

Parent
```
{} < {}
```

**Comment by 09jvilla** [comment]
To clarify the example...
```
{ status = error } << { span.http.target = "/customers" }
```

This will match the same set of traces as 
```
{ span.http.target = "/customers" } >> { status = error }
```

But the span set for those matched traces would be different? In the first case, the span set would be spans with `{ span.http.target = "/customers" }` and in the second case, the span set would be spans with ` { status = error }`?

**Comment by joe-elliott** [comment]
Yes. In all structural operator cases we are returning spans from the RHS only for consistency. Your example is correct.

**Comment by kousikmitra** [comment]
I am working on this, please let me know if anyone else has picked it up.
