### ISSUE TITLE
Query frontend drops requests when rolling

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2672]
When rolling the query frontend it drops queries resulting in Grafana errors. There are a lot of details to check here. Does the query frontend correctly drain queries? do we have our k8s config correct to give it time to finish? do we drop readiness while shutting down so queries are no longer routed to a shutting down pod? etc.

Make this as seamless as possible

**Comment by ie-pham** [comment]
Reproduced in dev-01 with only one query-frontend pod. Executed the query then immediately delete pod.
![Uploading Screenshot 2023-09-06 at 9.56.05 AM.png…]()

**Comment by knylander-grafana** [comment]
@joe-elliott Will we need docs of any type for this?

**Comment by joe-elliott** [comment]
Probably not? I suppose it depends on the fix

**Comment by knylander-grafana** [comment]
Confirmed with Joe that most likely won't need docs for this, however it does depend upon the fix.

**Comment by joe-elliott** [comment]
This PR will likely allow configurations to correct this issue: 

https://github.com/grafana/tempo/pull/3395

If a valid configuration cannot be found will reopen
