### ISSUE TITLE
Tempo on GKE does not have the option for structured logging

### ISSUE THREAD

**Issue by GeiserX** [grafana/tempo#2693]
**Describe the bug**
![Screenshot 2023-07-25 at 15 41 57](https://github.com/grafana/tempo/assets/9169332/ecdf70cf-7180-4f55-86a7-1a6cffc42a61)
Logs appear with the wrong severity level

**To Reproduce**
Deploy Tempo on GKE

**Expected behavior**
It seems confusing that the stderr and stdout are being disorderly managed, when in fact the severity of the errors are different from how it appear in the Logging console.

**Environment:**
 - Infrastructure: GKE
 - Deployment tool: Helm

**Additional Context**

**Comment by joe-elliott** [comment]
I do not know much about GKE logging. Obviously we use `logfmt` by default and it is our preferred structured logging format. I assume GKE does not support that?

You can try json logging by setting:
```
server:
  log_format: json
```
