### ISSUE TITLE
Sort options in tracing/Temp

### ISSUE THREAD

**Issue by ravish37** [grafana/tempo#2701]
**Is your feature request related to a problem? Please describe.**
Would like to see multiple sort options while looking at traces. Most importantly by time ( say last N hours)

**Describe the solution you'd like**
As mentioned above.

**Describe alternatives you've considered**

**Additional context**

**Comment by joe-elliott** [comment]
Is your request the same as this one: https://github.com/grafana/tempo/issues/2659 ?
