### ISSUE TITLE
Ingester : Creates block in backend with startTime and endTime not within the range of trace start time.

### ISSUE THREAD

**Issue by sagarwala** [grafana/tempo#2704]
**Describe the bug**
I recently noticed an issue - during high load, distributors got restarted, and the traces that got persisted during the window had a weird behaviour. Example - A trace had one span with startTime as 1690224429542000000 (24 July 2023 18:47 UTC) but the block that got created in the backend (s3 in our case) with this trace had meta.json with startTime as 2023-07-24T19:03:00Z and endTime as 2023-07-24T19:09:28Z. 

When we use /api/traces/{trace-id} on query frontend, it was able to fetch the traces and we were able to find the block id from logs. However, if we use the same API by providing the start and end parameters, the API returned 404 since the block's startTime and endTime were different from the actual trace time. 

**To Reproduce**
1. Start Tempo. We are running grafana/tempo:1.4,1; other versions may be affected.
2. Ingest traces at high load causing restart on the distributor. 
3. Attempt to search for the trace by providing the start and end parameters as per the trace's time.

**Expected behavior**
It is expected that the traces get persisted within blocks that match the start and end time of the trace.

**Environment:**
Infrastructure: We run Tempo in a large Kubernetes cluster on AWS.

**Comment by joe-elliott** [comment]
Oh wow. Tempo 1.4.1 is really reaching back :). I can't say I know exactly how things behaved then, but I will show you how they work now. I don't think they've changed much.

When we append the trace to the headblock:

https://github.com/grafana/tempo/blob/9f26cbcde651828227ebb24dbf6240066fc777ae/modules/ingester/instance.go#L539C26-L539C26

We adjust the time of the trace to account for "ingestion slack" before we modify the meta:

https://github.com/grafana/tempo/blob/9f26cbcde651828227ebb24dbf6240066fc777ae/tempodb/encoding/vparquet3/wal_block.go#L326C17-L326C40f

The reason we do this is b/c tracing data is often dirty and someone out there is sending empty timestamps and someone is sending timestamps 200 years in the future.

If an adjustment is made we increment a metric. You could check if this changed during the time:
```
tempo_warnings_total{reason="outside_ingestion_time_slack"}
```

The slack is controlled by this config option (defaults to 2m):

https://github.com/grafana/tempo/blob/9f26cbcde651828227ebb24dbf6240066fc777ae/tempodb/wal/wal.go#L35

And now for the gnarly part. When we replay the wal we pass in the max block duration as "additional slack time". This extends the `2m` so when we rebuild the block meta it will allow for a larger time range. This honestly could be done better and is the only part of this process that I really dislike.

https://github.com/grafana/tempo/blob/9f26cbcde651828227ebb24dbf6240066fc777ae/modules/ingester/ingester.go#L354

**Comment by sagarwala** [comment]
Thanks for the pointers @joe-elliott . If we do the adjustment of time in order to account for dirty input in tracing data, should we add checks on the start time and end time of the trace to make sure it is not empty or an invalid input before adjusting the time: https://github.com/grafana/tempo/blob/9f26cbcde651828227ebb24dbf6240066fc777ae/modules/ingester/instance.go#L539C26-L539C26

The drawback would still be, when we replay the wal, if the block is older than the max block duration, it would get dropped. But on the query by trace ID side, we would be either seeing 404s or get the trace by ID in correct ranges.  What do you think?

**Comment by joe-elliott** [comment]
> should we add checks on the start time and end time of the trace to make sure it is not empty or an invalid input before adjusting the time:

We do have checks before adjusting the block meta time. To be clear we don't modify the span data. The linked code above only impacts how the block meta is updated.

It's difficult to define what an "invalid" start/end time for a span is. That is why we have this configurable ingestion slack time. So the operator can define for their cluster what invalid means. Anything outside slack is not used to adjust the block meta.

> The drawback would still be, when we replay the wal, if the block is older than the max block duration, it would get dropped. But on the query by trace ID side, we would be either seeing 404s or get the trace by ID in correct ranges. What do you think?

It's not clear to me what you are proposing. This logic could use some improvement so I would gladly take some thoughts.
