### ISSUE TITLE
Tempo not correctly assigning the ServiceAccount for GCS

### ISSUE THREAD

**Issue by GeiserX** [grafana/tempo#2709]
**Describe the bug**
I am deploying Tempo with Workload Identity (WI) on GKE.

I have deployed WI successfully on other parts of the cluster, and I can verify the Kubernetes ServiceAccount is working through this method: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#verify_the_setup and using the offered-by-google tool "Policy Analyzer" I can successfully check that the Google Service Acccount has all the bindings and roles needed to acquire the role of ObjectAdmin in the bucket.

I also can see in the pod definition that the ServiceAccount is correctly set on the Pod, but somehow, I still keep getting on the `ingester` pod (Also on `compactor`, `querier` and `query-frontend`):
```
{"caller":"main.go:105","err":"failed to init module services error initialising module: store: failed to create store getting bucket attrs: googleapi: Error 403: grafana-tempo@xxx.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden","level":"error","msg":"error running Tempo","ts":"2023-07-26T14:23:44.241092969Z"}
```
The bucket is empty, as well.

**To Reproduce**
- Install GKE and use Workload Identity to authorize the ServiceAccount.

**Expected behavior**
Tempo to work

**Environment:**
 - Infrastructure: GKE
 - Deployment tool: Helm

**Additional Context**

**Comment by GeiserX** [comment]
Additionally, I have to create the Kubernetes ServiceAccount through terraform given the fact that it's not possible to add annotations to it via the Helm chart (for the WI to work, `"iam.gke.io/gcp-service-account" = "${google_service_account.tempo_sa.email}"`) which would be more desirable.

**Comment by TaylorMutch** [comment]
You likely need to use the Storage Admin role on the bucket. The permission `storage.buckets.get` is not granted as part of Object Admin, which is what Tempo needs to find the bucket in GCS.

So try granting storage admin role on the bucket and see if that solves it.

**Comment by GeiserX** [comment]
It is working now. Thanks for your support!
