### ISSUE TITLE
Make vParquet3 the default

### ISSUE THREAD

**Issue by stoewer** [grafana/tempo#2721]
Make vParquet3 the default encoding for Tempo

- [ ] Tempo uses vParquet3 by default 
- [ ] Update documentation: just write vParquet3 everywhere where vParquet2 is mentioned as a default (mostly the [configuration section](https://grafana.com/docs/tempo/latest/configuration/))

**Comment by knylander-grafana** [comment]
Instructions for Parquetv3 to enable it: https://grafana.com/docs/tempo/next/configuration/parquet/
* We need to update to make it the default
* Configuration section: 

Dedicated columns: 
* Basic content: https://grafana.com/docs/tempo/next/operations/dedicated_columns/

**Comment by knylander-grafana** [comment]
The benefits and wowo-factor of v3 would be a great blog post.
