### ISSUE TITLE
Storage S3 - AWS node role IMDSv1 does not work after upgrade to v2.2

### ISSUE THREAD

**Issue by coufalja** [grafana/tempo#2743]
**Describe the bug**
Tempo does not start with "transparent" AWS credentials (node role). It seems to not take the credentials/role into account at all.

**To Reproduce**
1. Start from tempo-distributed chart
2. Use node role credentials to connect to S3
3. Fail with `"err":"failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on <bucket name>: Access Denied"`

**Expected behavior**
Tempo connects and starts.

**Environment:**
 - Kubernetes
 - Helm chart tempo-distributed >=1.5.3

**Additional Context**
- Just downgrading image version while using the very same config fixes the problem, so must be code or image related issue.
- I also though about missing some niche permission in the attached policy so I temporarily granted `*` to the node role but no joy.

**Comment by joe-elliott** [comment]
I'm not seeing much changes to the s3 backend. 

Prefix Support: https://github.com/grafana/tempo/commit/a55da8161dc864d2c824e97020a8c9ddf45fa854

Standardized TLS config: https://github.com/grafana/tempo/commit/e809ae607a

Updated minio: https://github.com/grafana/tempo/commit/e9898effad

The first two seem innocuous. WDYT? The minio changes are here:

https://github.com/minio/minio-go/compare/v7.0.23...v7.0.52

If it's possible to test image versions immediately before some of these changes it could help us narrow down the issue. We could also try just upgrading minio again and see if it fixes it.

**Comment by coufalja** [comment]
So it is the minio upgrade. Image `grafana/tempo:main-9996433-amd64` works, the `docker.io/grafana/tempo:main-e9898ef-amd64` does not.

**Comment by joe-elliott** [comment]
Nothing really stands out in the minio changelog. Can you file an issue here:

https://github.com/minio/minio-go

Detailing your auth setup and see if they have insight into what may have changed?

**Comment by coufalja** [comment]
I have found the culprit: [Use 1s timeout for fetching imdsv2 token](https://github.com/minio/minio-go/pull/1626) introduced in v7.0.24.

**Comment by coufalja** [comment]
Seems to me as issue in Tempo that surfaced in due to 2 bugfixes made in mino lib: https://github.com/minio/minio-go/pull/1626 and https://github.com/minio/minio-go/pull/1682

**Comment by coufalja** [comment]
I backported the Cortex fix in #2760

**Comment by joe-elliott** [comment]
Excellent research and fix, @coufalja. Thank you.
