### ISSUE TITLE
Bundle tempo-query as part of tempo single-binary

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#275]
**Is your feature request related to a problem? Please describe.**

Right now, even with the Tempo single-binary, we need a tempo-query container to visualise traces in the Jaeger UI. 

**Describe the solution you'd like**

It would be nice to bundle the query components into the single-binary setup at some point and serve the query assets through the querier.

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by daixiang0** [comment]
Do you mean add subcmd like `query` for tempo?

**Comment by joe-elliott** [comment]
This will require bundling the Jaeger UI in the container for Tempo to load, but I don't think we're going to want that in our default image.  Perhaps we build a special "single binary" container that also has the UI?

Some research needs to be done before moving forward with this one.

**Comment by annanay25** [comment]
Yup, need some research for this feature. I agree we probably want a separate "single-binary" image to avoid bloating the size of our default images.

**Comment by morlay** [comment]
@annanay25 
 
check `cmd/tempo-query/Dockerfile` https://github.com/grafana/tempo/pull/305/files

```bash
# added jaeger-ui as submodule

# build ui assets to jaeger-ui/packages/jaeger-ui/build jaeger-ui/packages/jaeger-ui/build
# need node & yarn
cd jaeger-ui &&  yarn install --frozen-lockfile && cd packages/jaeger-ui && yarn build

# then install esc for gen assets to files.
go get -u github.com/mjibson/esc


# generate go files
esc -pkg assets -o cmd/tempo-query/ui/gen_assets.go -prefix jaeger-ui/packages/jaeger-ui/build jaeger-ui/packages/jaeger-ui/build

# edit go.mod
replace (
   "github.com/jaegertracing/jaeger/cmd/query/app/ui/actual" => cmd/tempo-query/ui
) 
```
now could import `github.com/jaegertracing/jaeger/cmd/query/*` in `cmd/tempo-query/main.go`
