### ISSUE TITLE
Error decoding trace while using tempo-cli

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#276]
**Describe the bug**
When I use tempo-cli to get a trace result in JSON, I get the following error:
```
➜  tempo git:(master) ✗ go run cmd/tempo-cli/main.go -query-endpoint http://localhost:16686 -traceID 354312a7d925cb70 -orgID 1
error querying tempo, err: error decoding trace json, err: unknown field "errors" in tempopb.Trace, traceID: 354312a7d925cb70
➜  tempo git:(master) ✗ go run cmd/tempo-cli/main.go -query-endpoint http://localhost:16686 -traceID 354312a7d925cb70 -orgID 1
error querying tempo, err: error decoding trace json, err: unknown field "data" in tempopb.Trace, traceID: 354312a7d925cb70
➜  tempo git:(master) ✗ go run cmd/tempo-cli/main.go -query-endpoint http://localhost:16686 -traceID 354312a7d925cb70 -orgID 1
error querying tempo, err: error decoding trace json, err: unknown field "offset" in tempopb.Trace, traceID: 354312a7d925cb70
```

**To Reproduce**
1. Run the [local storage](https://github.com/grafana/tempo/tree/master/example/docker-compose#local-storage) docker-compose example.
2. Pick a traceID generated by the synthetic-load-generator.
3. Run: `go run cmd/tempo-cli/main.go -query-endpoint http://localhost:<tempo-query-port> -traceID <trace-id> -orgID 1`

**Expected behavior**
Well, I would like to see the trace in JSON format.

**Environment:**
 - Infrastructure: Laptop
 - Deployment tool: Docker Compose

**Additional Context**
On [QueryTrace()](https://github.com/grafana/tempo/blob/59fa11648add3d0c9680a29600657942d02660ad/pkg/util/query.go#L35), if I print the `resp.Body` before Unmarshal I can see my trace! I think the problem is that the JSON API returns:
```
{
  data: "...",
  total: 0,
  limit: 0,
  offset: 0
}
```
And those fields are "unexpected" when Tempo unmarshals them.

**Comment by annanay25** [comment]
Hi @dgzlopes; thanks for filing this issue! Would you like to submit a PR to fix this?

**Comment by annanay25** [comment]
Actually I just tried this and it worked for me. 

I see now, the docs are slightly confusing we need to connect to the http endpoint of the tempo container, so for `<tempo-query-port>`, if you use the port exposed by the `docker-compose_tempo_1` port (which connects to `3100`) it works.

```
docker-compose -f docker-compose.local.yaml ps
           Name                         Command             State             Ports
----------------------------------------------------------------------------------------------
docker-compose_grafana_1      /run.sh                       Up      0.0.0.0:3000->3000/tcp
docker-compose_prometheus_1   /bin/prometheus --config.f    Up      0.0.0.0:9090->9090/tcp
                              ...
docker-compose_synthetic-     ./start.sh                    Up
load-generator_1
docker-compose_tempo-         /go/bin/query-linux --grpc    Up      0.0.0.0:16686->16686/tcp
query_1                       ...
docker-compose_tempo_1        /tempo -storage.trace.back    Up      0.0.0.0:32777->14268/tcp,
                              ...                                   0.0.0.0:32778->3100/tcp
```

```
go run cmd/tempo-cli/main.go -query-endpoint http://localhost:32778 -traceID 74fa9d2f4ef31586 -orgID 1

{"batches":[{"resource":{"attributes":[{"key":"service.name"....}
```

**Comment by dgzlopes** [comment]
Thanks for the quick response @annanay25!

Tried using the Tempo port, and it worked. Also, the `-query-endpoint` flag was a little confusing for me.

btw, I miss some structure on tempo-cli. Coming from logcli, I expected some kind of command-based-structure (e.g query, tools). I'm happy to create a new issue to track the improvements and to contribute wherever I can.

Closing this :)

**Comment by annanay25** [comment]
No problem :)

Thanks for your feedback, I agree with you @dgzlopes. Right now `tempo-cli` is a utility we stitched together for debugging purposes and we definitely plan on extended its functionality as we go. Feel free to create an issue to track improvements to the tool, and we can add to it as we go.
