### ISSUE TITLE
Tempo Compactor using excessive amounts of memory sporadically

### ISSUE THREAD

**Issue by jlcrow** [grafana/tempo#2769]
**Describe the bug**
Tempo Compactor randomly starts using excessive amounts of memory, so it's impossible to apply reasonable cost effective limits in Kubernetes.  On GKE, using Google Storage as backend The majority of time the tempo compactor uses around 5GB of memory, however I've seen it burst to as much as 27GB of memory which causes it to be killed by memory limits defined. Is it possible to run without the compactor? I've tried applying a GOMEMLIMIT environment variable and ended up with excessive amounts of CPU being consumed trying to keep up with GC and very little impact on CPU. I've tried running multiple copies of the compactor, which they all just consume huge amounts of memory, I've had this issue in last 2 versions of Tempo 2.1.x and 2.2, wasn't happening previously.

<img width="1702" alt="image" src="https://github.com/grafana/tempo/assets/4369807/33c9532d-7e78-447b-9e6c-52d365b1c248">

**To Reproduce**
1. Run Tempo Distributed 2.2.0 using chart tempo-distributed-1.6.0
2. Ingest traces to Google Storage as backend
3. Compactor randomly obtains excessive memory and killed by limits in Kubernetes

**Expected behavior**
1. consistent/predictable memory usage

**Environment:**
 - Infrastructure: GKE
 - Deployment tool: Helm

**Additional Context**
---- values.yaml ----
```
fullnameOverride: tempo

tempo:
  podLabels:
    app: tempo


rbac:
  create: true

# Configuration for the ingester
ingester:
  replicas: 8
  autoscaling:
    enabled: true
    minReplicas: 8
    maxReplicas: 18
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 75
  resources:
    requests:
      cpu: 1
      memory: 10Gi
    limits:
      cpu: 2
      memory: 10Gi
  persistence:
    enabled: true
    size: 100Gi
    storageClass: fast-persist

# Configuration for the metrics-generator
metricsGenerator:
  enabled: true
  replicas: 4
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi
      
  config:    
    storage:
      path: /var/tempo/wal
      wal:
      remote_write_flush_deadline: 1m    
      remote_write:
        - url: https://trace-metrics/api/v1/push


# Configuration for the distributor
distributor:
  replicas: 8

  autoscaling:
    enabled: true
    minReplicas: 8
    maxReplicas: 18
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 75
  resources:
    requests:
      cpu: 100m
      memory: 3Gi
    limits:
      memory: 3Gi

compactor:
  replicas: 3
  resources:
    requests:
      cpu: "700m"
      memory: "6Gi"
    limits:
      cpu: 2
      memory: "6Gi"

# Configuration for the querier
querier:
  replicas: 4
  resources:
    requests:
      cpu: 100m
      memory: 6Gi
    limits:
      memory: 6Gi  
  config:
    frontend_worker:
      # -- grpc client configuration
      grpc_client_config:
        max_recv_msg_size: 9e+07
        max_send_msg_size: 9e+07      
    trace_by_id:
      # -- Timeout for trace lookup requests
      query_timeout: 10s
    search:
      # -- A list of external endpoints that the querier will use to offload backend search requests
      external_endpoints: []
      # -- Timeout for search requests
      query_timeout: 30s
      # -- If search_external_endpoints is set then the querier will primarily act as a proxy for whatever serverless backend you have configured. This setting allows the operator to have the querier prefer itself for a configurable number of subqueries.
      prefer_self: 10
      # -- If set to a non-zero value a second request will be issued at the provided duration. Recommended to be set to p99 of external search requests to reduce long tail latency.
      external_hedge_requests_at: 8s
      # -- The maximum number of requests to execute when hedging. Requires hedge_requests_at to be set.
      external_hedge_requests_up_to: 2
    # -- This value controls the overall number of simultaneous subqueries that the querier will service at once. It does not distinguish between the types of queries.
    max_concurrent_queries: 20

# Configuration for the query-frontend
queryFrontend:
  query:
    enabled: false  
  replicas: 4
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 75
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 2Gi

traces:
  otlp:
    grpc:
      enabled: true
      receiverConfig: {}

# Set Tempo server configuration
# Refers to https://grafana.com/docs/tempo/latest/configuration/#server
server:
  # --  HTTP server listen host
  httpListenPort: 3100
  # -- Log level. Can be set to trace, debug, info (default), warn, error, fatal, panic
  logLevel: warn
  # -- Log format. Can be set to logfmt (default) or json.
  logFormat: logfmt
  # -- Max gRPC message size that can be received
  grpc_server_max_recv_msg_size: 1.048576e+08
  # -- Max gRPC message size that can be sent
  grpc_server_max_send_msg_size: 1.048576e+08

# To configure a different storage backend instead of local storage:
# storage:
#   trace:
#     backend: azure
#     azure:
#       container-name:
#       storage-account-name:
#       storage-account-key:
storage:
  trace:
    backend: gcs
    gcs:
      bucket_name: staging-tempo-twm

# Global overrides
global_overrides:
  ingestion_rate_strategy: local
  ingestion_rate_limit_bytes: 30000000
  max_traces_per_user: 0
  max_bytes_per_trace: 0
  metrics_generator_processors:
    - service-graphs
    - span-metrics 

# memcached is for all of the Tempo pieces to coordinate with each other.
# you can use your self memcacherd by set enable: false and host + service
memcached:
  resources:
    requests:
      cpu: 1
      memory: 500Mi
    limits:
      cpu: 2
      memory: 1Gi
```

**Comment by pingping95** [comment]
Same problem

**Comment by joe-elliott** [comment]
It seems you are using `GOMEMLIMIT` which would be my first recommendation for anyone stumbling on this issue. My second recommendation would be to impose a max trace size on you users. In our experience large spikes in compactor memory usage occur when attempting to combine very large traces.

This is the Tempo config:
```
overrides:
  max_bytes_per_trace: <int>
```

I'm not super familiar with Helm but perhaps it is:
```
global_overrides:
  max_bytes_per_trace: <int>
```

If that doesn't work a heap dump would help us determine what is consuming memory.

> Is it possible to run without the compactor? 

Compactors have two important jobs. One is to build the tenant index which helps reduce TCO b/c then only one component has to poll all of the backend blocks. The second is to reduce the blocklist length for trace by id search and total data for traceql. I do believe it would be possible to run without compactors, but it would likely only work for smaller clusters.

**Comment by jlcrow** [comment]
@joe-elliott Thanks for responding. I actually ended up removing GOMEMLIMIT as it caused very excessive CPU and didn't really stop the memory issue.  I'm sure our traces are pretty large, we actually remove the limit in our config by passing a 0 for that override because so many traces were just being dropped, our traces span several systems and include service and database calls. Doesn't imposing a max trace size kind of reduce the usefulness of the tool?  Are there tuning capabilities on the compactor to deal with the larger traces without avoiding ingesting them?

**Comment by aptomaKetil** [comment]
@jlcrow We've had the same problem, our issue turned out to be excessively large attribute values attached to spans. Adding truncation of attribute values above a max length (in the OTEL collector) solved the issue for us.

**Comment by pingping95** [comment]
@aptomaKetil

Could you provide a url how to do that in OTEL Collector ?

**Comment by aptomaKetil** [comment]
@pingping95 

Abridged:

```yaml
processors:
  transform/truncate:
    trace_statements:
      - context: resource
        statements:
          - limit(attributes, 50, [])
          - truncate_all(attributes, 512)
      - context: span
        statements:
          - limit(attributes, 50, [])
          - truncate_all(attributes, 512)
service:
  pipelines:
    traces:
      processors:
        - transform/truncate
```

**Comment by suraciii** [comment]
Hi @joe-elliott , We have the same issue, after we decreased `max_bytes_per_trace`, many `TRACE_TOO_LARGE` errors raises by tempo, and that errors cause opentelemetry-collector export failed.
> {"level":"error","ts":1693969322.7219872,"caller":"exporterhelper/queued_retry.go:391","msg":"Exporting failed. The error is not retryable. Dropping data.","kind":"exporter","data_type":"traces","name":"otlp/tempo","error":"Permanent error: rpc error: code = FailedPrecondition desc = TRACE_TOO_LARGE: max size of trace (3000000) exceeded while adding 40488 bytes to trace 00000000000000008097242a47649e55 for tenant flprod","dropped_items":339,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send\n\tgo.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:391\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send\n\tgo.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/traces.go:126\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1\n\tgo.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:195\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1\n\tgo.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/internal/bounded_memory_queue.go:47"}

Is there any way to let tempo just discard these invalid spans instead of raising errors?

**Comment by joe-elliott** [comment]
> Is there any way to let tempo just discard these invalid spans instead of raising errors?

@suraciii we are working on a PR right now that will return 200/OK in the event of trace to large instead of FailedPrecondition.

https://github.com/grafana/tempo/pull/2571

is this what you're looking for?

**Comment by suraciii** [comment]
> > Is there any way to let tempo just discard these invalid spans instead of raising errors?
> 
> @suraciii we are working on a PR right now that will return 200/OK in the event of trace to large instead of FailedPrecondition.
> 
> #2571
> 
> is this what you're looking for?

Yes, and it's better than what I expected, thanks for the information :)
