### ISSUE TITLE
How to get trace names of too big traces?

### ISSUE THREAD

**Issue by MarcinGinszt** [grafana/tempo#2776]
When spans are failing because of their huge size, I don't know how can I check which spans are that, as it is impossible to retrieve them from Tempo. 

Tempo-compactor logs:
```
compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=<trace-id> discarded_span_count=<count>
```
When I'm using the traceID to look for span in tempo, I'm getting the response: 
```
failed to get trace with id: <id> Status: 500 Internal Server Error Body: response larger than the max (<size> vs <size>)
```

It would be great if tempo-compactor could log the span name.  Or, is there other way to get the span information, without tweaking my settings? 

Thanks a lot for your time and sorry if it's newbie question.

**Comment by joe-elliott** [comment]
> It would be great if tempo-compactor could log the span name. Or, is there other way to get the span information, without tweaking my settings?

In general I'd say we'd want to default to minimal logging in this case. However, for debugging purposes or at a smaller scale it could be quite useful to log some additional info about the dropped spans. Unfortunately this might be a bit tough to do. We purposefully don't "Construct" the trace from the parquet row in this case b/c it's quite costly.

https://github.com/grafana/tempo/blob/42a0d6dcfdb64603e9c212f61cc139712384ed93/tempodb/encoding/vparquet2/compactor.go#L105C13-L105C27

Technically span names can be pulled from the parquet row directly, but it's ugly. Give it a try :). I'd be willing to add this logging at the debug level if you (or anyone else) wanted to give it a shot.

Look at the `countSpans()` function to see how you can pull some info from the row without completely Constructing it.

https://github.com/grafana/tempo/blob/42a0d6dcfdb64603e9c212f61cc139712384ed93/tempodb/encoding/vparquet2/compactor.go#L320

> When I'm using the traceID to look for span in tempo, I'm getting the response:

This is likely b/c the trace is quite large (hence some spans refused). See if this helps: https://grafana.com/docs/tempo/latest/operations/troubleshooting/response-too-large/

> Thanks a lot for your time and sorry if it's newbie question.

No problem at all. Thanks for your interest Tempo.

**Comment by MarcinGinszt** [comment]
Hey @joe-elliott thanks a lot for your response! I'll try to create PR this week.
