### ISSUE TITLE
Allow to fetch tags for more than the duration of complete_block_timeout

### ISSUE THREAD

**Issue by rubenvp8510** [grafana/tempo#2780]
**Is your feature request related to a problem? Please describe.**

At present, tags are sourced from the Ingesters. However, this approach poses a challenge due to the inherent limitation tied to the maximum lifespan of these tags, which is determined by the `complete_block_timeout` parameter. 

To illustrate, if traces containing certain value , for example  `service.name = frontend,`  not received within the timeframe defined by the `complete_block_timeout`, the corresponding tag becomes inaccessible.

 This becomes a concern as certain UIs that depends on the list of services for doing the search, specifically I can mention the Jaeger UI plugin.

**Describe the solution you'd like**

One viable approach to address this issue involves extending the tag search functionality to the storage backend. We can use a time range so don't need to scan all blocks. This still have the issue that we only be able to select the tags for certain amount of time, but at least we don't depend on a short period time set on `complete_block_timeout`  or we are not forced to set that configuration to a large value

**Describe alternatives you've considered**

We can implement a separate tag storage and may be with this we will be able to fetch them efficient. I'm still learning the internal of tempo but this seems to not be a good idea, because I think this will impact other areas like retention, compaction etc..

**Comment by joe-elliott** [comment]
Does this issue cover your request: https://github.com/grafana/tempo/issues/1705

To give an update, we are currently focused on two things before we attempt to tackle this.

- Filtering tags by other tags in the query. i.e. `{ span.foo = "bar" && span.baz = ?? ` In this case we'd like to return only values for baz where `foo = "bar"`
- Some kind of page level caching. Pulling the data from the backend for a tags query can get quite expensive. We intend to look at page level caching to reduce this cost which will make this feature more tenable.
