### ISSUE TITLE
Enforce limitations on parquet trace by id queries

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2794]
The v2 format enforces `max_bytes_per_trace` on query to prevent OOMs in the query path. The vParquet* formats has no such equivalents and we have seen OOMs when very large traces (100s of MBs) are requested.

Enforce `max_bytes_per_trace` in the vParquet* formats when doing a trace by id lookup OR build equivalent limitations for vParquet. The challenge is that the size of a trace in bytes used to be enforced on the proto size which was trivial to calculate in v2, but impossible to calculate in vParquet. We have [various](https://github.com/grafana/tempo/blob/12bdeff1d7ee726f703914cd43b9fd3c2d55a3b1/tempodb/encoding/vparquet3/compactor.go#L293) [hacky](https://github.com/grafana/tempo/blob/12bdeff1d7ee726f703914cd43b9fd3c2d55a3b1/tempodb/encoding/vparquet3/compactor.go#L314C6-L314C42) [attempts](https://github.com/grafana/tempo/blob/12bdeff1d7ee726f703914cd43b9fd3c2d55a3b1/tempodb/encoding/vparquet3/create.go#L239) to calculate sizes, but none of them are great.

It's possible that simply applying some combination of existing estimates against the per tenant max_bytes_per_trace will be sufficient and should be attempted. It's also possible that new limitations specific to vParquet will be required.

Also consider profiling trace by id lookup to determine if there's any obvious inefficiencies to remove.

**Comment by 09jvilla** [comment]
A Tempo user surfaced to us that when this OOM event happens, all Tempo returns is a generic 'failed to get trace' and 'timeout' error, rather that an error that indicates that the trace that was being fetched was too large. See example screenshot in Grafana:

<img width="1167" alt="Screenshot 2023-08-16 at 9 35 19 PM" src="https://github.com/grafana/tempo/assets/9610816/f3ea1519-2604-449a-ad56-af9aa1aff4d8">


So as part of enforcing these limits, we'll also want to ensure that the error message that gets returned to the user is explicit that a size limit has been hit.

**Comment by stoewer** [comment]
> The challenge is that the size of a trace in bytes used to be enforced on the proto size which was trivial to calculate in v2, but impossible to calculate in vParquet

Would it make sense to add a column for storing the trace size in the next iteration of the vParquet block format?

**Comment by joe-elliott** [comment]
> Would it make sense to add a column for storing the trace size in the next iteration of the vParquet block format?

Possibly. This is WIP but it shows how we can do a pretty good job of enforcing these limits w/o a new field:

https://github.com/grafana/tempo/pull/2935
