### ISSUE TITLE
Add more structure and extend tempo-cli

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#281]
From #276 

Right now `tempo-cli` is a utility for debugging purposes but there are plans to extend its functionality.

Created this issue to track/discuss the improvements of the tool.

**Comment by dgzlopes** [comment]
From my POV, the most pressing issue is the CLI structure. Having some kind of command-based structure (like in Logcli) would make the tool easier to extend and use.

Example:
```
$ tempo-cli query <args>
```

**Comment by joe-elliott** [comment]
Yup, this has come up in internal discussions a few times.  It's just not something anyone has had time to spend on.

**Comment by luisfmelo** [comment]
What kind of structure are we talking about? What capabilities (aka actions) we want to explicitly provide?

**Comment by joe-elliott** [comment]
Currently tempo-cli only does two things: 

- dump all the blocks in your gcs/s3 backend with some basic stats
- query the `/api/traces` endpoint and dump the json

So I suppose it would be nice to make those the two subcommands:

```
./tempo-cli dump-blocks
./tempo-cli query
```
