### ISSUE TITLE
[TraceQL Enhancement] Support Arrays and KVLists

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#2810]
TraceQL currently supports all attributes of primitive type, but it doesn't yet support [array and kvlist attributes](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L31).  Tempo reads and writes these attributes fine, but they are not accessible in TraceQL.  Here is a proposed syntax for working with them.

**Arrays**
Array operations look like this:  `.value[0] = 5`. This query would find all attributes named "value" that are arrays, and check if the first element is an integer equal to 5.   We can check all elements of the array by using empty brackets without an index:  `.value[] = 5`.

More formally: 
`.<attr>[index?] <operation> <operand>`

Brackets denote that we are checking an array attribute.  Array access can be combined with the full range of TraceQL comparison expressions (regexes on strings, >= on integers, duration checks, etc) and boolean logic for very flexible and deep capabilities.   The array index is optional and this is how we indicate if we want to check all elements in the array or a specific index. 

To summarize these are all valid queries:
* `.value[] >= 5` Check for any integer >= 5
* `.value[0] =~ "[0-9A-F]+"` Check if the first element is a hexadecimal-formatted string
* `.value[1] > 1.5` Check if the second element is a float greater than 1.5.
* `.value[] = "foo" || .value[] = "bar"` Combining expressions 

**KVLists**
KVList operations are similar to array operations but use string indexes instead of numeric:  `.value["foo"] = 5`.   KVLists keys are [always strings](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L64).  Parsing rules for keys follows the same rules for quoted attribute names as in #2805 .   In this case the quotes are required and is how we distinguish between the array index `[0]` and the kv-lookup `["0"]`.  KVList operations can be combined with the full range of TraceQL comparison expressions just like arrays described above.

Just like arrays can check all elements or a specific index, so can KVLists.  This is done by using a regex index with the regex operator `~`: `.value[~".*"] = 5`.  Any valid regex can be used so we can check for specific matches or the wildcard regex (`.*`) to check all.

More formally:
`.<attr>[(~?)"<string>"] <operation> <operand>`

These are all valid queries:
* `.value["foo"] = "bar"` Check if the kvlist contains element "foo" and it is the string "bar"
* `.value[~".*"] = 5` Check all elements of the kvlist for the integer 5
* `.value[~"device.*"] =~ "[0-9]+"` Check all entries in the kvlist starting with "device" for non-empty numeric strings and return the matches.

**Additional Notes**
The benefits of this syntax:
* The most common use cases are simple, and the hard things are still possible.  A specific common case in mind is checking [OTEL-compatible http headers](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-request-and-response-headers) recorded through auto-instrumentation for a matching string.  #1789   This query would be `{ span.http.request.headers.<myheader>[] =~ "foo.*"}`  Check all string values of <myheader> for a regex match on `foo.*` and return the matching spans.
* All queries still retain explicit type information, so that the TraceQL engine and Tempo storage layers can optimize access.  For example consider a query like `.value=5`, since 5 is an integer Tempo can optimize access by only checking integer attributes.  Similarly the query `.value[]=5`, Tempo can optimize access by only checking attributes that are arrays and contain integers.

Future thoughts:
* There are probably additional operations on arrays and kvlists that we can think of (like checking the length of an array). If there is a need we can cover that in future proposals.

**Comment by joe-elliott** [comment]
What do you think about the following for lists? Are these valid statements? How should they behave?

```
{ .list1[] = .list2[] }
{ .list1 = .list2 }
```

I assume these work in an obvious way based on your spec above:
```
{ .list1[] = .list2[0] }
{ .list1[0] = .list2[0] }
```

Similarly for kvmaps:
```
{ .kvmap1[~".*"] = .kvmap2[~".*"] }
{ .kvmap1 = .kvmap2 }
```

Should we add a note that nested kvmaps/list combinations are unsupported? (or are they?)

After we do some quick edge case defining, I think we should wrap this and https://github.com/grafana/tempo/issues/2805 up into a PR that adds a doc similar to: https://github.com/grafana/tempo/blob/main/docs/design-proposals/2022-04%20TraceQL%20Concepts.md

**Comment by mdisibio** [comment]
I think most should work as expected:

Equality check, already works for primitive types we just extend to deep compare arrays and maps.
```
.array = .array2
.map   = .map2
.array = 5        // Always false
.map   = 5        // Always false
```

Indexing array[0] or map["foo"] yields a single primitive value and gets compared like expected:
```
.array[]  = .array2[0]     // same as .array[] = 5
.array[0] = .array2[0]     // same as 5 = 5

.map[~".*"] = .map2["bar"] // same as .map[~".*"] = 5
.map["foo"] = .map2["bar"] // same as 5 = 5
```

If it's a nested array/map (!) then it's deep compared like above.  This checks if the map entry is a nested array equal to `.array`. 
```
.map["foo"] = .array
```

These are the queries that I'm not sure about.
```
.array[]    =  .array2[]
.array[]    =~ .array2[]
.map[~".*"] =  .map2[~".*"]
.map[~".*"] =~ .map2[~".*"]
```

Considering the proposed grammar I think there are two options.

1. Pairwise comparison.  .array[] = .array2[] checks if .array contains any element from .array2.   This is a surprisingly powerful use case that wasn't even on the radar.  If I was going to come up with a syntax for this use case, this isn't bad at all and promising that it arose naturally.  The operator could of course be anything (=~, >=, etc)

2. Deep compare.    .array[] = .array2[] could also mean "all elements of .array match all elements of .array2".   Behavior is undefined for all other operators, which starts to seem weird.   `.array[] >= ...` is only valid if right-hand side doesn't have a `[]`.   Also deep compare can already be covered by `.array = .array2`

**Comment by mdisibio** [comment]
Noticing that there's use cases coming together for defining static arrays and maps in queries, like we have for strings/ints/floats/bools.  Just thinking out loud, leaving these examples because I think they help clarify the other ideas.

```
.array = .array2
.array = [1, "foo", true]
```

```
.map = .map2
.map = ["a":1, "b": "foo", "c": true]
```
