### ISSUE TITLE
Connection Resets after updating to 2.2.0

### ISSUE THREAD

**Issue by zackman0010** [grafana/tempo#2814]
**Describe the bug**
After updating my Tempo from 2.1.1 to 2.2.0, I was no longer able to connect to the main HTTP port. It would immediately close the connection before even sending the SSL cert. I attempted to connect from both my local machine and while SSH'd into the server running Tempo. Below are logs from when I tried to connect from my local machine.

```
zsistrunk@IT-45712-MAC ~ % curl https://sl-sitempo1t.corp.wan:8080/ready
curl: (35) Recv failure: Connection reset by peer
zsistrunk@IT-45712-MAC ~ % openssl s_client -connect sl-sitempo1t.corp.wan:8080
CONNECTED(00000005)
write:errno=54
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 323 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**To Reproduce**
1. Start Tempo 2.2.0
2. Attempt to curl /ready endpoint

**Expected behavior**
Able to curl /ready endpoint

**Environment:**
 - Infrastructure: RHEL 8.9 virtual server
 - Deployment tool: N/A (Directly deployed binary)

**Additional Context**
Rolling back to 2.1.1 fixed the issue. If you need any other information, I'll be happy to provide it.

**Comment by mdisibio** [comment]
Hi, sorry about that.  The streaming search changes broke TLS in 2.2.0, and we are including the fix https://github.com/grafana/tempo/pull/2803 in an upcoming patch build 2.2.1, should be next week.

**Comment by zackman0010** [comment]
Great, thanks! I'll stay on 2.1.1 until that's available, then.

**Comment by joe-elliott** [comment]
2.2.1 has been published which should fix this issue:

https://hub.docker.com/layers/grafana/tempo/2.2.1/images/sha256-dbb58d5d4bc27720111b16ab3700fbb22fafac8c8b4cfb0d1ded6862cc9f4124?context=explore

I'm going to close this, but please reopen if you continue to see the problem.

**Comment by zackman0010** [comment]
Just confirming that we no longer see the issue after updating to 2.2.1!
