### ISSUE TITLE
Add app microservices example

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#282]
I think that having some kind of app microservices demo would be great for newcomers to distributed tracing and it would be useful to illustrate how Tempo can be used in the "real-world" (in collab with Grafana and Loki).

Inspiration? The [Jaeger Hot R.O.D demo](https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod)[0]. Maybe that demo can be re-used, and even adapted (in the future) to OpenTelemetry.

 [0] Hot R.O.D is a demo application that consists of several microservices and illustrates the use of the OpenTracing API.

**Comment by dgzlopes** [comment]
I'm happy to take a stab at this 😄

**Comment by joe-elliott** [comment]
Please do!

**Comment by dgzlopes** [comment]
Small question!

Do we prefer one hotrod service with the `all` flag ([reference](https://github.com/jaegertracing/jaeger/blob/ee3bbee410fd5aafba70e428f2e2e319de02d006/examples/hotrod/docker-compose.yml#L10)) or multiple services (e.g: frontend, driver...).

I think having multiple services is better. We get Loki labels out of the box (multiple streams instead of one for all the services) and feels more real.

**Comment by Freakin** [comment]
You could also use Omnition's [Synthetic Load Generator](https://github.com/Omnition/synthetic-load-generator) which has a default topology emulating Google's [Hipster Shop](https://github.com/GoogleCloudPlatform/microservices-demo)

**Comment by dgzlopes** [comment]
Yep! That project is really cool @Freakin. But, Tempo already has [some examples](https://github.com/grafana/tempo/blob/d91c415e5d23919c98586e21da8eda825e3cffd5/example/docker-compose/docker-compose.yaml#L34) with it.

Personally, the first demo I saw of Jaeger (that used HotROD) amazed me. I think it's perfect for newcomers to distributed tracing because it creates the following scenario:
- You've some "real" instrumented microservices.
- Those microservices have issues.
- You find them with Distributed tracing.

And well, I would like to recreate that experience with Grafana's stack 😛

btw, I already have something that works. I'll create a PR later this week.

**Comment by joe-elliott** [comment]
Closing in favor #235
