### ISSUE TITLE
Using Tempo with OpenTelemetry auto-instrumentation

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#283]
OpenTelemetry project is pushing auto-instrumentation. It's interesting because we can gather telemetry data without code changes. 

They are working a lot on the [Python](https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-instrumentation) and [Java](https://github.com/open-telemetry/opentelemetry-java-instrumentation) instrumentation, so they are ready for the GA milestone.

The problem is that, If our code is not aware of the instrumentation, we can't log the TraceIDs required by Tempo. 

Maybe there is a workaround? This should be researched and documented somewhere.

**Comment by dgzlopes** [comment]
Well, if the service has some kind of proxy (e.g envoy as a sidecar) we can log the TraceID. This solution is not ideal as it requires an external dependency.

**Comment by joe-elliott** [comment]
I'm not super familiar with writing services in either of those languages, but I believe that the trace id will be stored/extractable from the context as it is passed through your service.

Having said that I do agree that pursuing an option to automatically do request logging with trace id would be valuable for auto instrumented applications.

**Comment by joe-elliott** [comment]
As reported in slack here are some ways to extract relevant IDs in Java: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/logger-mdc-instrumentation.md

**Comment by dgzlopes** [comment]
I researched the situation of the OTEL Python auto-instrumentation and well, there is no option to inject trace IDs in logs! 

Some "old" auto-instrumentations had this option, like the one that [SignalFX maintained](https://github.com/signalfx/signalfx-python-tracing#inject-trace-ids-in-logs). Here you can see that it's a [known issue](https://github.com/signalfx/splunk-otel-python/blob/main/migration.md#known-issues) with OpenTelemetry (at least for some people).

Given that OpenTelemetry is doing a lot of work on this area, and they want to push it further, maybe it would be interesting to open a feature request on the OTEL Python repo.

**Comment by joe-elliott** [comment]
Here is an otel/java/springboot example: https://github.com/joe-elliott/tempo-springboot-example

**Comment by dgzlopes** [comment]
Feature request on the OpenTelemetry Python project: https://github.com/open-telemetry/opentelemetry-python/issues/1562

**Comment by joe-elliott** [comment]
A few examples of instrumentation (auto and otherwise) available here:

https://github.com/grafana/tempo/blob/master/docs/tempo/website/guides/instrumentation.md
