### ISSUE TITLE
Tempo eating 429s on trace by ID path

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2843]
If the query frontend receives a non 2XX it converts it to a 500 on the trace by id path here:

https://github.com/grafana/tempo/blob/2c05a8782a9b253f3e90d675b32595872c6eb12c/modules/frontend/tracebyidsharding.go#L162

This is currently eating 429s and returning 500 to the client. We need to propagate this status code back to the client correctly.

**Comment by zalegrala** [comment]
I believe https://github.com/grafana/tempo/pull/3267 will help.
