### ISSUE TITLE
Tempo Query frontend restart issue

### ISSUE THREAD

**Issue by sivesh1989** [grafana/tempo#2847]
We observe tempo query restarting very frequently under below scenario,

1)	Deployed tempo 2.2.1 with 1 query-frontend and one querier.
2)	Write path load (100k spans/sec) is working fine 
3)	Executing 1 user, 1 Traceql query from jmeter continuously and observe query-frontend restarting very frequently (every 2 to 5 mins)
4)	No resource crunch observed in query-frontend and querier.
5)  From the query-front end logs we observe Queriers lost connection to Query Frontend.
5)	Below is the sequence of failure observed in logs,

level=debug ts=2023-08-25T06:02:16.601207731Z caller=searchsharding.go:188 msg="exiting early from sharded query" url="/querier/api/search?blockID=31e5112c-c2d1-4f3b-b4ea-bb9efa723386&dataEncoding=&encoding=none&end=1692942619&footerSize=33474&indexPageSize=0&limit=20&pagesToSearch=1&q=%7B+.http.method+%3D+%22GET%22+%7D+%7C+count%28%29+%3E+2&size=378541869&start=1692939019&startPage=3&totalRecords=4&version=vParquet2" err="context canceled"
level=info ts=2023-08-25T06:02:16.601441333Z caller=searchsharding.go:236 msg="sharded search query request stats and SearchMetrics" query="q={ .http.method = \"GET\" } | count() > 2&limit=20&start=1692939019&end=1692942619" duration_seconds=1.710058558s request_throughput=8.561746573826976e+06 total_requests=97 started_requests=97 cancelled_requests=92 finished_requests=5 totalBlocks=24 inspectedBytes=14641088 inspectedTraces=0 totalBlockBytes=9177313420
level=info ts=2023-08-25T06:02:16.609177313Z caller=handler.go:124 tenant=albertsons1rep method=GET traceID=7960b2ce7aa70e52 url="/api/search?q=%7B%20.http.method%20%3D%20%22GET%22%20%7D%20%7C%20count()%20%3E%202&limit=20&start=1692939019&end=1692942619" duration=1.717860739s response_size=51200 status=200
level=debug ts=2023-08-25T06:02:16.609648618Z caller=logging.go:101 traceID=7960b2ce7aa70e52 msg="GET /api/search?q=%7B%20.http.method%20%3D%20%22GET%22%20%7D%20%7C%20count()%20%3E%202&limit=20&start=1692939019&end=1692942619 (200) 1.718388045s"
level=info ts=2023-08-25T06:02:16.865077471Z caller=frontend.go:396 msg="not ready: number of queriers connected to query-frontend is 0"
level=info ts=2023-08-25T06:02:16.865130671Z caller=frontend.go:396 msg="not ready: number of queriers connected to query-frontend is 0"
level=debug ts=2023-08-25T06:02:16.865141672Z caller=logging.go:101 traceID=20ed78625f115419 msg="GET /ready (503) 98.502µs"
level=debug ts=2023-08-25T06:02:16.865186872Z caller=logging.go:101 traceID=2492d3d6c23f5d2b msg="GET /ready (503) 87.901µs"
level=info ts=2023-08-25T06:02:16.866709588Z caller=frontend.go:396 msg="not ready: number of queriers connected to query-frontend is 0"
level=debug ts=2023-08-25T06:02:16.866756888Z caller=logging.go:101 traceID=4736cc55651ad5db msg="GET /ready (503) 82.901µs"
level=info ts=2023-08-25T06:02:16.875369478Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=debug ts=2023-08-25T06:02:16.87559358Z caller=module_service.go:127 msg="module waiting for" module=server waiting_for=overrides
level=debug ts=2023-08-25T06:02:16.87559468Z caller=module_service.go:127 msg="module waiting for" module=memberlist-kv waiting_for=query-frontend
level=debug ts=2023-08-25T06:02:16.87560318Z caller=module_service.go:127 msg="module waiting for" module=internal-server waiting_for=memberlist-kv
level=debug ts=2023-08-25T06:02:16.87561828Z caller=module_service.go:127 msg="module waiting for" module=overrides waiting_for=query-frontend
level=debug ts=2023-08-25T06:02:16.87562518Z caller=module_service.go:127 msg="module waiting for" module=store waiting_for=query-frontend
level=debug ts=2023-08-25T06:02:16.87563028Z caller=module_service.go:104 msg=stopping module=query-frontend
level=info ts=2023-08-25T06:02:16.875670281Z caller=module_service.go:114 msg="module stopped" module=query-frontend
level=debug ts=2023-08-25T06:02:16.875690481Z caller=module_service.go:104 msg=stopping module=store
level=debug ts=2023-08-25T06:02:16.875703681Z caller=module_service.go:104 msg=stopping module=overrides
level=debug ts=2023-08-25T06:02:16.875707381Z caller=module_service.go:104 msg=stopping module=memberlist-kv
level=info ts=2023-08-25T06:02:16.875744482Z caller=module_service.go:114 msg="module stopped" module=memberlist-kv
level=info ts=2023-08-25T06:02:16.875758682Z caller=module_service.go:114 msg="module stopped" module=overrides
level=debug ts=2023-08-25T06:02:16.875765982Z caller=module_service.go:127 msg="module waiting for" module=internal-server waiting_for=overrides
level=debug ts=2023-08-25T06:02:16.875773382Z caller=module_service.go:127 msg="module waiting for" module=internal-server waiting_for=query-frontend
level=debug ts=2023-08-25T06:02:16.875778282Z caller=module_service.go:127 msg="module waiting for" module=internal-server waiting_for=server
level=debug ts=2023-08-25T06:02:16.875784382Z caller=module_service.go:127 msg="module waiting for" module=server waiting_for=query-frontend
level=debug ts=2023-08-25T06:02:16.875791082Z caller=module_service.go:127 msg="module waiting for" module=server waiting_for=memberlist-kv
level=debug ts=2023-08-25T06:02:16.875797982Z caller=module_service.go:104 msg=stopping module=server
level=info ts=2023-08-25T06:02:16.875802182Z caller=module_service.go:114 msg="module stopped" module=store
level=warn ts=2023-08-25T06:02:17.418561219Z caller=grpc_logging.go:64 method=/frontend.Frontend/Process duration=1.057311ms err="queue is stopped" msg=gRPC
level=warn ts=2023-08-25T06:02:17.41967623Z caller=grpc_logging.go:64 method=/frontend.Frontend/Process duration=754.108µs err="queue is stopped" msg=gRPC
level=info ts=2023-08-25T06:02:46.877268986Z caller=server_service.go:50 msg="server stopped"
level=info ts=2023-08-25T06:02:46.877304986Z caller=module_service.go:114 msg="module stopped" module=server
level=debug ts=2023-08-25T06:02:46.877326086Z caller=module_service.go:104 msg=stopping module=internal-server
level=info ts=2023-08-25T06:02:46.877344387Z caller=module_service.go:114 msg="module stopped" module=internal-server
level=info ts=2023-08-25T06:02:46.877356887Z caller=app.go:197 msg="Tempo stopped"

Regards,
Sivesh Kumar R

**Comment by joe-elliott** [comment]
The logs show that the frontend is receiving a signal to stop:

> level=info ts=2023-08-25T06:02:16.875369478Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"

This means that something is asking the query frontend to shut down and so it is. Do you know of any process that might be doing this?

**Comment by sivesh1989** [comment]
We had set  failureThreshold : 10 part of liveness probe for querier and queryfrontend which seemed to fix the restart issue for queryfrontend.

Will continue with further testing and share the results if any issues observed again.
