### ISSUE TITLE
Blocklist never prunes missing tenants

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#285]
**Describe the bug**
If a tenant disappears (say by deleting all of its blocks manually from the backend) the internal in memory blocklist will never be updated to indicate this.

**To Reproduce**
1. Send spans to tempo
2. Let some blocks build up
3. Stop sending spans to tempo
4. Delete the tenant level folder on the backend
5. Note that the tempodb_blocklist_length value doesn't go to 0.

**Expected behavior**
Blocks should be pruned from the in memory blocklist.

**Environment:**

**Additional Context**
This is b/c the `pollBlocklist` method in tempodb updates the blocklist of any tenant it finds, but if it fails to find the tenant it does nothing.

**Comment by dgzlopes** [comment]
Hey :)

The blocks should be pruned from the in-memory compactedBlockLists too?
