### ISSUE TITLE
tempo-vulture doesn't correctly metric 404s

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#286]
**Describe the bug**
Even when the querier returns a 404 the tempo-vulture does not metric it correctly.  Instead it logs:

```
E1029 17:32:44.343430       1 main.go:115] tempo url http://querier:3100/api/traces/3359040636e8a98b
E1029 17:32:44.560477       1 main.go:91] error querying Tempo error decoding trace json, err: invalid character 'U' looking for beginning of value, traceID: 3359040636e8a98b
```

**Comment by dgzlopes** [comment]
I tried to reproduce this locally. For me, the `tempo_vulture_error_total` Counter is incremented on each 404.

```
# HELP tempo_vulture_error_total tempo vulture errors
# TYPE tempo_vulture_error_total counter
tempo_vulture_error_total 299
```

Maybe I'm missing something!

**Comment by joe-elliott** [comment]
Thanks for digging into this.  404s should be metric'ed with the label `error="notfound"`

https://github.com/grafana/tempo/blob/master/cmd/tempo-vulture/main.go#L97.

**Comment by dgzlopes** [comment]
Oh, nice!

I suppose this is the problematic code snippet:
```go
for _, id := range traceIDs {
		// code
		trace, err := util.QueryTrace(baseURL, id, tempoOrgID)
		if err != nil {
			return nil, err
		}

		if len(trace.Batches) == 0 {
			glog.Error("trace not found", id)
			tm.notfound++
			continue
		}
		// code
	}
``` 
If QueryTrace fails we return the error (as shown on your logs) and stop checking the traceIDs. 

From what I understand, only the 404s should be labeled with `error="notfound"`? The rest of QueryTrace errors should increase `tempo_vulture_error_total` counter?

**Comment by joe-elliott** [comment]
yup.  That must have been broken when we consolidated that QueryTrace method.
