### ISSUE TITLE
Tempo returns success for { span.att = nil }

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2879]
Tempo returns 200 on an "= nil" query. This is not actually evaluated by the engine and the results will always be empty.

```
{ span.att = nil }
```

![image](https://github.com/grafana/tempo/assets/2272392/f3fac7e4-998a-46e1-8977-05c5c80eb54a)

**Comment by kousikmitra** [comment]
@joe-elliott is this fixed? Getting correct error on main branch.

**Comment by mapno** [comment]
It was fixed as part of https://github.com/grafana/tempo/pull/2698. Nice catch, thanks!
