### ISSUE TITLE
`coalesce` is not documented

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/tempo#2920]
On the [online documentation of TraceQL](https://grafana.com/docs/tempo/latest/traceql/#selecting-spans), the `coalesce` operator is not documented.

**Comment by joe-elliott** [comment]
I left `coalesce` off purposefully because I could think of a good use case for it and I wanted to keep the TraceQL documentation focused. This may have been a wrong decision. Just because I can't think of a use for something doesn't mean it doesn't exist. WDYT?

**Comment by knylander-grafana** [comment]
Should we close this issue? Or leave it in the backlog in case we think of a good example for coalesce?
