### ISSUE TITLE
Return additional trace metadata in TraceQL search response

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo#2940]
**Is your feature request related to a problem? Please describe.**
It would be great if  trace visualization tools (e.g. Grafana, Jaeger UI) can show additional metadata in the search results for each matched trace. Specifically, the service names of traversed services, span count and error count.

Example in the Jaeger UI:
![grafik](https://github.com/grafana/tempo/assets/538011/037f0e0b-72f4-47f5-b86f-4652c6851f68)

**Describe the solution you'd like**
The `/api/search?q=...` API should return the above metadata, for example:
```
{
  "traceID": "20ae1e9d40ab5759699035e3c09092b3",
  "rootServiceName": "frontend",
  "rootTraceName": "HTTP GET /dispatch",
  "startTimeUnixNano": "1695040911822070267",
  "durationMs": 738,
  "spanSets": [
    {
      "spans": [
        {
          "spanID": "f953b82c348121d2",
          "startTimeUnixNano": "1695040911822559586",
          "durationNanos": "321561466"
        },
        {
          "spanID": "299e15e2db12f15f",
          "startTimeUnixNano": "1695040911822502499",
          "durationNanos": "321668520"
        },
        {
          "spanID": "e6cfbd41f7438b69",
          "startTimeUnixNano": "1695040911822213022",
          "durationNanos": "322204809"
        }
      ],
      "matched": 51
    }
  ],
  "servicesMeta": [
    {
      "serviceName": "mysql",
      "spanCount": "1"
    },
    {
      "serviceName": "customer",
      "spanCount": "1"
    },
    {
      "serviceName": "frontend",
      "spanCount": "24"
    },
    {
      "serviceName": "route",
      "spanCount": "10"
    },
    {
      "serviceName": "driver",
      "spanCount": "1"
    },
    {
      "serviceName": "redis",
      "spanCount": "14",
      "errorCount": 2
    }
  ]
},
```

**Describe alternatives you've considered**
Alternatively, the visualization tool can query the entire trace by ID for each search result. This will result in slow performance however.

**Comment by joe-elliott** [comment]
Is this complete with the release of vparquet4?

**Comment by andreasgerstmayr** [comment]
Yes, this is complete and can be closed :+1:
