### ISSUE TITLE
Use the standard 'errors' package to create, wrap, and handle errors

### ISSUE THREAD

**Issue by stoewer** [grafana/tempo#2946]
**Is your feature request related to a problem? Please describe.**

The Tempo code base uses two packages to create, wrap, and handle errors:
* `errors` from the standard library
* `github.com/pkg/errors` a drop-in replacement for `errors` that was created before [Go 1.13 added error wrapping](https://go.dev/blog/go1.13-errors)

Using both packages creates the following problems:
*  Where both packages can be used it can be confusing which one to import
* `github.com/pkg/errors` implements a function `errors.Wrap(err, "...")` that does the same as `fmt.Errorf("... : %w", err)` and it can be confusing which function should be used
* `github.com/pkg/errors` is archived and does not provide more recent additions to the `errors` package such as `errors.Join()`: It is no longer a real drop-in replacement

**Describe the solution you'd like**

* Replace all imports of `github.com/pkg/errors` with `errors`
* Use `fmt.Errorf("%w")` instead of `errors.Wrap()` and `errors.Errorf("%w")`
* Remove `github.com/pkg/errors` from direct dependencies (it is probably still an indirect dependency that is used by other packages we use)
* Look for errors that are not properly wrapped with i.e. `fmt.Errorf("%v", err)` and wrap them properly

**Additional context**
Here is a [recent discussion about this problem](https://github.com/grafana/tempo/pull/2907#discussion_r1328699378)

**Comment by trader7** [comment]
I'm happy to take a stab at this, seems pretty straightforward

**Comment by trader7** [comment]
Looks like @sonisr has this one. Let me know if your changes don't get merged, I have made a start on it here
