### ISSUE TITLE
slices.Delete

### ISSUE THREAD

**Issue by Deleplace** [grafana/tempo#2947]
Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [this code](https://github.com/grafana/tempo/blob/1d2d423c59b979ee6d2d7ba2ed07daee1d45fdc4/modules/distributor/forwarder/manager_test.go#L373):

```
slices.Delete(o.tenantIDToForwarders["testTenantID"], idx, idx)
```

which probably doesn't behave as intended and should look like this instead:

```
o.tenantIDToForwarders["testTenantID"] = slices.Delete(o.tenantIDToForwarders["testTenantID"], idx, idx+1)
```

(2 differences: using the returned value, and deleting `+1` element instead of zero).

I have not tried to execute it.

**Comment by joe-elliott** [comment]
Nice. Thanks for the heads up! I wonder why this test passes?
