### ISSUE TITLE
Allow settings of histogram buckets by span kind

### ISSUE THREAD

**Issue by jcarres-mdsol** [grafana/tempo#2964]
It is difficult to create a set of histogram buckets that could cover a wide range of situations with accuracy.

Currently we can set `histogram_buckets` for service graph metrics and span metrics, these buckets apply to any incoming span.

Given that a SERVER/CONSUMER span would have multiple CLIENT/PRODUCER children in general, then in general the latency of CLIENT/PRODUCER is going to be significant lower.

An example is an API responding in the 200ms - 500ms range and internally doing multiple redis/database calls on the 1ms 10ms range.

I think it would help increase histogram accuracy if it is possible to apply different buckets for different span kinds.
For instance someone may want to have more accuracy around the 1 second response time on server:

```
      histogram_buckets_server:
      - 0.1
      - 0.2
      - 0.4
      - 0.6
      - 0.8
      - 1.2
      - 1.6
      - 2.4
      - 3.2
      - 6.4
      - 12.8
```

And at the same time have great accuracy on the very lower end of client to capture redis/database interactions:
```
      histogram_buckets_client:
      - 0.0004
      - 0.0012
      - 0.0024
      - 0.005
      - 0.012
      - 0.024
      - 0.05
      - 0.1
      - 0.2
      - 0.4
      - 0.8
      - 1.6
      - 3.2
```

Right now it would be very expensive to try to get both so either we need to choose one use case over the other, spend the resources of having both for all spans which is wasteful or make a big compromise.

As alternative, it seems the new exponential histograms may be way superior but I have never used them, so can't tell, I am also not sure what's the current support for them in Mimir.

**Comment by joe-elliott** [comment]
Since server/client are only set on the boundary spans having different histograms for them seems odd to me. It might help in some very specific cases, but in the general case I'm not sure if it adds much.

![image](https://github.com/grafana/tempo/assets/2272392/68039ccb-12ae-45c3-ac3b-fe0b888a964d)

> As alternative, it seems the new exponential histograms may be way superior but I have never used them, so can't tell, I am also not sure what's the current support for them in Mimir.

This is a direction I would definitely prefer going. My impression is that both remote write and Mimir support the new histograms.

**Comment by jcarres-mdsol** [comment]
Yes, it is true that when the client is used for inter-service communication client will have a duration equivalent to server.

I'm closing this as probably the feature would not be this but instead be to create exponential histograms from the metrics generator.
