### ISSUE TITLE
metrics-generator: Option to disable adding X-Scope-OrgID in remote write requests

### ISSUE THREAD

**Issue by vineetjp** [grafana/tempo#2973]
**Describe the bug**

When using metrics-generator to remote write metrics to Amazon Managed Prometheus (Cortex), the authentication to the server fails. Support case has been logged with AWS

**To Reproduce**
1. Start Tempo 2.21 in multi tenant mode with metrics-generator enabled and storage config with remote-write to amazon managed prometheus server.
2. Start metric ingestion . Following error will appear in metrics generator logs
`ts=2023-09-30T11:50:02.769098012Z caller=dedupe.go:112 tenant=Amway component=remote level=error remote_name=e3f5ba url=https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/xxx/api/v1/remote_write msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 403 Forbidden: {\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n'POST\\n/workspaces/x/api/v1/remote_write\\n\\ncontent-encoding:snappy\\ncontent-type:application/x-protobuf\\nhost:aps-workspaces.ap-southeast-1.amazonaws.com\\nx-amz-date:20230930T115002Z\\nx-amz-security-token:xxx//////////xxx//////////xxx/xxx"`

**Expected behavior**
It will be better if X-Scope-OrgID header in remote write request can be turned off.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
In order to verify that X-Scope-OrgID header is causing the issue, a prometheus server's remote write configuration was modified to add X-Scope-OrgID header. After removing the X-Scope-OrgID header configuration in the remote write configuration, remote writing was completed successfully with the same sigv4 arn.

Prometheus Server remote write config
`metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
      - url: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/x/api/v1/remote_write
        sigv4:
          region: ap-southeast-1
          role_arn: arn:aws:iam::xxxx:role/xxx`

Tempo metrics generator helm config
`metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
      - url: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/xxx/api/v1/remote_write
        sigv4:
          region: ap-southeast-1
          role_arn: arn:aws:iam::xxxx:role/xxx`

**Comment by joe-elliott** [comment]
Thanks for filing an issue and a PR. Will review when I get a chance!
