### ISSUE TITLE
Make links that work both on the docs site and the readme

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#303]
**Describe the bug**
The links currently only work on the docs site, but fail in the readme.  This causes confusion and has resulted in a few PRs:

#299 
#297 

We need to see if we can create links that work in both places to prevent confusing people.

**Comment by daixiang0** [comment]
I do want to know it.

**Comment by calvernaz** [comment]
Hi @joe-elliott, thanks for opening this. Do you know which tool is used to generate the site? Maybe that could help us understand how links are generated and fix the broken links in the README.

Another way to solve it is to use references to the links from grafana.com in the README.

**Comment by annanay25** [comment]
Yeah, I agree, this can be confusing. We're using Hugo as the static site generator for the Grafana docs website, and I think the way it works is by creating subdirectories at each `_index.md` level. Over the next couple of days I will try and spend some time to document the format to be followed while writing docs.

> Another way to solve it is to use references to the links from grafana.com in the README.

@calvernaz - If I understand correctly you mean directly linking `grafana.com/docs/tempo/latest/<file.md>` links in the README? I don't think we should do that because it can be very fragile, those docs are generated based on the directory structure in this repository. We should keep the links relative and dependent only on the source.

**Comment by daixiang0** [comment]
@annanay25 i think now links in docs only can be recognized by hugo, like #297, it would be recognized by Github too. Then we can easily introduce link checker as #293.

**Comment by annanay25** [comment]
Hi @daixiang0, I checked #297 by manually changing the link to `loki-derived-fields.md` and it breaks the website. Attached a gif below (which is much slower than recording speed for some reason 😄 )



![website-recording](https://user-images.githubusercontent.com/10982987/97842792-345a1a80-1d0e-11eb-9e60-7b7cebce9ead.gif)

**Comment by daixiang0** [comment]
Which version of  hugo does Grafana Site use? Or where can i see site config if possible?

**Comment by annanay25** [comment]
Running `make docs` in the Tempo root directory should spin up a container with a preview of the website as it will be rendered on the grafana.com page.

**Comment by calvernaz** [comment]
> @calvernaz - If I understand correctly you mean directly linking `grafana.com/docs/tempo/latest/<file.md>` links in the README? I don't think we should do that because it can be very fragile, those docs are generated based on the directory structure in this repository. We should keep the links relative and dependent only on the source.

I agree that it makes it fragile, it was an idea for the short term to avoid people (like me) coming back with PRs for the broken links.

**Comment by knylander-grafana** [comment]
@joe-elliott  Is this ticket still a concern? If so, I can get input from the docs squad for recommendations.

**Comment by joe-elliott** [comment]
I don't think so. If I wanted to locally double check that everything worked I'd use the local hugo website thing. Honestly, I'm willing to close this if you are.

**Comment by knylander-grafana** [comment]
Okay, I'll close it.
