### ISSUE TITLE
Override metric generator processor for specific tenant is not working

### ISSUE THREAD

**Issue by logamanig** [grafana/tempo#3032]
**Describe the bug**

i'm using the latest tempo-distributed helm chart (1.6.12) and using the overrides section to configure the following for the specific tenant, before the override, I can see both service graphs and span metrics processor. The main different between the global config (both metrics processor are enabled

  overrides: |
    overrides:
     tenant1:
        metrics_generator_processors: [service-graphs, span-metrics]
        metrics_generator_processor_service_graphs_dimensions: [k8s.namespace.name]
        metrics_generator_processor_service_graphs_histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.2, 1.6, 2, 2.4, 2.8, 3.2, 3.6, 4, 4.4, 4.8, 5.2, 5.6, 6, 6.4, 8.6, 10.6, 12.8, 14.2, 15.6, 18, 20, 22, 25, 28, 32, 36, 40]
        metrics_generator_processor_span_metrics_dimensions: [k8s.namespace.name, http.target]
        metrics_generator_processor_span_metrics_histogram_buckets: [ 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 0.768, 1.02, 1.53, 2.04, 2.55, 3.06, 3.57, 4.08, 5.10, 6.12, 7.14, 8.16, 9.18, 10.2, 11.3, 12.4, 13.5, 14.6, 15.8, 17.0, 20.0, 22.0, 24.0, 26.0, 30.0, 35.0, 40.0, 50.0, 60.0]

**To Reproduce**
1. override the tenant config as in the description
2. all other tenants are working correctly except the tenant with override

**Expected behavior**
Expecting the overrides is working for specified tenant (i.e http.target as additional label)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm (distributed-tempo chart version 1.6.12)

**Comment by joe-elliott** [comment]
Can you share the complete rendered configmaps? They would help me understand why your overrides might not be working.
