### ISSUE TITLE
Got 404 Not Found on query frontend service

### ISSUE THREAD

**Issue by jxdn** [grafana/tempo#3033]
i have deployed using latest helm chart

https://artifacthub.io/packages/helm/grafana/tempo-distributed

i didnt change a lot just on minio part, i change it to true

all service successfully deployed and running

but when i try to curl its 404 not found

bash-5.1# curl tempo-query-frontend.monitoring.svc:3100
404 page not found
bash-5.1# 

i tried to add /metrics and its successfull 

curl tempo-query-frontend.monitoring.svc:3100/metrics
# HELP deprecated_flags_inuse_total The number of deprecated flags currently set.
# TYPE deprecated_flags_inuse_total counter
deprecated_flags_inuse_total 0
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 2.9971e-05
go_gc_duration_seconds{quantile="0.25"} 3.0357e-05
go_gc_duration_seconds{quantile="0.5"} 0.000250455
go_gc_duration_seconds{quantile="0.75"} 0.000405112
go_gc_duration_seconds{quantile="1"} 0.005815659
go_gc_duration_seconds_sum 0.006950193
go_gc_duration_seconds_count 7
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 505
# HELP go_info Information about the Go environment.
# TYPE go_info gauge

any ideo why i got 404 not found ?

**Comment by mapno** [comment]
Hi @jxdn. You can check the available endpoint in the [documentation](https://grafana.com/docs/tempo/latest/api_docs/#endpoints). If you want a UI, you can use the [Tempo datasource](https://grafana.com/docs/grafana/latest/datasources/tempo/) in Grafana.

**Comment by jxdn** [comment]
may i know which one that i supposed to add in the tempo datasource ? 
i got below error in grafana, i put tempo-http://query-frontend.monitoring.svc:3100 as endpoint

Unable to connect with Tempo (Bad Gateway). Please check the server logs for more details.
