### ISSUE TITLE
remove not check min traceID and max traceID

### ISSUE THREAD

**Issue by zdyj3170101136** [grafana/tempo#3080]
there are lots of code do not check block meta's min traceID and max traceID.

https://github.com/grafana/tempo/blob/3322d2879554d52c558fb3cbefaa9819f7bad858/tempodb/tempodb.go#L495
```
// includeBlock indicates whether a given block should be included in a backend search
func includeBlock(b *backend.BlockMeta, _ common.ID, blockStart []byte, blockEnd []byte, timeStart int64, timeEnd int64) bool {
	// todo: restore this functionality once it works. min/max ids are currently not recorded
	//    https://github.com/grafana/tempo/issues/1903
	//  correctly in a block
	// if bytes.Compare(id, b.MinID) == -1 || bytes.Compare(id, b.MaxID) == 1 {
	// 	return false
	// }
```
as the issue https://github.com/grafana/tempo/issues/1903 already fix , please remove it.

**Comment by joe-elliott** [comment]
I'm not 100% sure this has been fixed. We have disabled the trace by id index b/c we were still seeing some strangeness with trace ids.

If someone wants to confirm it's been fixed and re-enable the linked code I'm fine with it.
