### ISSUE TITLE
Publish tempo-cli binary with Releases. 

### ISSUE THREAD

**Issue by vanugrah** [grafana/tempo#3083]
Hey folks, 

This is a request to publish tempo-cli binary along with releases of tempo. Loki and Mimir both follow this convention with LogCLI and Mimirtool respectively. I'm happy to contribute this - though it is unclear to me how the binaries are added to the release.

**Comment by joe-elliott** [comment]
i think they already are. if i go to [a release](https://github.com/grafana/tempo/releases/tag/v2.2.4) and download [tempo_2.2.4_linux_arm64.tar.gz](https://github.com/grafana/tempo/releases/download/v2.2.4/tempo_2.2.4_linux_arm64.tar.gz) there is a tempo-cli binary included.

are you seeing something different?

**Comment by vanugrah** [comment]
You are correct - it seems like Loki and Mimir attach the binary as a separate zip file so it is more easily discoverable, hence the confusion. 

Thank you!

**Comment by kyeongjun-dev** [comment]
@joe-elliott you saved my time so much. Thanks!
