### ISSUE TITLE
Cannot escape characters in TraceQL regex query

### ISSUE THREAD

**Issue by dyllandry** [grafana/tempo#3086]
**Describe the bug**

When I use TraceQL to do a regex search involving escaping a character like `\$` as in `{ .attribute =~ ".*\$[0-9]" }` I get an error:

```
Query error
Error (invalid TraceQL query: parse error at line 1, col 20: invalid char escape). Please check the server logs for more details.
```

Seems to be the same error as in Loki: https://github.com/grafana/loki/issues/2016

Sorry if this is not correct the repo for this issue.

**To Reproduce**
1. Explore and search for traces using TraceQL on Grafana Cloud

**Expected behavior**

There not to be an error and the search to work.

**Environment:**
 - Infrastructure: Grafana Cloud
 - Deployment tool: Grafana Cloud

**Additional Context**

**Comment by joe-elliott** [comment]
Based on those threads it looks like you can use `\\` to get this to work? Is that true? If you enclose your string in backticks `\`` does it work?

**Comment by dyllandry** [comment]
Oh, it does work, despite the TraceQL editor underlining it with red and the message: "Invalid value after comparison or aritmetic operator." I'm going to start trying some of these searches even though the editor reports errors, I didn't know it could still potentially work.

Thanks for the help Joe.
