### ISSUE TITLE
Repetitive ERRORS - failed to clear compacted block during retention and WARNINGS  - unable to find meta during compaction

### ISSUE THREAD

**Issue by dorinand** [grafana/tempo#3092]
**Describe the bug**

Repetitive errors from copactor and retention caller. We do not register any outages or missing data yet, but we register high IO on disks its running on. Not sure if this could cause high IO issue or not but repetitive errors and warning is suspicious. We even run Tempo with empty directory, so we could exclude corrupted data.

**To Reproduce**
1. Tempo 2.1.1
2. Run in docker swarm 24.0.5 as service

Not sure if this will help to reproduce it. 

**Expected behavior**
I expect only INFO logs, no WARNING or ERROR.

**Environment:**
 - Infrastructure: docker swarm 24.0.5, data directory mounted from server
 - Deployment tool: docker service

**Additional Context**
Configuration:
```
server:
  http_listen_port: 3200

distributor:
  receivers:
    zipkin:
    otlp:
      protocols:
        http:

ingester:
  trace_idle_period: 10s

compactor:
  compaction:
    compaction_window: 1h
    block_retention: 84h
    compacted_block_retention: 1h

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /data/generator/wal
    remote_write:
      - url: http://prometheus-master:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
      v2_index_downsample_bytes: 1000
      v2_encoding: zstd
    wal:
      path: /data/wal
      v2_encoding: snappy
    local:
      path: /data/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  metrics_generator_processors: [service-graphs, span-metrics]
  max_bytes_per_trace: 7000000
```
Errors and warnings for last 3 hours:
![image](https://github.com/grafana/tempo/assets/27764640/864b7c2f-d121-40e3-b8c8-7b08b63f95d5)

Its occour every 5 minuts. From [doc of compactor](https://grafana.com/docs/tempo/latest/configuration/#compactor) it looks like only configuration with default value of **5m** is `max_time_per_tenant - Optional. The maximum amount of time to spend compacting a single tenant before moving to the next. Default is 5m`.

Warning log:
```
level=warn ts=2023-10-31T14:32:05.337882591Z caller=compactor.go:145 msg="unable to find meta during compaction.  trying again on this block list" err="does not exist"
```

Error logs:
```
level=error ts=2023-10-31T14:52:01.902675303Z caller=retention.go:100 msg="failed to clear compacted block during retention" blockID=a0cb3a8b-f678-49f1-966a-eb645c25d6b3 tenantID=single-tenant err="failed to remove keypath for block /data/blocks/single-tenant/a0cb3a8b-f678-49f1-966a-eb645c25d6b3: unlinkat /data/blocks/single-tenant/a0cb3a8b-f678-49f1-966a-eb645c25d6b3: directory not empty"
level=error ts=2023-10-31T14:52:01.771061276Z caller=retention.go:100 msg="failed to clear compacted block during retention" blockID=718c7b7e-3eb9-40e9-8f47-b3c434625045 tenantID=single-tenant err="failed to remove keypath for block /data/blocks/single-tenant/718c7b7e-3eb9-40e9-8f47-b3c434625045: unlinkat /data/blocks/single-tenant/718c7b7e-3eb9-40e9-8f47-b3c434625045: directory not empty"
level=error ts=2023-10-31T14:52:01.611920501Z caller=retention.go:100 msg="failed to clear compacted block during retention" blockID=6349891b-0357-45f6-99c2-e4e76fd8f00f tenantID=single-tenant err="failed to remove keypath for block /data/blocks/single-tenant/6349891b-0357-45f6-99c2-e4e76fd8f00f: unlinkat /data/blocks/single-tenant/6349891b-0357-45f6-99c2-e4e76fd8f00f: directory not empty"
level=error ts=2023-10-31T14:47:01.650974622Z caller=retention.go:100 msg="failed to clear compacted block during retention" blockID=47534186-95f4-4fc5-88fa-7bef889a1c07 tenantID=single-tenant err="failed to remove keypath for block /data/blocks/single-tenant/47534186-95f4-4fc5-88fa-7bef889a1c07: unlinkat /data/blocks/single-tenant/47534186-95f4-4fc5-88fa-7bef889a1c07: directory not empty"
level=error ts=2023-10-31T14:47:01.58454277Z caller=retention.go:100 msg="failed to clear compacted block during retention" blockID=040c5eab-8ba7-44e9-9650-9f9e3897b092 tenantID=single-tenant err="failed to remove keypath for block /data/blocks/single-tenant/040c5eab-8ba7-44e9-9650-9f9e3897b092: unlinkat /data/blocks/single-tenant/040c5eab-8ba7-44e9-9650-9f9e3897b092: directory not empty"
```
When I list block directories mentioned from error logs, they are all empty, so error message `direcory not empty` is suspicious:
```
ll blocks/single-tenant/a0cb3a8b-f678-49f1-966a-eb645c25d6b3 blocks/single-tenant/718c7b7e-3eb9-40e9-8f47-b3c434625045 blocks/single-tenant/6349891b-0357-45f6-99c2-e4e76fd8f00f blocks/single-tenant/47534186-95f4-4fc5-88fa-7bef889a1c07 blocks/single-tenant/040c5eab-8ba7-44e9-9650-9f9e3897b092
blocks/single-tenant/040c5eab-8ba7-44e9-9650-9f9e3897b092:
total 116
drwxr-xr-x    2 nobody nobody   4096 Oct 31 15:47 .
drwxr-xr-x 1068 nobody nobody 110592 Oct 31 16:00 ..

blocks/single-tenant/47534186-95f4-4fc5-88fa-7bef889a1c07:
total 116
drwxr-xr-x    2 nobody nobody   4096 Oct 31 15:47 .
drwxr-xr-x 1068 nobody nobody 110592 Oct 31 16:00 ..

blocks/single-tenant/6349891b-0357-45f6-99c2-e4e76fd8f00f:
total 116
drwxr-xr-x    2 nobody nobody   4096 Oct 31 15:52 .
drwxr-xr-x 1068 nobody nobody 110592 Oct 31 16:00 ..

blocks/single-tenant/718c7b7e-3eb9-40e9-8f47-b3c434625045:
total 116
drwxr-xr-x    2 nobody nobody   4096 Oct 31 15:52 .
drwxr-xr-x 1068 nobody nobody 110592 Oct 31 16:00 ..

blocks/single-tenant/a0cb3a8b-f678-49f1-966a-eb645c25d6b3:
total 116
drwxr-xr-x    2 nobody nobody   4096 Oct 31 15:52 .
drwxr-xr-x 1068 nobody nobody 110592 Oct 31 16:00 ..
```

**Comment by joe-elliott** [comment]
It seems like you're running Tempo using local block storage. Our recommendation would be to use object storage.

To the issue in question, is this a single instance of Tempo working on a local disk?
Are the same block guids logged every time? or do they change?

Given that the folders seem empty despite the error suggests some kind of race condition. Can you give a file listing of a normal block under `/blocks/single-tenant/<guid>`?

**Comment by dorinand** [comment]
Hi @joe-elliott, thank you for your reply.

You are right, I am using local block storage, sorry for unclear description. We are planning to move to object storage in close future I hope.

Yes, it is a single instance of Tempo. I check logs for last 24 hours and all the BlockID are uniq, so there is no repetitive block ids error.

List of directory under `816039dc-da6e-42bb-bb3e-d0d5f6c1dbfa` block:
```
/data # ll blocks/single-tenant/816039dc-da6e-42bb-bb3e-d0d5f6c1dbfa
total 1280
drwxr-xr-x    2 99       99            4096 Nov  2 13:58 .
drwxr-xr-x 1983 99       99          208896 Nov  2 21:25 ..
-rw-r--r--    1 99       99          102424 Nov  2 13:58 bloom-0
-rw-r--r--    1 99       99          971309 Nov  2 13:58 data.parquet
-rw-r--r--    1 99       99             404 Nov  2 13:58 meta.json
```

Files `bloom-0` and `data.parquet` are binaries so I can't read them but I can attach output of `meta.json` file:
```
{
  "format": "vParquet",
  "blockID": "816039dc-da6e-42bb-bb3e-d0d5f6c1dbfa",
  "minID": "AEjqjrohxlEa59lBupxANA==",
  "maxID": "/+u3xvUqO4K9LuVv77N1Tw==",
  "tenantID": "single-tenant",
  "startTime": "2023-11-02T13:57:20+01:00",
  "endTime": "2023-11-02T13:58:02+01:00",
  "totalObjects": 1795,
  "size": 971309,
  "compactionLevel": 0,
  "encoding": "none",
  "indexPageSize": 0,
  "totalRecords": 1,
  "dataEncoding": "",
  "bloomShards": 1,
  "footerSize": 7293
}
```

**Comment by joe-elliott** [comment]
This seems like some kind of issue specific to perhaps swarm? or the nature of your disks? The call that's failing is this:

https://github.com/grafana/tempo/blob/281f824413becc49a0cdeac763c83d901b961bb0/tempodb/backend/local/compactor.go#L32

which is a go runtime call to `rm -rf` a folder. Perhaps a bug with this call and your specific setup?

> Yes, it is a single instance of Tempo. I check logs for last 24 hours and all the BlockID are uniq, so there is no repetitive block ids error.

It's throwing an error, but seems to eventually clean up the files. 

I'd say that unless you're willing to debug the issue between the go runtime and your setup then just swap to object storage.
