### ISSUE TITLE
pre where iterator

### ISSUE THREAD

**Issue by zdyj3170101136** [grafana/tempo#3111]
for now, the parquetquery join iterator could process something like 'where app='post' and env='prod''
but it could not process something like 'PREWHERE app='post' and env='prod''。

which we could add bloom filter in app so we can skip many rows.

**Comment by joe-elliott** [comment]
Here is where we decide to skip a row group or not for a string predicate:

https://github.com/grafana/tempo/blob/281f824413becc49a0cdeac763c83d901b961bb0/pkg/parquetquery/predicates.go#L48

We are currently using the min/max of each page as well as the dictionary. It would be nice to add bloom filters for some columns, but we have not yet done that.

**Comment by zdyj3170101136** [comment]
> tempo/pkg/parquetquery/predicates.go

the join iterator is a random iterator, i want some column iterator have priority cause i know it may skip many pages~.

**Comment by joe-elliott** [comment]
why do you think the join iterator is random? i'm pretty sure it respects column priority. if the first iterator skips to row N it fast forwards all other iterators there without checking.

**Comment by zdyj3170101136** [comment]
> 为什么你认为连接迭代器是随机的？我很确定它尊重列优先级。如果第一个迭代器跳到第 N 行，它会快进那里的所有其他迭代器，而不检查每个值。

you are right.

i also have a question about how to do range query if i store timestamp as parquet column.

i could use this to do specific time point query: parquetquery.NewStringInPredicate("2023-11-02").
but i do not know how to do range time query.

**Comment by joe-elliott** [comment]
we store date/times as unix epochs and use ranges like this:

https://github.com/grafana/tempo/blob/281f824413becc49a0cdeac763c83d901b961bb0/tempodb/encoding/vparquet3/block_traceql.go#L1335

**Comment by mdisibio** [comment]
Because we start timestamps as unixnanoseconds, a query for a date like `2023-11-02` would be an integer check `>= unixnanos(2023-11-02)` and `< unixnanos(2023-11-03)`.

**Comment by mdisibio** [comment]
> nice to add bloom filters for some columns

Yes this needs some exploration because they have both pros and cons.  Extra overhead for writing blocks and increased i/o during search.  For common tags they won't have better filtering power than the dictionary per row group.
