### ISSUE TITLE
unexpected error opening parquet file: reading footer of parquet file: error in range read from s3 backend, bucket: tempo, objName: single-tenant/e6719758-84c9-4999-aeb7-6385c7e32072/data.parquet: The specified key does not exist

### ISSUE THREAD

**Issue by halleystar** [grafana/tempo#3117]
**Describe the bug**
![image](https://github.com/grafana/tempo/assets/5334156/a15ec2b5-8fae-4343-a898-541ab530f830)

**To Reproduce**
Choose 1 hour or 3 hours. Occasionally bugs occur

**Expected behavior**
Normal return results

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: none
 - config: 
![image](https://github.com/grafana/tempo/assets/5334156/7799f24a-b426-4575-ac9a-480a024ba75d)

**Additional Context**
When I tried to solve this problem, I found that the trace was incomplete.

**Comment by joe-elliott** [comment]
There are two issues here. 

The first is occurring b/c the queriers have an incorrect picture of the backend. This may be due to polling misconfiguration or a lifecycle rule in s3 is removing blocks unexpectedly or perhaps something else. I would review compactor logs to see if it removed this block or if something external to Tempo removed it.

The second is occurring b/c the queriers are unable to communicate effectively with the ingesters. When you request a trace by id from Tempo it checks object storage as well as the ingesters to find all spans associated with the ID. Just because the id exists in s3 doesn't mean there aren't also recent spans associated with that trace id in the ingesters.

**Comment by halleystar** [comment]
the first  I am sure  the data exist in s3(minio). so the data is  not  removed  by   unexpectedly  app. when happen the error, I immediately went to query s3 and found that the data existed。
![image](https://github.com/grafana/tempo/assets/5334156/bf49624f-5693-4cd7-a16d-94577e546e4b)
![image](https://github.com/grafana/tempo/assets/5334156/65655168-4bfb-4d29-8936-814a0ad6e0b5)

**Comment by joe-elliott** [comment]
It is unlikely that the querier is configured correctly if is not seeing that block.

**Comment by wangjinxiang0522** [comment]
I have encountered the same issue where there are no problems with my Minio when the disk usage is SSD, but when I switch to HDD, the issue arises. My configuration is as follows: 
`usage_report:
  reporting_enabled: false

server:
  http_listen_port: 3200
  log_level: debug
  grpc_server_max_recv_msg_size: 15728640
  grpc_server_max_send_msg_size: 15728640
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
          max_recv_msg_size_mib: 100

ingester:
  lifecycler:
    ring:
      replication_factor: 1
  max_block_duration: 15m
  complete_block_timeout: 30m
  flush_all_on_shutdown: true
  max_block_bytes: 104857600

compactor:
  disabled: true
  compaction:
    block_retention: 48h
    compacted_block_retention: 1h
    compaction_window: 1h
    max_compaction_objects: 6000000
    max_block_bytes: 209715200

memberlist:
  cluster_label: tempo-cluster
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    - xx.xx.xx.xx:7946
    - xx.xx.xx.xx:7946




storage:
  trace:
    backend: s3                        
    wal:
      path: /tmp/tempo/wal             
      v2_encoding: snappy
      search_encoding: snappy
    s3:
      bucket: tempo                   
      endpoint: minio-nginx:9081
      access_key: xxxx
      secret_key: xxxxxxxx
      insecure: true

    pool:
      max_workers: 100
      queue_depth: 10000

query_frontend:
  search:
    concurrent_jobs: 1500
    query_backend_after: 15m
    query_ingesters_until: 30m

  trace_by_id:
    hedge_requests_at: 0
    hedge_requests_up_to: 0


querier:
  max_concurrent_queries: 20
  trace_by_id:
    query_timeout: 10s
  search:
    query_timeout: 30s
  frontend_worker:
    frontend_address: tempo-query-frontend.com:9095


metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: tempo-cluster
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir-write.com:8080/api/v1/push
        send_exemplars: true

overrides:
  metrics_generator_processors: ['service-graphs', 'span-metrics']
  max_bytes_per_trace: 12000000
  ingestion_burst_size_bytes: 30000000
  ingestion_rate_limit_bytes: 25000000`


![screenshot-20231108-173748](https://github.com/grafana/tempo/assets/37041095/89098b14-8c09-45c1-8114-cab2e84388d4)

**Comment by wangjinxiang0522** [comment]
> I have encountered the same issue where there are no problems with my Minio when the disk usage is SSD, but when I switch to HDD, the issue arises. My configuration is as follows: [tempo.yaml.txt](https://github.com/grafana/tempo/files/13295012/tempo.yaml.txt)
> 
> ![screenshot-20231108-173748](https://user-images.githubusercontent.com/37041095/281347160-89098b14-8c09-45c1-8114-cab2e84388d4.png)

@joe-elliott Do I need to optimize my query parameters? Also, would there be any issues with Tempo using Minio with HDD storage? Looking forward to your response.

**Comment by joe-elliott** [comment]
There are no known issues using Minio with HDD storage. If there is a real issue here you will likely need to debug it yourself.
