### ISSUE TITLE
tempo-cli does not support vParquet2 format

### ISSUE THREAD

**Issue by 62mkv** [grafana/tempo#3118]
**Describe the bug**

When trying to run `tempo-cli list index` command against local backend, created by tempo (version main-b6bfb21 (branch: main, revision: b6bfb215a)), running locally in Docker, I get following error:

> tempo-cli: error: main.listIndexCmd.Run(): unsupported block version: vParquet2

If I run, for example, `list blocks` command or `query trace-summary` or `query blocks` command, I just receive smth like 

> total blocks: 0

I believe it's comparing `vParquet2` value from `format` field of a bucket `meta.json` file with `V2` value hardcoded in `tempodb/encoding/v2` module, and fails with `Unsupported format:` but why?? Should not it be supported? As far as I can see from the docs, `tempo-cli` supports Parquet v2 and v3, so what is the issue here? 

PS: the full command for more context: 

> tempo-cli list index single-tenant dfba9636-c391-4e24-8aa2-34b5100e9229 --backend=local --bucket=C:/Users/my-folder/docker-compose-setups/with_postgre/tempo-data/blocks/

**To Reproduce**
1. Start Tempo (version main-b6bfb21 (branch: main, revision: b6bfb215a) in Docker under Windows 10 x64
2. Perform Operations (Read/Write/Others)

**Expected behavior**

I would expect something else (never used tempo-cli before but it would be reasonable to expect some meaningful processing of blocks)

**Environment:**
 - Infrastructure: Docker Compose in Windows x64 host
 - Deployment tool: docker-compose

**Additional Context**

**Comment by 62mkv** [comment]
by the way, I 've opened some of those bucket files with `pyarrow`, look perfectly valid - 8 column, 4634 rows, first column is `TraceID`...

**Comment by 62mkv** [comment]
as one might conclude from the [commit description](https://github.com/grafana/tempo/commit/87f20a071c0c7bf33560e6441253437eb85ac5f7) that has added this check, "only commands specific to V2 are allowed here" so two questions here: 
- is it indeed so that none of this commands is applicable to vParquet2? 
- if so, then probably this should be highlighted both on the website and in the cmd help

**Comment by 62mkv** [comment]
and maybe the error message could be also improved (like "this command is only supported on V2 but block %s format is %s") something like that

**Comment by joe-elliott** [comment]
> I believe it's comparing vParquet2 value from format field of a bucket meta.json file with V2 value hardcoded in tempodb/encoding/v2 module, and fails with Unsupported format: but why?? Should not it be supported? As far as I can see from the docs, tempo-cli supports Parquet v2 and v3, so what is the issue here?

This particular command opens a v2 trace id index and dumps the content. This index simply does not exist in any of the vParquet* formats. I agree the error message could be improved.
