### ISSUE TITLE
Give users the options to output native histograms, instead of classic histograms, from the metrics-generator

### ISSUE THREAD

**Issue by 09jvilla** [grafana/tempo#3119]
**Is your feature request related to a problem? Please describe.**
The Tempo metrics-generator currently outputs a classic histogram, which creates the following 3 metrics:
```
traces_spanmetrics_latency_bucket
traces_spanmetrics_latency_count
traces_spanmetrics_latency_sum
```

**Describe the solution you'd like**
Instead of outputting a classic histogram, I'd like to have the metrics-generator output a native histogram. I know that native histograms is still an experimental feature in Prometheus and Mimir, but its already showing a lot of promise. The benefits of [native histograms ](https://prometheus.io/docs/concepts/metric_types/#histogram)are that they're much higher resolution than classical histograms, which, in this case, gives users a much more precise picture of the distribution of latencies of their spans. They do this at a fraction of the cost it would take to deliver that precision with a classical histogram. 

**Describe alternatives you've considered**
Just stick with outputting native histograms. 

**Additional context**
Metrics-generator should support outputting both classical and native histograms since not all users should be expected to have native histogram ingestion enabled on their Prometheus or Prometheus-compatible database.

**Comment by 09jvilla** [comment]
cc @zhehao-grafana @krajorama for vis

**Comment by 09jvilla** [comment]
Keep alive!

**Comment by 09jvilla** [comment]
@zhehao-grafana mentioned he is following up with another user who was requesting this.

**Comment by mghildiy** [comment]
Maybe I can give it a try, if someone else is not.

**Comment by 09jvilla** [comment]
@mghildiy - Thank you for volunteering! We would really appreciate your help on this. Give us another week or two to find a Tempo maintainer to review the PR you put together and provide input/guidance.

**Comment by mghildiy** [comment]
Ok, I would meanwhile look into current histogram implementation.

**Comment by 09jvilla** [comment]
Sounds great!

**Comment by zalegrala** [comment]
[Tempo now has the ability](https://grafana.com/docs/tempo/next/metrics-generator/#native-histograms) to configure which kind of histograms to [generate on a per-tenant basis](https://grafana.com/docs/tempo/next/configuration/#standard-overrides).  I believe we can close this, but feel free to reopen if we need some follow up.

**Comment by 09jvilla** [comment]
This is awesome, Zach! Congrats on getting this one done. :) 

@zhehao-grafana and I will be reaching out this quarter to figure out how we can start testing this with customers who are already using the metrics-generator.
