### ISSUE TITLE
GRPC endpoint marked in the documentation as deprecated

### ISSUE THREAD

**Issue by iblancasa** [grafana/tempo#3140]
**Describe the bug**
During #2917, the GRPC API endpoint was marked as `deprecated`. During #3045 the documentation change was reverted to remove the documentation related to the WebSocket endpoint and not deprecate the GRPC endpoint. 

But not all the changes were reverted: the website still marks the Tempo GRPC API as deprecated.
https://grafana.com/docs/tempo/latest/api_docs/#tempo-grpc-api

**Comment by joe-elliott** [comment]
Good catch. We are committed to having a streaming endpoint for search results available in Tempo, but we've struggled to find the right technology. 

I am currently leaning toward GRPC (it was my first and preferred option), but we need to work out the issues with port sharing and TLS. In any case, GRPC is definitely _not_ deprecated and will likely be the way we support search streaming in the future. 

HTTP Websockets technically exists in the codebase but is undocumented for a reason. We will only choose this tech if we can't get the details with GRPC ironed out.
