### ISSUE TITLE
Using S3 Backend: Versioned Delete Markers Linger

### ISSUE THREAD

**Issue by gespi1** [grafana/tempo#3141]
**Describe the bug**
While using a Versioned S3 Backend as the storage backend, we noticed that versioned delete marker objects will not be deleted as we have a Lifecycle Config with `Number of newer versions to retain` set to >0 The revisions stay even after an object is deleted. The only options available for clean up via Lifecycle Config  is to not keep revisions and set `Number of newer versions to retain` to 0, as suggested by AWS. 

**To Reproduce**
1. Versioned enabled on S3 Bucket with retention for versions > 0

**Expected behavior**
Tempo (mimir and loki as well) having a way to allows users to version and be able to retain a certain amount of non-current versions while permanently deleting delete markers with non-current versions. 

**Environment:**
 - Infrastructure: [Kubernetes. AWS S3, Loki distributed: 0.69.16]
 - Deployment tool: [helm]

**Additional Context**
Other solutions suggester by AWS 
- When you application is deleting objects, you can issue a DELETE Object specifying the versionId which would delete versioned objects permanently
- Instead of your application issuing a delete command, move the object to a different prefix or apply an object tag. With Lifecycle policies, you can filter objects by prefix or object tags. 

Delete markers are taking up a significant amount of storage on our bucket out of 1million objects in the bucket, 900k are delete markers. Wondering how Tempo team is handling the deletion of versioned delete markers on a S3 versioned bucket? Should we even retain a certain number of versions? 

P.S. shout out to @joe-elliott and the Grafana team for all the help at Kubecon 23'

**Comment by joe-elliott** [comment]
Hey! It was great chatting with you at Kubecon. Thanks for putting together this detailed issue.

My opinion is that Tempo is fine to run without object versioning. If you do want to use object versioning my inclination would be to only support a single version. This would protect you from a bug that accidentally deleted blocks or if an operator accidentally configured a super short retention and Tempo started deleting blocks.

I believe in our cloud env we run settings that retain 1 old version for 1 week. So if there's a bug or a mistake we have 1 week to restore a customer's data.

Do you know how many old versions you are currently retaining? Or does this count not matter at all?

**Comment by gespi1** [comment]
In our prod buckets we do not have any lifecycle policies set, so all versions are being retained. We were testing this on dev to figure out a good balance between versions and pricing. On dev we have `Number of newer versions to retain` set to 10. After reading your comment i will probably set `Days after objects become noncurrent` to something like >= 7 days and `Number of newer versions to retain` == 0. 

You mentioned restoring a version,  im wondering how you would restore and still keep the newer data that was ingested?

**Comment by joe-elliott** [comment]
Let us know how those settings go, hopefully your issue will disappear:

> You mentioned restoring a version, im wondering how you would restore and still keep the newer data that was ingested?

Blocks are immutable. Tempo doesn't append to an existing block it just creates more. So if a block is incorrectly deleted it can be easily restored, the polling cycle will pick it up on the next run through and it will be considered for querying/compaction/deletion.
