### ISSUE TITLE
Docs feedback: /docs/sources/tempo/troubleshooting/unable-to-see-trace.md

### ISSUE THREAD

**Issue by felipewnp** [grafana/tempo#3143]
Hello.

On the Grafana.com website, the docs appear to be outdated compared to the docs in Git Hub.

It shows a flag in [this link](https://grafana.com/docs/tempo/latest/troubleshooting/unable-to-see-trace/) that doesn't exist: "**distributor.log-received-traces**".

But, the file **unable-to-see-trace.md** shows the correct flag "**log-received-spans**"

**Comment by knylander-grafana** [comment]
Thank you for reporting this. I'll take a look.

**Comment by knylander-grafana** [comment]
@felipewnp When I checked the GitHub file, it has the following content: 

```
Add the following flag to the distributor container - [`distributor.log-received-spans.enabled`](https://github.com/grafana/tempo/blob/57da4f3fd5d2966e13a39d27dbed4342af6a857a/modules/distributor/config.go#L55).
```

And the [Troubleshooting page linked above](https://grafana.com/docs/tempo/latest/troubleshooting/unable-to-see-trace/) has this line: 

```
Add the following flag to the distributor container - [distributor.log-received-traces](https://github.com/grafana/tempo/blob/57da4f3fd5d2966e13a39d27dbed4342af6a857a/modules/distributor/config.go#L55).
```

Are you saying that the `distributor.log-received-spans` is incorrect?

**Comment by felipewnp** [comment]
The troubleshooting page should say "distributor.log-received-spans.enabled" instead of "distributor.log-received-traces.enabled"

**Comment by knylander-grafana** [comment]
@felipewnp It looks like this change was corrected in https://github.com/grafana/tempo/pull/3130

I'm going to backport the change to publish it in the docs.

**Comment by knylander-grafana** [comment]
Thank you for opening this issue.
