### ISSUE TITLE
field tolerate_failed_blocks not found in type frontend.Config

### ISSUE THREAD

**Issue by swagsllc** [grafana/tempo#3145]
**Describe the bug**

failed parsing config: failed to parse configFile /conf/tempo.yaml: yaml: unmarshal errors:
  line 135: field tolerate_failed_blocks not found in type frontend.Config

**To Reproduce**
1. helm -n monitoring upgrade --install tempo grafana/tempo-distributed -f ../eks-modules/addons/kube_prometheus_stack/values/grafana-tempo.yaml
2. check logs of pods (tempo-metrics-generator-cf644f7f7-62vd7)

**Expected behavior**

**Environment:**
 - kubernetes
 - Deployment tool: helm

**Additional Context**

**Comment by joe-elliott** [comment]
Hey, `tolerate_failed_blocks` was removed in [v2.2.0](https://github.com/grafana/tempo/releases/tag/v2.2.0). We feel like it was an operational anti-pattern that muddied the waters when using it in conjunction with other features like request retries in the frontend.

If the helm chart still has explicit support for this we should remove it.

**Comment by swagsllc** [comment]
Hey @joe-elliott  Thanks for your response, Can you kindly tell what helm chart version or app version have this fix ? cos the chart version that's giving this error is the latest version which is:

Welcome to Grafana Tempo
 Chart version: 1.7.0
 Tempo version: 2.3.0

**Comment by joe-elliott** [comment]
I don't see `tolerate_failed_blocks` anywhere in the current helm chart. Can you share the contents of `../eks-modules/addons/kube_prometheus_stack/values/grafana-tempo.yaml` ?

**Comment by swagsllc** [comment]
@joe-elliott It's working fine for me now, i noticed i was using the values file for a different chart version. The helm chart version: 1.7.0 works fine now on my system, sorry for the confusion.

Thanks

**Comment by joe-elliott** [comment]
np! glad you got it working

**Comment by swagsllc** [comment]
Hi @joe-elliott 

Apologies for disturbing again, i am currently trying to view traces in grafana tempo datasource, i keep getting 

"0 series returned" error 

Meanwhile looking through the  logs of tempo-distributed-query-frontend pod, i see 

level=info ts=2023-11-16T22:45:33.259575682Z caller=handler.go:135 tenant=single-tenant method=GET traceID=35c0aed0733565a8 url=/api/search/tag/service.name/values duration=1.906359ms response_size=2 status=200

which looks like the app is getting the trace IDs but it's not showing up in grafana..

What do i need to configure in my values.yml to view this output in grafana console..

I am using chart version: 1.7.0, tempo: 2.3.0
