### ISSUE TITLE
[tempo-query] Show operations for a selected service

### ISSUE THREAD

**Issue by manojm321** [grafana/tempo#3158]
**Describe the bug**
In jaeger UI when I select a `Service` the `Operations` field doesn't filter to the right set. It shows all Operations. 

**To Reproduce**
Switch to various services and the Operations count remains the same.

**Expected behavior**
It should filter to a subset of all operations.

**Environment:**
- jaeger 1.47.0
- tempo distributed helm chart: v1.6.1

**Comment by joe-elliott** [comment]
This PR will add the capability to Tempo to correctly filter tag values by existing choices:

https://github.com/grafana/tempo/pull/2942

We will need to add some code to tempo-query to support it, but the capability will be there.

**Comment by nvolker** [comment]
Hey @joe-elliott, we're running into this issue with **tempo-query** whereby it takes 10-30 seconds to search for 20 spans. Compared to Jaeger, which takes 1-2 seconds.

Could we re-open the issue?

**Comment by joe-elliott** [comment]
The headline of this issue does not match the content. I'm going to edit the title. If you're having perf problems with tag search let's start a new issue.
