### ISSUE TITLE
Tempo-Vulture ERROR Logs

### ISSUE THREAD

**Issue by shaheislam** [grafana/tempo#3162]
**Describe the bug**

Tempo-vulture can write logs fine but is failing to query/search traces to validate them. Logs below.

**To Reproduce**

Deploy Tempo v2.3.0

Deploy tempo-vulture 

helm upgrade my-release grafana/tempo-vulture \ 
  --set tempoAddress.push=http://tempo-distributor.tempo.svc.cluster.local \
  --set tempoAddress.query=http://tempo-query-frontend.tempo.svc.cluster.local:3100 \
  --set 'extraArgs={-tempo-org-id=1}'

**Expected behavior**

I would not expect the fields to be unknown, is this due to some compatibility issue?

**Environment:**
Environment: EKS v1.27
Deployment tool: Helm 

**Additional Context**

T=2023-11-21T16:53:51.982Z L=INFO M="sending trace" org_id=1 write_trace_id=4eae568d05fb7da6652b31fc87a252dc seed=1700585505 longWritesRemaining=0
T=2023-11-21T16:53:51.985Z L=INFO M="queueing future batches" org_id=1 write_trace_id=05273fb31c55ee58431d178d21d86d62 seed=1700585565 longWritesRemaining=1
T=2023-11-21T16:54:06.960Z L=INFO M="sending trace" org_id=1 seed=1700585640
T=2023-11-21T16:54:06.960Z L=INFO M="querying Tempo" seed=1700582625 hexID=3028a7177945eb945ec2d8af5a9f5f84 ago=50m21.960729411s
T=2023-11-21T16:54:06.961Z L=INFO M="searching Tempo" seed=1700582685 hexID=6a33083cf79fbc392d3445fe06855a09 ago=49m21.961569217s key=vulture-1 value=KJXioprAbVMvLk
T=2023-11-21T16:54:06.997Z L=INFO M="sending trace" org_id=1 write_trace_id=335fb36f01f96faa3a3ea579aa31ebd3 seed=1700585580 longWritesRemaining=1
T=2023-11-21T16:54:07.021Z L=INFO M="queueing future batches" org_id=1 write_trace_id=335fb36f01f96faa3a3ea579aa31ebd3 seed=1700585580 longWritesRemaining=1
T=2023-11-21T16:54:07.106Z L=ERROR M="failed to search traces with tag vulture-1: error decoding *tempopb.SearchResponse json, err: unknown field \"completedJobs\" in tempopb.SearchMetrics body: {\"traces\":[{\"traceID\":\"6a33083cf79fbc392d3445fe06855a09\",\"rootServiceName\":\"tempo-vulture\",\"rootTraceName\":\"vulture-7\",\"startTimeUnixNano\":\"1700582685000000000\"}],\"metrics\":{\"inspectedTraces\":183,\"inspectedBytes\":\"1686476\",\"totalBlocks\":1,\"completedJobs\":2,\"totalJobs\":2,\"totalBlockBytes\":\"731988\"}}" seed=1700582685 hexID=6a33083cf79fbc392d3445fe06855a09 ago=49m21.961569217s key=vulture-1 value=KJXioprAbVMvLk
T=2023-11-21T16:54:07.107Z L=ERROR M="search for metrics failed" org_id=1 seed=1700582685 error="error decoding *tempopb.SearchResponse json, err: unknown field \"completedJobs\" in tempopb.SearchMetrics body: {\"traces\":[{\"traceID\":\"6a33083cf79fbc392d3445fe06855a09\",\"rootServiceName\":\"tempo-vulture\",\"rootTraceName\":\"vulture-7\",\"startTimeUnixNano\":\"1700582685000000000\"}],\"metrics\":{\"inspectedTraces\":183,\"inspectedBytes\":\"1686476\",\"totalBlocks\":1,\"completedJobs\":2,\"totalJobs\":2,\"totalBlockBytes\":\"731988\"}}"
T=2023-11-21T16:54:21.946Z L=INFO M="sending trace" org_id=1 seed=1700585655
T=2023-11-21T16:54:21.966Z L=INFO M="sending trace" org_id=1 write_trace_id=5e37f72d881aac742f3b51a3ae03aaac seed=1700585595 longWritesRemaining=1
T=2023-11-21T16:54:21.991Z L=INFO M="queueing future batches" org_id=1 write_trace_id=256b938f85959d3107a340f43369a551 seed=1700585655 longWritesRemaining=1
T=2023-11-21T16:54:21.994Z L=INFO M="queueing future batches" org_id=1 write_trace_id=5e37f72d881aac742f3b51a3ae03aaac seed=1700585595 longWritesRemaining=1
T=2023-11-21T16:54:36.956Z L=INFO M="sending trace" org_id=1 seed=1700585670
T=2023-11-21T16:54:36.956Z L=INFO M="querying Tempo" seed=1700585445 hexID=16f34e396cb1686c0ac6c9accc6a587f ago=3m51.95652081s
T=2023-11-21T16:54:36.974Z L=INFO M="sending trace" org_id=1 write_trace_id=0d916b05a0dcf5c71e9a69902d7f2925 seed=1700585610 longWritesRemaining=0

**Comment by joe-elliott** [comment]
It looks like a diffference in the response json is the issue:
```
T=2023-11-21T16:54:07.107Z L=ERROR M="search for metrics failed" org_id=1 seed=1700582685 error="error decoding *tempopb.SearchResponse json, err: unknown field "completedJobs" in tempopb.SearchMetrics body: {"traces":[{"traceID":"6a33083cf79fbc392d3445fe06855a09","rootServiceName":"tempo-vulture","rootTraceName":"vulture-7","startTimeUnixNano":"1700582685000000000"}],"metrics":{"inspectedTraces":183,"inspectedBytes":"1686476","totalBlocks":1,"completedJobs":2,"totalJobs":2,"totalBlockBytes":"731988"}}"
```

Do your versions of Tempo and vulture match?

**Comment by shaheislam** [comment]
@joe-elliott That was it, updating the vulture image corrected it, thank you.
