### ISSUE TITLE
When there are numerous projects causing an overwhelming number of spans, the dropdown list in the Span Name becomes very slow

### ISSUE THREAD

**Issue by halleystar** [grafana/tempo#3190]
**Is your feature request related to a problem? Please describe.**
When there are numerous projects causing an overwhelming number of spans, the dropdown list in the Span Name becomes very slow

**Describe the solution you'd like**
The span name should be associated with the Resource Service Name. Only the span name in the Resource Service Name is displayed.

**Describe alternatives you've considered**
The span name should be associated with the Resource Service Name. Only the span name in the Resource Service Name is displayed.

**Additional context**
![image](https://github.com/grafana/tempo/assets/5334156/bcc48a3e-c7f6-43c5-a6fe-039b8bba3ca6)

**Comment by mapno** [comment]
Hi @halleystar. We've recently added the ability to filter down results based on other existing filters. To enable it, set `autocomplete_filtering_enabled` to true.
