### ISSUE TITLE
Feature request: Generating charts, tables from traceql queries (similar to competitors like Honeycomb)

### ISSUE THREAD

**Issue by pete-woods** [grafana/tempo#3200]
**Is your feature request related to a problem? Please describe.**
Coming from Honeycomb, some equivalent to the span query page is something I'm looking for.

The key thing that's missing is being able to rapidly produce charts and tabular data to answer a question you didn't know you needed to answer. An example might be "discover customers affected by a bad incident who need to be reached out to".

More simple examples are simply producing basic HTTP request charts (i.e. group by method, route, status and the abililty to click through 500s into related traces).

**Describe the solution you'd like**

Pretty much I'm just looking for some analogue of what's in Honeycomb. See screenshot below.

**Describe alternatives you've considered**
In the short term, pumping the data into Clickhouse and quering via Grafana allows us to emulate this functionality, but the user experience leaves an awful lot to be desired.

**Additional context**
![190369047-e5cb456f-c4fe-4c2d-8ca1-77cee609d508](https://github.com/grafana/tempo/assets/152569/e989ead5-a846-46ad-9fbc-798b08ad1af3)

**Comment by pete-woods** [comment]
> Yes! metrics derived from traces are very compelling. We have [posted a TraceQL proposal](https://github.com/grafana/tempo/pull/3138). Please let us know if you have any thoughts!

This sounds promising! Can you clarify if "metrics from traces" means:
1. Creating some kind of pipeline that produces metrics you can later analyse?
2. Or if it means I can from the traceql query page, essentially create arbitrary charts? 

Number 2 is what I was hoping to interpret it as, but the PR page I think assumes too much internal knowledge for me to grok the answer for sure myself.

> In addition we have 2 engineers actively developing this feature with a goal of having beta functionality available early next year.
🎉

**Comment by joe-elliott** [comment]
You are correct. We are working on #2.

#1 already exists in tempo. The metrics generator component can remote write predetermined metrics to a prometheus compatible backend. This covers a lot of cases, but we are adding full dynamic metrics from traces as well.

For example, calculating the rate at endpoints are called would look something like:
```
{ resources.service.name="foo" } | rate(5m) by (span.http.route)
```
or the latency might look like:
```
{ resources.service.name="foo" } | quantile(.99, duration) by (span.http.route)
```

**Comment by pete-woods** [comment]
Sounds fantastic - thanks for all the info!

**Comment by pete-woods** [comment]
😔

**Comment by joe-elliott** [comment]
Hey Pete!

I assure you this is the #1 feature that we are developing right now. We are about to cut 2.4 which will have experimental support for TraceQL metrics.

**Comment by pete-woods** [comment]
Whew! Was just thrown by the ticket being closed as "not planned"
