### ISSUE TITLE
Tempo metrics generator naming convention no longer tracks with current OTel specification

### ISSUE THREAD

**Issue by hedss** [grafana/tempo#3201]
**Describe the bug**
We used to mimic the [spanmetrics processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/README.md) to generate metric names in-line with the convention defined for this processor.

However, the processor has now been deprecated in favour of the [spanmetrics connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/README.md) which also changes the convention of the metrics generated. 

The full list of breaking changes can be seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/README.md#span-to-metrics-processor-to-span-to-metrics-connector

**To Reproduce**
The Intro to MLT repo includes a branch (soon to be merged) that includes the spanmetrics connector via [Flow](https://github.com/grafana/intro-to-mltp/tree/hedss-add-metrics-generation-to-flow) which can be enabled to show the differences. The default dashboards will not work without appropriate changes from `_latency_` to `_duration_milliseconds_` naming.

**Expected behavior**
We should probably support the new naming conventions. *However*, that also potentially breaks customer dashboards in the wild as it would require that any use of the prior metrics naming conventions are now updated. New customers would, of course, expect the new naming convention.

**Environment:**
 - Infrastructure: N/A
 - Deployment tool: N/A

**Comment by gouthamve** [comment]
This is still relevant @zalegrala

**Comment by Jxlam-pdx** [comment]
@electron0zero will do some investigation and from that come up with a plan.

**Comment by hedss** [comment]
One thing to note, the docs for App o11y are very good at distinguising differences between metrics generated by OTel/Alloy/GCT/Tempo. We should probably link to these in the Tempo documentation for clarification.
@knylander-grafana
