### ISSUE TITLE
Problems with Tempo retention

### ISSUE THREAD

**Issue by igorestevanjasinski** [grafana/tempo#3203]
Hey guys, I don't know what I'm doing wrong, but some traces disappear after a couple of minutes, I configured the block_retention to 48h, after 30 minutes some disappear. Any tip?

![image](https://github.com/grafana/tempo/assets/108187126/2d72ec79-19dd-4c4e-a53e-4a700e794d0d)

**Comment by joe-elliott** [comment]
We're going to need more information to help. What do you mean "disappear"? 

If you can spend time more better characterizing the issue we are more likely to be able to help.
