### ISSUE TITLE
Link is not continuous

### ISSUE THREAD

**Issue by yunzck8s** [grafana/tempo#3229]
Query the link information of tranceid in tempo. There is no link for a few![企业微信截图_17024486261604](https://github.com/grafana/tempo/assets/86189975/79bfadf3-353b-4c58-b8de-79483933ab36)
 seconds.
![tempo](https://github.com/grafana/tempo/assets/86189975/adc760e4-a66d-4da8-9ec6-d457adafbf5f)

**Comment by mapno** [comment]
Are you running async operations? That could explain the time in between spans.

**Comment by yunzck8s** [comment]
@mapno Will http blocking cause this problem?

**Comment by mapno** [comment]
Can you explain a bit more? What do you mean by HTTP blocking?

**Comment by yunzck8s** [comment]
> Can you explain a bit more? What do you mean by HTTP blocking?

This is my misunderstanding, I have another question now, why is the first link of mine displayed at the end? My understanding of trance id is that it runs through the entire link.
![Uploading trance.png…]()

**Comment by yunzck8s** [comment]
![trance](https://github.com/grafana/tempo/assets/86189975/fb5ab5ec-5242-4543-a9a8-86c939a7b1c6)

**Comment by mapno** [comment]
It's difficult to know without more information. It's possible that the clock in both machines has a slight drift that's causing this. It could also be related to broken context propagation mixin spans for different traces. Is this happening always for all traces? Is the diff always the same?

**Comment by yunzck8s** [comment]
Yes, the difference is always the same, the judgment is a matter of time between servers, thank you very much!
