### ISSUE TITLE
Service-graph metrics for messaging_system connection type: Taking into account network+middleware latency

### ISSUE THREAD

**Issue by adirmatzkin** [grafana/tempo#3232]
### Discussed in https://github.com/grafana/tempo/discussions/3210

<div type='discussions-op-text'>

<sup>Originally posted by **adirmatzkin** December 10, 2023</sup>
I was wondering about the correctness of the way the service_graph metrics generated by the Metrics Generator are calculated for server side metrics.

As for the "classic" client-server interaction I have no doubt, but for the producer-consumer ones (`connection_type=messaging_system`), I believe it shouldn't be as how it is today (or at least expand to give a solution to another use case).

The case I'm describing is when the **total** latency (from the start time of the producer until the end time of the consumer) is the latency needed to be measured.

Imagine a situation where a message was published to some queue A, (publish span took 10ms), then the message sits in the queue for 20s (because no consumer was available to process another message for example), and then finally pulled and processed in 15ms by the consumer.

The service-graph metrics will only "count" the 10ms for the producer side, and the 15ms for the consumer side ([consumer calculates it's latency by the consumer span duration](https://github.com/grafana/tempo/blob/main/modules%2Fgenerator%2Fprocessor%2Fservicegraphs%2Fservicegraphs.go#L205)),
Leaving the 20s delay not mentioned on any side and in any metric...

I believe this 20s latency should be considered _somehow_, what do you guys think? 🙃

</div>

---

The need this issue comes to address is giving a more comprehensive metric to the calculated latency metric in the service-graph processor - specifically for the `messaging_system` connection_type.
As for today, the latency metric generated in the service-graph processor handles [producer-consumer] spans the same way [client-server] spans are. This situation leads us to essentially disregard the "actual" latency **between** the services.
To create a more "complete" picture, we should take into account the network overhead and middleware latency (for example the time a message waits in a queue).
 
My proposal is as follows:
1. Add a **new** latency histogram metric.
2. The calculation will involve subtracting the **`producer end_time` from the `consumer start_time`.**

That way, if considering the following trace:
```
Span A: |--------------------|
Span B:         (t1)|--------|(t2)
Span C:                                             (t3)|-----------|(t4)
Span D:                                                             |-----|  
```
we will be able to get all possible latencies aggregations:
- `t2-t1` ("span B") - using the client-side metric we already have today.
- `t4-t3` ("span C") - using the server-side metric we already have today.
- `t3-t2` (the missing part this issue comes to solve!)
- Any other combination of summing the above options (`t4-t2` might be an interesting one - the time alapsed from publishing a message to finishing processing it...).

**Comment by adirmatzkin** [comment]
I can take this one in about 2 weeks.
@mapno - what do you think about the proposed solution? 😃

**Comment by mapno** [comment]
I see two options: your proposed solution or reusing the current histogram but storing the new value. I think you're proposal is cleaner, but it'll require work in Grafana to be displayed (unless you're not interested in that). Whereas reusing the current histogram would work "out of the box".

I think both options are viable, I'm happy to let you choose.

**Comment by adirmatzkin** [comment]
I believe the "missing metric" is a different one - not a refinement of the existing one.
Also, overriding the current metric with a different measurement is probably a breaking change that will cause confusion - and for no good reason.

I'm not sure I understand what you mean by "work in Grafana",
Is that for the service-graph tab in Tempo DS?

I'm leaning towards creating a different metric as for now 🙃

**Comment by mapno** [comment]
>I'm not sure I understand what you mean by "work in Grafana",
>Is that for the service-graph tab in Tempo DS?

Yes, I meant for Grafana to represent this new measurement in the service graph view. If it's not within the scope of this change (ie. we just want the new metric), then that's fine.

>I'm leaning towards creating a different metric as for now 🙃

I agree with your thoughts. Let's go for that then :)

**Comment by adirmatzkin** [comment]
@mapno Should we reopen this one?
#3453 is in progress
