### ISSUE TITLE
Tempo treats `span.kind: internal` as a node edge

### ISSUE THREAD

**Issue by asger-noer** [grafana/tempo#3248]
**Describe the bug**
Tempo is treating the `internal` span kind as a virtual node. This leads to service graphs in the Grafana that have a `user` virtual node, when the request is originating from a service already present in the graph. With this, services, that for example execute cron jobs, will have traces showing up as originating from `user` virtual node instead of the service itself.

**To Reproduce**
Tempo connected to Grafana where traces have the following parent/child relation:

`span.kind: internal` -> `span.kind: client` -> `span.kind: server`

**Expected behavior**
I would expect this span kind `internal` to just be ignored when building the service graph as it is local to the service producing first `client` span kind. If the `internal` span  is the first span in a trace I would expect it to be naming the overall trace.

**Environment:**
N/A

**Comment by mapno** [comment]
Hi @asger-noer. [Virtual nodes](https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/#virtual-nodes) are created based on two different conditions, and both should skip internal spans 🤔 . Could you share a sample trace that generates the faulty graph you're describing?

**Comment by asger-noer** [comment]
This one is one me. I was expecting a span from a system but I started the span exporters after the span was created, so it was never sent to the otel-collector and Tempo. The southbound services was then referencing a parent trace that Tempo never received. Mimir and tempo was doing the right thing all along. Sorry for the inconvenience. 😅
