### ISSUE TITLE
Local disk space requirements

### ISSUE THREAD

**Issue by pdeva** [grafana/tempo#326]
This is not clear from docs:

How much local disk space is required, considering a tempo instance first batches data to disk before sending to s3?
At what point is that batch cleared? Is the batch size/flush interval configurable?

**Comment by joe-elliott** [comment]
The size of the required disk will be based on these two parameters and the number of tenants:

https://github.com/grafana/tempo/blob/master/modules/ingester/config.go#L20-L21

Each tenant will have its own WAL file which will be cut and flushed after the first of these two conditions hit.  When its time to flush the WAL it will rewrite it on disk in traceid order before deleting the original which also requires more space.

In our environment with a `traces_per_block` of 100k our WAL normally hits ~2.5 - 3GB when its cut.  Then it requires roughly the same amount of space to rewrite the WAL in order.  In our high volume single tenant internal environment we have about 10GB dedicated to each ingester and have no issues.

Additionally you can increase the value of this timeout to keep a flushed block on disk for longer.  By default it is 5 minutes.
https://github.com/grafana/tempo/blob/master/modules/ingester/config.go#L22

If you decide to significantly increase this value you will also need to take that into account when choosing a disk size.

**Comment by joe-elliott** [comment]
Thank you for the question. Closing to clean things up!
