### ISSUE TITLE
docker-compose examples: Non-multitenant otel-collector example and the local example (maybe others?) currently broken

### ISSUE THREAD

**Issue by sinback** [grafana/tempo#3260]
I'm going to use Tempo to help me profile an application and improve its performance, so I want to be running it in as minimalistic of an environment as possible. I took a look at the docker-compose examples and for both the `local` one and the `otel-collector` one, when I went to go view traces in the Explore -> Tempo section, I got a lot of errors like `rpc error: code = Unknown desc = no org id` and the logs didn't really tell me much more. I spent a long time trying to debug and learn until it started to dawn on me to try the otel-collector-multitenant example, which worked perfectly fine.

I then realized that `example/docker-compose/shared/tempo.yaml` had `multitenancy_enabled: true` at the top! So Tempo was expecting the otel-collector to act like a multitenant reporter, but otel-collector wasn't configured to. It looks like this was a recent change, made in commit 0fc6bf1283, so maybe not all the examples' working-ness got double-checked for that change.

Luckily, once I finally understood what was going on, I worked around it pretty easily, without modifying the shared tempo.yaml config, by going to the docker-compose.yaml for the otel-collector example and changed the tempo Docker command from `command: [ "-config.file=/etc/tempo.yaml" ]` to `command: [ "-config.file=/etc/tempo.yaml", "-multitenancy.enabled=false" ]`. Then everything was fine. I guess putting that field of the tempo.yaml config back to `multitenancy_enbabled: false` would work too. But if you don't want to, note that the flag to enable multitenancy in the `otel-collector-multitenant` example is also now redundant.

I could open a PR to fix it but I don't know what the preferred the stylistic decision would be on where to use flags vs where to change the config file, so I kind of want to leave it up to you all :)

**Comment by mapno** [comment]
Thanks for reporting this! I've created a PR to fix it https://github.com/grafana/tempo/pull/3265
