### ISSUE TITLE
Add readiness probes

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#328]
The kubelet uses readiness probes to know when a container is ready to start accepting traffic. 

These probes should be added to the k8s configs.

**Comment by joe-elliott** [comment]
Agree this would be nice.  Note that all components setup already expose a `/ready` endpoint:

https://github.com/grafana/tempo/blob/master/cmd/tempo/app/app.go#L183

This checks the state of the service manager to make sure that all dependent services are started.

**Comment by joe-elliott** [comment]
Fixed by #531
