### ISSUE TITLE
Cannot get traces from explorer / Query error

### ISSUE THREAD

**Issue by flenoir** [grafana/tempo#3285]
**Describe the bug**
Cannot get traces from explorer search tab / Query error

**To Reproduce**
Installation of Tempo-distributed 2.3.1 version through helm chart

**Expected behavior**
I expect to list result of request

**Environment:**
 - Infrastructure: Kubernetes / grafana 10.2.2 version
 - Deployment tool: helm

**Additional Context**
I just did a fresh installation of Tempo 2.3.1 (tempo-distributed) and when using the search tab in explorer i get an error :

"Query error
rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/plain; charset=utf-8""

![image](https://github.com/grafana/tempo/assets/3592378/7a6fdc0b-bdd2-4902-aec1-3841d57f18f2)

On my Kubernetes cluster i also did install Grafana 10.2.2 version and Opentelemetry Collector (v0.91.1) with helm chart version 0.77.0

Using "deprecated search), the serach is returning datas
![image](https://github.com/grafana/tempo/assets/3592378/b6622c84-2b0e-4be1-a8d5-c2398a5fa281)

Do i miss a setting here ?

**Comment by mapno** [comment]
Hi! It seems like the path to Tempo is not correctly configured. Does trace by ID work? Or does it fail with 404 as well? Can you check if you're using any prefixes in the Tempo server config?

**Comment by arren-ru** [comment]
I've got the same issue with OTEL receiver, tried to push spans using official docu but didn't have success whereas using zipkin receiver all fine.
opentelemetry spans are not shown in search, but zipkin's does
