### ISSUE TITLE
Update AWS SDK so we can use pod identity

### ISSUE THREAD

**Issue by rknightion** [grafana/tempo#3286]
**Is your feature request related to a problem? Please describe.**
We currently can't use AWS EKS Pod Identity instead of IRSA. You get permission denied errors in the default config. 

**Describe the solution you'd like**
Updating the AWS Go SDK to v1.47.11 is the minimum required version to utilise pod identity (https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html)

**Describe alternatives you've considered**
We are still using IRSA for now but pod identity is an AWS supported method to obtain credentials and has some administration benefits in terms of ease of use for users.

**Comment by joe-elliott** [comment]
I am definitely not opposed to this and if you are up to it feel free to submit a PR. However we do mostly interact with S3 through the minio-go sdk:

https://github.com/minio/minio-go

do you know if this supports the feature you are interested in?
