### ISSUE TITLE
docker-compose examples: k6-tracing The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by lusson-luo** [grafana/tempo#3291]
**Describe the bug**
I use tempo docker-compose example start( example/docker-compose/s3), but it don't have arm64 image. I use m2 pro cpu.

**To Reproduce**
1. Start Tempo (SHA or version)
tempo master
3. Perform Operations (Read/Write/Others)
mac m2 pro

**Expected behavior**

normal run

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by mapno** [comment]
Hi! You're right, the builds we have published of [xk6-client-tracing](https://github.com/grafana/xk6-client-tracing/) don't support arm processors. We should support multi-platform builds.

In the meantime, you can build an image from source that's compatible with `GOARCH=amd64 GOOS=linux make docker`. Sorry for the inconvenience.

**Comment by lusson-luo** [comment]
> Hi! You're right, the builds we have published of [xk6-client-tracing](https://github.com/grafana/xk6-client-tracing/) don't support arm processors. We should support multi-platform builds.
> 
> In the meantime, you can build an image from source that's compatible with `GOARCH=amd64 GOOS=linux make docker`. Sorry for the inconvenience.

i resolve it by run main.go, can you push new image to support arm64?
