### ISSUE TITLE
Ingester does not flush on call /shutdown or flush_all_on_shutdown

### ISSUE THREAD

**Issue by madaraszg-tulip** [grafana/tempo#3298]
**Describe the bug**
Ingester fails to flush its data when the /shutdown endpoint is called:

```
level=info ts=2024-01-16T14:03:36.661581721Z caller=flush.go:92 msg="shutdown handler called"
level=info ts=2024-01-16T14:03:36.661641905Z caller=lifecycler.go:533 msg="lifecycler loop() exited gracefully" ring=ingester
level=info ts=2024-01-16T14:03:36.661670623Z caller=lifecycler.go:907 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
level=info ts=2024-01-16T14:03:36.661769772Z caller=lifecycler.go:978 msg="transfers are disabled"
level=info ts=2024-01-16T14:03:36.661801813Z caller=lifecycler.go:995 msg="lifecycler entering final sleep before shutdown" final_sleep=0s
level=info ts=2024-01-16T14:03:36.661851741Z caller=lifecycler.go:585 msg="instance removed from the KV store" ring=ingester
level=info ts=2024-01-16T14:03:36.66251607Z caller=flush.go:177 msg="head block cut. enqueueing flush op" userid=single-tenant block=c9734a5a-1069-43b3-a2a7-9877b6a4f775
level=info ts=2024-01-16T14:03:36.662632056Z caller=flush.go:240 org_id=single-tenant msg="Abandoning op in flush queue because ingester is shutting down" op=0 block=c9734a5a-1069-43b3-a2a7-9877b6a4f775 attempts=1
level=info ts=2024-01-16T14:03:36.662731329Z caller=module_service.go:114 msg="module stopped" module=ingester
level=info ts=2024-01-16T14:03:36.662730418Z caller=flush.go:106 msg="shutdown handler complete"
```

Similar issue happens if `flush_all_on_shutdown` is true and the pod is deleted

**To Reproduce**
1. Start Tempo 2.3.0
2. Send some traces
3. Call the /shutdown endpoint

**Expected behavior**
I expect the block to be flushed to the backend storage, instead of abandoning the operation

**Environment:**
 Deployed to EKS using helm, tempo-distributed version 1.7.3

**Additional Context**
I have found [issue 2609](https://github.com/grafana/tempo/issues/2609) which is basically for the same topic. There is a statement there that after setting up persistent volumes `flush_all_on_shutdown` was working as expected. I suspect that this was because when using persistent volumes, the pod will flush the remaining data to the backend storage **after it has been restarted**. To verify this I set up the backend s3 with a prefix: 

```
  storage:
    trace:
      backend: s3
      s3:
        bucket: ...
        region: us-east-1
        endpoint: s3.us-east-1.amazonaws.com
        prefix: tempo-test1
```

Sent some test traces to the ingesters, then updated prefix to `tempo-test2` and redeployed. The missing data was flushed to s3, but to the new prefix, meaning the flush happened after restart. 

The linked issue also discusses some code paths, and how `i.flushRemaining()` should block until everything is flushed. However the issue is that the codepath from `i.flushRemaining()` -> `i.sweepAllInstances()` -> `i.sweepInstance()` -> `i.enqueue()` results in executing a goroutine, which allows the code in `i.flushRemaining()` to return and `i.flushQueues.Stop()` to be called before the goroutine continues. 

A possible fix would be to execute the actual `i.flushQueues.Enqueue()` synchronously instead of in a goroutine if no jitter was requested: 

```
func (i *Ingester) enqueue(op *flushOp, jitter bool) {
	delay := time.Duration(0)

	if jitter {
		delay = time.Duration(rand.Float32() * float32(flushJitter))
	}

	op.at = time.Now().Add(delay)

	go func() {
		time.Sleep(delay)

		// Check if shutdown initiated
		if i.flushQueues.IsStopped() {
			handleAbandonedOp(op)
			return
		}

		err := i.flushQueues.Enqueue(op)
		if err != nil {
			handleFailedOp(op, err)
		}
	}()
}
```

**Comment by joe-elliott** [comment]
Great catch. Reviewing the code I agree there is a gap here. This was likely introduced when we added jitter to reduce memory spikes on startup and during object storage outages.

Are you interested in submitting a fix?

**Comment by madaraszg-tulip** [comment]
Sure, I'm just quite new to go, and not yet familiar with best practices. I'll submit something today. Considering creating a helper method for what's inside the goroutine except for the Sleep(), to avoid duplication.
