### ISSUE TITLE
tempo pod failing 

### ISSUE THREAD

**Issue by uttarwar-yogesh** [grafana/tempo#3317]
below is my configuration:

apiVersion: v1
data:
  overrides.yaml: "overrides:\n  \"*\":\n    ingestion_rate_strategy:
    \"local\"\n    ingestion_rate_limit_bytes: 20000000\n    ingestion_burst_size_bytes:
    20000000\n    max_traces_per_user: 10000\n    max_global_traces_per_user: 0\n
    \   max_bytes_per_trace: 500000\n    max_bytes_per_tag_values_query: 500000\n
    \   block_retention: 0s \n"
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:

      receivers:
        jaeger:
          protocols:
            thrift_http:
            grpc:
            thrift_binary:
            thrift_compact:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
        opencensus:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    query_frontend:
      search:
        max_duration: 720h

    compactor:
      compaction:
        compaction_window: 1h
        max_block_bytes: 100_000_000
        block_retention: 720h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: azure
        azure:
          storage_account_key: ${STORAGE_KEY}
          storage_account_name: {{ .Values.storageaccountname }}
          container_name: tempo
        pool:
          max_workers: 100
          queue_depth: 10000

    overrides:
      per_tenant_override_config: /conf/overrides.yaml
kind: ConfigMap
metadata:
  name: tempo-config

Errors:
level=info ts=2024-01-22T12:13:00.25878435Z caller=poller.go:237 msg="writing tenant index" tenant=d0120a5f-dc66-4c8a-8c95-437be5fca4af metas=0 compactedMetas=0
level=error ts=2024-01-22T12:13:00.28806891Z caller=poller.go:224 msg="failed to pull bucket index for tenant. falling back to polling" tenant=d06c564a-38fd-4f1a-a4bf-7209a56fa513 err="does not exist"
level=info ts=2024-01-22T12:13:00.294576068Z caller=poller.go:237 msg="writing tenant index" tenant=d06c564a-38fd-4f1a-a4bf-7209a56fa513 metas=0 compactedMetas=0
level=error ts=2024-01-22T12:13:00.319097585Z caller=poller.go:224 msg="failed to pull bucket index for tenant. falling back to polling" tenant=d07be046-fdb4-439b-ad5a-ed949e0a52ea err="does not exist"

**Comment by joe-elliott** [comment]
I believe this is the same issue:
https://github.com/grafana/tempo/issues/2878

It occurs when you have a partial block under a tenant.

**Comment by uttarwar-yogesh** [comment]
May I know the steps to fix this ?

**Comment by joe-elliott** [comment]
Look for the partial block and remove it.

**Comment by uttarwar-yogesh** [comment]
we are facing this issue, when we restart the pod .. is there a way to fix the issue permanently ?
