### ISSUE TITLE
TraceQL: Certain queries fail to return root service name

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#3327]
The following query fails to return the root service name correctly. Note that it is returning the root span name so there is root information:

```
{ rootServiceName != "" } | by(name) | count() > 100
```

![image](https://github.com/grafana/tempo/assets/2272392/e9cedce7-7eaa-47fd-b615-baeea4ccfd1f)

**Comment by javiermolinar** [comment]
It this still happening @joe-elliott? I'm not able to reproduce it
![Image](https://github.com/user-attachments/assets/650d4aa5-6518-4113-bf70-5d425f9217cd)

**Comment by joe-elliott** [comment]
I'm also unable to repro. Closing!
