### ISSUE TITLE
If the link exceeds 1 minute, there will be discontinuity, resulting in incorrect time.

### ISSUE THREAD

**Issue by yunzck8s** [grafana/tempo#3335]
There is a time difference of about 4 seconds or higher between my multiple kubernetes nodes. Then when I check the link in grafana tempo, there are generally many interrupted links in the trance of more than 1 second. I suspect that the server time difference causes this interruption.

Kubernetes version: v1.24.2
contained version: v1.6.8
grafana version:  9.4.7
tempo version: 2.3.0
opentelemetry-operator version: v0.90.0

```
grafana tempo values.yaml

---
storage:
  trace:
    backend: s3
    s3:
      access_key: 'minio'
      secret_key: 'minio123123'
      bucket: 'tempo-traces'
      endpoint: 'minio.middle:9000'
      insecure: true
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false

My OpenTelemetryCollector configuration:

kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: syncplant-backend
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      otlp:
        endpoint: http://10.128.14.49:32621
        tls:
          insecure: true
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,otlp]
```
![image](https://github.com/grafana/tempo/assets/86189975/886a845d-3c05-4f59-8a31-12d75264a9e6)

**Comment by kvrhdn** [comment]
Can you describe what you expect to happen? It looks like the child spans with the red-ish color happen _before_ their parent spans which shouldn't be possible?

Tempo does not inject or add any timestamps to ingested spans. The timestamp on the span is created by the tracing client. So it looks like the system clocks of the nodes in your system aren't in sync.
