### ISSUE TITLE
spanmetrics generator creates negative values for traces_spanmetrics_latency_bucket

### ISSUE THREAD

**Issue by mar4uk** [grafana/tempo#3338]
**Describe the bug**
When spanmetrics metrics-generator is enabled sometimes it generates negative values for traces_spanmetrics_latency_bucket
The corresponding issues in app-o11y https://github.com/grafana/app-o11y/issues/497, https://github.com/grafana/app-o11y/issues/178

**To Reproduce**
It reproduces from time to time. There is no reliable way to reproduce this

**Expected behavior**
There should be no buckets with negative values because latency is always non-negative

**Comment by kvrhdn** [comment]
Doing a quick scan through the code, this is where we calculate the latency of each span:

https://github.com/grafana/tempo/blob/7d9defd2c802af7672412c309efbff11cd089733/modules/generator/processor/spanmetrics/spanmetrics.go#L141

We observe it here:

https://github.com/grafana/tempo/blob/7d9defd2c802af7672412c309efbff11cd089733/modules/generator/processor/spanmetrics/spanmetrics.go#L206-L208

So likely culprit seem to be:
- the end timestamp is earlier than the start, I'm not sure if this can happen, I'd imagine instrumentation should prevent this from happening
- span multiplier could be negative, but we calculate it here and there is a check to make sure this value isn't negative

https://github.com/grafana/tempo/blob/7d9defd2c802af7672412c309efbff11cd089733/modules/generator/processor/util/util.go#L33-L46

**Comment by kvrhdn** [comment]
Is there anything special about the spans this is happening to? Does this happen to a lot of spans or just a few, are they especially short?

**Comment by cedricziel** [comment]
hi @kvrhdn - we have a live example with accessible traces here https://otlpcortexdev01.grafana-dev.net/a/grafana-app-observability-app/services/python3.11?var-prometheus=grafanacloud-prom&var-loki=grafanacloud-logs&var-tempo=grafanacloud-traces&var-pyroscope=grafanacloud-profiles&var-environmentValue=$__all&var-groupBy=__empty

**Comment by mar4uk** [comment]
> Is there anything special about the spans this is happening to? Does this happen to a lot of spans or just a few, are they especially short?

In the case Cedric mentioned above, there are spans `GET /alive` that take ~1-2ms
<img width="1242" alt="Screenshot 2024-02-06 at 12 41 50" src="https://github.com/grafana/tempo/assets/2266206/2b4896e8-3850-4cbf-9e75-64780b91a629">
