### ISSUE TITLE
[DOC] How to build your own service graphs using the Node Graph visualisation from Tempo generated metrics

### ISSUE THREAD

**Issue by hedss** [grafana/tempo#3341]
Customers have asked for it in the past, we should really document the queries and a couple of examples of how to build this out in a dashboard panel.

**Comment by ilyamochalov** [comment]
@hedss @knylander-grafana 
I was able to create service graph visualization. All data transformations are done with Prometheus `label_join` operators. It does most of the job done, but leaves us with limitations that can not be compensated even by Grafana transform data feature. Some limitations:
- unable to add request stats to nodes and edges, such RPS and error rates
- unable to ad custom icons for nodes

Shall I make a PR adding docs to [https://github.com/grafana/tempo/tree/main/docs/sources/tempo/metrics-generator/](https://github.com/grafana/tempo/tree/main/docs/sources/tempo/metrics-generator/service_graphs)

![Screenshot 2024-06-07 at 16 02 26](https://github.com/grafana/tempo/assets/17251978/d30927e6-e097-4212-9e7e-af34d203a903)
