### ISSUE TITLE
Build tempo-query as part of goreleaser release process

### ISSUE THREAD

**Issue by dylanyht** [grafana/tempo#335]
Can I install tempo directly on the physical machine? I only found the executable file of tempo but not the tempo-query

**Comment by joe-elliott** [comment]
So there is no reason you can't run this on bare metal.  However, you are right that we are not building the tempo-query GRPC plugin.  I will create an issue to add it.

In the meantime if you pull the repo and run `make vendor-check` for dependencies and then `make tempo-query` then it should build.

Note that tempo-query is a plugin for Jaeger query.  Check out the Dockerfile to see how it is configured:

https://github.com/grafana/tempo/blob/master/cmd/tempo-query/Dockerfile
