### ISSUE TITLE
Is there a way to figure out the size of trace getting ingested in Grafana tempo 

### ISSUE THREAD

**Issue by SimranCode** [grafana/tempo#3351]
We want to add the limit on the size of data that gets ingested to Grafana tempo (traces stored in Azure blob) to save on the cost
So to identify the ideal size limit , I want to view the size of the traces that are getting pushed to Grafana tempo.

Is there any way by which we can find that out , through trace QL or something else?

**Comment by SimranCode** [comment]
Any one has any idea on this?

**Comment by kvrhdn** [comment]
Hi, you can use span metrics to gather aggregated data about span size. Note this works on spans, not traces.

Span metrics creates `traces_spanmetrics_size_total` which counts size of spans agggregated to preconfigured dimensions.
https://grafana.com/docs/tempo/latest/metrics-generator/span_metrics/

**Comment by joe-elliott** [comment]
agree with @kvrhdn that there may be no direct way to get what you want. other solutions that may work are:

use the "trace summary" cli command. this will search backend blocks directly and give information about large traces:
https://grafana.com/docs/tempo/latest/operations/tempo_cli/#query-trace-summary-command

use the `tempo_distributor_bytes_received_total` metric as well as the `tempo_ingester_traces_created_total` to get a rough sense of trace size. note that `tempo_ingester_traces_created_total` needs to be divided by replication factor
