### ISSUE TITLE
Grafana Tempo - Creates a junk data in Azure Object Storage in case of multi tenancy enabled

### ISSUE THREAD

**Issue by SimranCode** [grafana/tempo#3356]
**Describe the bug**
I have multi tenancy enabled in Grafana tempo and the data coming from specific tenant gets stored in the respective tenant folder auto-created in Azure blob .

For some reason , I see a lot of junk folders other than actual tenant folders getting created whose meta.json file does not have the tenant id stamped. 

Can someone help me understand why these junk folders are getting created and if there is a way to avoid the creation.

In the below image only 2 folders are actual tenants, other 2000 plus folders are junk.

<img width="315" alt="Capture1" src="https://github.com/grafana/tempo/assets/43096044/0629b0b7-e396-4278-800b-feebaa258ef3">

**Comment by joe-elliott** [comment]
What are the contents of the "junk" folders?

**Comment by SimranCode** [comment]
<img width="679" alt="Capture" src="https://github.com/grafana/tempo/assets/43096044/67fc4ae9-e2eb-4438-b7fc-6533e3fb1010">

All those folders have the data in this trace data format

**Comment by SimranCode** [comment]
Also , the meta.json file above doesnt have tenant id stamped , so that how I thought as its not linked to any Tenant , it would be a junk data.

**Comment by joe-elliott** [comment]
that's odd. tempo is somehow accepting traces with an empty tenant and writing them to the object storage root.

metrics like `tempo_distributor_bytes_received_total` are per tenant. are you seeing empty tenants there?

**Comment by SimranCode** [comment]
Metrics are not setup for tempo , so I cannot see this metrics. 
If multi tenancy is enabled , It shouldn't be accepting the trace without tenant id right ?
Is there a way to avoid creating traces for empty tenant.

**Comment by joe-elliott** [comment]
> Metrics are not setup for tempo , so I cannot see this metrics.

it's going to be difficult to operate tempo/debug issues w/o metrics. i'd recommend setting this up.

> If multi tenancy is enabled , It shouldn't be accepting the trace without tenant id right ?

correct, it should require a tenant set in the `X-Scope-OrgID` header. I'm wondering if a strange value is being inserted into that header which is causing the storage layer to interpret it as empty string.
