### ISSUE TITLE
Add Redis caching on Tempodb

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#337]
**Is your feature request related to a problem? Please describe.**
Right now Tempodb supports Diskcache and Memcached. Could be interesting to support Redis too!

**Describe the solution you'd like**
A Redis caching integration for Tempodb.

**Describe alternatives you've considered**
None

**Comment by dgzlopes** [comment]
I've been reading the code from `github.com/cortexproject/cortex/pkg/chunk/cache` for Redis. Looks straightforward :) 

Right now Tempo uses Cortex v1.3.0. I saw that in v1.4.0 Cortex devs refactored Redis code and added some [handy features](https://github.com/cortexproject/cortex/releases/tag/v1.4.0). 

It's OK to upgrade Tempo to Cortex >= v1.4.0? Could facilitate the development/maintenance of this feature.

**Comment by joe-elliott** [comment]
Yes, we have no issues upgrading the Cortex dependency, but let's make that a stand alone PR.

**Comment by dgzlopes** [comment]
This one can be closed! We merged #354
