### ISSUE TITLE
Distributor Ring HTTP 404

### ISSUE THREAD

**Issue by bradleypettit** [grafana/tempo#3385]
**Describe the bug**
The distributor ring is not available and produces a 404.

**To Reproduce**
1. Start Tempo (2.3.1)
2. Request '/distributor/ring' from any of the distributor pods

**Expected behavior**
The details of the distributor ring similar to other services that expose a ring.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Additional Context**
Noticed that the Distributor Ring is not working in the latest GET plugin. Found that the latest version of GET does not have the /distributor/ring available, and checked that the latest version of OSS Tempo does not either.

Helm Chart: tempo-distributed-1.8.3 
Images: docker.io/grafana/tempo:2.3.1 & docker.io/grafana/enterprise-traces:v2.3.2 both tested
Plugin:v2.2.2

**Comment by joe-elliott** [comment]
The distributor does not create its ring unless global rate limits are used:

https://grafana.com/docs/tempo/latest/operations/consistent_hash_ring/#distributor

I can confirm that the `/distributor/ring` page is present in our internal deployments.

**Comment by bradleypettit** [comment]
Ah I totally missed that obvious disclaimer while going through the different repos & readmes, thanks for pointing that out Joe. I'll close this and potentially look at adding some more info to the message shown in the GET plugin when it's not present.
