### ISSUE TITLE
Add support for Azure Blob Storage

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#340]
**Is your feature request related to a problem? Please describe.**
Tempo currently supports s3 and gcs.  It would be nice if it supported Azure as well.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
These are the interfaces that must be implemented to add a new backend: https://github.com/grafana/tempo/blob/master/tempodb/backend/backend.go

**Comment by calvernaz** [comment]
The Azurite emulator can be useful to test against this backend.

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite

**Comment by pedrosaraiva** [comment]
We are currently using Grafana and Loki in our platform, so Grafana tempo seems the right fit for us in the near future. 
I made a WIP PR to implement Azure storage since run on Azure would be a requirement for us. :)
