### ISSUE TITLE
Is Grafana Tempo FIPS compliant?

### ISSUE THREAD

**Issue by vsawant1608** [grafana/tempo#3416]
Our organization wants to make sure it uses all FIPS compliant tools.

To be FIPS compliant, an organization must adhere to the various data security and computer system standards outlined in the Federal information processing standards (FIPS).

Want inputs on whether Grafan tempo is FIPS compliant.

**Comment by joe-elliott** [comment]
For legal reasons I can't claim that Tempo is or is not FIPS compliant.

Grafana Tempo OSS is almost certainly not. The next release of our [enterprise product](https://grafana.com/docs/enterprise-traces/latest/) will have an optional install image compiled with [BoringCrypto](https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/FIPS.md) which has been FIPS validated.
