### ISSUE TITLE
Tempo TLS secrets mount not working

### ISSUE THREAD

**Issue by samyak335** [grafana/tempo#3439]
**Describe the bug**
Having issue to mount a TLS key and cert files on to tempo container , as it does not have extraContainerVolumes/volumes section in values.yaml. For example i need to mount certificates and keys on to tempo container i need create a secret for the cert file and key file and have  to provide configuration as shown below in the values.yaml .But as extraContainerVolumes/volumes section is not present in values.yaml file, having issue to mount certs.

**extraContainerVolumes:**
   - name: tempo-certs
     secret:
       secretName: tempo-certs
   - name: tempo-keys
     secret:
       secretName: tempo-keys

**extraVolumemounts:**
    - name: tempo-certs
      mountPath: /etc/tempo/cert
      readOnly: true
    - name: tempo-keys
      mountPath: /etc/tempo/key
      readOnly: true

**To Reproduce**
1. Create a secret for key and cert files as shown below 
kubectl create secret generic tempo-certs --from-file=example.crt=/root/example.crt
kubectl create secret generic tempo-keys --from-file=example.key=/root/example.key

2. Try to mount the secrets on to the container by specifying the volume mounts and volumes  in values.yaml as shown below (note: **extraContainerVolumes:** is not present in the values.yaml)

**extraContainerVolumes:**
   - name: tempo-certs
     secret:
       secretName: tempo-certs
   - name: tempo-keys
     secret:
       secretName: tempo-keys

**extraVolumemounts:**
    - name: tempo-certs
      mountPath: /etc/tempo/cert
      readOnly: true
    - name: tempo-keys
      mountPath: /etc/tempo/key
      readOnly: true

**Expected behavior**
values.yaml should have a section named as volumes or extraContainerVolumes to mount the certs and keys .

**Environment:**
 - Infrastructure:  kuburnetes
 - Deployment tool:  helm

**Additional Context**
I have tried extraArgs ,extraEnv, extraEnvFrom sections in values.yaml but it didnt work faced errors.

**Comment by joe-elliott** [comment]
Is this a helm issue? and not a Tempo issue?

**Comment by samyak335** [comment]
In general how do we use  cert file and key file for tempo , how do we do it in helm ?

**Comment by joe-elliott** [comment]
tls config docs are here: https://grafana.com/docs/tempo/latest/configuration/network/tls/

i do not know how one would do that in helm

**Comment by jeffreyflynt** [comment]
You'd have to do it like this:

```
tempo:
  extraVolumeMounts: 
  - name: tempo-certs
    mountPath: /path
extraVolumes:
  - name: tempo-certs
    secret:
       secretName: tempo-certs
```

**Comment by samyak335** [comment]
Thanks , i  have added the following in my values.yaml file , its not displaying any errors while doing helm install, but tempo pod is not created. If i remove the secrets pod is being created.

tempo:
  extraVolumeMounts:
    - name: tempo-certs
      mountPath: /etc/tempo/cert
      readOnly: true
    - name: tempo-keys
      mountPath: /etc/tempo/key
      readOnly: true
  extraVolumes:
    - name: tempo-certs
      secret:
       secretName: certs
    - name: tempo-keys
      secret:
       secretName: keys

**Comment by jeffreyflynt** [comment]
@samyak335 You'd have to debug further. An option could be `kubectl describe pod xxxxxxx -n namespace` or `kubectl -f logs xxxxxx -n namespace` and see what error you are now encountering. 

Here is more info: https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/

**Comment by samyak335** [comment]
@jeffreyflynt i have checked the event logs and i have came across this warning as shown below.

>  Warning   FailedCreate              statefulset/tempo   create Pod tempo-0 in StatefulSet tempo failed error: Pod "tempo-0" is invalid: [spec.containers[0].volumeMounts[0].name: Not found: "tempo-certs", spec.containers[0].volumeMounts[1].name: Not found: "tempo-keys"]

**Comment by jeffreyflynt** [comment]
@samyak335 
I have this setup in my environment. You can see extraVolumes listed here: https://github.com/grafana/helm-charts/blob/main/charts/tempo/README.md. Which helm chart are you using?

**Comment by samyak335** [comment]
@jeffreyflynt Thanks . My mistake i had tried placing  extraVolumes inside tempo block , rather than giving outside of it. Once i placed it outside tempo block it worked.
