### ISSUE TITLE
traceQLStreaming options is not working

### ISSUE THREAD

**Issue by kadhamecha-conga** [grafana/tempo#3452]
hi team,

Traceql streaming option is not available in grafana even after traceQLStreaming feature toggle enabled.

tempo datasource in grafana is configured to use  http://tempo-query-frontend:3100 and http_over_streaming_enabled option is also set to true in tempo.

let me  know , if i'm missing any config.

version:
grafana: 10.2.0
tempo: 2.3.1

thanks.
kapil

**Comment by mapno** [comment]
Hi! Are you getting any errors in Tempo or is data just not being streamed? Also, the config parameter for HTTP streaming is [`stream_over_http_enabled`](https://grafana.com/docs/tempo/latest/api_docs/#tempo-grpc-api), but you shouldn't need. It should work fine over gRPC.

**Comment by luistilingue** [comment]
My problem is on Grafana https://github.com/grafana/grafana/issues/81998
