### ISSUE TITLE
Label improvements for Service identification

### ISSUE THREAD

**Issue by t00mas** [grafana/tempo#3461]
**Is your feature request related to a problem? Please describe.**

The current reliance on the `connection_type` label values for the purpose of identifying if a node is un-instrumented is problematic. For example, its `virtual_node` value alone doesn't identify which node is the `virtual` one. A similar issue arises with the `database` and `messaging_system` values, or even if there's a confluence of any of those in the same mode.

In the case of `database` and `messaging_system`, further identification relies on inspection of resource attributes (`db.system` and `messaging.system`, for example).

**Describe the solution you'd like**

Ideally:

1. In the cases where `connection_type` had the value of `virtual_node`, we’d like to generate a new label `virtual_node` with a value of either `client` or `server`.

2.1. In the cases where `connection_type` is of value `database`, then we'd like to surface either `client_db_system` or `server_db_system` labels, with the same value as the `db.system` resource attribute.

2.2. In the cases where `connection_type` is of value `messaging_system`, then surface either `client_messaging_system` or `server_messaging_system` labels, with the same value as the  `messaging.system` resource attribute.

**Describe alternatives you've considered**

We've also considered adding more values to `connection_type` itself, with the drawback of it not being enough to cover all cases of client/server and intersection of the previous values.

**Additional context**

Resources:

- You can follow discussion, comments, and links to original issues in this [DesignDoc](https://docs.google.com/document/d/1t3d4P7a6Yo_0Ly5zLpovC1rLqCCKj3G_SsrBuiMqijc/edit).

I have bandwidth to propose PR(s), as necessary.

**Comment by joe-elliott** [comment]
Thanks for the detailed overview.

> In the cases where connection_type had the value of virtual_node, we’d like to generate a new label virtual_node with a value of either client or server.

This makes sense to me and I'm good on the addition.

> 2.1. In the cases where connection_type is of value database, then we'd like to surface either client_db_system or server_db_system labels, with the same value as the db.system resource attribute.

For databases it looks like we already attempt to extract the database name and add it:

https://github.com/grafana/tempo/blob/baddeafb52d35b5c50bc1d0c8f8f543f6442ea47/modules/generator/processor/servicegraphs/servicegraphs.go#L187-L192

> 2.2. In the cases where connection_type is of value messaging_system, then surface either client_messaging_system or server_messaging_system labels, with the same value as the messaging.system resource attribute.

Currently if we detect a `connection_type` of `messaging_system` it looks like we record the two services on either side and no details about the messaging system itself. Is that what you're trying to add?

cc @mapno b/c he knows this code better than myself

**Comment by t00mas** [comment]
Thanks! Just a note to add here @joe-elliott

What we refer to for 2.1 is db.system intentionally (not db.name), because it's what will unlock UX objectives.

And, yes, in 2.2 the addition is both about knowing about the messaging.system itself, mainly, but also note that, in general, what we try to achieve is having as much information as possible about each of the sides, especially if they're un-instrumented/virtual.

**Comment by joe-elliott** [comment]
> What we refer to for 2.1 is db.system intentionally (not db.name), because it's what will unlock UX objectives.

Apologies, misread that. I have no issue with adding a new label with the value of db.system. Generally I'm guessing this won't increase cardinality b/c db.name is more specific and already included. i.e. a database with a given name should always be the same system. This might not be true in some cases, but I think it's generally ok.

Overall, this looks good to me. It's adding some interesting data w/o impacting cardinality. I would be glad to take this PR.

**Comment by t00mas** [comment]
Thanks Joe - I'll draft a PR as soon as I'm back on 2024/04/01
