### ISSUE TITLE
Error: error copying block from local to remote backend

### ISSUE THREAD

**Issue by flenoir** [grafana/tempo#3468]
**Describe the bug**
Hi, after a while on using Tempo. I get this kind of error messages :
I get an error message "err="error copying block from local to remote backend: error writing object to s3 backend, object single-tenant/e4e7ad1b-c753-4496-82f6-87e56504755a/data.parquet: Check if quota has been exceeded or object has too many versions"

This may be related to the fact that Compactor pod did a restart

**To Reproduce**
Use Tempo as expected and store data on a s3 bucket

**Expected behavior**
Not having this error message

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - S3 Buckets are hosted on Dell ECS

**Comment by joe-elliott** [comment]
I have never used Dell ECS before nor have we ever seen that error. Did you check what the error message suggested?
