### ISSUE TITLE
Allow querying traces by span instrumentation "Library Name"

### ISSUE THREAD

**Issue by atsu85** [grafana/tempo#3500]
**Is your feature request related to a problem? Please describe.**
I'm trying to find traces with spans created by specific library name.

**Describe the solution you'd like**
TraceQL query should support finding traces that have spans with specific library name. For example, smth like following pseudocode:
```TraceQL
{ resource.service.name="skeleton-nestjs" && instrumentationLibrarySpans.instrumentationLibrary.name="@opentelemetry/instrumentation-http"}
```
to match traces similar to the example screenshot from Grafana:
![image](https://github.com/grafana/tempo/assets/1206512/0f6da491-433f-4e62-9713-eafda6067163)

When exporting the example trace to JSON (from Grafana), then it looks like following:
```JSON
{
  "batches": [
    {
      "resource": {
        "attributes": [
          ...
        ],
        "droppedAttributesCount": 0
      },
      "instrumentationLibrarySpans": [
        {
          "spans": [
            {
              "traceId": "1245cf2e87b6be30ed3700f1c126b557",
              "spanId": "0882ee038dfdb585",
              "parentSpanId": "0000000000000000",
              "traceState": "",
              "name": "GET /ping",
              "kind": "SPAN_KIND_SERVER",
              "startTimeUnixNano": 1710846323303000000,
              "endTimeUnixNano": 1710846323303740000,
              "attributes": [
                ...
              ],
              "droppedAttributesCount": 0,
              "droppedEventsCount": 0,
              "droppedLinksCount": 0,
              "status": {
                "code": 0,
                "message": ""
              }
            }
          ],
          "instrumentationLibrary": {
            "name": "@opentelemetry/instrumentation-http", // this is the attribute to match using TraceQL
            "version": "0.49.1"
          }
        }
      ]
    },
  ]
}
```

**Additional context**
If it would be possible to find traces based on instrumentation library name, i could figure out the traces that are used for specific service (without looking at its code) to understand what instrumentation libraries could be disabled (to speed up [application startup time that is super-slow when using auto-instrumentation for nodejs applications](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1953#issuecomment-1961107798))

**Comment by devurandom** [comment]
https://github.com/grafana/tempo/pull/3967 implements this.

**Comment by atsu85** [comment]
the PR #3967 that implements this feature is now merged :+1:
(although the task was closed as stale before it got merged)
