### ISSUE TITLE
Grafana Tempo throws no org Id Error even after disabling Multi tenancy

### ISSUE THREAD

**Issue by SimranCode** [grafana/tempo#3512]
Hi ,

I have the Observability Setup hosted in AKS 
I am trying to disable the Multi tenancy in Grafana tempo as I want to setup Tail Sampling
**Tempo Config Change** : multitenancy.enabled=false
And I have also removed the header **X-Scope-OrgId** from the tempo data source passed in grafana.
And I was earlier using headers setter extension in otel config to set the tenant id , I have removed that as well now since multi tenancy is disabled.

below is the updated otel config

Otel Config : 

extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-Scope-OrgID
        from_context: tenantid
receivers:
  otlp:
    protocols:
      grpc:
        # include_metadata: true
        endpoint: 0.0.0.0:5555
      # http:
      #   include_metadata: true
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"   
  otlp:
    endpoint: "http://tempo:4317"
    # tls:
    #   insecure: true
    tls:
      insecure: true
    # auth:
    #   authenticator: headers_setter
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    # auth:
    #   authenticator: headers_setter
processors:
  transform:
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["TenantName"], resource.attributes["tenantid"])
  
service:
 // extensions: [headers_setter]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [transform]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: []

But after doing the above changes I still get the error in Grafana Tempo :

 Query error
**Error (Authentication to data source failed). Please check the server logs for more details.**

And In server Logs  : It says **"tempo : no org Id found"**

Any help/inputs will be highly appreciated.
Thanks in advance .

**Comment by mapno** [comment]
Hi, can you share your Tempo config?

**Comment by SimranCode** [comment]
apiVersion: v1
data:
  overrides.yaml: "overrides:\n  \"*\":\n    ingestion_rate_strategy:
    \"local\"\n    ingestion_rate_limit_bytes: 20000000\n    ingestion_burst_size_bytes:
    20000000\n    max_traces_per_user: 10000\n    max_global_traces_per_user: 0\n
    \   max_bytes_per_trace: 1000000\n    max_bytes_per_tag_values_query: 1000000\n
    \   block_retention: 0s \n    metrics_generator_processors: ['service-graphs', 'span-metrics']\n"
  tempo.yaml: |
    multitenancy_enabled: false
    server:
      http_listen_port: 3200

    distributor:

      receivers:
        jaeger:
          protocols:
            thrift_http:
            grpc:
            thrift_binary:
            thrift_compact:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
        opencensus:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 5_000_000
      max_block_duration: 5m
      complete_block_timeout: 12h

    query_frontend:
      search:
        max_duration: 336h

    compactor:
      compaction:
        compaction_window: 1h
        max_block_bytes: 5_000_000
        block_retention: 720h
        compacted_block_retention: 12h
    metrics_generator:
      processor:
        service_graphs:
          enable_client_server_prefix: true
        span_metrics:
          enable_target_info: true
      registry:
        external_labels:
          source: tempo
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://mimir-nginx.default.svc.cluster.local:80/api/v1/push
            send_exemplars: true


    storage:
      trace:
        backend: azure
        azure:
          storage_account_key: ${STORAGE_KEY}
          storage_account_name: {{ .Values.storageaccountname }}
          container_name: tempo
        blocklist_poll: 6h
        blocklist_poll_concurrency: 100
        blocklist_poll_tenant_index_builders: 1
        blocklist_poll_jitter_ms: 500
        blocklist_poll_fallback: false
        pool:
          max_workers: 1000
          queue_depth: 10000

    overrides:
      per_tenant_override_config: /conf/overrides.yaml
kind: ConfigMap
metadata:
  name: tempo-config

**Comment by SimranCode** [comment]
Hi @mapno 
Issue was with the deployment file. the multitenancy was set to true in deployment.yaml.

Issue is resolved.
Appreciate your quick response. Thankyou
