### ISSUE TITLE
Span count diff between tempo cli and grafana ui

### ISSUE THREAD

**Issue by edgarkz** [grafana/tempo#3555]
**Describe the bug**
Tempo cli `query trace-summary` shows 2 spans in count while the Grafana search of same trace id shows only 1 span.

**To Reproduce**
Search for specific trace summery and see the result 
Search for the same traceid in grafana ui - shows only 1 span

`
 go run ./cmd/tempo-cli query trace-summary fba16576765b0d04668c2a63e568a7de single-tenant  --backend=s3 --bucket=xxxxxx --s3-endpoint s3.us-east-1.amazonaws.com        
total blocks to search:  784
...........................0..........................................................................100....................................................................................................200....................................................................................................300....................................................................................................400....................................................................................................500....................................................................................................600....................................................................................................700...................................................................................Number of blocks: 2 
Span count: 2 
Trace size: 2338 B 
Trace duration: 0 seconds 
`

![image](https://github.com/grafana/tempo/assets/68842306/65fe5b7e-518f-4426-aa6d-62051cf64811)

**Expected behavior**
Trace should have exact same amount of spans in both queries

**Environment:**
Eks 1.26
Tempo 2.4.1 deployed via helm chart distributed
Grafana 10.4

**Comment by joe-elliott** [comment]
The trace-summary is designed to give summary information about traces that are so large that attempting to recombine them from the backend blocks is not worth it. For instance, It's not uncommon to persist a trace id in a batch job over days and create multi GB traces that Tempo cannot return through it's normal http endpoint. This cli command gives an operator insight into that trace to help them track down the offending process.

B/c it's designed to work with such large traces it does not attempt to recombine/dedupe the span ids. Those "2 spans" are the same span not deduped.

Use "query blocks" to query trace ids directly from the blocks and fully dedupe them:

https://grafana.com/docs/tempo/latest/operations/tempo_cli/#query-blocks-command

This is not particularly well named. The CLI tool could use a reorganization and cleanup pass.
