### ISSUE TITLE
Add reference for configuration docs

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#356]
**Is your feature request related to a problem? Please describe.**
I like the configuration docs. They are straightforward and explain the more used options.

But... We don't have a structured reference (like [Loki](https://grafana.com/docs/loki/latest/configuration/) and [Cortex](https://cortexmetrics.io/docs/configuration/configuration-file/) have). Right now, knowing all the configuration options for Memcached, limits or X involves taking a look at the code or asking on Slack.

**Describe the solution you'd like**
Some kind of structured docs that users/operators can reference.

**Describe alternatives you've considered**
None

**Additional context**
This was (briefly) discussed with @annanay25 offline. Moving the conversation here!

**Comment by joe-elliott** [comment]
@achatterjee-grafana  This might be a good one to look at.  Just getting the structure going would be worth merging so others could easily jump in and add details.

**Comment by achatterjee-grafana** [comment]
Sure...

**Comment by achatterjee-grafana** [comment]
Changed TOC and reorganized individual topics as suggested by @joe-elliott. Closing the issue.
