### ISSUE TITLE
Bad 2.4.1 release?

### ISSUE THREAD

**Issue by bpfoster** [grafana/tempo#3570]
**Describe the bug**
Is it possible that the 2.4.1 release available on GitHub was created without the commits that comprise the bugfix reported to be in that version?

After my fix for [S3 prefix handling](https://github.com/grafana/tempo/issues/3465) was [merged](https://github.com/grafana/tempo/pull/3466) and [released](https://github.com/grafana/tempo/pull/3502) into 2.4.1, I upgraded.  I've noticed that beginning the day I upgraded from 2.3 to 2.4.1, data in S3 is not getting cleaned up correctly, much like I found was happening in 2.4.0.

When Tempo starts up, I see this for the version reported:
`caller=main.go:118 msg="Starting Tempo" version="(version=2.4.1, branch=HEAD, revision=b1c4d3fbf)"`

`version=2.4.1` looks good, but revision b1c4d3fbf is the revision of [v2.4.0](https://github.com/grafana/tempo/releases/tag/v2.4.0)!  Could someone make sure I'm not going crazy?

**Comment by joe-elliott** [comment]
![image](https://github.com/grafana/tempo/assets/2272392/6c58205e-ea1f-4e35-8256-dc082cf40a05)

the tag is on the correct hash, but it does look like it was built incorrectly. nice catch. we will look to fix soon.

**Comment by joe-elliott** [comment]
I re-genned the release and it looks ok on my side:

![image](https://github.com/grafana/tempo/assets/2272392/40eb296f-e0ed-47f2-a2bf-8c91cc117892)

Are you seeing the same thing?

**Comment by bpfoster** [comment]
I am now seeing the same thing in the version string, and looks like compaction/retention is running.

Thanks for addressing this so quickly!

**Comment by knylander-grafana** [comment]
A lot of doc updates are missing from this release that were in the 2.4 release..

**Comment by knylander-grafana** [comment]
Jack resynced the docs and we're sorted!

**Comment by fnordian** [comment]
grafana/tempo:2.4.1-amd64 was available at least 3 weeks ago with hash sha256:cf466cd97e5c8d4591feaddb85372360c1d1d482615ed

now it's sha256:cf1ed1d5cc671c80d389f7c59cfa491a9e5b99d28a42fccb9d6cbbef0da378e4

**Comment by joe-elliott** [comment]
We just re-genned the binaries b/c they were built on the wrong commit. The docker image was always correct.
