### ISSUE TITLE
Docs feedback: /docs/sources/tempo/setup/set-up-test-app.md

### ISSUE THREAD

**Issue by kastl-ars** [grafana/tempo#3587]
Small typo: `Generate traces using telemtrygen` => telemtrygen is missing an `e` between `m` and `t`.

Otherwise a wonderful documentation, easy to read and easy to follow. Thanks a lot.

**Comment by knylander-grafana** [comment]
Thank you! It looks like we fixed this typo in [this PR](https://github.com/grafana/tempo/commit/69c14a71c711109c794e0cff4e08ba4bb1808ca9). 

So glad that you found the documentation easy to ready and follow!
