### ISSUE TITLE
Deprecated Cache configurations is still in the current documentation. (2.4)

### ISSUE THREAD

**Issue by pingping95** [grafana/tempo#3597]
**Is your feature request related to a problem? Please describe.**
It is not a feature request.

https://grafana.com/docs/tempo/latest/operations/caching/

<img width="1226" alt="image" src="https://github.com/grafana/tempo/assets/67780144/e7c9d25f-9b89-4469-9ea8-78e1ee30c092">

this configuration is out-of-date and not works in tempo 2.4 version.

as far as i know, from 2.4 multi cache role is introduced and that config does not effect

**Describe the solution you'd like**
Updating the cache docs

**Describe alternatives you've considered**
Same above.

**Additional context**
None.

I followed the setup documentation below and applied cache.

https://grafana.com/docs/tempo/latest/configuration/#cache

but it can be quite confusing for people who are unfamiliar with Grafana tempo or who are new to Grafana tempo in 2.4 and trying to introduce cache.

I apologize for not being able to PR due to lack of expertise.

**Comment by joe-elliott** [comment]
@knylander-grafana, it seems we missed this when redoing the cache. do you have bandwidth to remove these settings from docs?

@pingping95 Thanks for the heads up!

**Comment by knylander-grafana** [comment]
Okay, I reviewed the 4 PRs associated with the cache rework: 

In [this PR](https://github.com/grafana/tempo/pull/3166), Joe wrote this in the description: 
* cache_min_compaction_level and cache_max_block_age were the only caching settings that were left alone. These are policy settings and I decided to leave them under storage.trace in the config block

The current manifest and configuration have the two configuration options `cache_min_compaction_level` and `cache_max_block_age` still in storage.trace settings. 

I think the example is okay. 

However, I'm going to ask for help doing a review of the rest of the [Improve performance with caching](https://grafana.com/docs/tempo/latest/operations/caching/) page.

**Comment by knylander-grafana** [comment]
Updated docs. Should be published with 2.5 in a few days.
