### ISSUE TITLE
Tempo is unable to create directories when using local storage

### ISSUE THREAD

**Issue by AdrianColaianni** [grafana/tempo#3601]
**Describe the bug**
When starting Tempo for the first time, it is unable to create the directories in it's local storage.

**To Reproduce**
1. `git clone https://github.com/grafana/tempo`
2. `cd tempo/examples/docker-compose/local`
3. `docker-compose up -dV`
4. `docker logs local-tempo-1` and the following error will show
```
level=error ts=2024-04-23T14:06:56.550397594Z caller=main.go:121 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: mkdir /var/tempo/blocks: permission denied"
```

**Expected behavior**
Tempo creates the directories and uses the storage

**Environment:**
 - Infrastructure: Linux 6.8.7-arch1-1 x86_64
 - Deployment tool: docker v26.0.2 & docker-compose v2.26.1

**Comment by AdrianColaianni** [comment]
I am on main at `148ba6d` and my grafana/tempo image is `d523ba7846350e8e529c3f65effcfab8d97a57f3385ce5a6bc09f3b428f97fbe`

**Comment by zalegrala** [comment]
Hmm, I don't have `148ba6d` locally, but try to pull an updated `main` and run the docker-compose example again.

**Comment by zalegrala** [comment]
Oh I see now, you were ahead of me.  You may need to chown the path for the data to be owned by `10001:10001`.

**Comment by AdrianColaianni** [comment]
Thank you zalegrala,

Changing ownership fixed the issue, but this should be documented or automated during startup.
