### ISSUE TITLE
[DOCS] Missing `metrics_generator.traces_storage`, `metrics_generator.query_timeout` and `metrics_generator.override_ring_key`

### ISSUE THREAD

**Issue by WesselAtWork** [grafana/tempo#3642]
Noticed that some keys are missing in the documentation for the complete configuration.

https://github.com/grafana/tempo/blob/251bf5a9a74fd586ffd3dedcc2c8000f36aa9a78/modules/generator/config.go#L27-L36

https://github.com/grafana/tempo/blob/251bf5a9a74fd586ffd3dedcc2c8000f36aa9a78/docs/sources/tempo/configuration/_index.md?plain=1#L286-L412

**Comment by joe-elliott** [comment]
Thanks for the heads up!

**Comment by derek-cadzow** [comment]
Assigning to myself so that it can be reassigned to our new Mimir writer when she has started and is on board.

**Comment by knylander-grafana** [comment]
@derek-cadzow, this is a Tempo configuration for the metrics-generator, a component used in Tempo to generate metrics from traces. @WesselAtWork has a PR to update the metrics-generator doc (#3643).

**Comment by MrMegaMango** [comment]
does metrics generator need access to the blob storage for trace?
