### ISSUE TITLE
Can we upgrade the base image of tempo-query?

### ISSUE THREAD

**Issue by kevincantu** [grafana/tempo#3652]
Even `grafana/tempo-query:latest` is still based on Alpine 3.16.7, I gather, and 3.16 is about to be EOL ([ref](https://alpinelinux.org/releases/)).

**Comment by joe-elliott** [comment]
`tempo-query` is based on the `jaeger-query` docker image and is defined here:

https://github.com/grafana/tempo/blob/main/cmd/tempo-query/Dockerfile#L1

So we can upgrade to whatever the latest jaeger version is based on. Do you want to give it a shot?

**Comment by kevincantu** [comment]
I see the latest is `jaegertracing/jaeger-query:1.57`, which fixes a few things: based on Alpine 3.16.9.
