### ISSUE TITLE
Finding the duration between 2 spans within the same trace

### ISSUE THREAD

**Issue by lokesh411** [grafana/tempo#3654]
As far as i have read, we don't have a way to find the duration between startTimes of 2 child spans of a trace. The use case is, there are multiple operations within a trace and if we want to find the difference between start times of 2 operations (spans) if might be very useful. Correct me if this is already there
Thanks

**Comment by joe-elliott** [comment]
Unfortunately, this does currently exist in TraceQL. I agree this could be useful but, in general, may be difficult to pull off.

What syntax do you think may be appropriate for a query like this?
