### ISSUE TITLE
Missing common.proto and trace.proto

### ISSUE THREAD

**Issue by XiangFrank** [grafana/tempo#3666]
**Describe the bug**
In the [pkg/tempopb/tempo.proto file](https://github.com/grafana/tempo/blob/3f420b6a4a3a77908cd2139f00e3825c56febda3/pkg/tempopb/tempo.proto#L5), it import common.proto and trace.proto, these two files are supposed to be under /pkg/tempopb/common/v1 and /pkg/tempopb/trace/v1, but they are missing.

I suppose they should be the same to the OpenTelemetry proto [common.proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto) and [trace.proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto), but still wanna confirm it and possibly add them back to avoid confusion.

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by joe-elliott** [comment]
Yup. We have a somewhat convoluted process to generate proto in the repo. Run `make gen-proto` from the root to create those files.
