### ISSUE TITLE
Can't use https while accessing minio s3. I have deployed k8s on AKS and using minio to store traces on onprem . I am using https:// but can't access s3.

### ISSUE THREAD

**Issue by waqasdev54** [grafana/tempo#3696]
**Describe the bug**
msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: unexpected error creating core: Endpoint url cannot have fully qualified paths."

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by joe-elliott** [comment]
I believe the s3 minio client attempts to connect using SSL automatically. I don't think `https://` is necessary. Just don't set `insecure: true`.

https://github.com/grafana/tempo/blob/main/example/docker-compose/distributed/tempo-distributed.yaml#L52-L57
