### ISSUE TITLE
Add k6 script for mocking/smoke testing the write path

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#370]
(from the Slack discussion)

It might be interesting to add a [k6](https://github.com/loadimpact/k6) script for testing the write path of Tempo. This script could be used for:
- Generating fake trace data and shipping it to Tempo.
- Smoke testing new/existing Tempo deployments.
- Stress/Soak testing the write path.

I propose (for this first script) that we use the HTTP Zipkin receiver. Later-on we can add the other receivers :)

If this experiment goes well, might be interesting to add another script for the read path.

**Comment by dgzlopes** [comment]
Can I get this one assigned? :P 

cc @simskij (probably he's interested on this)

**Comment by joe-elliott** [comment]
The zipkin receiver will induce extra work b/c it will have to translate from Zipkin to OTLP internally.  However, I don't think this is a big deal and would love to see this work in Tempo.

**Comment by dgzlopes** [comment]
I though that it was the most straightforward to add (my ugly script is based on it). 

Probably we can mock all of them! I would love to see how Tempo behaves depending on the receiver.
