### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ddatsh** [grafana/tempo#371]
```
go get -v github.com/grafana/tempo/cmd/tempo
```

```
go\pkg\mod\github.com\cortexproject\cortex@v1.3.0\pkg\querier\frontend\worker.go:16:2: module google.golang.org/grpc@latest found (v1.33.2), but does not contain package google.golang.org/grpc/naming
```

**Comment by joe-elliott** [comment]
We do have a strange vendor situation at the moment.  For this particular issue you need this replace rule 

https://github.com/grafana/cortex/blob/master/go.mod#L83

etcd is still trying to upgrade their version of grpc: https://github.com/etcd-io/etcd/pull/12398

Until they do we, and a lot of other applications are stuck using 1.29.1.  

May I ask what you're vendoring tempo for?
