### ISSUE TITLE
Tags Endpoint: Incorrect intrinsics returned

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#3714]
**Describe the bug**
When querying the `/api/v2/tags` endpoint Tempo still returns the old intrinsic names.  In https://github.com/grafana/tempo/pull/3629 we added support for the new intrinsic names but forgot to swap over this endpoint:

> curl -H 'X-Scope-OrgID: 1' 'http://localhost:3100/tempo/api/v2/search/tags?scope=intrinsic'
{"scopes":[{"name":"intrinsic","tags":["duration","kind","name","rootName","rootServiceName","status","statusMessage","traceDuration"]}]}

Should return names like:

`span:duration`, `span:kind`.

While we're at it, let's add these two new intrinsics as well:

https://github.com/grafana/tempo/pull/3670

We should consider returning both the legacy and new values since we intend to support them both for the foreseeable future.

**Code changes**

This is the code that returns intrinsic tags:
https://github.com/grafana/tempo/blob/main/pkg/search/util.go#L57

Also confirm that this method works for the new intrinsic names:
https://github.com/grafana/tempo/blob/main/pkg/search/util.go#L31

**Comment by parambath92** [comment]
Hi @joe-elliott ,
Is this issue open for contribution ?

**Comment by joe-elliott** [comment]
It is! @ie-pham can you help @parambath92 with any questions/reviews?

**Comment by ie-pham** [comment]
@parambath92 I'd be happy to help with any questions and whenever you need a review

**Comment by ishanjain28** [comment]
hi @parambath92 I didn't realize you had claimed this issue. Let me know if you'd still like to work on it and i'll retract my PR

**Comment by parambath92** [comment]
Hey @ishanjain28 ,
I wanted to work on this over this weekend but haven't started yet. Since you have already raised the PR I think the team can review this and you can pick up the issue.
cc: @joe-elliott
