### ISSUE TITLE
User-configurable overrides api Documentation 

### ISSUE THREAD

**Issue by gpadidala** [grafana/tempo#3715]
**Is your feature request related to a problem? Please describe.**

We are in search of the API payload required to establish user-configurable overrides for each tenet. Our objective is to individually update each tenet and assign a corresponding label. During our review, we encountered difficulty in locating the folder in the pods and overrides/tenet/overrides.json.

**Describe the solution you'd like**

Please share any links to follow the api documentation for the user-configurable overrides  to an update, so it will be helpful. looking for the API documentation to follow to update the configuration and use the user-configurable overrides.

**Comment by mapno** [comment]
Hi! The documentation for the Overrides API is [here](https://grafana.com/docs/tempo/latest/operations/user-configurable-overrides/).
