### ISSUE TITLE
[docs] Enhance storage section in docs to describe all storage backends & options

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#372]
Came up in https://github.com/grafana/tempo/pull/354#discussion_r529279871

**Comment by mdisibio** [comment]
Documentation for GCS was added in https://github.com/grafana/tempo/pull/397, now docs cover gcs, s3, and redis.  That leaves memcached?   It is somewhat covered in the Storage section of Configuration (https://grafana.com/docs/tempo/latest/configuration/#storagehttpsgithubcomgrafanatempoblobmastertempodbconfiggo) but could have a dedicated page.

**Comment by dgzlopes** [comment]
I can add the Memcached section @mdisibio. Can be part of the WIP #399 PR.
