### ISSUE TITLE
Refactor cache section in tempodb/backend to use Cache interface

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#373]
The Cache section of `tempodb/backend` has a lot of copied code between `disk_cache`, `memcached` & `redis`. 

This is because each of the cache backends are implementing the entire `backend.Reader` & `backend.Writer` interfaces. Instead, we should split `cache` into a separate package (that lives in `tempodb/backend/cache`) and should accept a cache implementation that implements a smaller interface that interacts with the respective datastores. A rough draft looks something like this

```
type Cache interface {
    func Get(ctx context.Context, key string) []byte
    func Set(ctx context.Context, key string, val []byte)
}
```

Each of the caches should live within `tempodb/backend/cache/disk_cache`, `tempodb/backend/cache/memcached` and `tempodb/backend/cache/redis` respectively and just implement this small interface described above.

This will reduce repetition and keep all of the testing in one place.

Came up in https://github.com/grafana/tempo/pull/354#discussion_r529283403

**Comment by dgzlopes** [comment]
I'll start working on this :)

Had small sync about the scope/design today with @annanay25.
