### ISSUE TITLE
Drop Vulture's Loki Dependency

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#374]
**Is your feature request related to a problem? Please describe.**
Currently the vulture requires Loki to find trace ids.  Instead we would like it to generate its own traces, push those into Tempo and then request them back for analysis.

**Describe the solution you'd like**
Alternative ideas are welcome but what makes sense to me is something like:

1) Every n seconds wake up and generate a trace
2) Divide unixTime / n to get a stable value and then seed the random # generator with it
3) Generate and push a random trace to Tempo

Then a second goroutine can randomly select one of the time slots, use the same seed to generate the same trace, request it from Tempo and confirm it everything matches.

**Comment by rfratto** [comment]
> Then a second goroutine can randomly select one of the time slots, use the same seed to generate the same trace, request it from Tempo and confirm it everything matches.

Is there a reason why you'd need to store the timestamps in memory instead of just storing the trace IDs? If it's possible to just store the trace IDs and pull a random one for querying, it might simplify the logic a bit.

**Comment by joe-elliott** [comment]
I actually don't want to store the timestamps.  I chose the timestamps as a seed because I thought it would be a way we could generate known seeds without having to store anything.

**Comment by joe-elliott** [comment]
Marking this v1 because I think a vulture that purposefully generates traces that test different elements of Tempo is desired for 1.x.  For instance purposefully creating long lived traces that cross compaction windows or are flushed in different blocks to test the exhaustive search of the query frontend.

**Comment by dgzlopes** [comment]
I'll pick this one :)
