### ISSUE TITLE
Unable to get Service list within time range even if 'start' and 'end' parameters are sent

### ISSUE THREAD

**Issue by sillabiji** [grafana/tempo#3772]
**Describe the bug**
The API end point **GET /api/search/tag/service.name/values** which returns the services are not filtering them when we pass start and end parameters

**To Reproduce**
Below are details of the request which is used to get services

_METHOD_ - GET
_URL_ - https://{baseurl}/api/search/tag/service.name/values
_URL PARAMETERS_ - {"start": "1718153111", "end" : "1718174711"}

**Expected behavior**
The URL above returns all the services, instead it should pass only services which has data in the given time range

**Environment:**
 - Tempo : 2.4.2

**Additional Context**
Tried with v2 as well, but not working

**Comment by joe-elliott** [comment]
Is this a valid call?

```
https://{baseurl}/api/search/tag/service.name/values
```

I'm surprised that doesn't 400. Do you mean:

```
https://{baseurl}/api/search/tag/resource.service.name/values
```

**Comment by sillabiji** [comment]
Sorry the issue no longer exists
