### ISSUE TITLE
Filters not working for Span Name

### ISSUE THREAD

**Issue by tg3rh** [grafana/tempo#3778]
**Describe the bug**
When applying the a filter for the Span Name, it does not seem to be applied/recognized.

**To Reproduce**
1. Navigate to the Explore section in Grafana
2. Navigate to Query type: Search
3. Select a Span Name and filter to exclude it
4. Run query and check results, these are still included

**Expected behavior**
Expecting these traces to be excluded from the list below.

**Environment:**
 - Grafana Cloud

**Additional Context**
Attaching screenshots for reproduction.
![Screenshot 2024-06-17 at 08 18 36](https://github.com/grafana/tempo/assets/110967603/ce078e24-43b3-480e-89dc-fa58de3f6ff7)
![Screenshot 2024-06-17 at 08 22 35](https://github.com/grafana/tempo/assets/110967603/90794e20-a5c5-43de-a7b7-de761089c95b)

**Comment by joe-elliott** [comment]
The TraceQL query you are constructing:
```
{ resource.service.name="spring-boot-redis" && name!="GET /api/users/{id}"}
```
will find spans that match these criteria. What you have circled is the name of the root span of a trace and not the span that matched the search. Use the drop down arrow to the left to find the spans that matched your search conditions.

**Comment by tg3rh** [comment]
Thanks for the speedy response @joe-elliott! 
So might this be a bug related to selection menu? As this TraceQL query that was constructed is generated from the selection menu above, where I could choose the suggested Span Name (screenshot 1).

**Comment by joe-elliott** [comment]
> So might this be a bug related to selection menu? 

This is a misunderstanding of what the query is asking for and what the results are telling you.
