### ISSUE TITLE
Add ingestion metrics to anonymous usage reporting

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#3779]
Similar to Loki:

https://github.com/grafana/loki/blob/main/pkg/loghttp/push/push.go#L55-L57

Add metrics related to ingestion to the anonymous usage report.

**Comment by 09jvilla** [comment]
@joe-elliott -- it says 'similar to Loki' so I'm guessing this is already taken care of but ideally this bytes received statistic would look at bytes received before replication happens as opposed to after. By doing this, one doesn't have to adjust by the replication factor (which can vary among different setups) to figure out the amount of unique data being ingested by the database.

**Comment by 09jvilla** [comment]
Marking this as keepalive - would like to get this into the next release.

**Comment by zalegrala** [comment]
I believe this has already been completed.  I'm seeing distributor metrics for the tempo reports.
