### ISSUE TITLE
[docs] Add a section on metrics and a basic operational runbook

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#378]
**Is your feature request related to a problem? Please describe.**

The docs section is missing a section on operational visibility while setting up Tempo. 

**Describe the solution you'd like**

To start with, we can document -
- The metrics endpoint and some important metrics to watch out for (and why). Metrics I can think of right now -
  - Number of spans received
  - Number of blocks cut and flushed
  - Size of blocklist
  - Number of queries and latency
  - Number of traces in the backend (using tempo-cli)
- Basic operational runbook (and steps to follow when setting up Tempo to make sure its running correctly)

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by joe-elliott** [comment]
We already have a runbook that covers our alerts:

https://github.com/grafana/tempo/blob/master/operations/tempo-mixin/runbook.md

It could certainly be improved.
