### ISSUE TITLE
Document timerange limit on TraceQL metrics

### ISSUE THREAD

**Issue by hedss** [grafana/tempo#3782]
**Describe the bug**
We don't explicitly call out the default timerange limit on TraceQL metrics.

**To Reproduce**
N/A

**Expected behavior**
The TraceQL metrics page should note the default time limit, different to that of other TraceQL queries. We should note this in the Cloud docs, when rectifying this issue.

**Environment:**
N/A

**Comment by knylander-grafana** [comment]
PR https://github.com/grafana/tempo/pull/3800

**Comment by knylander-grafana** [comment]
Published to 2.5 Tempo docs.
