### ISSUE TITLE
Span status.code UNSET causes an error=true label to be added

### ISSUE THREAD

**Issue by panagiks** [grafana/tempo#380]
**Describe the bug**
If a span has `status.code=1` (`UNSET`) at some point in tempo, a tag `error=true` is added. This seems to be a bit too aggressive since the [OpenTelemetry specification, Semantic conventions for HTTP spans](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#status) defines the following for conversion of HTTP status code to span status:

> Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges

As a result requests with an HTTP 200  status will show up in tempo UI as an error (with a red exclamation mark next to the service name).

**To Reproduce**
1. Bring up the basic setup from [Tempo's getting started docs](https://grafana.com/docs/tempo/latest/getting-started/)
2. Send a Trace with a span with status `UNSET` and no `error` tag (see example json bellow)
3. Visit the Tempo UI, navigate to the trace details and notice that there is a red exclamation mark next to the service name and a the tag `error=true` has been added to the span's tags

Example json of a trace:

```json
{
    "name": "foo",
    "context": {
        "trace_id": "0xc3bcfcc918ede75f3d565e6390e6d9b6",
        "span_id": "0xa4d31950ad2c77de",
        "trace_state": "{}"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2020-11-29T20:39:22.856245Z",
    "end_time": null,
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "0.16b1"
    }
}
```

**Expected behavior**
IMO a safe(r) assumption would be to mark as errors only those spans that have an explicit status of `ERROR`.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: docker containers, see mentioned getting started above.

**Additional Context**
Nothing relevant logged in `tempo` or `tempo-query`, running with the default configs from the getting started guild.

**Comment by joe-elliott** [comment]
So our ingestion layer uses the OpenTelemetry [receivers](https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver) and [translation layer](https://github.com/open-telemetry/opentelemetry-collector/tree/master/translator).  It is most likely that the issue you are seeing is due to code in here.

Unfortunately we are quite a bit behind the collector due to an dependency conflict with etcd being on an old version of grpc.  It's quite possible that once we update our collector dependency this will be fixed.

Out of curiosity what receiver are you using to pass your traces?

**Comment by panagiks** [comment]
Hello @joe-elliott :) 

Thank you for the response!

I am using the Jaeger `thrift_compact` receiver. IIRC with the Jaeger all-in-one there wasn't such conversion (but I am not aware what upstream dependencies that is based on). I will verify if the above recollection is correct and ping back here (just for documentation purposes).
