### ISSUE TITLE
Trace by ID: JSON response does not align with OTLP JSON format

### ISSUE THREAD

**Issue by siebeclaes** [grafana/tempo#3802]
**Describe the bug**
According to the Tempo [documentation for Query API](https://grafana.com/docs/tempo/latest/api_docs/#query), if the `Content-Type: application/protobuf` header is absent Tempo "returns [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/trace/v1) JSON".

However, the returned JSON output has `batches` as the top-level key instead of `resourceSpans`. This can also be seen in the Tempo docs: https://grafana.com/docs/tempo/latest/api_docs/pushing-spans-with-http/#retrieve-traces

Because of this, it is not possible to unmarshal the returned JSON into a `TracesData` message from the official OTLP spec.
When requesting protobuf results from tempo, it can be unmarshaled into the official `TracesData` message because the protobufs are compatible.

**To Reproduce**
1. Start Tempo (SHA or version)
2. Query a trace by ID as described here: https://grafana.com/docs/tempo/latest/api_docs/#query

**Expected behavior**
Returned JSON output is compatible with OTLP spec.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
Is it expected to be able to unmarshal the query responses into `TracesData` messages of the official OTLP spec? The documentation appears to hint that it is.
Or should applications querying Tempo unmarshal the response into the structs provided by Tempo (eg. https://github.com/grafana/tempo/blob/main/pkg/tempopb/tempo.proto)?

**Comment by joe-elliott** [comment]
I can confirm I'm seeing the same thing on tip of main:

![image](https://github.com/grafana/tempo/assets/2272392/4eb60690-06b1-47e7-97a1-af9e96c6c922)

> Is it expected to be able to unmarshal the query responses in `TracesData` ...

Yes, this is our intention. Thank you for pointing out the gap.

For the most part we use OTel proto and the json it produces directly. So we are mostly OTel compatible. The gap is right here:

https://github.com/grafana/tempo/blob/b29d56c1ad1a42081d586ae83a608edbbab68d13/pkg/tempopb/tempo.proto#L225-L227

The good news is that I've been wanting to rev the traces endpoint for awhile now, but never had the time. I propose we create an `/api/v2/traces` with at least the following changes (I'm open to suggestions):

- Rename `batches` to `resourceSpans` to cover this issue
- Nest the trace itself one deeper. This will allow the endpoint to return metadata or other messages alongside it:
  ```
  {
    trace: <otel compatible trace>,
    ...
  }
  ```
- Stop returning 404 to mean "trace not found". Instead 200 with an empty trace.

**Comment by siebeclaes** [comment]
@javiermolinar , thanks a lot for your PR!

Is my understanding correct that your PR makes the internal proto definitions OTEL compatible with the rename from `batches` to `resourceSpans` but that when querying the current `traces` API the JSON output will still return `batches`?

If that is true, I think this issue should be kept open a bit longer until there is a new API endpoint that returns fully compatible OTEL JSON output.

**Comment by javiermolinar** [comment]
> Is my understanding correct that your PR makes the internal proto definitions OTEL compatible with the rename from `batches` to `resourceSpans` but that when querying the current `traces` API the JSON output will still return `batches`?

You are right @siebeclaes. I'm currently working on that https://github.com/grafana/tempo/pull/3912
