### ISSUE TITLE
Add semver version to api/status/buildinfo endpoint

### ISSUE THREAD

**Issue by joey-grafana** [grafana/tempo#3811]
**Is your feature request related to a problem? Please describe.**
[isFeatureAvailable](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/datasource.ts#L252) is used in the Tempo front end to check if features should be made available in the UI based on which version of Tempo is running.

The function above (in the link) returns something like “r154-0b3d297” but for semver to work it needs to be something like “2.5.1”
This means that the function above always returns true so it is possible this would enable streaming in an environment where an old version of Tempo is being used.

**Describe the solution you'd like**
To return a semver string from the `api/status/buildinfo` endpoint.

Having this semver string would also allow us to check if other features are available and cleans up the code/makes it more resilient on the frontend.

**Describe alternatives you've considered**
Removing the function above and simply running a streaming query for example and if it fails then falling back to a non-streaming query.

**Additional context**
![Screenshot 2024-06-26 at 09 27 28](https://github.com/grafana/tempo/assets/90795735/ca299152-a5c1-449a-be9f-597fb2230308)
![Screenshot 2024-06-26 at 09 27 32](https://github.com/grafana/tempo/assets/90795735/7d937143-23ed-4321-8f75-38fdf43e06cb)

**Comment by joey-grafana** [comment]
There was some discussion and initial improvements in [this issue](https://github.com/grafana/tempo/issues/2387).

**Comment by ishanjain28** [comment]
Hey @joey-grafana, Can you explain this a bit more please ? 

`version` field in response comes from `main.Version` flag set when compiling the program. For normal releases, It's set to a semver value and the response is what you'd expect. 

```
{"version":"2.5.0","revision":"46dad3411","branch":"HEAD","buildUser":"","buildDate":"","goVersion":"go1.21.3"}
```

If I understand correctly, With this PR, you always want a semver value here ?

**Comment by joey-grafana** [comment]
Hey this does not work correctly for cloud deployments as the versioning is slightly different. We are basing our check on there being a semver version present.

@fabrizio-grafana I know you worked on the feature initially so if you have any additional context please feel free to share.

**Comment by JahJahWei** [comment]
https://github.com/grafana/tempo/blob/89e67899e215183cdb1aaa3e9c6d245a20672426/Makefile#L50
https://github.com/grafana/tempo/blob/89e67899e215183cdb1aaa3e9c6d245a20672426/Makefile#L9
https://github.com/grafana/tempo/blob/89e67899e215183cdb1aaa3e9c6d245a20672426/tools/image-tag#L14-L21
I think not have a `git tag` in the current commit when you are building.

**Comment by javiermolinar** [comment]
Since the version depends on the tag/branch we have discrepancies between enterprise/non-enterprise versions. 

One simple approach could be having a VERSION file directly in the root of the repo and then read it on building time like Mimir does:

https://github.com/grafana/mimir/blob/0e8c09f237649e95dc1bf3f7547fd279c24bdcf9/VERSION#L1

https://github.com/grafana/mimir/blob/0e8c09f237649e95dc1bf3f7547fd279c24bdcf9/Makefile#L17

**Comment by Aki0x137** [comment]
Hi folks, was looking into the repository and saw this issue was marked as stale recently.
If its fine, can I take this up? Would be great if there is a guide on how to contribute.

**Comment by Aki0x137** [comment]
Hi folks!
I have raised a [PR #4110 ](https://github.com/grafana/tempo/pull/4110/files) as per the suggestions in this conversation. I'm new to open source in general and have tried to do stuff as much as possible, mentioned in the CONTRIBUTING.md.
Kindly let me know if any changes/additions are required.

Thanks!
