### ISSUE TITLE
Tempo mixin: alert and recording rules make range interval configurable

### ISSUE THREAD

**Issue by jmichalek132** [grafana/tempo#3815]
**Is your feature request related to a problem? Please describe.**

In our case we have scrape interval of 1m, however one alert and recording rules in the mixin seem to have hardcoded range interval, examples:

https://github.com/grafana/tempo/blob/main/operations/tempo-mixin/alerts.libsonnet#L202
https://github.com/grafana/tempo/blob/main/operations/tempo-mixin-compiled/rules.yaml#L4

**Describe the solution you'd like**

Have a config option for the range interval window in alerts, similar to what is already present for recording rules in mimir mixin. https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/config.libsonnet#L666.

**Describe alternatives you've considered**

Manually editing the alerts after they are rendered, which kind of defeats the point of mixins imho.

**Additional context**

https://www.robustperception.io/what-range-should-i-use-with-rate/
I can raise a PR for the changes.

**Comment by joe-elliott** [comment]
Yup, I think this is a solid improvement and would love to see a PR. Thanks for raising an issue.
