### ISSUE TITLE
unable to add data source to tempo with URL

### ISSUE THREAD

**Issue by raghav20241** [grafana/tempo#3825]
**Describe the bug**

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by mapno** [comment]
Please fill out the issue template.

**Comment by raghav20241** [comment]
Tempo pods are up and running with AWS s3 as backend to store traces but could not add tempo data source in garfana URL its showing testing but not added any particular issue I need to check (DS url: http://tempo:3100)

**Comment by raghav20241** [comment]
resolved myself
