### ISSUE TITLE
Services list is empty in the tempo-query UI

### ISSUE THREAD

**Issue by eran-levy** [grafana/tempo#384]
We are not sure if this is the default behaviour while using Tempo - we deployed all and we can search by specific TraceIDs but not able to see the services list in the UI - see attached screenshot.
Looks like its the default but we are not sure and would like to validate - we see the following: "...You’re all set to use Tempo! Make sure you’re logging trace ids in your application logs,..." written in https://grafana.com/docs/tempo/latest/getting-started/

Do we miss anything? 
<img width="485" alt="Screen Shot 2020-11-30 at 20 57 35" src="https://user-images.githubusercontent.com/584783/100651883-d0e3fc80-334e-11eb-868e-44f2902bfe30.png">

**Comment by annanay25** [comment]
Hi @eran-levy, thanks for reaching out. Yes, this is the expected behaviour, Tempo can only retrieve traces given a traceID, and the services drop-down is not expected to list anything :)
