### ISSUE TITLE
Support Zone Aware Replication cli Flags

### ISSUE THREAD

**Issue by KyriosGN0** [grafana/tempo#3877]
**Is your feature request related to a problem? Please describe.**
in our org we use 3 AZ for mimir and we would like to be able do that with Tempo
**Describe the solution you'd like**
Ability to specify an AZ in cli flag like `-ingester.availability-zone` 
**Describe alternatives you've considered**
use ENV var (but as we use helm chart its not possible) 
**Additional context**

**Comment by KyriosGN0** [comment]
@zalegrala @joe-elliott, i've seen we parse the Cli flags [here](https://github.com/grafana/tempo/blob/980437f8a9a4d71aa6c0faca5de588a9f8ae19ba/modules/ingester/config.go#L35)
and we use default flags in `ring.lifecyclerConfig` which already has this cli flag defined [here](https://github.com/grafana/dskit/blob/f54a6bf931daca88f770c78c86de7297203ae1bb/ring/lifecycler.go#L47)
does this mean i just need to export this flag in Tempo cli ? or is there anything else needed ?

**Comment by joe-elliott** [comment]
That is correct. If you'd like to expose that config option you simply need to add a line in `RegisterFlagsAndApplyDefaults`
