### ISSUE TITLE
getting field role_arn not found in type s3.Config (error to add role_arn for garfana tempo-distributed )

### ISSUE THREAD

**Issue by raghav20241** [grafana/tempo#3878]
**Describe the bug**
After adding AWS IAM role arn in tempo-distributed storage unable to access getting field not not found

**To Reproduce**
1. Start Tempo (SHA or version) 2.5.0
2. Perform Operations (Read/Write/Others)

**Expected behavior**
 Able to connect with AWS access key and sceret key but not with role (arn) with same policy

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] kubernetes
 - Deployment tool: [e.g., helm, jsonnet] helm 

**Additional Context**

**Comment by raghav20241** [comment]
storage:
  trace:
    backend: s3
    blocklist_poll: 5m
    pool:
      max_workers: 400
      queue_depth: 20000
    s3:
      bucket: tempo-distributedstg
      region: eu-central-1
      role_arn: arn:aws:iam::********:role/tempo-role
    wal:

error in pod failed parsing config: failed to parse configFile /conf/tempo.yaml: yaml: unmarshal errors:
  line 111: field role_arn not found in type s3.Config

**Comment by joe-elliott** [comment]
There is no `role_arn` field on that config struct. Here are the options available:

https://github.com/grafana/tempo/blob/main/tempodb/backend/s3/config.go#L13

**Comment by raghav20241** [comment]
@joe-elliott Thanks for the reply please try to include AWS I am role arn in newer updates.
