### ISSUE TITLE
TIME_WAIT Issue inside pod for tempo-distributed 

### ISSUE THREAD

**Issue by raghav20241** [grafana/tempo#3883]
**Describe the bug**
I have deployed tempo and tempo-distributed using helm in same cluster with demo opentel service, but I am able to get traces for tempo without any issue for data source but for tempo-distributed getting TIME_WAIT error inside the pod and not getting any traces (0 series ) or connect to demo service. 

**To Reproduce**
1. Start Tempo (SHA or version) 2.5.0.
2. Perform Operations (Read/Write/Others)

**Expected behavior**
Please suggest conf for TIME_WAIT Issue and need to established connection between opentel demo service with tempo-distributed.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] ---kubernetes
 - Deployment tool: [e.g., helm, jsonnet]---helm

**Additional Context**
 plz find pod with netstat 
<img width="775" alt="image" src="https://github.com/user-attachments/assets/4c10f6a7-cd60-409c-9d22-d92cbe5e7b88">

**Comment by joe-elliott** [comment]
you seem to be struggling to get the most basic elements of tempo to work. this is quite difficult to debug with limited information and requires an operator to debug simple networking and other config elements.

in the past i've used these steps to startup the distributed helm chart with a load generator:

https://github.com/grafana/tempo/tree/main/example/helm

**Comment by raghav20241** [comment]
@joe-elliott tempo is working fine with opentel demo services able to get traces but same for tempo-distributed i am facing issue with traces not able to get traces ,can you share any end-to-end document for grafana tempo-distributed with demo service for testing.
