### ISSUE TITLE
Bug in wal.go causes c.BlocksFilepath config to be overwritten in tempo.yaml

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#3902]
**Describe the bug**
Configuration file section for `cBlocksFilepath` is overwritten in tempo.yaml. 

@WesselAtWork reported [this issue in PR 3643](https://github.com/grafana/tempo/pull/3643/files#r1624087743): 

[tempo/tempodb/wal/wal.go](https://github.com/grafana/tempo/blob/3a4f309b0d9413fc8762daaa0bd9769a08cc8bf8/tempodb/wal/wal.go#L70-L75)

Lines 70 to 75 in [3a4f309](https://github.com/grafana/tempo/commit/3a4f309b0d9413fc8762daaa0bd9769a08cc8bf8)
```
 p := filepath.Join(c.Filepath, blocksDir) 
 err = os.MkdirAll(p, os.ModePerm) 
 if err != nil { 
 	return nil, err 
 } 
 c.BlocksFilepath = p
```

I think it's supposed to look like this (but with c.BlocksFilepath == ""):
[tempo/tempodb/wal/wal.go](https://github.com/grafana/tempo/blob/3a4f309b0d9413fc8762daaa0bd9769a08cc8bf8/tempodb/wal/wal.go#L56-L67)

Lines 56 to 67 in [3a4f309](https://github.com/grafana/tempo/commit/3a4f309b0d9413fc8762daaa0bd9769a08cc8bf8)
```
 // The /completed/ folder is now obsolete and no new data is written, 
 // but it needs to be cleared out one last time for any files left 
 // from a previous version. 
 if c.CompletedFilepath == "" { 
 	completedFilepath := filepath.Join(c.Filepath, completedDir) 
 	err = os.RemoveAll(completedFilepath) 
 	if err != nil { 
 		return nil, err 
 	} 
  
 	c.CompletedFilepath = completedFilepath 
 }
```

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by joe-elliott** [comment]
@WesselAtWork why do we think this is an issue? The `c.CompletedFilePath` check is for old functionality. That code is meant to be a final cleanup of old files. We should probably remove it.

The "c.BlocksFilepath" code is just setting up where the wal stores completed wal blocks.

**Comment by javiermolinar** [comment]
I think he meant that c.BlocksFilepath is overwritten always, no matter what you set in the Wal section of the  tempo.yaml config file

**Comment by knylander-grafana** [comment]
I updated the description and title to be more specific.

**Comment by joe-elliott** [comment]
oh, I see. Technically you can set BlocksFilePath in the config, but we ignore it and use FilePath + "/blocks".

My .02:
- Remove the CompletedFilePath logic
- Remove the ability to config the blocks filepath directly. Does anyone use this?

**Comment by javiermolinar** [comment]
> oh, I see. Technically you can set BlocksFilePath in the config, but we ignore it and use FilePath + "/blocks".
> 
> My .02:
> 
> * Remove the CompletedFilePath logic
> * Remove the ability to config the blocks filepath directly. Does anyone use this?

I agree with both, for the first point, we should aim to delete all unused code as possible, and for the second, why anyone would want that fine-grained configuration?
