### ISSUE TITLE
Add large traces to k6.io tests

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#394]
**Is your feature request related to a problem? Please describe.**
We know that tempo has some performance issues returning extremely large traces.  Let's add some benchmark testing of this to the k6.io scripts added here:  #392 to help us track this issue and improve on it.

**Comment by dgzlopes** [comment]
We should create traces with tons of spans? Or with huge spans (size-wise)? Or both?

**Comment by joe-elliott** [comment]
We have tracked this down to being almost entirely an issue with marshalling/unmarshalling.  Removing the jaeger-query dependency and allowing Grafana to query Tempo directly will be the best thing we can do.   Also, for clarity, "large traces" are in the couple hundred thousand span range.

I think we can just close this tbh.

**Comment by dgzlopes** [comment]
Oh, if that's the case, I agree! We can close this one.

Thanks for the clarification anyway :P
