### ISSUE TITLE
aws s3 storage backend:List

### ISSUE THREAD

**Issue by shayal01** [grafana/tempo#3955]
**Describe the bug**
 there is no listobject action in aws s3.its list bucket,but that action is performed by the pods after deploying tempostack instance.

**To Reproduce**
1. install and deploy a tempo stack instance in rosa classic cluster

**Expected behavior**

**Environment:**
 - Infrastructure: Rosa service in aws
 - Deployment tool: tempo operator by redhat
**Logs**
`error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: unexpected error from ListObjects on tempo-openshift: The specified method is not allowed against this resource.`

**Comment by joe-elliott** [comment]
This is the error in question:

https://github.com/grafana/tempo/blob/50631af4c0a72e8d347d06d820da36b45402131d/tempodb/backend/s3/s3.go#L117

This has been corrected in the docs:

https://grafana.com/docs/tempo/latest/configuration/hosted-storage/s3/

We could probably clarify the error here.

**Comment by knylander-grafana** [comment]
If we're updating the docs for the error message, this might be a good first issue for someone to handle.
