### ISSUE TITLE
[DOC] Release notes for 2.6

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#3968]
Topic: 

* TraceQL events, links, and arrays (with autocomplete for both) 
  * Querying links and events (JPham)
  * `scope:scope` may be (PR: https://github.com/grafana/tempo/pull/3967)
  * These features may not be fully implemented in Grafana - https://github.com/grafana/grafana/issues/89567 
* Exemplars (Grafana doesn't support it yet) - Refers to exemplars of traces from a TraceQL Metric query. We should add / update content about exemplars in our intro section
* Tag name filtering (Grafana doesn't support it yet)
* Performance improvements - lots of things here
  * Polling and memory improvements
  * Digesters improvements 
  * Total cost of ownership increases - Metrics performance
  * Blockmeta performance improvements with dedicated columns (Zach Leslie SME)
* Adding cache
* Add the ability to flush RF1 (replication factor 1) blocks for metrics and anyone running metrics should use it. 
  * Marty and Mario worked on this. 
  * Configuration parameters. Provide examples of config and benefits for using it. 
  * Normally things are RF3, we're moving to RF1. You end up with a lot of duplicate info - hard to do with dedup etc. So we're moving to RF1 to help with this for metrics. 
  * native histograms - https://github.com/grafana/tempo/pull/3929

Two biggest ones are events and links -- attributes and intrinsics that come with it. 
Arrays as well because of vParquet 4. We implicitly support arrays now. 

Timeline: Possibly 2 weeks

Related issues: 
* https://github.com/grafana/tempo-squad/issues/339
* https://github.com/grafana/tempo-squad/issues/414

**Comment by jSwanson99** [comment]
just curious, what does this point mean? 
"Exemplars (Grafana doesn't support it yet)"
What about this impl of exemplars is not yet supported by grafana?

**Comment by javiermolinar** [comment]
> just curious, what does this point mean? "Exemplars (Grafana doesn't support it yet)" What about this impl of exemplars is not yet supported by grafana?

Is refering to exemplars of traces from a TraceQL Metric query

**Comment by knylander-grafana** [comment]
Thank you for the question and the answer. Sorry about the rough description. They are my notes from a team meeting for what might be in the release notes.

**Comment by knylander-grafana** [comment]
Mario updated the tempo-distributed Helm chart for the 2.6 release: https://github.com/grafana/helm-charts/pull/3296
