### ISSUE TITLE
Seems the dashboards to monitor tempo are broken

### ISSUE THREAD

**Issue by chenlujjj** [grafana/tempo#3992]
**Describe the bug**

Hi team, I deployed tempo-distributed in k8s cluster and tried to monitor it with the dashboards [here](https://github.com/grafana/tempo/tree/main/operations/tempo-mixin-compiled/dashboards).
But I found that the dashboards are broken, for example:
* there is no `cluster` label in `tempo_build_info` metric, which causes the dashboard variable `cluster` no value at all
* there is no `tempo_receiver_accepted_spans` metric from the distributor, but it is used in the distributor monitor panel

**Expected behavior**

The dashboards should be normal and show metrics well

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**

**Comment by chenlujjj** [comment]
Found a PR: https://github.com/grafana/tempo/pull/3917 may be related to the `tempo_receiver_accepted_spans` metric, I'll try to upgrade my tempo deploy

**Comment by javiermolinar** [comment]
Hi, the tempo_receiver_accepted_spans will be available in the 2.6.0 release and then it will need to be updated in the helm chart. For the tempo_build_info metric, we use the same dashboards so it makes sense for us, maybe @zalegrala knows more.

**Comment by chenlujjj** [comment]
Thanks @javiermolinar 

Does the `tempo_build_info` metric in your stack have `cluster` label?
Below is what I get from one of the temp distributor instances:
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/3db2effa-5be3-45bc-80e2-039b7eac3d6b">

**Comment by javiermolinar** [comment]
Here is where is populated:
https://github.com/grafana/tempo/blob/fbf249a41fdc9ee9ddc8168c4a4f92e426f92bb0/cmd/tempo/build/build.go#L20

The cluster label is probably added in the K8s relabel configuration. That way all our metrics include the cluster info

**Comment by chenlujjj** [comment]
Got it!

**Comment by zalegrala** [comment]
That's right.  Add a `cluster` and `namespace` label in the scrape configs.  This should mean the queries in the dashboard work as intended.
