### ISSUE TITLE
Remove support for serverless functions

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#4014]
Currently our codebase supports [AWS Lambda and GCP Cloud Run](https://github.com/grafana/tempo/tree/main/cmd/tempo-serverless). However, we have recently found that our AWS runtime has been deprecated and the team has no bandwidth to continue maintaining this functionality. We are also generally unsure of the value of serverless and if it actually provides the presumed reduced latency at a lower cost.

Opening this issue as an opportunity for community members to express the desire to keep or maintain Tempo's serverless functionality. As of now, our position is to remove it.

**Comment by palerthanale** [comment]
Curious if we (Fleek.xyz / Network) might be able to help support here via Fleek Functions. Still in Alpha, but initial tests have been promising. Would love to connect and learn more, if of interest.

**Comment by edgarkz** [comment]
I haven't configured it since the Tempo 2.0 version, as I found that the standard Kubernetes HPA scaling works well for our needs.

**Comment by electron0zero** [comment]
serverless functions will be deprecated and deleted in the tempo next release, I am sending out a PR to mark them deprecated.

**Comment by xoan-grafana** [comment]
@electron0zero is this Done?
