### ISSUE TITLE
Add profiling endpoints

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#402]
> Package pprof serves via its HTTP server runtime profiling data in the format expected by the pprof visualization tool. The package is typically only imported for the side effect of registering its HTTP handlers. The handled paths all begin with /debug/pprof/ [0]

I propose the addition of a `--debug` flag.

If set, Tempo would export debugging information under the /debug path. In this case the pprof information (/debug/pprof).

This is interesting in case someone wants to continuously profile Tempo (with something like [Conprof](https://github.com/conprof/conprof) [1]) or manually use the [pprof visualization](https://github.com/google/pprof) tool [2].

[0] https://golang.org/pkg/net/http/pprof/
[1] https://github.com/conprof/conprof
[2] https://github.com/google/pprof

**Comment by joe-elliott** [comment]
Tempo already exposes pprof by using the weaveworks/common server:

https://github.com/weaveworks/common/blob/master/server/server.go#L361

This is controlled by the `server.register_instrumentation` config field which defaults to true.

**Comment by dgzlopes** [comment]
Oooooh! I see :)

Thanks a lot. Closing.

On the other hand, maybe it's interesting to add some docs about Server config, and maybe add an API section to the docs explaining the available endpoints.
