### ISSUE TITLE
Replace hedged requests roundtrips total with a counter

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#4060]
We are currently using a gauge incorrectly to report hedged roundtrips on both external endpoints and backend requests. This has worked in the past but recently we have seen this report erroneous results when `rate()`ing in prometheus. It's possible it never worked correctly and we have only recently noticed. Regardless, it's bad practice and we should fix it.

[External Hedged Requests Gauge](https://github.com/grafana/tempo/blob/f4b2642b16793ed13daf20c43cf37758c4fd6211/modules/querier/external/client.go#L33-L39)

[Backend Hedged Requests Gauge](https://github.com/grafana/tempo/blob/f4b2642b16793ed13daf20c43cf37758c4fd6211/tempodb/backend/instrumentation/hedged_requests.go#L10-L16)

[Shared code in use for both Gauges](https://github.com/grafana/tempo/blob/main/pkg/hedgedmetrics/metrics.go)

Let's replace the two linked gauges above with counters.

**Comment by galalen** [comment]
I would like to work on it

**Comment by joe-elliott** [comment]
Thanks @galalen. Let me know if you have any questions.
