### ISSUE TITLE
Imbalance resource usage of compactor instances

### ISSUE THREAD

**Issue by chenlujjj** [grafana/tempo#4067]
**Describe the bug**

We setup 8 replicas of compactor, and observed that the resource usage of them is imbalance, some instances' cpu and memory usage decreased suddenly to a very low level:
![Image](https://github.com/user-attachments/assets/5d88a8e5-a32e-4633-88bd-4225b955362d)
Seems this instance didn't send request to backend from a time point:
![Image](https://github.com/user-attachments/assets/44ebcabb-1ce0-4d8a-aeda-a13c7da9ed6f)

The normal instance:
![Image](https://github.com/user-attachments/assets/31c53819-c93e-4791-b956-9c7bb7d25dd5)
![Image](https://github.com/user-attachments/assets/60f0a499-5c60-4e96-b672-00417a46efd3)

**To Reproduce**
1. Start Tempo (SHA or version): 26.0
2. Perform Operations (Read/Write/Others): Produce traces in a steady rate and send to Tempo

**Expected behavior**

All compactor instances should have balanced resource usage

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment too: helm

**Additional Context**

The [TempoCompactorsTooManyOutstandingBlocks](https://github.com/grafana/tempo/blob/main/operations/tempo-mixin/runbook.md#tempocompactorstoomanyoutstandingblocks) is triggered, and `tempodb_compaction_outstanding_blocks` is increasing.
![Image](https://github.com/user-attachments/assets/5b855456-e0a4-4bb6-acf8-7c671f7dc2f7)

**Comment by joe-elliott** [comment]
As the rate of block creation increases I would recommend lowering the following setting to allow more compactors to participate in reducing the length of the blocklist:

```
compactor:
  compaction:
    compaction_window: 1h // default
```

Lowering this value too much will prevent compactors from finding blocks to attempt to compact so perhaps try 30m and see the impact?

**Comment by markustoivonen** [comment]
@joe-elliott are there any other measures one could try? Changing the compaction_window to 30min did not change the situation

For us the situation is the same, most of the time there is an idle pod even though the active pods might go over the resources they have and get oomkilled

![Image](https://github.com/user-attachments/assets/7a2e979a-4c32-496f-bb27-c9157bdb471b)
![Image](https://github.com/user-attachments/assets/4b1a91a8-7903-4046-a05b-0c2cf0a01e8d)

**Comment by joe-elliott** [comment]
What's the value of `tempodb_compaction_outstanding_blocks` and how long is your blocklist? it's possible you can just scale down compactors. It's not necessary to perfectly compact the blocklist.

**Comment by etiennep** [comment]
We've also experienced the same issue and I've noticed some log activity:

```
2024-12-15 06:00:26.459	
caller=compactor.go:160 err="does not exist" host=ip-10-51-14-209.us-west-2.compute.internal level=warn msg="unable to find meta during compaction.  trying again on this block list" pod=tempo-compactor-6958d9dcd6-wzt4c time=2024-12-15T14:00:26.459937865Z ts=2024-12-15T14:00:26.459864184Z
2024-12-15 06:00:26.445	
caller=compactor.go:160 err="does not exist" host=ip-10-51-14-209.us-west-2.compute.internal level=warn msg="unable to find meta during compaction.  trying again on this block list" pod=tempo-compactor-6958d9dcd6-wzt4c time=2024-12-15T14:00:26.445155043Z ts=2024-12-15T14:00:26.445079252Z
2024-12-15 06:00:26.430	
caller=compactor.go:160 err="does not exist" host=ip-10-51-14-209.us-west-2.compute.internal level=warn msg="unable to find meta during compaction.  trying again on this block list" pod=tempo-compactor-6958d9dcd6-wzt4c time=2024-12-15T14:00:26.430962995Z ts=2024-12-15T14:00:26.430871084Z
2024-12-15 06:00:26.421	
caller=compactor.go:162 err="unable to mark 2 blocks compacted" host=ip-10-51-14-209.us-west-2.compute.internal level=error msg="error during compaction cycle" pod=tempo-compactor-6958d9dcd6-wzt4c time=2024-12-15T14:00:26.421975681Z ts=2024-12-15T14:00:26.421888458Z
2024-12-15 06:00:26.413	
blockID=fe4c1bb7-5b08-4915-88ed-2d5ea5a9dbfc caller=compactor.go:286 err="error copying obj meta to compacted obj meta: The specified key does not exist." host=ip-10-51-14-209.us-west-2.compute.internal level=error msg="unable to mark block compacted" pod=tempo-compactor-6958d9dcd6-wzt4c tenantID=default time=2024-12-15T14:00:26.413388724Z ts=2024-12-15T14:00:26.413262341Z
2024-12-15 06:00:26.400	
blockID=906429df-a136-4382-be1e-26b0bfe05b4f caller=compactor.go:286 err="error copying obj meta to compacted obj meta: The specified key does not exist." host=ip-10-51-14-209.us-west-2.compute.internal level=error msg="unable to mark block compacted" pod=tempo-compactor-6958d9dcd6-wzt4c tenantID=default time=2024-12-15T14:00:26.400824270Z ts=2024-12-15T14:00:26.400695568Z
```

And then suddenly this instance's instance activity goes down to zero and never recovers.

**Comment by joe-elliott** [comment]
@mdisibio just put up a PR that we believe may cause this issue:

https://github.com/grafana/tempo/pull/4446

The internal blocklist is not being updated correctly and the same block is constantly being rediscovered.
