### ISSUE TITLE
Appending spans to flushed traces

### ISSUE THREAD

**Issue by multimac** [grafana/tempo#407]
**Is your feature request related to a problem? Please describe.**
In a system in-place at our work, there can be a delay of seconds to minute or hours between successive spans being captured for a given trace. With the current setup of Tempo, it seems to be that once a trace is flushed to the backend storage, and new spans received for that trace overwrite the previous data.

We have initially set `trace_idle_period` to `10s`. I'm guessing we could bump this up to `1h` or more but I'm not sure what the consequences of that would be.

**Describe the solution you'd like**
Would it be possible to add some functionality which can check for the existence of a previously flushed trace and append newly received spans to it instead of overwriting them?

**Describe alternatives you've considered**
I'm not sure how Tempo structures data in the storage backend, but maybe this could be done at the query layer by searching backwards for any additional spans for a given trace id?

**Comment by joe-elliott** [comment]
Agree that this is a current limitation of Tempo.  The current state of things:

1. Your trace is split inside of one block:
   This should always return the entire trace both in the ingesters and when it's flushed.
2. Your trace is split across multiple blocks:
   As long as both blocks are in the ingester this should return as a whole trace.  Once they are flushed the blocks will have to be compacted to return an entire trace.  This may take minutes or hours depending on how many spans are being ingested and other factors.
3. Your trace is split across multiple compaction time windows:
  These blocks will never be compacted and the trace will always return partial.

We are currently working on changes to perform an exhaustive search of the ingesters and blocks backend by adding a query-frontend.  Hoping to get this in soon-ish and definitely by v1.0.  Once this is in place no matter which of the three scenarios above is true a complete trace will always be returned.

https://github.com/grafana/tempo/pull/400

> I'm guessing we could bump this up to 1h or more but I'm not sure what the consequences of that would be.  

Ingesters limit the number of active traces primarily as a multi-tenant protection mechanism.  This can be adjusted using the following config option (Default is 10k).  If you adjust your `trace_idle_period` to 1 hour then hitting this is your primary concern.

https://github.com/grafana/tempo/blob/master/integration/bench/config.yaml#L39-L40
