### ISSUE TITLE
Add aggregation of TraceQL results

### ISSUE THREAD

**Issue by benmathews** [grafana/tempo#4075]
I would like to be able query the trace data for traces and aggregate the results into a rate the TraceQL query is returning results. The number should be usable in a Grafana dashboard in conjunction w/ other metric sources. 

This would allow me to get more value from the tracing data to identify when (for instance) error conditions increase.

**Comment by joe-elliott** [comment]
This is possible now by using [TraceQL Metrics](https://grafana.com/docs/tempo/latest/traceql/metrics-queries/) queries. For instance, to see total erroring spans/second in your applications:

```
{ status = error } | rate()
```

**Comment by benmathews** [comment]
Perfect. I'll give them a try.
