### ISSUE TITLE
"searching for trace in block" log flood

### ISSUE THREAD

**Issue by fede843** [grafana/tempo#4105]
We are logging Tempo with INFO level. Every time we do a simple query, logs get bombarded by hundreds of instances saying "searching for trace in block" and some other non relevant info.
As we keep querying this becomes quickly in a issue, getting thousands of these unwanted records.
It would be nice these can be dropped down to debug or something like that? Not sure what is the value on having all these under INFO level.

Here a screen shot for a single and simple query causing almost 1k entries:

![Image](https://github.com/user-attachments/assets/561013e7-bcb8-477f-a872-018b129f4654)

**Comment by joe-elliott** [comment]
Thanks for filing this issue. Agree this would make more sense to be logged at a debug level. This is a great first PR for anyone who wants to take it on.

**Comment by Aki0x137** [comment]
hi @joe-elliott. So all that is required to be done here is to change log level for this single line in tempodb?

**Comment by joe-elliott** [comment]
yup, i believe that's it.
