### ISSUE TITLE
Tempo Compactor Restarts

### ISSUE THREAD

**Issue by snyaik** [grafana/tempo#4111]
Hi Team,

We have encountering tempo compaction alerts daily. 
After going through the logs we found the following log message: 
 msg="error during compaction cycle" err="error iterating input blocks: error iterating through block XXXXX error in range read from s3 backend: unexpected EOF" 

There isn't much info available on how to resolve this intermittent issue. 

Compaction window is 1h 
max compaction objects is 6000000
Compaction Cycle is 30s
block retention is 72h

**Comment by javiermolinar** [comment]
Hi, what version of Tempo are you using? What's the frequency of these errors? Does the error happen for the same blocks more than once?
As you mentioned, this is an intermittent error, compactors should retry the compaction in the next run.

**Comment by snyaik** [comment]
@javiermolinar 
tempo version 2.4.1
Alert is received with a frequency of ~ 3 days. 
I know the alert says the compaction should work on next retry but just want to be sure that when more applications are onboarded this does not become a permanent annoying issue. 
I have already update max_bytes_per_trace from 30MB to 35MB. 
Is there anything which can be done to resolve the alert permanently.

**Comment by javiermolinar** [comment]
There's been some work recently in that area:

https://github.com/grafana/tempo/issues/3750

although upgrading 2 versions of Tempo can be tricky.

You can always try tuning some compactor configs to reduce the number of compactions:

https://github.com/grafana/tempo/blob/main/operations/tempo-mixin/runbook.md#tempocompactionsfailing

**Comment by Filipcsupka** [comment]
i am having the same issue on tempo helm chart 1.18.1. Every few(2-3 days).
error iterating input blocks: error iterating through block xxxx
Pretty annoying do we have an update or at least information on which version of tempo its still fine so i can downgrade ?
