### ISSUE TITLE
Tempo fails to parse query with multi-value variable

### ISSUE THREAD

**Issue by niekcandaele** [grafana/tempo#4112]
**Describe the bug**

Running the following query results in error `Error (invalid TraceQL query: parse error at line 1, col 57: syntax error: unexpected IDENTIFIER). Please check the server logs for more details.`

Removing the `$endpoint` variable (so only filtering by `test_id`) works fine.

```
{span.test_id="20240923-131122-nca-FTXUVybwCd" && name=~{get,get_/v1/cardholders/me_,get_/v1/cultures_,get_/v1/lookups/access-accesslevel_,get_/v1/lookups/access-cardholder_,get_/v1/lookups/visit-accesslevel_,get_/v1/lookups/visit-division_,get_/v1/lookups/visit-location_,get_/v1/lookups/visit-sponsor_,get_/v1/lookups/visit-visitor_,get_/v1/requests_,get_/v1/timezones_,get_/v1/users/me/settings_,get_/v1/users/me_}}
```

![Image](https://github.com/user-attachments/assets/34842efe-3e33-4d59-96e2-021de2bd1969)

**To Reproduce**
1. Start Tempo 2.6.0
2. Execute the above query, you should receive the error message

**Expected behavior**
The query should parse successfully and return results

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: `tempo-distributed` helm chart 1.18.0

**Additional Context**

Relevant log line: `level=error ts=2024-09-23T13:28:18.707351006Z caller=metrics_query_range_handler.go:88 msg="query range: query range combiner failed" err="compiling query: parse error at line 1, col 57: syntax error: unexpected IDENTIFIER"`

Query inspector output: 
![Image](https://github.com/user-attachments/assets/fbd9d365-fc63-4a15-ab42-0066ea209bb4)

**Comment by joe-elliott** [comment]
So this is an invalid query:
```
{span.test_id="20240923-131122-nca-FTXUVybwCd" && name=~{get,get_/v1/cardholders/me_,get_/v1/cultures_,get_/v1/lookups/access-accesslevel_,get_/v1/lookups/access-cardholder_,get_/v1/lookups/visit-accesslevel_,get_/v1/lookups/visit-division_,get_/v1/lookups/visit-location_,get_/v1/lookups/visit-sponsor_,get_/v1/lookups/visit-visitor_,get_/v1/requests_,get_/v1/timezones_,get_/v1/users/me/settings_,get_/v1/users/me_}}
```

You need `"` around the second value like:

```
{span.test_id="20240923-131122-nca-FTXUVybwCd" && name=~"{get,get_/v1/cardholders/me_,get_/v1/cultures_,get_/v1/lookups/access-accesslevel_,get_/v1/lookups/access-cardholder_,get_/v1/lookups/visit-accesslevel_,get_/v1/lookups/visit-division_,get_/v1/lookups/visit-location_,get_/v1/lookups/visit-sponsor_,get_/v1/lookups/visit-visitor_,get_/v1/requests_,get_/v1/timezones_,get_/v1/users/me/settings_,get_/v1/users/me_}"}
```

Also, is that a valid regex? This seems more like a Grafana query templating question than a Tempo question.

**Comment by niekcandaele** [comment]
Thanks for the quick response!

> This seems more like a Grafana query templating question than a Tempo question.

Yeah it might be, I used the Grafana UI to create this query and I guess it created an invalid query? Should the issue be transferred to the Grafana repo?

As far as I can tell, the regex should look like this (`|` instead of `,` between the options)
`{span.test_id="20240923-131122-nca-FTXUVybwCd" && name=~"get_/v1/cardholders/me_|get_/v1/cultures_"}`

**Comment by joe-elliott** [comment]
So I tried to reproduce your issue and could not. I created a "foo" variable populated with Tempo span names:

![Image](https://github.com/user-attachments/assets/1a722c3a-0acf-4bb5-a8da-3054ffb744b7)

I have also selected "Multi value" at the bottom. The pane is configured like:

![Image](https://github.com/user-attachments/assets/84f45cfb-6af0-4ca8-8d70-9b7b07d121dc)

This is rendering queries as expected when I choose multiple values:

![Image](https://github.com/user-attachments/assets/28aed200-dbe8-4ec0-aefe-43a021ad249d)

It looks kind of like Grafana is rendering your var with a non default format like csv:

https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#csv

**Comment by niekcandaele** [comment]
Thanks for looking at it again. I still see the commas when interpolating the variable, I did not enable any special parsing like what you linked. Just using the Grafana UI to build the query.

If I make the query directly in TraceQL, it's working fine so I don't think this is a Tempo issue but rather something in how Grafana generates the TraceQL from UI.

My problem is fixed by doing it directly in TraceQL, this issue can be closed. If you think it's necessary/helpful, I can create an issue in the Grafana repo to track the bug? It may just be me _doing it wrong_ in the UI

This works OK:
![Image](https://github.com/user-attachments/assets/b57d0a6f-856e-4d45-9aea-43920f7c419f)

This breaks (this generated query seems wrong, the syntax highlighting is all messed up):
![Image](https://github.com/user-attachments/assets/23f44e9d-097a-4c2f-9c5c-1bdcd3269ce7)

![Image](https://github.com/user-attachments/assets/1987fe4a-5989-44b0-ac39-5491cc9d528b)

This is the variable config:
![Image](https://github.com/user-attachments/assets/65858c36-4beb-4b1a-9fe5-c8e3616a1649)

Thanks for all your work, Tempo (and all the other Grafana projects) are really amazing!

**Comment by joe-elliott** [comment]
I'm going to close this issue (as opposed to transferring it) as it has a lot of Tempo detail, but this does seem like a Grafana TraceQL rendering issue. If you find the time and don't mind writing up an issue in the https://github.com/grafana/grafana/ repo we would appreciate it.
