### ISSUE TITLE
Empty Content-Type header from search endpoint

### ISSUE THREAD

**Issue by eddumelendez** [grafana/tempo#4121]
**Describe the bug**

There is a difference in the headers for `Content-Type` when calling `/api/search` between version `2.5.0` and `v2.6.0`

`grafana/otel-lgtm:0.7.2` uses tempo `2.5.0`

```
HTTP/1.1 200 OK
Content-Length: 698
Content-Security-Policy: sandbox
Content-Type: application/json
Date: Thu, 19 Sep 2024 00:18:27 GMT
Vary: Accept-Encoding
Via: 1.1 grafana
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

`grafana/otel-lgtm:0.7.3` uses tempo `v2.6.0`

```
HTTP/1.1 200 OK
Content-Length: 752
Content-Security-Policy: sandbox
Content-Type: 
Date: Thu, 19 Sep 2024 00:20:30 GMT
Vary: Accept-Encoding
Via: 1.1 grafana
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

The issue still happens in version `grafana/otel-lgtm:0.7.4`

**To Reproduce**
1. Start Tempo 2.5.0
2. Write a trace
3. Read trace

**Expected behavior**
Response should include header `Content-Type: application/json`

**Environment:**
[grafana/otel-lgtm](https://github.com/grafana/docker-otel-lgtm/)

**Additional Context**
I'm using [RestAssured](https://rest-assured.io/) to perform jsonpath operations but due to the lack of the header tests started failing when docker image version was updated.

**Comment by joe-elliott** [comment]
Thanks for filing this. We will likely build a 2.6.1 if you'd like to submit a PR to fix this we can get this in as well.

Any particular reason you're running tests against Tempo?

**Comment by eddumelendez** [comment]
I'm building an application that uses OpenTelemetry for metrics, traces and logs. In order to see is well configured and it is producing what I expect I am writing tests to see if metrics, traces and logs are stored correctly.

**Comment by javiermolinar** [comment]
The regression happened here:
https://github.com/grafana/tempo/commit/195936efd4648e011c3034986341492e673b249a

Before that change, the header was always set to `application-json` now we need to initialize the combiner with default values first. This was done for the TraceByIdV2 handler but not for others
