### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by RajGuru878** [grafana/tempo#4126]
Hi Team,

I am installed docker based tempo and my container is up and running. Thing is I am getting "404 page not found" in a browser (Screenshot attached below ) but able to see some metrics in browser with same ip/metrics. Also I am unable to receive any traces from my application. I am trying and working on this from last one month, requesting please anyone help me to resolve this issue and successfully get traces to my Grafana and visualise it. 
Thanks advance. 
![Image](https://github.com/user-attachments/assets/e193d254-058a-44ae-9e87-4f511c606c78)

**Comment by javiermolinar** [comment]
Hi, you can try one of the examples listed here and copy the configuration:

https://github.com/grafana/tempo/tree/main/example/docker-compose

**Comment by RajGuru878** [comment]
@javiermolinar 
I will you about our application, that my php laravel application is installed in another server and i configured open telemetry and zipkin. I am able to get traces in zipkin. Now i wanted to configure tempo to receive traces directly from open-telemetry and crate dashboard on that. I have installed tempo fro that. Now i am unable to receive traces. Can you please suggest anything on this , my grafana and tempo is running on my grafana serrver and my open-telemetry and zipkin is running on different server where i have my laravel application.

**Comment by RajGuru878** [comment]
anybody please help me in this

**Comment by mapno** [comment]
Hi @RajGuru878. I believe there's a misunderstanding here. Tempo's UI is Grafana, there's not a embedded UI at `/` in Tempo. If you want to use Tempo's API without Grafana, you can check the API docs [here](https://grafana.com/docs/tempo/latest/api_docs/).

**Comment by knylander-grafana** [comment]
@RajGuru878 Which doc did you follow? We can add a statement to the doc to clarify that Tempo only has the API or you can use Grafana for a UI.
