### ISSUE TITLE
tempo tag search slow / not cached

### ISSUE THREAD

**Issue by msvechla** [grafana/tempo#4182]
**Is your feature request related to a problem? Please describe.**

We have configured two additional static filters in the Tempo data source in Grafana, for two common tags we add to all traces.
Both have a very low cardinality (less than 20 values).

When opening the Tempo Explore Search view in Grafana, all values for the configured filters are queried to populate the dropdown fields.
The built-in `resource.service.name` and `name` requests return very quickly, while the two custom tags take usually around 7 seconds or more to complete.

**Describe the solution you'd like**

It seems there is some special handling for these built-in tags, in comparison to the two custom tags we added. It would be great if similar optimization could be implemented for common queried tags, especially if they are always queried on the Tempo Search landing page.

In our case, these values are even fairly static, so caching them would be very efficient.

**Describe alternatives you've considered**

**Additional context**

The following API is used to query the tags: `/api/v2/search/tag/span.platform.aws.organizational_unit/values?q=%7B%7D`

Thanks a lot for your help!

**Comment by mapno** [comment]
Hi! That's because `resource.service.name` and `name` are special columns in the parquet schema that Tempo uses. Whereas the other attributes are more generic and don't have a special column for them. You can achieve a similar behaviour to special attributes with [dedicated columns](https://grafana.com/docs/tempo/latest/operations/dedicated_columns/).

**Comment by msvechla** [comment]
@mapno thanks for the hint, I will give dedicated columns a try!

@joe-elliott interesting, I will give this a try as well once it has been released

**Comment by msvechla** [comment]
@mapno I just tried out [dedicated columns](https://grafana.com/docs/tempo/latest/operations/dedicated_columns/) and they improved the performance significantly. Thanks a lot for this hint!
