### ISSUE TITLE
Release 2.6.1 is missing binaries

### ISSUE THREAD

**Issue by nicholasdille** [grafana/tempo#4194]
**Describe the bug**

The latest release (v2.6.1) does not offer any release binaries.

**To Reproduce**

Check out the release for v2.6.1: https://github.com/grafana/tempo/releases/tag/v2.6.1

**Expected behavior**

The release offers binaries just like 2.6.0.

**Comment by electron0zero** [comment]
Hi, our release pipeline was broken, and team is working on a fix. 

we should have the binaries built and pushed once that's sorted out.

**Comment by joe-elliott** [comment]
Thanks for the heads up! This has been fixed:

https://github.com/grafana/tempo/releases/tag/v2.6.1
