### ISSUE TITLE
Enable SpanMultiplier Calculation from Resource Attributes, not Just Span Attributes

### ISSUE THREAD

**Issue by JunhoeKim** [grafana/tempo#4202]
**Is your feature request related to a problem? Please describe.**
We manage deployment configurations by assigning resource attributes through environment variables. For instance, we set `OTEL_TRACES_SAMPLER_ARG: 0.05` and intend to specify `OTEL_RESOURCE_ATTRIBUTES: sampler_rate=$(OTEL_TRACES_SAMPLER_ARG)` accordingly. Therefore, we would like to calculate Tempo's SpanMultiplier using resource attributes to adjust and correct the metrics accurately.

**Describe the solution you'd like**
By modifying the GetSpanMultiplier function in the util package, it seems like this feature could be implemented fairly easily.

**Comment by joe-elliott** [comment]
If you want to work on this, we would be glad to accept the PR. Agree this shouldn't be too difficult and we can help with any questions you may have.
