### ISSUE TITLE
tempo-cli: add support for dropping multiple traces in single operation

### ISSUE THREAD

**Issue by electron0zero** [grafana/tempo#4246]
We currently have a command in `tempo-cli` under `rewrite-blocks drop-trace` to delete a [single trace from a block](https://grafana.com/docs/tempo/latest/operations/tempo_cli/#drop-trace-by-id).

However, there are scenarios where operators may need to drop multiple traces from a single block. 
To achieve this now, they must loop through the list of trace IDs and execute the `drop-trace` command. This is inefficient, as it requires rewriting the same block multiple times (_pulling and uploading the same block to backend_) when dropping several traces.

I propose adding a new command (or updating the current one) to accept a list of trace IDs to delete multiple traces from a block in a single operation.

**Comment by ndk** [comment]
How about letting to specify multiple trace IDs separated by commas?
```console
tempo-cli rewrite-blocks drop-trace --backend=local --bucket=./data --drop-trace traceid1 single-tenant
tempo-cli rewrite-blocks drop-trace --backend=local --bucket=./data --drop-trace traceid1,traceid2 single-tenant
tempo-cli rewrite-blocks drop-trace --backend=local --bucket=./data --drop-trace traceid1,traceid2,traceid3 single-tenant
```

**Comment by electron0zero** [comment]
I am good on passing the multiple traceIDs via comma to the current command instead of adding a new command, very valid approach and gets the job done.

To better indicate that it can take multiple traceIDs, we are rename the command to be plural (from `drop-trace` to `drop-traces`)

will leave more feedback on the PR when it's out of draft and ready for review.
