### ISSUE TITLE
Count over time Traceql query doubles the actual span count randomly

### ISSUE THREAD

**Issue by imjibi** [grafana/tempo#4257]
**Describe the bug**
When trying to count the number of spans using `count_over_time` the actual count gets doubled randomly.  Query used was `{} | count_over_time() by (name)`

**To Reproduce**
1. Use https://github.com/grafana/docker-otel-lgtm/tree/main and make sure it uses Tempo version 2.6.0
2. Change backend to Azure blob storage and fill in required details. Mine was as follows,
```
  storage:
    trace:
      backend: azure
      azure:
        container_name: 'containername'
        storage_account_name: 'storageaccount'
        storage_account_key: 'key'
```
3. Start generating traffic using  curl command that can be found [here](https://github.com/grafana/docker-otel-lgtm/blob/main/generate-traffic.sh). Make sure to send traffic without a delay _(wanted to replicate our production scenario hence chose to skip delay)_ and I triggered traffic from command line as follows

```
while true
do
curl -s http://localhost:8081/rolldice
done
```
4. After waiting for almost an hour, go to Grafana and choose Tempo data source and run `{name="roll"} | count_over_time() by (name)` . Please make sure step is set to `1m` and time range is last 1 hour - this is really important as issue happens only when range is set to last 1 hour, if you choose an hour window in the past query works just fine. It will show a time series with a huge spike at a random point `(if you don't see any spike at once just try hitting Run Query every minute )`. Looking the value you could see that its exactly twice the actual value and the next minute the doubling behaviour moves to next point in time.
5. The following snap shot show the buggy behaviour
At 16:26 you could see that the count is 4.87K which is the actual value
![Image](https://github.com/user-attachments/assets/ea4d05a5-c2aa-4aae-bab4-c0d3df54fb2e)
After a moment later the count is changed to 9.74K which exactly the double of the actual value.
![Image](https://github.com/user-attachments/assets/6cc1186b-aca2-452f-a32f-fa7249b13fd0)
And then it continuously slides through the window.
Actual Count at 16:27  is 4.73K
![Image](https://github.com/user-attachments/assets/a291b0ab-2feb-45e9-b3fd-1433e780a5e2)
Couple of minutes later it is 9.45K
![Image](https://github.com/user-attachments/assets/89d422ac-022a-4c9a-8081-5a97745963fc)

**Expected behavior**
The count should n't get doubled when looking at the last 1 hour span count
**Environment:**
 - Infrastructure: k8s, docker-compose
 - Deployment tool: helm, docker

**Comment by joe-elliott** [comment]
Unfortunately I have not had time to dig into this yet, but my belief is that spans are occasionally being double counted on the border between the metrics generators and the backend.

The frontend calculates a cut off here:
https://github.com/grafana/tempo/blob/3449ef6a6d9532474a6ba83c9d257c5d8359c0df/modules/frontend/metrics_query_range_sharder.go#L114

and attempts to cleanly divide what is requested from the generators and backend. Perhaps if the timing of the query is aligned in a specific way we actually double count.

**Comment by mdisibio** [comment]
I was able to reproduce this and will take a look.
