### ISSUE TITLE
Document all APIs

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#428]
**Is your feature request related to a problem? Please describe.**
There is no concise place where all apis are documented for Tempo.  We should add this.  For the various ingestion protocols we should just link to external docs.  There's no reason to replicate it.

**Comment by annanay25** [comment]
Cortex API docs for reference: https://github.com/cortexproject/cortex/blob/master/docs/api/_index.md

cc @achatterjee-grafana

**Comment by swartz-k** [comment]
Does this api docs are mostly about Querier and Query-Frontend?
Show API in [here](https://github.com/grafana/tempo/blob/master/cmd/tempo/app/modules.go) Such as in Querier `/querier/api/traces/{traceID}` to FindTraceByID

**Comment by joe-elliott** [comment]
This does not need to cover the APIs of the receiver shims. However, it should link to appropriate documentation where possible.
