### ISSUE TITLE
Documentation feedback: /docs/sources/tempo/operations/traceql-metrics.md

### ISSUE THREAD

**Issue by MrMegaMango** [grafana/tempo#4294]
This sentence appears twice in doc:
"Setting flush_to_storage to true ensures that metrics blocks are flushed to storage so TraceQL metrics queries against historical data."
You should talk about how traces_storage in tempo-distributed whether ReadWriteMany PersistentVolumeClaim needed for metricsGenerator to read WAL from ingesters.

**Comment by knylander-grafana** [comment]
Thank you for creating this doc issue!
