### ISSUE TITLE
Distributor Failing to Consume Trace Data with Context Deadline Exceeded Errors in Tempo 2.5.0

### ISSUE THREAD

**Issue by gustavosett** [grafana/tempo#4400]
**Describe the bug**
The distributor component in Grafana Tempo version 2.5.0 is experiencing issues where it fails to consume trace data. Errors such as `pusher failed to consume trace data` with `context deadline exceeded` and `rpc error: code = Unavailable desc = connection error` are frequently logged. Additionally, there are warnings about failing health checks for distributor pools and memberlist suspicions that other components like ingesters and compactors have failed.

**To Reproduce**
1. Start Tempo version 2.5.0 using `lgtm-distributed-2.1.0` in a Kubernetes cluster.
2. Perform regular read and write operations.
3. Monitor the logs of the distributor component over time.

**Expected behavior**
The distributor should reliably consume trace data without errors or timeouts and maintain stable communication with other Tempo components like ingesters and compactors.

**Environment:**
- Infrastructure: Kubernetes v1.30.2
- Deployment tool: Helm v3.15.2

**Additional Context**
Below are excerpts from the distributor logs showing the errors and warnings:

```
level=warn ts=2024-11-25T20:44:44.32033078Z caller=main.go:130 msg="-- CONFIGURATION WARNINGS --"
level=warn ts=2024-11-25T20:44:44.320400471Z caller=main.go:136 msg="Local backend will not correctly retrieve traces with a distributed deployment unless all components have access to the same disk. You should probably be using object storage as a backend."
...
level=warn ts=2024-11-27T18:41:30.388287267Z caller=pool.go:250 msg="removing distributor_pool failing healthcheck" addr=10.244.30.101:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
ts=2024-11-27T18:41:34.363570836Z caller=memberlist_logger.go:74 level=info msg="Suspect lgtm-tempo-compactor-566df495f7-l26qg-e7d24187 has failed, no acks received"
level=error ts=2024-11-27T18:41:36.100192223Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
level=error ts=2024-11-27T18:41:38.631352045Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: read tcp 10.244.23.237:53618->10.244.30.101:9095: use of closed network connection\""
...
ts=2024-11-28T18:41:54.36321052Z caller=memberlist_logger.go:74 level=info msg="Suspect lgtm-tempo-compactor-566df495f7-l26qg-e7d24187 has failed, no acks received"
level=error ts=2024-11-28T18:41:54.735725132Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
```

**Notes:**
- The issue persists across multiple days, indicating a consistent problem.
- The logs frequently mention timeouts, suspect nodes, and closed network connections.
- There is a configuration warning suggesting the use of object storage as a backend instead of local storage in a distributed setup.

**Comment by joe-elliott** [comment]
I don't know much of anything about the lgtm chart. This issue may belong in the https://github.com/grafana/helm-charts repo, but we can do some investigation here.

> Monitor the logs of the distributor component over time.

Are you seeing similar log messages in other components?

> ts=2024-11-27T18:41:34.363570836Z caller=memberlist_logger.go:74 level=info msg="Suspect lgtm-tempo-compactor-566df495f7-l26qg-e7d24187 has failed, no acks received"

These kind of messages can occur if you have pod instability or during a rollout. If the pods are all stable and you're seeing these messages it suggests possibly some network? or other resource saturation issues.

> level=warn ts=2024-11-27T18:41:30.388287267Z caller=pool.go:250 msg="removing distributor_pool failing healthcheck" addr=10.244.30.101:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
> level=error ts=2024-11-27T18:41:38.631352045Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: read tcp 10.244.23.237:53618->10.244.30.101:9095: use of closed network connection\""

I'm not seeing errors like this in our production clusters. Are your ingesters stable? Were they rolling out when these errors occurred?

> level=warn ts=2024-11-25T20:44:44.320400471Z caller=main.go:136 msg="Local backend will not correctly retrieve traces with a distributed deployment unless all components have access to the same disk. You should probably be using object storage as a backend."

This suggests a bad configuration, but is not important unless the ingesters, compactors, or queriers are also logging this. The distributors don't use the backend so it may just be a weird configuration in the distributors only. If you are seeing this message in the components mentioned above it is an incorrect configuration that will result in strange behavior.
