### ISSUE TITLE
make vendor-check fails with spaces in working dir path

### ISSUE THREAD

**Issue by savishy** [grafana/tempo#451]
**Describe the bug**

`make vendor-check` fails when the path has spaces, for example `/Users/username/Path With Spaces/work/savishy-tempo`.
The error is `docker: invalid reference format.` which I have seen typically when Docker thinks we are passing it incorrect arguments.
I moved to a path without spaces i.e. `/Users/username/savishy-tempo` and `make vendor-check` works fine. 
My first guess is we just need to surround with quotes at the appropriate point in the `Makefile`.

**To Reproduce**
1. Fork the repo 
2. Clone it to a directory with spaces in the path.
3. Run `make vendor-check`

**Expected behavior**
Successful run.

**Environment:**
 - Infrastructure: Macbook

**Additional Context**

Full output

```
~/Path With Spaces/work/savishy-tempo$ make vendor-check
rm -rf opentelemetry-proto
go mod vendor
go mod tidy
# ignore log.go b/c the proto version used by v0.6.1 doesn't actually have logs proto.
find . | grep 'vendor/go.opentelemetry.io.*go' | grep -v -e 'log.go' | xargs -L 1 sed -i '' 's+go.opentelemetry.io/collector/internal/data/opentelemetry-proto-gen/+github.com/open-telemetry/opentelemetry-proto/gen/go/+g'
/Library/Developer/CommandLineTools/usr/bin/make gen-proto
git submodule init
git submodule update
Submodule path 'opentelemetry-proto': checked out 'e43e1abc40428a6ee98e3bfd79bec1dfa2ed18cd'
rm -rf ./vendor/github.com/open-telemetry/opentelemetry-proto
docker run --rm -u 502 -v/Users/username/Path With Spaces/work/savishy-tempo:/Users/username/Path With Spaces/work/savishy-tempo -w/Users/username/Path With Spaces/work/savishy-tempo/ otel/build-protobuf:0.1.0 --proto_path=/Users/username/Path With Spaces/work/savishy-tempo -I./opentelemetry-proto/ -Ipkg/tempopb/ -I./ opentelemetry-proto/opentelemetry/proto/common/v1/common.proto --gogofaster_out=plugins=grpc:./vendor
docker: invalid reference format.
See 'docker run --help'.
make[1]: *** [gen-proto] Error 125
make: *** [vendor-dependencies] Error 2
```

**Comment by ie-pham** [comment]
I've taken some digging into this. We can do one thing to make sure the parameters are correctly formatted in this line:

https://github.com/grafana/tempo/blob/main/Makefile#L140

But ultimately, this is an upstream issue with the [docker-protobuf wrapper](https://github.com/jaegertracing/docker-protobuf/blob/master/protoc-wrapper) not being able to accept spaces.
