### ISSUE TITLE
[examples] Docker compose minio example fails to start

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#454]
**Describe the bug**

Tempo container fails with 
```
level=error ts=2021-01-13T09:43:38.572394324Z caller=main.go:92 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from BucketExists on tempo: Server not initialized, please try again."
```

(Reported by Julien on Public Slack, can confirm I get the same error)

A fix was attempted in #448 

**To Reproduce**
Run the docker compose minio example

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] - Mac, Ubuntu
 - Deployment tool: [e.g., helm, jsonnet] - docker-compose

**Additional Context**

**Comment by roidelapluie** [comment]
oh sorry , it seems like minio error: Error: Storage reached its minimum free disk threshold.


I wonder if by default we should have different minio settings

**Comment by annanay25** [comment]
Agree it works for me as well on the latest images. 

@roidelapluie - I think the min disk space is non-configurable. Do you know of any other settings we can tweak?

**Comment by annanay25** [comment]
Going to mark this as resolved.
