### ISSUE TITLE
tempo-query Docker Image fails to start in OpenShift

### ISSUE THREAD

**Issue by ralph089** [grafana/tempo#456]
**Describe the bug**
The tempo-query Docker Image does not run in OpenShift. It tries to write a file in /tmp which is not allowed without proper permissions, see: https://access.redhat.com/documentation/en-us/openshift_container_platform/3.10/html/creating_images/creating-images-guidelines

**To Reproduce**
1. Start Tempo-Query Docker Image in OpenShift using the given helm example in this repository

**Expected behavior**
Image starts without errors

**Environment:**
 - Infrastructure:  OpenShift 3.11
 - Deployment tool: helm

**Additional Context**
I resolved the issue using another base image.

```
FROM grafana/tempo-query:latest AS builder

FROM alpine:latest
COPY --from=builder /tmp/tempo-query /tmp/tempo-query
COPY --from=builder /go/bin/query-linux /go/bin/query-linux

ENV SPAN_STORAGE_TYPE=grpc-plugin \
    GRPC_STORAGE_PLUGIN_BINARY=/tmp/tempo-query

RUN chgrp -R 0 /tmp && chmod -R g+rwX /tmp

EXPOSE 16686/tcp
ENTRYPOINT ["/go/bin/query-linux"]
```

**Comment by joe-elliott** [comment]
Similar to #434

**Comment by kalali** [comment]
Is there any other solution than rebuilding the docker image? The issue is reproducible in openshift 4.6

**Comment by joe-elliott** [comment]
Grafana 7.5.0 along with Tempo image `grafana/tempo:d59fc755` does not require the tempo-query piece. Some docs here:

https://grafana.com/docs/tempo/latest/configuration/querying/

I was waiting for us to cut 0.7.0 to post announce this as the official workaround, but it will work now if you pull a commit hash directly.

**Comment by pavolloffay** [comment]
@joe-elliott it seems that this can be closed. I have deployed tempo monolith on OCP and I didn't have this issues.

**Comment by joe-elliott** [comment]
awesome, thanks pavol!
