### ISSUE TITLE
Persist gossip ring tokens for better membership stability

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#464]
**Describe the bug**
Gossip ring membership is not stable in some situations.  Tempo uses the cortex ring functionality and each instance claims tokens.  Because the tokens are not persisted, any case which causes the container to be recreated could cause tokens to be unexpectedly claimed again.  This is particularly impactful to compactors because 2 compactors operating on the same block will lead to errors.

**To Reproduce**
1. Deploy ingesters or compactors.  Visit :3100/ingester/ring or :3100/compactor/ring.  Note the Tokens.
2. Perform a change that recreates the pods:  change memory resources or deploy new version
3. Browse again and verify the tokens have changed.

**Expected behavior**
Sharding of blocks / tokens is stable across rollouts or minor changes.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Comment by joe-elliott** [comment]
The Cortex lifecycler already has support for this.  It is as simple as setting the right config option:

```
ingester:
    lifecycler:
        tokens_file_path: /var/tempo/tokens.json
```
