### ISSUE TITLE
Can you support it skywalking agent

### ISSUE THREAD

**Issue by 929541303** [grafana/tempo#466]

**Comment by annanay25** [comment]
Hi @929541303; Tempo supports most popular trace formats including - OpenTracing, OpenTelemetry and Zipkin. Is Apache Skywalking Agent opentracing compatible? This doc here (https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Opentracing.md) suggests that it is. If so, Tempo can ingest traces from the Apache Skywalking agent.

**Comment by joe-elliott** [comment]
OpenTracing is not a wire format.  So even if the Skywalking agent is OpenTracing compatible that does not mean that Tempo can ingest it.  

If there is sufficient interest or someone wanted to contribute support for the Skywalking client we would consider it.

**Comment by annanay25** [comment]
🤦  my bad. You're absolutely right. Should fix that to - Jaeger, OpenTelemetry and Zipkin.

**Comment by 929541303** [comment]
so, tempo could not ingest traces from  Apache Skywalking agent，right？

**Comment by joe-elliott** [comment]
As far as we are aware it can't.  Unless Apache Skywalking supports one of the open formats listed above.

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！

**Comment by mapno** [comment]
Closing. Feel free to re-open it.
