### ISSUE TITLE
Support AlibabaCloud OSS

### ISSUE THREAD

**Issue by swartz-k** [grafana/tempo#469]
**Is your feature request related to a problem? Please describe.**

While I use Tempo based on AlibabaCloud OSS, There will be an error say `Access Denied`. 
Refer to code `tempodb/backend/s3/s3.go:104` `HeadBucket` function
but [AlibabaCloud OSS ](https://www.alibabacloud.com/help/doc-detail/31967.htm?spm=a2c63.p38356.b99.988.58b05cb0eHGWrW)does not support it

**Describe the solution you'd like**

In MINIO、AlibabaOSS and S3 API they have those same methods, So I think could we change `HeadBucket` to `PutObject` ? In this way, we can support more backend storage.

**Describe alternatives you've considered**
HeadBucket means: if a bucket exists and you have permission to access it. 
PubObject    means: Adds an object to a bucket. You must have WRITE permissions on a bucket to add an object to it. If this object exist will be overwritten.

Maybe we can use a object with uniqe name lik `tempo-s3-storage-test` with method `PutObject`?

**Additional context**

**Comment by swartz-k** [comment]
What do you think?  :)   @joe-elliott @annanay25

**Comment by joe-elliott** [comment]
We do want to make sure we check that the bucket exists on startup so we can fail fast.  However, it appears that we immediately attempt to list the bucket which should cover that requirement:

https://github.com/grafana/tempo/blob/master/tempodb/backend/s3/s3.go#L104

Writing a dummy object would also be an interesting improvement as that would guarantee that not only does the bucket exist, but write permissions are setup correctly.

I am fine with the simple fix of just removing the `BucketExists` code in the link above if you have time to submit a PR.

**Comment by swartz-k** [comment]
> I am fine with the simple fix of just removing the `BucketExists` code in the link above if you have time to submit a PR.

Thanks. PR is [Here](https://github.com/grafana/tempo/pull/476)
