### ISSUE TITLE
production-ready helm chart

### ISSUE THREAD

**Issue by jjangga0214** [grafana/tempo#478]
Hi, 

As we all know, for k8s, helm chart is the most popular way of provisioning self-contained opensource services (e.g. Grafana, Loki).

Thus, I guess providing a production-ready helm chart is essential for a service (Tempo, in this case) to be used widely.

I am also evaluating it for production, but our company manages everything by helm, so the lack of the official helm chart can be an issue.  

Tempo is a young project. 

Being adapted to a variety of circumstances might accelerate its evolution to be more contributed, performant, and advanced.

Thus, I think releasing stable helm chart has a quite high priority for its growth.

How do you think?

Thanks.

**Comment by joe-elliott** [comment]
I agree!

There are two helm charts in the works here:

https://github.com/grafana/helm-charts/pull/167
https://github.com/grafana/helm-charts/pull/166

Feel free to review and add your thoughts!
