### ISSUE TITLE
Upgrade to the latest protobuf docker image

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#479]
OpenTelemetry is updating the protobuf image in the master repo to `0.2.1`, we should follow suit.

We're using `0.1.0` as of now - https://github.com/grafana/tempo/blob/3bd19f663f42c394e0b5ced8e1bd90a4f5798d75/Makefile#L124

**Comment by swartz-k** [comment]
I will test it and if works make a PR.

**Comment by mdisibio** [comment]
This is part of #546
