### ISSUE TITLE
Unable to query traces when using Azure Blob storage account as the storage backend

### ISSUE THREAD

**Issue by nshampur** [grafana/tempo#494]
**Describe the bug**
Unable to query traces when using Azure Blob storage account as the storage backend

**To Reproduce**
1. Update the helm chart https://github.com/grafana/tempo/tree/master/operations/helm/tempo-microservices values to use Azure Blob Storage per https://grafana.com/docs/tempo/latest/configuration/azure/ 
2. Deploy Tempo using helm to a k8s cluster (I used AKS) https://github.com/grafana/tempo/tree/master/operations/helm/tempo-microservices
3. Ingest traces and verify that they are ingested (metrics tempo_distributor_spans_received_total  and tempo_distributor_spans_received_total are greater than 0
4. Perform Query for traces using either jaeger or tempo datasource in grafana

**Expected behavior**
Querying traces should work

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
![image](https://user-images.githubusercontent.com/4503683/106373362-9afecc80-632d-11eb-8a2c-7ad60a993f6c.png)
![image](https://user-images.githubusercontent.com/4503683/106373394-c71a4d80-632d-11eb-9a00-b3c7f77d39fb.png)

**Comment by pedrosaraiva** [comment]
I think this is related to this issue #478, the chart has a couple of issues at the moment like some hardcoded namespaces. The issue with the  query is related to a missing port and a missing service you can check our fork https://github.com/anovateam/tempo/commit/7b1aae12dcf117948b5a1dcf8340cb0cd851bf09

**Comment by nshampur** [comment]
Thanks @pedrosaraiva - that was it. 
I already had locally fixed the issues with the helm chart for namespaces, but missed the query service-port. Which explains why the query was timing out and not a "Trace not found" message.

IMO - the chart still needs more improvements (e.g. parameterizing the receivers for the distributor [otlp], annotations for distibutor deployment [e.g- prometheus/scrape: true)

Also - {{- toYaml .Values.backend | nindent 12 }}  does not render valid YAML since it 
a. Writes out just the value (e.g:- azure | s3)
b. wont copy the storage configuration element (e.g- .Values.azure.container-name

Thanks for the assistance.  I'll close this issue and log the others as separate issues targeting the helm chart.

**Comment by joe-elliott** [comment]
Apologies for the gross helm chart.  We intend to remove it once these are merged:

https://github.com/grafana/helm-charts/pull/167
https://github.com/grafana/helm-charts/pull/166

**Comment by nshampur** [comment]
That's great.  I'll sync up our forked version when merged. 

Thanks folks. gr8 work!
