### ISSUE TITLE
Publish a grafana dashboard that captures the health of a tempo deployment

### ISSUE THREAD

**Issue by nshampur** [grafana/tempo#499]
**Is your feature request related to a problem? Please describe.**
In order to know if tempo is working as desired and capturing traces, it would be handy to have a grafana dashboard that helps visualize the prometheus metrics that are exposed (ingested spans, traces, dropped etc)

**Describe the solution you'd like**
A grafana dashboard that can be easily imported

**Describe alternatives you've considered**
Building a dashboard ourselves.

**Comment by dgzlopes** [comment]
Hi @nshampur! Thanks for creating the ticket.

I think there are dashboards available on the `/operations/tempo-mixin/out` folder.

These dashboards are generated with jsonnet, you can find more info about that [here](https://github.com/grafana/tempo/tree/master/operations/tempo-mixin).

**Comment by nshampur** [comment]
That's perfect. 

RTFM for me, I guess :)
