### ISSUE TITLE
can you support arm 64 

### ISSUE THREAD

**Issue by 929541303** [grafana/tempo#501]
At present, only x86 CPU can be found in docker hub. Can't find arm or arm64 version. Can you support arm64 and when

**Comment by swartz-k** [comment]
Sure. I will add multi OS Arch artifact. It may be useable after 3 days.

**Comment by joe-elliott** [comment]
We used to have basic multi arch support in our Makefile using `docker buildx` but abandoned it b/c it required experimental docker features enabled.  Yes, we definitely would like to support multi arch images, but we were waiting for buildx to not require the experimental flag.

@annanay25 @mdisibio @dgzlopes 

Thoughts on going back to buildx and requiring experimental features enabled locally to build our docker images?  Or perhaps we can have two `make` commands?  One that is intended for locally building the images and one in CI that uses buildx?

**Comment by dgzlopes** [comment]
I kinda prefer having two commands. That way the "normal" command just works for anyone trying to run it locally (without having to enable experimental features).

**Comment by swartz-k** [comment]
Build image refer to [Build: add support for multi arch build #311
](https://github.com/grafana/tempo/commit/814282d57ad64a2477522289f1c79a321a6a3251#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) and split that into commands like `make docker-tempo` and `make ci-docker-tempo` ?

**Comment by joe-elliott** [comment]
yup.  i would support readding buildx under a different make command and using it in CI to generate multi-arch images.

**Comment by 929541303** [comment]
so, how long would you publish multi-arch images to the hub.docker.com

**Comment by annanay25** [comment]
Sorry I missed this, +1 to having two commands.

**Comment by joe-elliott** [comment]
@929541303 
I intend to get into this next week.
