### ISSUE TITLE
Remove ObjectCombiner from the Find path

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#507]
**Is your feature request related to a problem? Please describe.**
Currently we pass an ObjectCombiner down through the `Find` methods in the Complete and Append blocks.  This causes for inefficient combines as well as complicated logic that is unnecessary.

**Describe the solution you'd like**
- Remove the ObjectCombiner parameter from the mentioned Find methods and clean up all relevant logic.
- Return a `[][]byte` and just return all matched objects in TempoDB
- In the querier handle recombining.  We should marshal to proto first before combining for efficiency.

**Comment by mdisibio** [comment]
Note:  `[][]byte` is insufficient, it would need the accompanying `dataEncoding` for each slice.
