### ISSUE TITLE
Trace Id which is working after couple of hours for same trace id 404 is reported

### ISSUE THREAD

**Issue by mnadeem** [grafana/tempo#511]
**Describe the bug**

TraceId which used to work couple of hours before, started giving 404

![image](https://user-images.githubusercontent.com/476145/107230520-30444400-6a45-11eb-8305-fe1ea73927f7.png)

**To Reproduce**
I have deployed tempo as described in the [blog](https://reachmnadeem.wordpress.com/2021/01/30/distributed-tracing-using-grafana-tempo-jaeger-with-amazon-s3-as-backend-in-openshift-kubernetes)

**Expected behavior**

Trace ID should not be lost, there should be a way to configure the persistence, like 14 days or so the way we do it in prometheus 

**Environment:**
 - Infrastructure: [[Openshift with S3 as backend](https://reachmnadeem.wordpress.com/2021/01/30/distributed-tracing-using-grafana-tempo-jaeger-with-amazon-s3-as-backend-in-openshift-kubernetes/)]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by joe-elliott** [comment]
You are configured to drop blocks after 1h:

```
compactor:
  compaction:
    block_retention: 1h
```

If you wish to increase your retention do it here.  By default Tempo has a `78h` (3d) retention.  In our internal cluster we use `336h` (14d).

**Comment by mnadeem** [comment]
Any idea, I have started getting the following the error for latest image?

````
  | failed parsing config: failed to parse configFile /etc/tempo/tempo.yaml: yaml: unmarshal errors:
-- | --
  | line 44: field bloom_filter_false_positive not found in type wal.Config
  | line 45: field index_downsample not found in type wal.Config
````

**Comment by mnadeem** [comment]
I have found it

https://github.com/grafana/tempo/blob/master/example/docker-compose/etc/tempo-s3-minio.yaml
