### ISSUE TITLE
Add Cortex Background Cache

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#528]
Currently, we cache keys (bloom/index) in Memcached in the Query hot path and this affects our latency when memcached has issues with eviction/high throughput.. we should add support for [Cortex Background Cache](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/background.go), which in @gouthamve's words - "is magic :slightly_smiling_face: It buffers and writes things with a goroutine pool. And drops things on the floor if too many writes are pending".

Additionally, we should see if we can reuse Cortex's Cache interfaces to avoid repetition of code. 
https://github.com/cortexproject/cortex/blob/16265a049d1d7b8498bd54b9ba154acfc98bc025/pkg/chunk/cache/cache.go#L20-L24

**Comment by dgzlopes** [comment]
I'll start working on this one :)
