### ISSUE TITLE
Distributors should drain before terminating

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#530]
**Is your feature request related to a problem? Please describe.**
Currently in a high volume environment when rolling out a new version the distributors will terminating instantly and drop any in flight spans.

**Describe the solution you'd like**
Instead, when receiving SIGTERM, the distributor should:
- Drop readiness
- Wait a configurable amount of time
- Exit

**Comment by joe-elliott** [comment]
As part of this PR let's add the `maxUnavailable` parameter to the distributors to prevent them all rolling at once.

Here's an example of it being used on the compactor:
https://github.com/grafana/tempo/blob/master/operations/jsonnet/microservices/compactor.libsonnet#L37

**Comment by annanay25** [comment]
<img width="345" alt="Screenshot 2021-03-17 at 12 55 29 PM" src="https://user-images.githubusercontent.com/10982987/111468325-6dd67400-874b-11eb-8ced-15ad3bfab956.png">
We are also seeing drops in the distributor metrics on a rollout, and relaxing the rollout by setting `maxUnavailable` to a smaller number (it is at 25% currently) together with waiting for a configurable time before exiting should help smoothen the graph (by allowing prometheus to scrape before it disappears)
