### ISSUE TITLE
Complete Observability Stack Realtime example 

### ISSUE THREAD

**Issue by mnadeem** [grafana/tempo#540]
**Is your feature request related to a problem? Please describe.**

Real World project demonstrating Complete Observability Stack utilizing Prometheus, Loki, Tempo ( OpenTelemetry Auto / manual Instrumentation), Grafana for NodeJs / Java applications involving microservices with DB interactions

**Describe the solution you'd like**
Spring Boot Java Applications : https://github.com/mnadeem/boot-opentelemetry-tempo

Node Js Applications : https://github.com/mnadeem/nodejs-opentelemetry-tempo

**Describe alternatives you've considered**

N/A

**Additional context**

With just  `docker-compose up`  things would work out of the box.

**Comment by joe-elliott** [comment]
These examples are excellent.  We currently have some similar guides here:

https://grafana.com/docs/tempo/latest/guides/instrumentation/

Can we add your examples to this page?

**Comment by mnadeem** [comment]
Sure @joe-elliott  it would help the community a lot. Kindly go ahead and add it to the page

Further the java version has support for both 0.15 and 0.16 ot (There is a minor difference in both)
![image](https://user-images.githubusercontent.com/476145/108576627-48209f80-7344-11eb-8938-b8387624822d.png)
