### ISSUE TITLE
Documentation on how to deploy without using containers

### ISSUE THREAD

**Issue by zlepper** [grafana/tempo#542]
**Is your feature request related to a problem? Please describe.**
We are currently investigating using Tempo for storing traces from our application. Currently we deploy our entire application (Consisting of several smaller services) on a single windows machine. This presents two problems:
1. There isn't a ready build of tempo and tempo-query for windows. This is easily solved by simply compiling Tempo ourselves, and that seems to work on windows without any problems. 
2. I cannot find any documentation on how to connect Tempo and Tempo-query without using the containers Grafana provides, without isn't an option considering that we are on windows servers. 

**Describe the solution you'd like**
I would like some documentation about how to configure and run Tempo-query without relying on the prebuild containers. 

**Describe alternatives you've considered**
Using Grafana cloud, however i need to be able to provide a proper comparison between Managed vs Unmanaged before we can take a decision.

**Comment by dgzlopes** [comment]
Hi @zlepper, thanks for opening the issue :)

Fully agree with you, there is no documentation on how to run Tempo without Docker and that should change. 

We have an open ticket for this: https://github.com/grafana/tempo/issues/358

However, we've plans to drop the tempo-query dependency and that will simplify **a lot** the non-docker local setup. See: https://github.com/grafana/tempo/issues/382

Meanwhile. I don't have a lot of experience with Windows nor with Tempo-Query but, from what I understand: the Tempo-query container bundles Jaeger Query UI + tempo-query binary and configures the Query UI to communicate with the binary by using the [gRPC plugin system](https://www.jaegertracing.io/docs/1.21/deployment/#query-service--ui). 

So, maybe, you can try to [run Jaeger Query UI](https://www.jaegertracing.io/docs/1.21/windows/#query-ui)... and once that's working, compile the tempo-query binary, set the right [env vars](https://github.com/grafana/tempo/blob/c9fe67601aff65d126367c04c7c68916343af760/cmd/tempo-query/Dockerfile#L3), and run the whole thing. 

Hopefully, someone can give you more insights into this!

**Comment by zlepper** [comment]
Hi @dgzlopes,

Thank you for the thorough response :)

We don't particular need the Jeager UI itself, we just need enough for us to be able to query things in Grafana, which is why i imagine we need Tempo-Query (until 382 is done). 

But it sounds like it might be easier to just run jeager's all-in-one deployment with badger as storage for now, rather than trying to fit all these components together :) 

But thank you for the answers, I'm eagerly awaiting first class Tempo support in Grafana :D

**Comment by dgzlopes** [comment]
Np, I'm here to help @zlepper  :)

Yup, probably the all-in-one deployment is easier!

I'll close this issue b/c these things are being tracked on #358 and #382. I hope we can close those two shortly :P

**Comment by dgzlopes** [comment]
Hi @zlepper! In case you're still interested, in Grafana v7.5.x, you can query Tempo directly. Yup, without tempo-querier.

[Here](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v7-5/#tempo-as-a-backend-data-source) are the Grafana release notes. Also, #617 will add docs about this.

Hope it's useful :)
