### ISSUE TITLE
Add capacity planning guides

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#543]
**Is your feature request related to a problem? Please describe.**
We have good SLO alerts.  These are alerts are great at telling a user when things are breaking, but we'd like additional alerts to be more proactive then reactive.  Let's build an alert using internal metrics that suggests when to scale ingesters.

**Describe the solution you'd like**
Spend some time determining a good measure of the amount of work that each ingester is doing and build an alert around it.  Perhaps total active traces held in memory?

**Update**
We're looking at creating/updating a [GET sizing calculator spreadsheet](https://docs.google.com/spreadsheets/d/1chxb1DciWQlViXXa8rdlQ4SOIzz2HDkqK2sPp1ewQRE/edit#gid=1423139469) for capacity planning. The current spreadsheet will need to be redone to account for Parquet any way. 

Customers are requesting this information. May need this for Tempo 2.0 (for ObsCon)

**Comment by annanay25** [comment]
Given an input on spans/sec + bytes/sec, we need capacity planning guidelines that can help with cluster sizing. 

Also it would be good to have a list of current metrics we can watch to determine this.

**Comment by knylander-grafana** [comment]
This could be part of the capacity calculator that we've had discussions about this. 
@annanay25 Would you be willing to update the description to match what our current work is?

**Comment by electron0zero** [comment]
leaving this note as paper trail for anyone who finds this issue, also see discussion in https://github.com/grafana/tempo/issues/1540 

we have added a [cluster sizing guide](https://grafana.com/docs/tempo/latest/setup/size/) in the tempo docs. Please use this to size your tempo cluster but please be aware that these are just guidelines and not hard rules, and it might change with new releases.
