### ISSUE TITLE
S3 Backend Store Authentication Failure

### ISSUE THREAD

**Issue by sherifkayad** [grafana/tempo#566]
**Describe the bug**
Currently we are are running Tempo in a Kubernetes Cluster (in AWS). We have created an S3 bucket and assigned a policy with the needed permissions to the EC2 worker nodes. The expectation is that Tempo is running smoothly. However we are getting the following error from Tempo at startup:
```bash
level=error ts=2021-03-03T14:27:40.32038732Z caller=main.go:92 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on MY_BUCKET: Access Denied"
```

The current IAM Policy attached to the nodes is:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::MY_BUCKET",
                "arn:aws:s3:::MY_BUCKET/*"
            ]
        }
    ]
}
```

Also here I wanted to post a snippet of my config (I am using Helm to install Tempo):
```yaml
storage:
    trace:
      backend: s3
      blocklist_poll: 5m
      s3:
        endpoint: s3.eu-central-1.amazonaws.com
        bucket: MY_BUCKET
      wal:
        path: /var/tempo/wal
      # Disable Memcached for now ..
      # cache: memcached
      # memcached:
      #   consistent_hash: true
      #   host: {{ include "tempo.fullname" . }}-memcached
      #   service: memcached-client
      #   timeout: 500ms
      block:
        encoding: zstd
```

**To Reproduce**
1. Start Tempo (SHA or version)

**Expected behavior**
Tempo works smoothly and the access to S3 is fine

**Environment:**
 - Infrastructure: Kubernetes on AWS (EKS)
 - Deployment tool: helm

**Additional Context**

**Comment by mdisibio** [comment]
Hi, this might be from copy and paste, but it looks like there could be a missing `:` here:
```
"arn:aws:s3::MY_BUCKET",
"arn:aws:s3:::MY_BUCKET/*"
```

**Comment by sherifkayad** [comment]
@mdisibio where is the missing `:` you mean?

**Comment by sherifkayad** [comment]
@mdisibio got ya .. no it was a copy paste error on my end. I double checked the policy now and it looks fine with the dots

**Comment by mdisibio** [comment]
Oh well, that would have been a nice easy fix.   Here are some ideas of what to check next:

* Is there an S3 bucket policy preventing access? (Different than the IAM policy)
* Is there another policy attached to the role that is unexpectedly denying access ?
* Can you try running tempo locally with the same permissions? That would rule out environmental issues with EKS, etc.
* Is there a good way to verify the pod is inheriting the worker node permissions as expected?   In the EKS there are also pod execution roles, and IRSA (IAM roles for service accounts).

**Comment by sherifkayad** [comment]
@mdisibio The first three points are either not the case or not relevant in my view. Running Tempo locally won't work because my assumption here is that the roles assigned to the worker nodes won't apply and hence we know that the auth would fail.

The fourth point is interesting though: ```Is there a good way to verify the pod is inheriting the worker node permissions as expected? In the EKS there are also pod execution roles, and IRSA (IAM roles for service accounts).```

How can I validate that? Do you have some tricks in mind? Maybe worth mentioning I have Loki already installed exactly with the same setup and roles on its dedicated bucket and it's working like a charm .. so how do you see this?

**Comment by mdisibio** [comment]
For running locally, you are correct it won't be able to use the EC2 worker role.  I meant to try attaching an identical policy to a user, then provide access/secret keys to tempo.  

Anything in CloudTrail?  Should be able to confirm the role is being inherited correctly, or in the case of failure, may provide some more information.

**Comment by sherifkayad** [comment]
@mdisibio with an IAM user and manually adding the AWS_ACCESS_KEY_ID and secret it works like a charm. I am still wondering why it can't work with the EC2 default policy though .. any ideas how I should proceed with debugging the problem?

**Comment by mdisibio** [comment]
Ok that's good to hear it works locally.  Unfortunately we do not have much experience using EKS.   Some more ideas:
* Look in CloudTrail for failing S3 requests
* Investigate switching from node roles to [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).   
* This may be difficult if the container is exiting, but could try `exec`ing to the pod and dumping information from the instance metadata endpoint `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/`.  I believe this will list the iam roles assigned to the node.
* Tempo has 2 parameters for compatibility in some scenarios:  `forcepathstyle` and `signature_v2`. Since it works locally, these are likely not needed, but might be worth double-checking if they are relevant to your bucket or region.
* The credential chain used by tempo places precedence on env vars or config yaml values over IAM inherited permissions (see [here](https://github.com/grafana/tempo/blob/master/tempodb/backend/s3/s3.go#L87) ).  Could double check that the pod does't accidentally have an env var that is overriding things.

**Comment by sherifkayad** [comment]
@mdisibio Finally my resolution was the following:
- Upgraded to chart version 0.8.5
- The following as config for s3:
```yaml
s3:
  endpoint: s3.eu-central-1.amazonaws.com
  bucket: MY_BUCKET
```

Closing this issue.
