### ISSUE TITLE
failed: failed to create memberlist: Failed to get final advertise address: no private IP address found, and explicit IP not provided

### ISSUE THREAD

**Issue by hellertang** [grafana/tempo#571]
deploy distribute tempo base on official helm charts : https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed, config could be the same.

**install**
cd helm-charts/charts/tempo-distributed
helm install coding-micro-tempo ./ -n micro-tempo

**error info**
failed: failed to create memberlist: Failed to get final advertise address: no private IP address found, and explicit IP not provided
![image](https://user-images.githubusercontent.com/10046299/110323788-0dab4800-8050-11eb-985e-6b1210dc2a6e.png)

is there any config error? i see the default config is memeber list.
Need help, please~

**Comment by annanay25** [comment]
Hi @hellertang - what platform are you deploying the helm chart on? It seems like its unable to retrieve a private IP for the container, are private IPs disabled in your cluster?

**Comment by joe-elliott** [comment]
There should be a headless k8s service named something like `tempo-gossip-ring` that the compactors, queriers, distributors and ingesters belong to.  Can you tell us what ips are present in this service?

Also, can you share the tempo configmap?

**Comment by hellertang** [comment]
> There should be a headless k8s service named something like `tempo-gossip-ring` that the compactors, queriers, distributors and ingesters belong to. Can you tell us what ips are present in this service?
> 
> Also, can you share the tempo configmap?

headless service? Sorry, I can't find headless service in charts, is there any errors in helm?
tempo-goosip-ring: https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/service-gossip-ring.yaml
**service status**
kubectl get service -n micro-tempo
![image](https://user-images.githubusercontent.com/10046299/110408064-f3a94e00-80bf-11eb-8b36-bc254dec8e66.png)
kubectl describe  service coding-micro-tempo-tempo-distributed-gossip-ring -n micro-tempo
![image](https://user-images.githubusercontent.com/10046299/110408177-20f5fc00-80c0-11eb-890a-99088384aa29.png)

**config is the same**
```
config: |
  auth_enabled: false
  compactor:
    compaction:
      block_retention: 48h
    ring:
      kvstore:
        store: memberlist
  distributor:
    receivers:
      {{- if  or (.Values.traces.jaeger.thriftCompact) (.Values.traces.jaeger.thriftBinary) (.Values.traces.jaeger.thriftHttp) (.Values.traces.jaeger.grpc) }}
      jaeger:
        protocols:
          {{- if .Values.traces.jaeger.thriftCompact }}
          thrift_compact:
            endpoint: 0.0.0.0:6831
          {{- end }}
          {{- if .Values.traces.jaeger.thriftBinary }}
          thrift_binary:
            endpoint: 0.0.0.0:6832
          {{- end }}
          {{- if .Values.traces.jaeger.thriftHttp }}
          thrift_http:
            endpoint: 0.0.0.0:14268
          {{- end }}
          {{- if .Values.traces.jaeger.grpc }}
          grpc:
            endpoint: 0.0.0.0:14250
          {{- end }}
      {{- end }}
      {{- if .Values.traces.zipkin}}
      zipkin:
        endpoint: 0.0.0.0:9411
      {{- end }}
      {{- if or (.Values.traces.otlp.http) (.Values.traces.otlp.grpc) }}
      otlp:
        protocols:
          {{- if .Values.traces.otlp.http }}
          http:
            endpoint: 0.0.0.0:55680
          {{- end }}
          {{- if .Values.traces.otlp.grpc }}
          grpc:
            endpoint: 0.0.0.0:55680
          {{- end }}
      {{- end }}
      {{- if .Values.traces.opencensus}}
      opencensus:
        endpoint: 0.0.0.0:55678
      {{- end }}
  querier:
    frontend_worker:
      frontend_address: {{ include "tempo.queryFrontendFullname" . }}:9095
  ingester:
    lifecycler:
      ring:
        replication_factor: 1
      tokens_file_path: /var/tempo/tokens.json
  memberlist:
    abort_if_cluster_join_fails: false
    join_members:
      - {{ include "tempo.fullname" . }}-gossip-ring
  overrides:
    per_tenant_override_config: /conf/overrides.yaml
  server:
    http_listen_port: 3100
  storage:
    trace:
      backend: local
      blocklist_poll: 5m
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
      cache: memcached
      memcached:
        consistent_hash: true
        host: {{ include "tempo.fullname" . }}-memcached
        service: memcached-client
        timeout: 500ms

```

**Comment by hellertang** [comment]
> Hi @hellertang - what platform are you deploying the helm chart on? It seems like its unable to retrieve a private IP for the container, are private IPs disabled in your cluster?

i deploy on  TKE（Tencent Kubernetes Engine）,  cluster could be able to retrieve a private IP for the container~

**Comment by hellertang** [comment]
Now, I change the config use etcd to replace memberlist, like loki config。
```
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: etcd
          prefix: tempo-ingester/
          etcd:
            endpoints:
              - xxxxxxx:2379
```
every pod could be ready now,  is Tempo support consul ?

**Comment by joe-elliott** [comment]
"Headless" means that the service does not have a virtual ip address and instead returns a list of all the ips that belong to it.  This is what our gossip-ring service looks like:
```
gossip-ring                ClusterIP   None            <none>        7946/TCP                                363d
```
Are you using the helm chart to deploy?  This may be a bug with the helm chart.

> is Tempo support consul ?
Yes Tempo supports consul and etcd to maintain the ring.  The config would be the same as Cortex or Loki.

**Comment by hellertang** [comment]
> Are you using the helm chart to deploy? This may be a bug with the helm chart.
yes,  i use  [helm chart ]( https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed) to deploy。

> Yes Tempo supports consul, etcd or memberlist to maintain the ring. The config would be the same as Cortex or Loki.
thanks, it may be written in online documents:)~

**Comment by nielstenboom** [comment]
Also landed here having this issue, wasn't completely clear what to do to solve it at first, so this is what I did to resolve this issue:

Install `etcd` helm chart in the same namespace without rbac enabled.
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install tempo-etcd bitnami/etcd --version 6.8.2 -n yournamespace --set auth.rbac.enabled=false
```
Change all the `ring.kvstore` entries in the tempo chart values file from:
```yaml
kvstore:
  store: memberlist
```
to
```yaml
kvstore:
  store: etcd
  prefix: tempo-ingester/
  etcd:
    endpoints:
      - tempo-etcd:2379 # the etcd service you just deployed with helm
```
Redeploy the chart and then it should work 👍
