### ISSUE TITLE
error querying store in Querier.FindTraceByID: queue doesn't have room for 998 jobs

### ISSUE THREAD

**Issue by hellertang** [grafana/tempo#582]
Sorry, bother again. I deploy distribute-tempo and use S3 for storage, but one day later, it encounter fatal errors. 

#### 1、Grafana error 
![image](https://user-images.githubusercontent.com/10046299/110596842-c68d9600-81ba-11eb-91f4-d696cd4cd45e.png)
#### 2、Tempo-Query error
![image](https://user-images.githubusercontent.com/10046299/110597887-16b92800-81bc-11eb-92c9-87e369d10667.png)
#### 3、Query-fronted error
![image](https://user-images.githubusercontent.com/10046299/110598295-8c24f880-81bc-11eb-8ba3-ee76b10f524f.png)
#### 4、Querier error
![image](https://user-images.githubusercontent.com/10046299/110606529-3acd3700-81c5-11eb-8091-78d635ee6cad.png)
#### 5、Comapctor error
![image](https://user-images.githubusercontent.com/10046299/110606776-7cf67880-81c5-11eb-90cd-66ec7d3d099c.png)

### Config
deploy by [helm charts](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed)
```
config: |
  auth_enabled: false
  compactor:
    compaction:
      block_retention: 48h
    ring:
      kvstore:
        store: etcd
        prefix: tempo-compactor/
        etcd:
          endpoints:
            - 9.139.250.5:2379
  distributor:
    receivers:
      {{- if  or (.Values.traces.jaeger.thriftCompact) (.Values.traces.jaeger.thriftBinary) (.Values.traces.jaeger.thriftHttp) (.Values.traces.jaeger.grpc) }}
      jaeger:
        protocols:
          {{- if .Values.traces.jaeger.thriftCompact }}
          thrift_compact:
            endpoint: 0.0.0.0:6831
          {{- end }}
          {{- if .Values.traces.jaeger.thriftBinary }}
          thrift_binary:
            endpoint: 0.0.0.0:6832
          {{- end }}
          {{- if .Values.traces.jaeger.thriftHttp }}
          thrift_http:
            endpoint: 0.0.0.0:14268
          {{- end }}
          {{- if .Values.traces.jaeger.grpc }}
          grpc:
            endpoint: 0.0.0.0:14250
          {{- end }}
      {{- end }}
      {{- if .Values.traces.zipkin}}
      zipkin:
        endpoint: 0.0.0.0:9411
      {{- end }}
      {{- if or (.Values.traces.otlp.http) (.Values.traces.otlp.grpc) }}
      otlp:
        protocols:
          {{- if .Values.traces.otlp.http }}
          http:
            endpoint: 0.0.0.0:55680
          {{- end }}
          {{- if .Values.traces.otlp.grpc }}
          grpc:
            endpoint: 0.0.0.0:55680
          {{- end }}
      {{- end }}
      {{- if .Values.traces.opencensus}}
      opencensus:
        endpoint: 0.0.0.0:55678
      {{- end }}
  querier:
    frontend_worker:
      frontend_address: {{ include "tempo.queryFrontendFullname" . }}:9095
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: etcd
          prefix: tempo-ingester/
          etcd:
            endpoints:
              - 9.139.250.5:2379
        replication_factor: 1
      tokens_file_path: /var/tempo/tokens.json
  memberlist:
    abort_if_cluster_join_fails: false
    join_members:
      - {{ include "tempo.fullname" . }}-gossip-ring
  overrides:
    per_tenant_override_config: /conf/overrides.yaml
  server:
    http_listen_port: 3100
  storage:
    trace:
      backend: s3
      blocklist_poll: 5m
      s3:
        bucket: coding-tempo-staging-1251316161
        endpoint: cos.ap-nanjing.myqcloud.com
        region: ap-nanjing
        access_key: xxxx
        secret_key: xxxxx
        insecure: false
      wal:
        path: /var/tempo/wal
      cache: memcached
      memcached:
        consistent_hash: true
        host: {{ include "tempo.fullname" . }}-memcached
        service: memcached-client
        timeout: 500ms
```

**Comment by joe-elliott** [comment]
The querier is attempting to access more blocks then your queue length.  It creates one job for every block it attempts to scan.

Options:
1) Increase compactors and review your blocklist length.
2) Increase your queue length in the queriers:
```
storage:
    trace:
        pool:
            queue_depth: 4000
```
3) Increase query shards.  This will make each querier try to do less work.
```
query_frontend:
    query_shards: 20
```

**Comment by hellertang** [comment]
Thanks, everything could be ok under your help~
But queier also exist some errors , is there any other config bugs? 
### Error infos ###
![image](https://user-images.githubusercontent.com/10046299/110730726-ede86f80-825b-11eb-8a38-7aac4563fa0f.png)

**Comment by joe-elliott** [comment]
it seems like it can't connect to the frontend? @annanay25 is this message "normal"?

@hellertang to be clear are you able to successfully execute queries despite that error message?

**Comment by annanay25** [comment]
Oh we have a troubleshooting page for exactly this -  https://grafana.com/docs/tempo/latest/troubleshooting/too-many-jobs-in-queue/

We should add the query shards solution to this list, nice one @joe-elliott.

About those error messages in the querier, yeah they're "normal" and I suspect they prop up only on startup or when the pods are restarted, but I haven't dug into it. Is the querier working regardless?

**Comment by mdisibio** [comment]
The "transport is closing" message is normal and occurs when there has not been a query within some time, the frontend times out the connection to the querier (but it is reestablished).  #493

**Comment by annanay25** [comment]
Nice, thanks @mdisibio. 

I'm going to close this one, but please feel free to reopen if you're still having trouble.
