### ISSUE TITLE
Cache the first N cache index page requests

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#587]
**Is your feature request related to a problem? Please describe.**
#577 removed indexes from the caching.  Overall this is a good thing as a large percentage of our indexes didn't fit into our memcached instance and it generated a lot of errors.

Let's reenable index caching.

**Describe the solution you'd like**
With #577 we introduced a binary search over a paged index.  This means that the first 2 or 3 levels of the search are going to be "hot" in that the same pages are repeatedly accessed while resolving the search.  Let's cache the first few index requests on every search.

My gut says this configurable value should default to 2.

**Comment by annanay25** [comment]
6000 * 2 * 1/4MB = 3GB. Let's do this!
