### ISSUE TITLE
Improve Ingester Record Insertion

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#591]
**Is your feature request related to a problem? Please describe.**
Currently when adding new records on insertion the ingester is having to insert them into a slice:

https://github.com/grafana/tempo/blob/07121344c8b3ae7aecb95e50c531710d548ed862/tempodb/encoding/appender.go#L35

This is expensive b/c it requires copying the entire slice after the insertion point forward.  It may also requires expensive allocations on the `append` line to extend the array underlying the slice.

Let's find a better way to insert records.

**Comment by joe-elliott** [comment]
Perhaps we can use a skip list: https://en.wikipedia.org/wiki/Skip_list

**Comment by annanay25** [comment]
IIUC, the above library allows for key overwrite - https://github.com/dgraph-io/badger/blob/master/skl/skl.go#L287

Need to be careful with that since we can have multiple records for the same traceID

**Comment by joe-elliott** [comment]
Another random implementation. Agree that our need to support multiple traceIDs is going to be a challenge here

https://github.com/huandu/skiplist

**Comment by joe-elliott** [comment]
After some thought, we could frankly just use something like a `map[string][]Record` to hold a map of trace ids -> records.
