### ISSUE TITLE
The lastest docker image of tempo-query arm64 could not run on system arm64

### ISSUE THREAD

**Issue by 929541303** [grafana/tempo#594]
The lastest docker image of tempo-query arm64 could not run on system arm64. when we use the command ，it could not run. 

[run command]
docker run --rm -p 16686:16686 -v $(pwd)/tempo-query.yaml:/etc/tempo-query.yaml \
    --network docker-tempo \
    grafana/tempo-query:arm64 \
    --grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml

[error info]
standard_init_linux.go:211: exec user process caused "exec format error"

![image](https://user-images.githubusercontent.com/73211930/111286728-75c7e280-867d-11eb-8941-b32117b64547.png)

standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by joe-elliott** [comment]
Reviewing the CI instructions the binary should be built with `GOARCH=arm64`. Can you run other go binaries built this way?

`GOOS=linux GOARCH=arm64 go run ...` ?

What is the output of `uname -m` on your system?

**Comment by 929541303** [comment]
`uname -m` output is `aarch64`. 
![image](https://user-images.githubusercontent.com/73211930/111313642-8d15c880-869b-11eb-9bf9-6e71bef6006c.png)

`Can you run other go binaries built this way? GOOS=linux GOARCH=arm64 go run ... ?` how to do this.

**Comment by joe-elliott** [comment]
just make a simple main.go:

```
import "fmt"
func main(){
  fmt.Println("hello world!")
}
```

and then try `GOARCH=amd64 go run ./main.go`

Oh, but now that I'm looking closer I wonder if this is related to tempo-query being based on jaeger-query.  Does the standard tempo amd64 image work?

**Comment by 929541303** [comment]
Tempo run by docker work well, i don't find any error logs. But i don't know when i query trace logs, it also work well. i will try it tomorrow.

**Comment by joe-elliott** [comment]
If running the docker `tempo` image works but running the docker `tempo-query` image does not work then it's probably b/c we are building on top of a jaeger-query image.

**Comment by 929541303** [comment]
I try `GOARCH=amd64 go run ./main.go`, it works well.
I think the tempo-query docker run error, the reason is not caused by the system arm64. I think your ` buildding tempo-query image` have a bug in somewhere. please check it for me. 
probably it hase caused by ` jaeger-query image`.
![image](https://user-images.githubusercontent.com/73211930/111402614-75275e80-8706-11eb-9454-4abda9da46fa.png)

**Comment by joe-elliott** [comment]
So unfortunately jaeger-query does not currently support arm64. We would have to rebuild the entire jaeger-query image to get this to work.

![image](https://user-images.githubusercontent.com/2272392/111468514-03e2ae00-86fc-11eb-84b3-170b9c390d38.png)

However, fortunately, the next version of Grafana will be able to query Tempo directly and will no longer require jaeger-query.  I think this will be the best path forward.

**Comment by 929541303** [comment]
OK, thank you for your patience. I'd like to know when your next version will be released.

**Comment by 929541303** [comment]
When will you release the next version？I want to use it in a hurry!

**Comment by annanay25** [comment]
If you are okay using a pre-release image of Grafana in your environment it should be available already. @zoltanbedi from the Grafana team can help that.

**Comment by zoltanbedi** [comment]
@929541303 Grafana 7.5.0-beta.2 will have this. It will be released on Friday. If you can't wait you can always use our nightly builds https://grafana.com/grafana/download/7.5.0-14627pre?pg=get&plcmt=selfmanaged-box1-cta1

**Comment by 929541303** [comment]
@zoltanbedi  I deployed the version of grafana you said, and also deployed tempo. but I could not query trance from Tempo . 
 How can I configure this file to connect to tempo. 

deploy command is :
`
docker run --rm -itd   --name tempo -p 9411:9411 -p 3101:3100  -v $(pwd)/tempo-local.yaml:/etc/tempo-local.yaml grafana/tempo:latest -config.file /etc/tempo-local.yaml

docker run -u root -itd --name grafana  -p 3000:3000 -v /home/loki/grafana-data/etc:/etc/grafana/ -v /home/loki/grafana-data/grafana:/var/lib/grafana  grafana/grafana:7.5.0-beta2
`
![image](https://user-images.githubusercontent.com/73211930/112473436-53367780-8da9-11eb-8e8e-9c2e1a21795a.png)

![image](https://user-images.githubusercontent.com/73211930/112473361-3b5ef380-8da9-11eb-8818-9c37d6c090b2.png)

![image](https://user-images.githubusercontent.com/73211930/112473396-487be280-8da9-11eb-9874-b1d3c68b5a4a.png)

**Comment by zoltanbedi** [comment]
If you get back 400 then you are connected to tempo from Grafana. This is Tempo not finding your trace.

**Comment by joe-elliott** [comment]
The Tempo query path does not return "404 page not found" in the body. Try using this as your datasource url:

`http://192.168.40.197:3100/tempo`

**Comment by annanay25** [comment]
@929541303 - Please use this guide https://grafana.com/docs/tempo/latest/configuration/querying/ to upgrade to Grafana 7.5, which no longer requires Tempo-Query!

Going to close this as resolve. Feel free to reopen if you continue to see issues.
