### ISSUE TITLE
Document Fargate requirement

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#622]
**Is your feature request related to a problem? Please describe.**
We need to document a configuration snafu required in AWS Fargate.

Per this conversation the interface `eth1` needs to  be provided for Tempo to automatically detect and use the correct IP.
https://community.grafana.com/t/distributor-ingester-issue-consuming-traces/45209/5

**Comment by mdisibio** [comment]
Adding another note related to Fargate deployments - Tempo ingesters currently expect persistent storage, and when running in Fargate this is not available unless using EFS.   Unless the the /shutdown endpoint on the ingester is called prior to deleting the ingester, there will be data loss as anything not flushed off the ingester will be lost.
