### ISSUE TITLE
Create a way for a Grafana datasource to be able to confirm it is correctly configured for Tempo

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#624]
**Is your feature request related to a problem? Please describe.**
We need a way for Grafana to query Tempo when setting up a datasource so that it knows for sure everything is configured correctly.  Currently it queries `/api/traces/` and if it receives a 404 then it assumes things are correct.  This, however, does not catch situations where you point the datasource at a non-Tempo http service or just the wrong path in Tempo

**Describe the solution you'd like**
Add a way for Grafana to query Tempo and confirm that the datasource is setup correctly.

Possible ideas:
- add an echo endpoint that always 200s: `/api/echo`
- add a special trace id that always 200s `/api/traces/0` or `/api/traces/test` or something.
- key off the 404 body that confirms it did indeed hit the `/api/traces` endpoint.

**Comment by ad-m** [comment]
I have notice that current version of Tempo:

* reply with content `trace not found in Tempo`  and status code `404` when traceId is not found
* reply with content `404 page not found` and status code `404` when path is invalid

I believe this information can be used to even partially configuration validation.

**Comment by kvrhdn** [comment]
I've made a PR to fix this in Grafana: https://github.com/grafana/grafana/pull/34762

**Comment by kvrhdn** [comment]
We don't want to guarantee the body of a 404 stays consistent, reopening to add a separate endpoint for testing purposes.

**Comment by kvrhdn** [comment]
After team discussion we decided to add a `/api/echo` endpoint.

**Comment by kvrhdn** [comment]
fyi, I've opened a new issue in Grafana to use this endpoint in the future: https://github.com/grafana/grafana/issues/34919
