### ISSUE TITLE
List and reorganise Tempo HTTP API

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#632]
Over time we have added a lot of endpoints to Tempo's HTTP API, including `/metrics` `/shutdown` `/config` `/memberlist` etc. While a few of these provide information that is useful in debugging and monitoring, there are others that are used to perform administrative tasks, for instance the shutdown one, and should probably not be defined at root (`/`). As we start working towards a stable release, we should attempt to
- add an "admin" endpoint that lists all the endpoints exposed by the target module
- decide on an API nomenclature and move the endpoints to locations that make sense in terms of functionality

**Comment by tharun208** [comment]
@annanay25 I like to work on this

**Comment by annanay25** [comment]
Its yours! @tharun208

**Comment by JosephWoodward** [comment]
@tharun208 Are you working on this? Otherwise I'm happy to pick it up.

**Comment by tharun208** [comment]
@JosephWoodward yes, I am working on this

**Comment by JosephWoodward** [comment]
@tharun208 Okay, no problem 😁

**Comment by JosephWoodward** [comment]
@tharun208 How have you been getting on with this? Need a hand?
