### ISSUE TITLE
Change OTLP gRPC port number

### ISSUE THREAD

**Issue by dgzlopes** [grafana/tempo#637]
The port that we're using for OTLP gRPC (`55680`) has been deprecated. We should use `4317` instead.

The old port still works, but, there are plans to completely remove it in the future (at least on the OpenTelemetry Collector). 

Right now, `4317` is the only one [mentioned](https://github.com/open-telemetry/opentelemetry-specification/blob/6701b5084af3cda351031a9a062e411f44616bcf/specification/protocol/otlp.md#otlpgrpc-default-port) on the specification.

Related ([Collector PR 2104](https://github.com/open-telemetry/opentelemetry-collector/pull/2104)):
> Users who use the default Collector config can continue sending data to the legacy ports and have a graceful period to update their senders to start sending to the new ports.

**Comment by mapno** [comment]
We fixes this a long ago https://github.com/grafana/tempo/pull/1142
