### ISSUE TITLE
Non-multi-tenant mode.

### ISSUE THREAD

**Issue by bwplotka** [grafana/tempo#639]
👋🏽 Is there a mode without multi-tenancy as designed by tempo? I have simple demo app which literally uses OTLP gRPC on clients and Tempo receiver as:

```
 server:
      http_listen_port: 9090
    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m0s
      max_block_bytes: 1000000
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:9091
    compactor:
      compaction:
        compaction_window: 1h0m0s
        max_block_bytes: 1000000
        block_retention: 1h0m0s
        compacted_block_retention: 10m0s
    storage:
      trace:
        pool:
          max_workers: 100
          queue_depth: 10000
        wal:
          path: /data/wal
          completedfilepath: ""
        block:
          index_downsample_bytes: 1048576
          index_page_size_bytes: 256000
          bloom_filter_false_positive: 0.05
          encoding: zstd
        backend: local
        local:
          path: /data/blocks
```

However, whenever my client (opentelemetry-go) pushes traces I got:

```
2021/04/10 22:50:01 rpc error: code = Unknown desc = no org id
2021/04/10 22:50:06 exporter disconnected
2021/04/10 22:50:11 exporter disconnected
2021/04/10 22:50:16 rpc error: code = Unknown desc = no org id
2021/04/10 22:50:21 exporter disconnected
2021/04/10 22:50:26 exporter disconnected
```

And on tempo:

```
imeout" ring=ingester
level=info ts=2021-04-10T22:46:10.051244922Z caller=app.go:224 msg="Tempo started"
level=info ts=2021-04-10T22:47:10.050428573Z caller=compactor.go:99 msg="enabling compaction"
level=info ts=2021-04-10T22:47:10.050569602Z caller=tempodb.go:370 msg="compaction and retention enabled."
level=error ts=2021-04-10T22:47:10.059266955Z caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-04-10T22:47:10.059517872Z caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-04-10T22:47:10.059684374Z caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-04-10T22:47:10.059846183Z caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-04-10T22:47:10.059852709Z caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-04-10T22:48:19.002653074Z caller=log.go:27 msg="failed to extract org id" err="no org id"
level=error ts=2021-04-10T22:48:24.003988084Z caller=log.go:27 msg="failed to extract org id" err="no org id"
level=error ts=2021-04-10T22:48:34.003977664Z caller=log.go:27 msg="failed to extract org id" err="no org id"
level=error ts=2021-04-10T22:48:44.005104593Z caller=log.go:27 msg="failed to extract org id" err="no org id"
```

I think this is the problematic spot https://github.com/grafana/tempo/blob/master/modules/distributor/distributor.go#L204

Any ideas if there is a blocker to enable non tenancy mode on Tempo, or I have to somehow inject it?

**Comment by bwplotka** [comment]
It's not a big deal TBH (: I just injected in yolo in my client code.

Probably might surprise users when trying it out. Also not sure if this was intended. Feel free to close if it is.

**Comment by dgzlopes** [comment]
Hi @bwplotka! Thanks for opening an issue :) 

You can use the `auth_enabled` config parameter.

We've some docs about this here: https://grafana.com/docs/tempo/latest/configuration/#authenticationserver

**Comment by dgzlopes** [comment]
Personally, I think that having this disabled by default is... well, a better default :smile:

**Comment by bwplotka** [comment]
Wooo, thanks!

I actually have it disabled in my Go code: 

![image](https://user-images.githubusercontent.com/6950331/114298362-e4963100-9aad-11eb-844d-bcdbccb0f7aa.png)


But sneakly enough it had `omitempty` field:

![image](https://user-images.githubusercontent.com/6950331/114298355-d5af7e80-9aad-11eb-8bc0-6eadee123612.png)

So it was false was rendered as an empty field.... and it was parsed on Tempo as true.

Default `false` would make sense, but also yolo thoughts:

1. I don't know how auth is related to X-Orgs-ID requirement - since I don't setup any other authorization/authentication provider etc 🤗 
2. If we want default to be `auth_enabled` it would be better to have `auth_disabled` field =D not only for my https://github.com/bwplotka/mimic parsing, but overall for understanding what's the default? 🤔 

Anyway, thanks for finding my bug!

**Comment by dgzlopes** [comment]
Happy to help! :)

1. From what I know, there is no relation between this config param and authorization/authentication providers. This is just for enabling "authentication via" the X-Scope-OrgID header. Grafana Loki docs have a [more lengthy](https://grafana.com/docs/loki/latest/configuration/#supported-contents-and-default-values-of-lokiyaml) explanation about this than our docs.
2. I like that rename! I think that your proposal is easier to understand and reason about. But Cortex, Loki, and Tempo share this param... So idk how feasible is to change this only on Tempo or if it's going to confuse some users that use all the three tools.

**Comment by joe-elliott** [comment]
Yes, `auth_enabled` is a holdover from Cortex/Loki. It is poorly named and has nothing to do with authentication/authorization.

I think the obvious thing to do is just disable it by default since 99% of open source users don't care about multitenant.
