### ISSUE TITLE
Write uncompressed size to page headers

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#652]
**Describe the solution you'd like**
Currently when reading a page from compressed to uncompressed we use `io.ReadAll`:

https://github.com/grafana/tempo/blob/86f250985ac5e86cdad324fb5283bf4ed4d549cf/tempodb/encoding/v1/data_reader.go#L56

This is extremely memory inefficient and will shortly be replaced with `io.ReadAllWithEstimate`.  However, in the case of compressed data this still results in unnecessary allocations.  If we wrote the uncompressed size to the data page header we could allocate a buffer of the appropriate size and only allocate once.

**Comment by wperron** [comment]
Quickly looking at `data_reader.go` seems like `ioutil.ReadAll` was replaced with `tempo_io.ReadAllWithBuffer` -- is this issue still valid then?

**Comment by wperron** [comment]
No idea if this is a good first issue but what the heck, I'll give it a shot :shrug:

**Comment by joe-elliott** [comment]
> No idea if this is a good first issue but what the heck, I'll give it a shot

I would say this is not a good first issue as it's buried in the blocks code. I don't, however, mind helping you through it if you want to try to tackle it. You will find that I favored code reuse in the v0, v1, and v2 blocks where I probably should have just copied and pasted for clarity/ease of maintenance.

The dataheader here needs the uncompressed size added:
https://github.com/grafana/tempo/blob/main/tempodb/encoding/v2/page_header.go#L25

When the page is cut and written we will need to find a way to get the uncompressed size and add it:
https://github.com/grafana/tempo/blob/main/tempodb/encoding/v2/data_writer.go#L40

This might not be too many lines of code, but it will probably have to be carefully written. Feel free to ask questions!
