### ISSUE TITLE
License confusion in cmd/tempo-query/tempo 

### ISSUE THREAD

**Issue by roidelapluie** [grafana/tempo#663]
Hello,

cmd/tempo-query/tempo depends on github.com/grafana/tempo/pkg/util

The util/ package is not listed as Apache 2.

I think pkg/util was probably forgotten in the relicensing?

**Comment by joe-elliott** [comment]
Thanks @roidelapluie for taking the time to review Tempo and file this issue. We appreciate the support from the community while we work through the details of the licensing change.
