### ISSUE TITLE
tempo --version is not returning much information

### ISSUE THREAD

**Issue by attachmentgenie** [grafana/tempo#669]
**Describe the bug**
running tempo --version doesnt return much useful information (currently only the used go version) this seems to have been the case for the last couple of releases

**To Reproduce**
`tempo_0.7.0_linux_amd64 ❯ ./tempo --version
tempo, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.15.11
  platform:         linux/amd64
tempo_0.7.0_linux_amd64 ❯ ../tempo_0.6.0_linux_amd64 
tempo_0.6.0_linux_amd64 ❯ ./tempo --version         
tempo, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.15.8
  platform:         linux/amd64
tempo_0.6.0_linux_amd64 ❯ ../tempo_0.5.0_linux_amd64 
tempo_0.5.0_linux_amd64 ❯ ./tempo --version         
tempo, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.14.13
`

**Expected behavior**
output more information, at least all the defined KV pairs

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Comment by mdisibio** [comment]
To confirm, the issue is that the info is missing when running the binaries from the release pages ?   The docker images seem ok at least.

```
$ docker run -it grafana/tempo:0.7.0 -version
tempo, version 0.7.0 (branch: HEAD, revision: 83021a11e)
  build user:       
  build date:       
  go version:       go1.16
  platform:         linux/amd64

$ docker run -it grafana/tempo:0.6.0 -version
tempo, version 0.6.0 (branch: HEAD, revision: a8bf22014)
  build user:       
  build date:       
  go version:       go1.15.3
  platform:         linux/amd64
```

**Comment by attachmentgenie** [comment]
indeed the downloadable artifacts
