### ISSUE TITLE
Pushing Spans with HTTP is not working as documented

### ISSUE THREAD

**Issue by attachmentgenie** [grafana/tempo#670]
**Describe the bug**
while following the new instructions for the demo mentioned doesnt return the results expected when calling the new api url. However the old url does still return results

**To Reproduce**
tempo 0.7.0

`
[root@traces ~]# curl http://localhost:3100/tempo/api/traces/0123456789abcdef
404 page not found
[root@traces ~]# curl http://localhost:3100/api/traces/0123456789abcdef
{"batches":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"shell script"}}]},"instrumentationLibrarySpans":[{"instrumentationLibrary":{},"spans":[{"traceId":"AAAAAAAAAAABI0VniavN7w==","spanId":"AAAAAAAAEjQ=","name":"span from bash!","startTimeUnixNano":"1608239395286533000","endTimeUnixNano":"1608239395386533000","attributes":[{"key":"http.path","value":{"stringValue":"/api"}},{"key":"http.method","value":{"stringValue":"GET"}}],"status":{}}]}]}]}[root@traces ~]# 
`

**Comment by joe-elliott** [comment]
Ah, Thank you for the issue. We recently made that prefix configurable and missed this place in the docs. I will fix shortly.
