### ISSUE TITLE
Tempo does not recover from credential expiry

### ISSUE THREAD

**Issue by the-maldridge** [grafana/tempo#686]
**Is your feature request related to a problem? Please describe.**
When using an external credentials provider for S3 storage (or I suspect others with a shared credentials file), Tempo notices that the credentials have become invalid due to the errors being returned from the library, so it should have all the information needed to reload them, and reloading them is an easy fallback thing to see if it fixes the problem.

**Describe the solution you'd like**
I want either tempo to reload its credentials on error or to provide signal handler functionality to reload them at the command of an external system.

**Describe alternatives you've considered**
I've considered not using Tempo and finding some other software that more gracefully handles credential rotation, but the field is pretty thin right now.  I've also considered just restarting tempo on a timer, but this seems like it may have boundary conditions that are poorly handled if things get restarted too close together.

**Additional context**
Reloading credentials used to be a standard feature across many software systems.  While I recognize that everything is "cloud native" now, it still seems rather limiting to lose the features that make tools suitable for actually running the cloud.

**Comment by joe-elliott** [comment]
So, we rely on external clients such as [minio's s3 client](https://github.com/minio/minio-go) to handle authentication and solving this generally would add a fair amount of complexity to the system.

I suppose we'd have to rebuild the client (s3, azure, gcs) and synchronously swap old for new in the event of one of the conditions you described. Detecting failed auth may also be problematic, but perhaps we'd be able to do something with a custom HTTP transport in each client and watch for the appropriate error codes.

We support quite a few authentication options using the minio client:

https://github.com/grafana/tempo/blob/main/tempodb/backend/s3/s3.go#L76

Can you share which one you are using? The most direct path to solving your issue may be to add support for dynamic reload for the credential type to minio directly.

**Comment by the-maldridge** [comment]
I am using the AWS Shared Credentials file provider.  An alternative and significantly simpler option than doing this as a fallback would be to have a signal handler to reload clients.  This would solve the problem of wanting to reload the authentication data or otherwise update the client state without needing to rely on hacks that introspect the client library state.

**Comment by joe-elliott** [comment]
So I think the most straightforward path to what you need is to submit an issue/PR to the minio client to support reloading the auth file on a regular interval.

If there is enough interest from the community we can reprioritize this and look to add it directly into Tempo.

**Comment by the-maldridge** [comment]
Minio considers this out of scope for the SDK and as such this is back to being considered a defect in tempo: https://github.com/minio/minio-go/issues/1487.

**Comment by harshavardhana** [comment]
> So I think the most straightforward path to get what you need is to submit an issue/PR to the minio client to support reloading the auth file on a regular interval.

@joe-elliott SDKs shouldn't read resources on a continuous basis - it is the application logic.  What MinIO SDK provides here is a simple way to implement a credential reading logic. 

There seems to be a PR submitted today which might do what you want https://github.com/minio/minio-go/pull/1486 @the-maldridge
