### ISSUE TITLE
Docker-compose examples cleanup

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#731]
The docker-compose examples were recently split out to have individual readmes which helps with readability, but all of the files are just jammed in the same folder: ./example/docker-compose.

Reorganize the examples into individual subfolders for clarity. For instance move:
```
example/docker-compose/docker-compose.agent.yaml
example/docker-compose/etc/agent.yaml
example/docker-compose/readme.agent.md
```
to
```
example/docker-compose/agent/docker-compose.yaml
example/docker-compose/agent/agent.yaml
example/docker-compose/agent/readme.md
```

Note that there are shared config files and relative paths that will need to be cleaned up.

**Comment by kvrhdn** [comment]
I can pick this up :)

**Comment by joe-elliott** [comment]
@kvrhdn Be careful when doing this. I noticed a fair number of these files are linked directly from our docs.

**Comment by kvrhdn** [comment]
Oh, good call! I can find the links by searching the docs folder for `example/docker-compose`. I'll make sure to update them as well.
