### ISSUE TITLE
Add more details for tracesToLogs

### ISSUE THREAD

**Issue by sergeyshaykhullin** [grafana/tempo#735]
**Is your feature request related to a problem? Please describe.**

I am trying to do a next step with observability - link all datasources together with `tracesToLogs`, `logsToTraces(derivedFields)` and `exemplarTraceIdDestinations`

I am .NET user and tried to find some more info here: https://grafana.com/blog/2021/02/11/instrumenting-a-.net-web-api-using-opentelemetry-tempo-and-grafana-cloud/

The problem is to link Tempo traces with Loki logs:
- In example above spans has no `app` tag to use in LogQL. It can be fixed inside app, but maybe there is a better solution?
- Constructed LogQL query is not filtering by span, only by specified in `tracesToLogs.tags` tags

**Describe the solution you'd like**
Tempo `Logs for this span` is filtering by span id:

Now: `{ app="my-app" }`
Desired: `{ app="my-app" }` |~ "span id"

**Describe alternatives you've considered**

**Additional context**
Query without specified tags
![image](https://user-images.githubusercontent.com/46970457/120709644-c48b5880-c4c5-11eb-8ca1-0844a8a136de.png)

Query with custom app tag without span filtering
![image](https://user-images.githubusercontent.com/46970457/120709786-f7cde780-c4c5-11eb-97de-27cbf94958e5.png)

**Comment by joe-elliott** [comment]
This is a cool suggestion. We specifically did not include `|= "span id"` b/c we felt like most people would not have the span ids in their logs and we wanted this to just find all process logs at the time the span occurred.

I do feel like this could be a useful option for those who are logging the span or trace id in their logs. However, this feature requests belongs in the Grafana repo:  https://github.com/grafana/grafana.

If you file the request there and link it back here I can raise it with our internal team who works on that UI. Thanks for interest in the project!

**Comment by sergeyshaykhullin** [comment]
Thanks, i will create and link a new issue in grafana repo

Hmm, anyone with enabled logsToTraces(loki derivedFields) has already logging their traceIDs

**Comment by sergeyshaykhullin** [comment]
Hmm, yes, it is valid

**Comment by dbluxo** [comment]
@sergeyshaykhullin  I like your suggestion and gave a thumbs up as I find it useful as well.

A question about current behavior:

> Now: { app="my-app" }

How does the current LogQL query come up? I always get an empty expression `{}`, how do I set the app tag?

**Comment by sergeyshaykhullin** [comment]
Hmm, i think you need labels in logs first. Then add label names to tracesToLogs

**Comment by dbluxo** [comment]
> Then add label names to tracesToLogs

Where do I configure this? Is this documented somewhere?

**Comment by kvrhdn** [comment]
This is documented here: https://grafana.com/docs/grafana/latest/datasources/tempo/#trace-to-logs

The tags you specify will be used to create the Loki query.

**Comment by dbluxo** [comment]
Ah I see, thanks! Not only the logs must contain the labels, but the traces must have the appropriate tags, and then the LogQL query *matches* the configured tags with the log labels :bulb:

**Comment by r0fls** [comment]
Hi, I'm sorry to try and hijack this thread with my issue, but can anyone provide more detail on getting this to work? 🤔  I added level tags to my spans (e.g. `level: info`) that match the log lines, and the Grafana UI link "Logs for this span" now brings up log lines, but they are all over the place, and I just want the ones related to that trace. Is there anyway to use the traceId from the log line as a filter in the UI query as well?

**Comment by kvrhdn** [comment]
Grafana now has a toggle to filter on trace or span ID. This was added in https://github.com/grafana/grafana/pull/38943
Each field is also documented here: https://grafana.com/docs/grafana/latest/datasources/tempo/#trace-to-logs

Closing this issue 🙂
