### ISSUE TITLE
Create/adapt dashboards for single binary deployment

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#744]
**Is your feature request related to a problem? Please describe.**
Follow up from #740: the default dashboards do not work with a single binary deployment because:

- the dashboard has filters [on cluster and job](https://github.com/grafana/tempo/blob/main/operations/tempo-mixin/dashboard-utils.libsonnet#L31-L32)
- some components aren't deployed in a single binary deployment (memcached, gateway) so we shouldn't show panels for these

**Describe the solution you'd like**
Ideally we make two versions of the dashboard that are optimised for microservices or single binary deployment.

Cortex has a toggle in the jsonnet config: https://github.com/grafana/cortex-jsonnet/blob/main/cortex-mixin/config.libsonnet#L24

**Describe alternatives you've considered**

**Additional context**

**Comment by kvrhdn** [comment]
Closing in favour of https://github.com/grafana/tempo/issues/242

**Comment by sokratisg** [comment]
@kvrhdn did you manage to find a working JSON for this one? 

I am looking for exactly the same thing and was hoping to avoid re-editing all dashboard panels to replace `cluster` and `job` labels.
