### ISSUE TITLE
Add a tempo-distributed docker-compose

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#746]
It would be nice to have a docker-compose setup that has all services. This would be useful for testing the distributed mode of different components - for ex: routing by traceID on distributor with a replication factor > 1, sharding on the query path, rolling out different images for different services, testing a breaking config/schema change, etc.

We currently have one for performance testing of the write path - https://github.com/grafana/tempo/blob/main/integration/microservices/docker-compose.yaml. We could copy this over and add the query path components.

**Comment by hionnode** [comment]
Can I take this up?

**Comment by kvrhdn** [comment]
Go for it! 😀

**Comment by zalegrala** [comment]
Hi @hionnode, have you already started this work?  I was thinking of picking this up next week if not.
