### ISSUE TITLE
Azure: Add Instrumentation

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#759]
The GCS client is currently instrumented to provide standard RED metrics:

![image](https://user-images.githubusercontent.com/2272392/121730564-d9677d80-cabd-11eb-9aa3-4ced7466a1ef.png)

add similar instrumentation to the Azure backend.

**Comment by JosephWoodward** [comment]
I made a start on this last night with [this draft PR](https://github.com/grafana/tempo/pull/767).

**Comment by JosephWoodward** [comment]
I presume this can now be closed @joe-elliott ?

**Comment by joe-elliott** [comment]
Yup! I'm surprised it didn't automatically. Thanks again for the fix.
