### ISSUE TITLE
Change standard example port to 3200

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#770]
All of our examples use port 3100 as the Tempo http port. This collides with the standard example in Loki that also uses 3100. This occasionally confuses users when they attempt to run standard Loki and Tempo configs in the same network namespace. 

Change all in repo examples/docs/whatever to use 3200.

**Comment by MurzNN** [comment]
Yeah, I got very confused when see same default port on Tempo and Loki docs, especially when Tempo also needs `loki-url` option to same port :)
