### ISSUE TITLE
Support environment variable expansion in config file

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#788]
Allow adding sensitive information to the config file by expanding environment variables. Some backend drivers have native support for this (ex: GCS/S3) but there might be other instances where this is desired, for instance in Memcached/Redis/Azure/etc. 

The solution is to add a new cli option `-config.expand-env` that will replace any environment variables denoted by `${VAR}` in the config file.

This is inspired by Loki inspired by Cortex :)
https://github.com/grafana/loki/issues/2311
https://cortexmetrics.io/docs/configuration/configuration-file/#use-environment-variables-in-the-configuration

Related: https://github.com/grafana/tempo/issues/749

**Comment by NickLarsenNZ** [comment]
This doesn't work for tempo-vulture
