### ISSUE TITLE
Skywalking oap Cluster

### ISSUE THREAD

**Issue by wwh-coder** [grafana/tempo#807]
When building a skywalking OAP cluster, how to configure the routing when using the gateway, how to sense OAP expansion between UI and agent, and whether to directly configure the gateway address? Can you provide a configuration example？

**Comment by mapno** [comment]
Hi! I'm not sure if this is the correct repository for this question, maybe https://github.com/apache/skywalking is better suited? If the question is about Tempo, could you expand a bit what problems your encountering?
