### ISSUE TITLE
Provide short easy examples of implementing Grafana Tempo traces in Node.js and other languages

### ISSUE THREAD

**Issue by MurzNN** [grafana/tempo#811]
**Is your feature request related to a problem? Please describe.**
I'm in moving our project tracing implementation from [Sentry.io](https://sentry.io/) to Grafana Tempo, and have a lot of questions how to implement the things, or even how to make some separate easy test code, that will upload test traces directly to Grafana Cloud Tempo instance.

**Describe the solution you'd like**
Will be good to share some very easy and clean code examples, that implements uploading one span to Tempo, at least for Node.js, but glad to see in other languages too (for me - PHP is the second preferred language).

At now on page https://grafana.com/docs/tempo/latest/getting-started/instrumentation/ I see only one link to Node.js example here https://github.com/mnadeem/nodejs-opentelemetry-tempo but it is very complicated:
- A lot of docker images are included, even mssql server
- A lot of js files https://github.com/mnadeem/nodejs-opentelemetry-tempo/tree/main/src and even with connecting to mssql

Very good examples are in Sentry project, here is the short and easy example for Node.js https://docs.sentry.io/platforms/node/
```js
import * as Sentry from "@sentry/node";
import * as Tracing from "@sentry/tracing";

Sentry.init({
  dsn: "

https://examplePublicKey@o0.ingest.sentry.io/0",

  // We recommend adjusting this value in production, or using tracesSampler
  // for finer control
  tracesSampleRate: 1.0,
});

const transaction = Sentry.startTransaction({
  op: "test",
  name: "My First Test Transaction",
});

setTimeout(() => {
  try {
    foo();
  } catch (e) {
    Sentry.captureException(e);
  } finally {
    transaction.finish();
  }
}, 99);
```
And same for PHP https://docs.sentry.io/platforms/php/

**Comment by joe-elliott** [comment]
Here is our getting started guide:
https://grafana.com/docs/tempo/latest/getting-started/

Under our instrumentation examples, there is a community provided github repo that had nodejs instrumentation:
https://grafana.com/docs/tempo/latest/getting-started/instrumentation/

If these resources don't help please provide feedback so we can improve them!

**Comment by MurzNN** [comment]
I already reviewed that guide and example https://github.com/mnadeem/nodejs-opentelemetry-tempo and wrote feedback in first post - this example is VERY complicated for new Tempo users! Especially with comparison to Sentry and other competing solutions...

**Comment by MurzNN** [comment]
I have created the short and easy example for PHP language here: https://github.com/MurzNN/grafana-tempo-tracing-examples-php
@joe-elliott, maybe add it as example to this page https://grafana.com/docs/tempo/latest/getting-started/instrumentation/ ?

**Comment by bboreham** [comment]
IMHO the code examples should be in OpenTelemetry repos, with a small document here explaining how to adapt them to use with Tempo.  Here's the [current getting started doc](https://opentelemetry.io/docs/js/getting_started/nodejs/).

Moving to OpenTelemetry for the first time I found it very frustrating to find loads of examples for Lightstep, Honeycomb, etc., when I wanted to use Jaeger.  Please improve the central repos; don't make that problem worse.
