### ISSUE TITLE
Dashboard that shows per-tenant data

### ISSUE THREAD

**Issue by mapno** [grafana/tempo#813]
**Is your feature request related to a problem? Please describe.**

Per-tenant information can be specially useful for large Tempo deployments with multi-tenancy enabled to debug issues such as per-tenant rate limiting, huge shifts in traffic patterns, etc. It'd be interesting to have this kind of information in the tempo-mixin dashboards.

We could either add `tenant` as a selector for the existing dashboards or create new per-tenant-everything dashboards

**Comment by joe-elliott** [comment]
I prefer an additional dashboard with all per tenant metrics.

We should also remove the per tenant metrics from the operational dashboard. Some graphs are useless with any real number of tenants.
