### ISSUE TITLE
Query-frontend retries queries that timed out in querier

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#824]
**Describe the bug**
After merging #814 I noticed the query-frontend is retrying request that timed out in the querier.

The good: after retrying the request, it usually succeeds quickly
The bad: if we keep retrying a query that timed out, the query might hang for up `max_retries * query_timeout` seconds (50s by default).

An example of such a trace:

![Screenshot 2021-07-16 at 14 52 32](https://user-images.githubusercontent.com/7748404/125950678-e6f4bf22-b7c3-4de5-aab5-336cdf926fd6.png)

**To Reproduce**
1. Start Tempo (2ad27e7c or more recent)
2. Perform a query
3. If the querier times out, observe retries in the query-frontend

**Expected behavior**
I'm not sure to be honest. Some options:

- do not retry a query that timed out
- enforce a timeout in the query-frontend
- leave it as is (but a request that OOMs the querier could be sent 5 times this way)

**Comment by joe-elliott** [comment]
Can we hedge timed out requests instead of retrying?

**Comment by kvrhdn** [comment]
The improvements in https://github.com/grafana/tempo/pull/850 should also help with this issue.
