### ISSUE TITLE
When a querier is shutdown, all in-flight requests are cancelled

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#826]
**Describe the bug**
When a querier is shutdown, it notifies the query-frontend and immediately cancels all running requests. Instead we should allow the server to gracefully shutdown and handle all in-flight requests.

This is a known issue in Cortex: https://github.com/cortexproject/cortex/issues/3571#issuecomment-786563209

This issue is split off from #761. See https://github.com/grafana/tempo/issues/761#issuecomment-877169191 and https://github.com/grafana/tempo/issues/761#issuecomment-880024530

**To Reproduce**
1. Run tempo (disable `query-frontend.max_retries` so retries don't mask it)
2. Shutdown queriers or roll the querier deployment (`kubectl rollout restart deployment querier`)
3. Queries will fail with 500 error

**Expected behavior**
The querier should allow the server to drain requests.

**Comment by bboreham** [comment]
ICYMI Cortex added a graceful shutdown notification in https://github.com/cortexproject/cortex/pull/3901
