### ISSUE TITLE
Allow configuration via expansion of environment variables

### ISSUE THREAD

**Issue by hrodic** [grafana/tempo#827]
**Is your feature request related to a problem? Please describe.**
Not a problem, just extra operational complexity

**Describe the solution you'd like**
env vars expansion like open telemetry collector
https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables

**Comment by joe-elliott** [comment]
Support was added here: https://github.com/grafana/tempo/pull/796/files

I don't believe this is in a release yet though.

**Comment by hrodic** [comment]
I see! thanks, waiting for the release!
