### ISSUE TITLE
official docs or package for tempo backend without container

### ISSUE THREAD

**Issue by leopinho** [grafana/tempo#836]
I think it would be to good to have a rpm/linux package for tempo backend like Grafana does (below), or at least official docs of how to install in a linux env without containers.

https://grafana.com/docs/grafana/latest/installation/rpm/

**Comment by kvrhdn** [comment]
Hi, thanks for opening an issue. We currently do not offer rpm packages for Tempo, a good first step would be to actually build them.

Looking at Cortex, they build rpm and deb packages as part of their release process. The packages are attached to their GitHub releases ([example v1.9.0](https://github.com/cortexproject/cortex/releases/tag/v1.9.0)). ([their Makefile](https://github.com/cortexproject/cortex/blob/d9e1f81f40c607b9e97c2fc6db70ae54679917c4/Makefile#L348-L378)).

I'd suggest we start with something similar for Tempo by adding support for rpm in Makefile and our GoReleaser setup.

**Comment by kvrhdn** [comment]
This can be a good first issue if you wan to learn more about packages and build automation

**Comment by zalegrala** [comment]
I believe we'd just need to extend the `goreleaser` config to include the package spec.
https://github.com/grafana/tempo/blob/main/.goreleaser.yml
https://goreleaser.com/customization/nfpm/

**Comment by joe-elliott** [comment]
I forgot about this issue! We do have both rpms and debs available for all releases:

https://github.com/grafana/tempo/releases/tag/v1.5.0

Added here: https://github.com/grafana/tempo/pull/1533

Perhaps we can close this issue?

**Comment by knylander-grafana** [comment]
We've added doc for a linux installation here: https://github.com/grafana/tempo/pull/1954

**Comment by knylander-grafana** [comment]
The doc for a Linux setup without containers is now merged with this PR: https://github.com/grafana/tempo/pull/1954
