### ISSUE TITLE
Ingester does not detect when a query has been cancelled

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#840]
**Describe the bug**
When a request has been cancelled by the querier (usually after a 10s timeout), the ingester does not observe this and continues searching. Ideally, the ingester should abort all work when the request has been cancelled.

![Screenshot 2021-07-27 at 15 17 46](https://user-images.githubusercontent.com/7748404/127160124-e10bce49-ccb4-45c7-8dc7-8b09f9a44c10.png)

**To Reproduce**
1. Start Tempo
2. Send a query
3. If the ingester hangs for over 10s (the default query timeout), the querier will cancel the request

You can artificially trigger this behaviour by adding an extra `time.Sleep(11 * time.Second)` in [`FindTraceByID`](https://github.com/grafana/tempo/blob/80b91be2879d5e35b6292a147553b47e8e5ea9ea/modules/ingester/instance.go#L308)

**Expected behavior**
If the request is cancelled the ingester should immediately stop spending resources on this request.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Jsonnet

**Additional Context**
I'm guessing [`FindByTraceID`](https://github.com/grafana/tempo/blob/80b91be2879d5e35b6292a147553b47e8e5ea9ea/modules/ingester/instance.go#L308) is not checking `ctx` has been cancelled and some operation that occasionally takes a really long time.

**Comment by annanay25** [comment]
We had another incidence of this behaviour
<img width="1359" alt="Screenshot 2021-08-17 at 12 27 23 PM" src="https://user-images.githubusercontent.com/10982987/129679532-430aee45-28b7-407b-8848-51b9c9a3d6f7.png">
