### ISSUE TITLE
Trace ID with extra space triggers complex error message

### ISSUE THREAD

**Issue by bboreham** [grafana/tempo#846]
**Describe the bug**
I copy-pasted a trace ID and added a space at the end by accident.
The resulting error was:
```
failed to get trace with id: 1f34e43692d1f5d8 Status: 400 Bad Request Body: encoding/hex: invalid byte: U+0020 ' '
```

This error is quite difficult to understand, and also not helpful in pointing out the problem.

**Expected behavior**
Something like this would be easier to use:
```
failed to get trace with id: "1f34e43692d1f5d8 "; invalid character: U+0020 ' ' at position 17
```

**Comment by kvrhdn** [comment]
If anyone wants to work on this:

We validate the traceID here: https://github.com/grafana/tempo/blob/d50c64ba9df22e20fb895562aec3e04c107bf6a2/modules/frontend/frontend.go#L54-L62

The function actually parsing traceID is here: https://github.com/grafana/tempo/blob/d50c64ba9df22e20fb895562aec3e04c107bf6a2/pkg/util/http.go#L34-L55

We should improve the error messages this function returns to be more human-friendly 🙂
