### ISSUE TITLE
Add HA Scaleable Mode

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#86]
Ultimately I'm seeing three modes for tempo:
- Single binary
- HA
  - This would look like a scalable single binary.   I think this would be a good option for people who want a simpler to operate Tempo, but require more than the single binary option can give them.
- Full Microservice
  - All microservices deployed separately (distributor, ingester, querier, compactor)

Requires #36

**Comment by mdisibio** [comment]
Does HA mode in this case mean multiple instances with target=all, but still operating together with ring/gossip for like ingest/query/compaction?   There might be some changes needed to support this.

**Comment by joe-elliott** [comment]
> Does HA mode in this case mean multiple instances with target=all, but still operating together with ring/gossip for like ingest/query/compaction?
Yes, this was my intention.  I think it's a valid operational mode in between single binary and completely split out microservices.

**Comment by waszi** [comment]
I am trying to configure single binary in HA mode (3 instances):
- s3 storage (ceph)
- memcached (3 instances)

/api/traces/<id> returns 404 on 2 nodes (after few minutes trace is available on all nodes).

I have configured ring kvstore for compactor/distributor, do I assume correctly problem is ingester and inmemory ring which is enforced in single binary mode ?

**Comment by joe-elliott** [comment]
yeah, that makes sense. it's probably b/c the querier can't see all ingesters. i think you should be able to override that though and setup an ingester ring as well.

**Comment by joe-elliott** [comment]
Yup, that's bad. We should default to in memory but allow overrides. That's a really weird place for that code too.

We tend to do that here:
https://github.com/grafana/tempo/blob/main/modules/ingester/config.go

We are already defaulting to memberlist. We need a clean way to see if those values have been set and not override.

**Comment by dpires** [comment]
I've experimented with HA mode and everything looks good when removing the above mentioned "all" block overrides to get the ingesters to join the ring.

Is this on the roadmap/waiting for documentation? HA mode would be a great middle ground.
