### ISSUE TITLE
Rename CLI flag: --storage.trace.maintenance-cycle to --storage.trace.blocklist_poll

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#862]
**Describe the bug**
The CLI has a flag `--storage.trace.maintenance-cycle`
https://github.com/grafana/tempo/blob/c61b67851b576a673176582f3388eb3c7f0c7145/modules/storage/config.go#L34

But in the YAML config this flag corresponds with `storage.trace.blocklist_poll`
https://github.com/grafana/tempo/blob/9485f96bf7042a3b0e98d93a7c3aa0e42287074c/tempodb/config.go#L30-L31

Changing this will be a breaking change.

**Expected behavior**
Name of YAML config options and CLI flags match with each other.

**Comment by joe-elliott** [comment]
I'd prefer going the other way and rename the cli option. It will cause less headache and I think the name makes more sense.

**Comment by kvrhdn** [comment]
Sure, I must have misread your comment. Agree `blocklist_poll` is better since this is the only thing we do.
