### ISSUE TITLE
Invalid docker compose arguments for gcs emulator

### ISSUE THREAD

**Issue by warrenhodg** [grafana/tempo#869]
**Describe the bug**
In the examples, the docker-compose command arguments combine "-public-host gcs:4443" into one array element,
making it invalid. the two words should be two distinct array elements.

**To Reproduce**
1. Attempt to use docker-compose up for examples/docker-compose/gcs

**Expected behavior**
Containers start

**Environment:**
 - Infrastructure: laptop, docker-desktop
 - Deployment tool: docker compose

**Additional Context**

**Comment by zalegrala** [comment]
Thank you for the report.  I'll take a look shortly.
