### ISSUE TITLE
Before retrying to flush a block, check if the block still exists

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#886]
**Describe the bug**
When flushes fail, the ingester will keep retrying to flush the block. Sometimes a block is 'bad' and will never be flushed successfully. In this case an operator will manually remove the block from the WAL.
See https://github.com/grafana/tempo/blob/main/operations/tempo-mixin/runbook.md#tempoflushesfailing

The logic that requeues the flush operation, waits backoff time and then queues the operation again without checking that this block exists.

https://github.com/grafana/tempo/blob/e2c68727f342018b66bb915c186339f27614f7e6/modules/ingester/flush.go#L345-L373

If the block has been removed in the meantime, this will be an infinite loop that can only be reset by restarting the entire ingester.

**To Reproduce**
1. Run Tempo
2. Corrupt a block in the WAL by for instance removing `data`
3. After a while the ingester will try to flush this block and fail
4. Remove this block, Tempo will continue trying to flush this block

**Expected behavior**
If a block does not exist anymore, give up on trying to flush it.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Additional Context**

**Comment by annanay25** [comment]
An alternate solution might be to delete the block after some (configurable?) number of retries, similar to what we do in the `handleCompleteOp`

**Comment by kvrhdn** [comment]
Yeah agree, we could move this logic up a level and use it for all operations.
https://github.com/grafana/tempo/blob/e2c68727f342018b66bb915c186339f27614f7e6/modules/ingester/flush.go#L241-L248

I'm only worried this can cause a lot of data loss when the backend is unavailable for a long time, if we are not running out of diskspace we can hold on to blocks for longer. So we might want to check if the error is something local or not and only remove the block if there is pressure on diskspace.
