### ISSUE TITLE
Add more detail to traces for finding trace by ID

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#907]
**Is your feature request related to a problem? Please describe.**
We were diagnosing an issue where a trace ID was occasionally not found in Tempo (404 from /api/traces/<traceid>). The root cause was a misconfiguration of polling cycles between queriers, which was easily fixed.   This is a request to add more details to the traces output by Tempo on the read path, for data points that would have been really helpful.

**Describe the solution you'd like**
Let's add tags for the following spans/locations. 
* querier.FindTraceByID (querier.go)
  * found true/false when querying blocks (exists already when querying ingesters)
* readerWriter.Find (tempodb.go)
  * Number of live blocks
  * Number of live blocks included in the search
  * Number of compacted blocks
  * Number of compacted blocks included in the earch

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by annanay25** [comment]
Beyond the scope of this issue but it would be great if we could extend this work to gather query statistics - #822
