### ISSUE TITLE
Ingester search production readiness

### ISSUE THREAD

**Issue by mdisibio** [grafana/tempo#932]
Ingester search was recently merged #806 but it is marked experimental. This issue is tracking the list of additional work to consider it production-ready:

- [x] Config: Ingester: Make search block encoding and page size configurable (https://github.com/grafana/tempo/pull/990)
- [x] Config: Querier: separate search timeout from trace lookup timeout (https://github.com/grafana/tempo/pull/984)
- [ ] Querier: tolerate disappearing ingesters and return partial results
  - Related to https://github.com/grafana/tempo/issues/899
- [x] Querier/Ingester: correctly enforce `limit`, make the default configurable (#1022)
- [x] Ingester: Add block headers to eliminate blocks from search faster. Maybe also use blockheaders for autocomplete lookups instead of in-memory LRU cache which is somewhat inefficient. (https://github.com/grafana/tempo/pull/943)
- [x] Ingester: Fix duration filtering (sometimes incorrect results are returned) (https://github.com/grafana/tempo/pull/933)
- [x] Ingester: Dedupe WAL records when converting StreamingSearchBlock -> to BackendSearchBlock (https://github.com/grafana/tempo/pull/940)
- [x] Ingester: Reload search blocks on startup (requires gracefully handling blocks without search data) (https://github.com/grafana/tempo/pull/1000)
- [x] Distributor: Extract span status and make available for searching (error=y?) (https://github.com/grafana/tempo/pull/1093)
- [ ] Operational: alerts for search apis
- [x] Operational: dashboard panels for search apis (https://github.com/grafana/tempo/pull/930)
- [x] Documentation: config options, apis, alerts, troubleshooting (https://github.com/grafana/tempo/pull/1003)

**Comment by joe-elliott** [comment]
We are seeing traceheaders use quite a bit of disk space in the ingesters. More than previously estimated. Consider the following tasks as well:

- [ ] Global denylist of tags that should not be added to traceheaders
- [ ] Per tenant allowlist/denylist of tags
- [ ] Max tag value length? Just truncate the value if it's > then some configurable number of bytes/runes
