### ISSUE TITLE
using logql pattern feature to extract fields

### ISSUE THREAD

**Issue by RichardWright** [grafana/tempo#942]
Hi, tempo supports json and logfmt. We've built a parser using the logql 'pattern' feature recently released and exteneded the pattern to support a trace id. 

Could tempo be extended to support the output of custom logql patterns?

Thanks!

**Comment by annanay25** [comment]
Hi Richard, I'm not sure I understand what you mean by the following:

> Could tempo be extended to support the output of custom logql patterns?

Could you please elaborate?

Tempo is the backend to store traces, was this issue for [Loki](https://github.com/grafana/loki) by any chance? :)

**Comment by RichardWright** [comment]
Maybe! I'm really unsure of the boundaries of each one. Spefically I'm referring to the two log parsers mentioned in here - https://grafana.com/blog/2020/11/09/trace-discovery-in-grafana-tempo-using-prometheus-exemplars-loki-2.0-queries-and-more/

Which...does sound like a loki question! I shall try there.
