### ISSUE TITLE
Add support for Google Cloud Profiler

### ISSUE THREAD

**Issue by tanner-bruce** [grafana/tempo#986]
Tempo already has the `debug/pprof` endpoint, however using this can be a little tedious and quite manual. As well, capturing profiles that actually contain what you are looking for, such as high memory usage/allocations can be challenging to time. 

**Describe the solution you'd like**
Google Cloud Profiler adds an async process that capture pprof stats and sends the profiles to GCP itself allowing for analysis at a later time. It can be optionally enabled/disabled, and offers minimal production performance overhead. See [Cloud Profiler](https://cloud.google.com/profiler/docs/about-profiler) for more info.

**Describe alternatives you've considered**
I'm sure there are some alternatives to Cloud Profiler, but I've considered none of them since this is what we use internally.

**Additional context**
We've implemented this internally already and can follow this FR up with a PR if desired.

![image](https://user-images.githubusercontent.com/21345430/134937572-de71e370-230d-4264-8536-bf66576a6894.png)

**Comment by joe-elliott** [comment]
We have experimented with [conprof](https://github.com/conprof/conprof) in the past which has similar functionality as this automatic profiling. As long as this is a no-op when it's not configured we would welcome the PR.
