### ISSUE TITLE
traces missing discarded because of internal_error

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/tempo#995]
**Describe the bug**
traces are being discarded because of internal_error. I am not sure what is the error. but I see that the `tempo_discarded_spans_total` metric is showing the reason as `internal_error`.
```
tempo_discarded_spans_total{cluster="services", container="distributor", endpoint="http", instance="10.8.15.4:3100", job="tempo-distributed", namespace="observability", pod="tempo-distributor-6dbd749d86-cnc4j", reason="internal_error", region="ap-south-1", service="tempo-distributor", tenant="901688089596"}
```

**To Reproduce**
Brought up tempo using Helm Charts in EKS. And the traces are appearing in grafana. But I observed from 1-2 days that some of the traces are missing. 
```
$ ko get po | grep tempo
tempo-compactor-7f88c7895c-thzq4            1/1     Running   0          3m38s
tempo-distributor-6dbd749d86-2ssxb          1/1     Running   0          58m
tempo-distributor-6dbd749d86-cnc4j          1/1     Running   0          58m
tempo-distributor-6dbd749d86-w8fjp          1/1     Running   0          76m
tempo-ingester-0                            1/1     Running   0          30h
tempo-ingester-1                            1/1     Running   0          51m
tempo-ingester-2                            1/1     Running   0          30h
tempo-ingester-3                            1/1     Running   0          30h
tempo-memcached-0                           1/1     Running   0          30h
tempo-memcached-1                           1/1     Running   0          30h
tempo-querier-847b96df59-zp92x              1/1     Running   0          58m
tempo-query-frontend-5bdc9d4f9f-d96lq       2/2     Running   0          30h

$ ko get svc
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                          AGE
kube-state-metrics               ClusterIP   None             <none>        8080/TCP,8081/TCP                                15d
tempo-compactor                  ClusterIP   172.20.142.240   <none>        3100/TCP                                         19d
tempo-distributor                ClusterIP   172.20.82.43     <none>        3100/TCP,9095/TCP,55681/TCP,4317/TCP,55680/TCP   19d
tempo-gossip-ring                ClusterIP   None             <none>        7946/TCP                                         19d
tempo-ingester                   ClusterIP   172.20.122.125   <none>        3100/TCP,9095/TCP                                19d
tempo-memcached                  ClusterIP   172.20.183.208   <none>        11211/TCP,9150/TCP                               19d
tempo-querier                    ClusterIP   172.20.57.75     <none>        3100/TCP,9095/TCP                                19d
tempo-query-frontend             ClusterIP   172.20.110.177   <none>        3100/TCP,9095/TCP,16686/TCP,16687/TCP            19d
tempo-query-frontend-discovery   ClusterIP   None             <none>        3100/TCP,9095/TCP,16686/TCP,16687/TCP            19d

```

**Expected behavior**
The traces not should be discarded.

**Environment:**
 - Infrastructure: Kubernetes (EKS)
 - Deployment tool: helm

**Additional Context**
Below are the logs I am continously seeing in the distributor console:

```
level=error ts=2021-09-29T13:19:21.607323606Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:19:24.799841435Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-compactor-595888cf59-fdtv5-77c967f7)"
ts=2021-09-29T13:19:26.999147708Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-compactor-595888cf59-fdtv5-77c967f7 but other probes failed, network may be misconfigured"
ts=2021-09-29T13:19:28.000058002Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-querier-847b96df59-tmcr9-b5377673 but other probes failed, network may be misconfigured"
ts=2021-09-29T13:19:29.00087064Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-ingester-2-c207c4cb but other probes failed, network may be misconfigured"
ts=2021-09-29T13:19:30.001360547Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-ingester-0-1790077c but other probes failed, network may be misconfigured"
ts=2021-09-29T13:19:30.956657176Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-compactor-595888cf59-fdtv5-77c967f7)"
ts=2021-09-29T13:19:31.002582643Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-distributor-6dbd749d86-xfgm4-b79faabc but other probes failed, network may be misconfigured"
ts=2021-09-29T13:19:34.999175631Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-distributor-6dbd749d86-xfgm4-b79faabc but other probes failed, network may be misconfigured"
ts=2021-09-29T13:19:36.01541191Z caller=memberlist_logger.go:74 level=info msg="Suspect tempo-ingester-2-c207c4cb has failed, no acks received"
ts=2021-09-29T13:19:39.336431026Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-distributor-6dbd749d86-xfgm4-b79faabc)"
level=error ts=2021-09-29T13:19:45.814285282Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:19:47.177893684Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-compactor-595888cf59-fdtv5-77c967f7)"
ts=2021-09-29T13:19:50.998215926Z caller=memberlist_logger.go:74 level=info msg="Suspect tempo-ingester-2-c207c4cb has failed, no acks received"
level=error ts=2021-09-29T13:19:51.615225245Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:20:03.291601219Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-ingester-1-e33048a2)"
ts=2021-09-29T13:20:10.027464106Z caller=memberlist_logger.go:74 level=info msg="Suspect tempo-distributor-6dbd749d86-xfgm4-b79faabc has failed, no acks received"
ts=2021-09-29T13:20:12.803481918Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-ingester-2-c207c4cb)"
level=error ts=2021-09-29T13:20:15.814699677Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:20:16.014402937Z caller=memberlist_logger.go:74 level=info msg="Suspect tempo-ingester-1-e33048a2 has failed, no acks received"
level=error ts=2021-09-29T13:20:21.608440296Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:20:45.998778023Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-querier-847b96df59-tmcr9-b5377673 but other probes failed, network may be misconfigured"
level=error ts=2021-09-29T13:20:46.830010012Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
level=error ts=2021-09-29T13:20:51.60530996Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:20:58.800716431Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-ingester-0-1790077c)"
ts=2021-09-29T13:21:10.998845028Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-distributor-6dbd749d86-p769f-882ca03e but other probes failed, network may be misconfigured"
ts=2021-09-29T13:21:14.063398896Z caller=memberlist_logger.go:74 level=info msg="Suspect tempo-compactor-595888cf59-fdtv5-77c967f7 has failed, no acks received"
level=error ts=2021-09-29T13:21:15.810340014Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:21:19.594754454Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-ingester-2-c207c4cb)"
level=error ts=2021-09-29T13:21:21.605252769Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
ts=2021-09-29T13:21:26.998418309Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-querier-847b96df59-tmcr9-b5377673 but other probes failed, network may be misconfigured"
ts=2021-09-29T13:21:33.802067923Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: tempo-distributor-6dbd749d86-p769f-882ca03e)"
ts=2021-09-29T13:21:41.019170698Z caller=memberlist_logger.go:74 level=info msg="Suspect tempo-distributor-6dbd749d86-p769f-882ca03e has failed, no acks received"
```

I tried to do forget the ingester nodes and restarted the compactor, distributor pods. But still seeing this same errors in console.

**Comment by kvrhdn** [comment]
`internal_error` indicates \*something\* went wrong when the distributor attempted to push traces to the ingesters. I believe the actual error will be logged together with the message `pusher failed to consume trace data`.
Can you find this line being logged anywhere?

Those memberlist errors should not impact ingestion, they are usually transient and we see them appear when pods are rolled out/replaced. They aren't very actionable and we don't fully understand them yet unfortunately.

**Comment by mvkrishna86** [comment]
thanks @kvrhdn . I was getting the below logs:

```
2021-09-29T14:47:03.259967768Z stderr F level=error ts=2021-09-29T14:47:03.259827716Z caller=log.go:27 msg="pusher failed to consume trace data" err="rpc error: code = FailedPrecondition desc = LIVE_TRACES_EXCEEDED: max live traces per tenant exceeded: per-user traces limit (local: 10000 global: 0 actual local: 10000) exceeded"
2021-09-29T14:47:02.278336066Z stderr F level=error ts=2021-09-29T14:47:02.278157162Z caller=log.go:27 msg="pusher failed to consume trace data" err="context canceled"Show context
2021-09-29T14:46:50.25517615Z stderr F level=error ts=2021-09-29T14:46:50.254964345Z caller=log.go:27 msg="pusher failed to consume trace data" err="context canceled"
```

Can you suggest what configuration I need to correct to increase the number of traces at an instance?

**Comment by mvkrishna86** [comment]
Got this link: https://grafana.com/docs/tempo/latest/configuration/#overrides to increase the limit.
Thanks @kvrhdn . Any idea to resolve the errors:
`level=error ts=2021-09-29T13:19:45.814285282Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G`
`ts=2021-09-29T13:19:28.000058002Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-querier-847b96df59-tmcr9-b5377673 but other probes failed, network may be misconfigured"`

**Comment by kvrhdn** [comment]
Yeah, increasing the limits to avoid `LIVE_TRACES_EXCEEDED` is the right thing to do (up to certain point of course). But this will be especially necessary if you have a single very large tenant.

> Any idea to resolve the errors:
> `level=error ts=2021-09-29T13:19:45.814285282Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G`
> `ts=2021-09-29T13:19:28.000058002Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to tempo-querier-847b96df59-tmcr9-b5377673 but other probes failed, network may be misconfigured"`

These lines are logged by memberlist and are usually transient errors while components settle. Are they persistent?
You can view the state of memberlist on the `/memberlist` endpoint. We also have endpoints for the different rings.
See https://grafana.com/docs/tempo/latest/api_docs/
And https://grafana.com/docs/tempo/latest/operations/consistent_hash_ring/

**Comment by mvkrishna86** [comment]
Yes, these are consistent. And I see the memberlist and ring status of ingester and compactor are healthy/ACTIVE. 
And one more issue, I see the below messages in the logs during the load testing:
```
2021-09-30T16:26:04.368737761Z stderr F level=error ts=2021-09-30T16:26:04.368625064Z caller=log.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
2021-09-30T16:24:16.868248685Z stderr F level=error ts=2021-09-30T16:24:16.868151339Z caller=log.go:27 msg="pusher failed to consume trace data" err="context canceled"
2021-09-30T16:24:05.261988245Z stderr F level=error ts=2021-09-30T16:24:05.261870567Z caller=log.go:27 msg="pusher failed to consume trace data" err="context canceled"
```
And I see the traces are being dropped, and the metric value of `tempo_discarded_spans_total` is being increased. Again with the same reason 'internal_error'. This time, I dont see any specific error code like LIVE_TRACES_EXCEEDED.

**Comment by kvrhdn** [comment]
`context deadline exceeded` means the request timed out, aka the ingester did not process it in time and the distributor gave up. I'd look into the latency metrics of the ingesters, they are most likely struggling to keep up so either decrease the load on Tempo or scale up the distributors/ingesters.
I strongly recommend getting the Tempo Writes dashboard online, so you can get visibility into what each component is processing and what their latency is. We have a section on monitoring Tempo here: https://grafana.com/docs/tempo/latest/operations/monitoring/

The `internal_error` label can have multiple causes, so spans being dropped because of `LIVE_TRACES_EXCEEDED` get lumped together with requests timing out.

**Comment by kvrhdn** [comment]
My previous reply is not completely correct... so the `tempo_discarded_spans_total` metric actually has specific labels for every limit. So there will be separate series for `live_traces_exceeded`, `rate_limited`... and `internal_error`

![image](https://user-images.githubusercontent.com/7748404/135593279-a543c15a-fd02-49b6-99be-bb4772020499.png)

If `internal_error` keeps showing up that means some requests are still failing (for reasons other than limiting). The logs should usually contain more information.

**Comment by mvkrishna86** [comment]
![image](https://user-images.githubusercontent.com/15136443/135633861-2c36045b-3bfd-499b-91f0-5a5f23e3454e.png)

Most of the time I am getting internal_error only.. but not much info in the logs.

**Comment by kvrhdn** [comment]
This can have several causes, I'd recommend visualising some of request and latency metrics to see if there is any correlation between the amount of requests or maybe the size of the requests and these errors. We have several dashboards in the tempo-mixin for this purpose: https://grafana.com/docs/tempo/latest/operations/monitoring/#dashboards

They are a bit difficult to set up right, I'm planning to work on that next week 🙂 
https://github.com/grafana/tempo/issues/802
